### ISSUE TITLE
Input text mask

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1001]
Helpful package to only allow certain characters in an input

https://github.com/text-mask/text-mask/tree/master/angular2#readme

See it in action here:
https://stackblitz.com/edit/angular-mat-date-mask?file=app%2Fdatepicker-overview-example.ts

**Comment by lmmrssa** [comment]
Looks like masking can be used only for fields like date where we have fixed characters. Or we need to find better masking packages

**Comment by paulbert** [comment]
Closing.  This repo is pretty outdated, and the other text mask libraries are not very good.
