### ISSUE TITLE
Special warning before deleting admin of child planet

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1037]
It could cause problems if the nation deletes a community user.

**Comment by Rupesh87** [comment]
![ddd](https://user-images.githubusercontent.com/18145146/40355531-5fb96928-5dd6-11e8-8da2-4a42cc806860.png)

is this the view we are going to show special warning before deleting child parent

**Comment by lmmrssa** [comment]
@Rupesh87 If you clearly read the issue, then it is not about deleting child parent. Issue is about showing warning when you are deleting user that is admin of another planet.
Yes there is also warning to delete user but it does not mention anything that says that child planet will have issue or will not be able to connect if user is deleted.
Snapshot you have is deleting child planet not user.

**Comment by paulbert** [comment]
Extra warning isn't showing.  I think an ngIf rather than condition in the typescript will work better.
