### ISSUE TITLE
When no question exam option should not be available

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#1042]
When there is no question on step it gives error also exam does not make sense if no question is there. So we should disable *Take Exam* 
![screen shot 2018-05-18 at 17 14 44](https://user-images.githubusercontent.com/2909490/40341679-37fafdfa-5da6-11e8-9c31-5754541ff7fc.png)

**Comment by Tille88** [comment]
A bit ugly, but
*ngIf="stepDetail.exam**.questions.length**"
(change=bold) would do it...
