### ISSUE TITLE
Notification for new communities should be linked to accept place

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/planet#1048]
![screenshot_20180522_002731](https://user-images.githubusercontent.com/13684059/40342174-1a4f5980-5d57-11e8-841d-0c7467a248c7.png)

![screenshot_20180522_002830](https://user-images.githubusercontent.com/13684059/40342203-3f9acb16-5d57-11e8-928c-42164c827419.png)

**Comment by lmmrssa** [comment]
There is already a link attached to notification. But we do not have feature to navigate to link.
