### ISSUE TITLE
No indication of already completed exam

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/planet#1062]
In courses exam steps, after submitting a full exam, there is nothing to indicate that, the button says "take exam"

![screen shot 2018-05-22 at 6 07 38 pm](https://user-images.githubusercontent.com/16757941/40358931-2dd9695c-5deb-11e8-801d-8f8564de288f.png)

**Comment by lmmrssa** [comment]
Instead of attempt we should go with looking after progress as that is functionality we need to have on course anyway.
