### ISSUE TITLE
Filter users from child planet/community

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1080]
Users with an @ symbol are admins from a child planet/community.  We should have an option to filter these out so the admin can manage users on the nation.

**Comment by Rupesh87** [comment]
@paulbert where to add the filter? Is that in request table?

**Comment by lmmrssa** [comment]
This issue is about filtering user list not request table. We need to be able to look after users of child planets connected to nation or center. So that admin can control and manage those users easily.
