### ISSUE TITLE
Configuration setup error

### ISSUE THREAD

**Issue by Rupesh87** [open-learning-exchange/planet#1088]
![confi](https://user-images.githubusercontent.com/18145146/40483320-4befd33a-5f77-11e8-818a-05bf1168c208.png)

**Comment by lmmrssa** [comment]
This issue happens randomly seems like fork tasks run parallel so sometime admin creation completes before replicator. This issue will be solved if we go through solution of making nation connection after login. If we want immediate fix we can do it on pipe or any synchronous execution.

**Comment by lmmrssa** [comment]
Found one case of configuration failing again. Everything was setup correctly except User and Shelf on parent
![screen shot 2018-05-29 at 09 09 38](https://user-images.githubusercontent.com/2909490/40636817-08ab2ed2-6321-11e8-9384-6a2f48e9e7f4.png)

**Comment by paulbert** [comment]
Closing, outdated.
