### ISSUE TITLE
Only ASCII characters allowed in username?

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/planet#1090]
If only ASCII or numbers are allowed, the message should indicate that somehow - letters like ü or æ ä å, etc are still considered letters in many non-English alphabets. 

![screen shot 2018-05-24 at 8 39 30 pm](https://user-images.githubusercontent.com/16757941/40489179-bd0d8c36-5f92-11e8-8e3c-59d60d5d98c3.png)

**Comment by i5o** [comment]
Isn't it better if we change the message to something like
"No special characters are allowed"

**Comment by Tille88** [comment]
@i5o Still a bit of technical language for a regular user perhaps, but an improvement in my book. Can't exactly have mapping from any unicode char to closest allowed one if any... so... I don't have a good fix really

**Comment by paulbert** [comment]
Maybe we can update our regex with something like this: https://stackoverflow.com/questions/150033/regular-expression-to-match-non-english-characters
