### ISSUE TITLE
Configuration with same code should not be allowed

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1092]
![image](https://user-images.githubusercontent.com/9203229/40490839-ad04b68c-5f3a-11e8-853c-c93e8a9a7e80.png)

**Comment by MacNew** [comment]
@paulbert I think these code values are before we made validate for code. Now we can't put an existing value from the application. But if someone puts existing value and he/she is selecting some community. And he/she switch to nation than these values are accepted by application
