### ISSUE TITLE
Only send meetup request to learner or leader

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1095]
![image](https://user-images.githubusercontent.com/9203229/40493723-4ae485ca-5f41-11e8-8b65-89ed638af2f3.png)

**Comment by paulbert** [comment]
Hmm...that was because this user did not have rights to the meetups database.  Maybe we should only allow learners & leaders to be invited to meetups?

**Comment by MacNew** [comment]
@paulbert  I think we should close this issue on the favor of https://github.com/open-learning-exchange/planet/issues/1101
