### ISSUE TITLE
Debug observable logger can make original observable not complete

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/planet#1122]
This is not a new issue, I have seen this behavior before but didn’t know what was wrong. In the animations observable, it does not get completed when unsubscribing as seen from the screen shot below. Meaning that the unsubscription happens, but a new timer is created on each click.

![screen shot 2018-05-26 at 2 52 20 pm](https://user-images.githubusercontent.com/16757941/40574334-26d5e074-60fa-11e8-94ca-5973aedf8a6f.png)

In the screenshot it is just showing that a single timer keeps going, but if clicking again, a new timer starts on 0 as well.
The intended functionality is as seen below:

![screen shot 2018-05-26 at 2 59 59 pm](https://user-images.githubusercontent.com/16757941/40574336-44c6d570-60fa-11e8-9527-b13703cba04b.png)

If this is due to a deeper implementation error in the debug-operator returning an observable, and that is the one being unsubscribed to, it is worth looking into since this could cause memory leaks throughout, only in development, but that is annoying enough.

On the same branch as another animation-related fix (for quick reference, I have included this in the PR for quick reference, link will be in post below), I have made a solution for this particular issue, although ideally it would be nice to not have to create a Subject to force the debugger to create new timer on each click…. If the debug logger gets fixed, the original implementation could just as well be used.

**Comment by Tille88** [comment]
https://github.com/open-learning-exchange/planet/pull/1123

**Comment by paulbert** [comment]
Checking back on [the custom operator section of this talk](https://youtu.be/JCXZhe6KsxQ?t=3m47s) from one of the leads on the RxJS team, I think maybe rather than returning a new Observable just returning the source with a piped tap operator would be better & maybe solve this issue.
