### ISSUE TITLE
Delete replicator when deleting community

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1132]
![image](https://user-images.githubusercontent.com/9203229/40623556-729c799c-6275-11e8-9585-368542c996d7.png)

When remaking that community it will throw error if the replicator exists

**Comment by lmmrssa** [comment]
@paulbert replicator is created on child planet itself so if child planet is destroyed replicator will also be gone. Resend of request will also connect with same nation so replicator will not change.
Only if we change the configuration then we will require to change replicator. So will delete replicator on configuration update.

**Comment by paulbert** [comment]
This is for the dev only "Delete Community" button so we can quickly reset our environment and test changes to configuration.  In that function we do not remove the replicator, causing the final step of configuration to fail when we setup the community again.
