### ISSUE TITLE
Enforce uniqueness in design docs

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1137]
For databases with unique properties we should create/modify their design documents to enforce uniqueness so clicking quickly does not create a duplicate document.

**Comment by lmmrssa** [comment]
Looking after some docs for doing unique, it only seem to be possible by _id as couchdb being schemaless we can not enforce uniqueness to other fields. So its requires query beforehand or use _id to make it unique document.

**Comment by paulbert** [comment]
Outdated
