### ISSUE TITLE
logout not working 

### ISSUE THREAD

**Issue by Rupesh87** [open-learning-exchange/planet#1146]
v 0.1.20
If we login in and navigate to course or resources logout won't work.

![logout error](https://user-images.githubusercontent.com/18145146/40638308-3cbf9e48-632a-11e8-9b04-9b79e59ccfe3.png)

**Comment by lmmrssa** [comment]
Actually logout is working it is error on resource or course page which is stopping from navigation.
Session has already been destroyed though.
