### ISSUE TITLE
Question about Redirecting the back button.

### ISSUE THREAD

**Issue by MacNew** [open-learning-exchange/planet#1168]
@paulbert  and  @lmmrssa On users-update.component.ts line number 64. we are redirecting Url '/users/profile/username' only if there is a gender of the user. Is it compulsory?. If it is compulsory than it makes an issue if the user does not update their gender and click back button then he/she directly redirect to home page. And at line number 77 we are displaying a data on the console. (console.log('data: '+ data);

**Comment by paulbert** [comment]
We are assuming that the user will fill out the profile form immediately after creating their account.  Gender is a required field, so that is used as a simple indication if this is their first time logging in or second+.
