### ISSUE TITLE
Course progress display

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#1173]
Liked one of the concept of github where on code page it will display color code bar
![screen shot 2018-05-30 at 13 26 30](https://user-images.githubusercontent.com/2909490/40706358-43989326-640d-11e8-98d2-c7358b4f9cc3.png)
When clicked on color bar it will change to 
![screen shot 2018-05-30 at 13 26 37](https://user-images.githubusercontent.com/2909490/40706398-66ac5a5a-640d-11e8-9e62-e08e80176700.png)

We might want to use same for Unattempt, completed or other status of course

**Comment by lmmrssa** [comment]
We would like to start this once we have #1201 resolved

**Comment by paulbert** [comment]
Fixed in #1344
