### ISSUE TITLE
Disable action buttons once event is triggered and show indicator

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#1200]
We should disable buttons once someone trigger event to prevent immediate concurrent event request.
Also as some request will take a while to return response we should have some indicator showing action being carried on.

**Comment by paulbert** [comment]
Newbie friendly version: implement on `resources-add.component.ts` and `resources-add.component.html` only

**Comment by lmmrssa** [comment]
This error is also happening with actionbar so once we figure out it on resources-add, we need to implement it for all buttons

**Comment by paulbert** [comment]
#1293 Is a good start.  Next steps:

- Add a [spinner](https://material.angular.io/components/progress-spinner/overview) as an indication that the app is working on the request
- Roll this out for other buttons that submit data, ideally in a directive or something a little more DRY than repeating this on every component.

**Comment by lmmrssa** [comment]
Unassigned @gcantieni as it has not been worked for while.
**Anyone we wants to continue can grab it and continue working. We need to implement it all over and also add spinner.**

**Comment by paulbert** [comment]
I think this is complete.  If we need additional spinner functionality implemented, we should make a new issue
