### ISSUE TITLE
Past attempts after updating exam

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1216]
What should we do for this (probably rare) situation?

- Someone takes an exam a few times
- That exam is changed by the course leader
- That person reenters the course

Should the old attempts still show/be counted?  Should we have an option when updating an exam to for users to retake this version?

**Comment by lmmrssa** [comment]
From user and analytics old attempts should be counted. But may be we can give some notification or update to user that exam they have taken has been changes so they can retake exam.
