### ISSUE TITLE
Community paginator negative number

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1224]
Showing items -9 to 0 after switching from status with 0 results to one with many

![image](https://user-images.githubusercontent.com/9203229/40950114-51f17d80-683f-11e8-9602-a7687e968f66.png)

**Comment by paulbert** [comment]
Also when switching button filter after navigating to the second page of a list is blank when there should be one item

![image](https://user-images.githubusercontent.com/9203229/40950170-a4f7110c-683f-11e8-9ea2-b1cadaa4e164.png)

**Comment by lmmrssa** [comment]
Request list showing empty is the issue of #1241

**Comment by singharpita** [comment]
couldn't replicate.
