### ISSUE TITLE
Group buttons on the right side on modals?

### ISSUE THREAD

**Issue by i5o** [open-learning-exchange/planet#1229]
Right now the buttons are on the left side, why not on the right side like everyone else?
![image](https://user-images.githubusercontent.com/2650479/40951447-66a8eb06-684d-11e8-9268-2245e36ec50c.png)

**Comment by paulbert** [comment]
#1278 fixed this for one scenario.  We should go through and make sure our button positioning and order is consistent.

**Comment by i5o** [comment]
@paulbert are there more modals I'm missing?
I tried to find them

**Comment by lmmrssa** [comment]
@i5o We have other forms as well where button are aligned to left.

**Comment by empeje** [comment]
I'll take over this one.

**Comment by coder8102** [comment]
This issue has been already resolved.

![1229](https://user-images.githubusercontent.com/41846764/52988513-2c850600-33c5-11e9-9686-6f82bb7a32df.PNG)
