### ISSUE TITLE
Delete meetup undefined

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1256]
When checking meetup then clicking delete.
![image](https://user-images.githubusercontent.com/9203229/41101694-dc963cec-6a32-11e8-9407-1340e4b8b1ce.png)

![image](https://user-images.githubusercontent.com/9203229/41101700-e00d76f6-6a32-11e8-8aab-3c1da72a02c9.png)

**Comment by lmmrssa** [comment]
NOTE: It works on menu dropdown of each row
