### ISSUE TITLE
Other user profile edit changes top right image

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1258]
This should only change if you are changing your own profile image.  Note: Only admins can edit other users.

**Comment by lmmrssa** [comment]
![screen shot 2018-06-07 at 17 04 11](https://user-images.githubusercontent.com/2909490/41103415-d0103f62-6a88-11e8-9bad-bb1d79985a4b.png)
![screen shot 2018-06-07 at 17 04 19](https://user-images.githubusercontent.com/2909490/41103416-d04eaa22-6a88-11e8-8423-afad87af02dc.png)
