### ISSUE TITLE
Notifications remains when clicked

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/planet#1271]
No matter if clicking notifications or logging in again after logging out, previous notifications keep being listed. They basically never seem to go away. The wanted behavior could be to mark as shown on clicking dropdown, reading the message, marking as read, etc. so that's not obvious, but current functionality is certainly not the correct one.

![screen shot 2018-06-08 at 9 19 08 am](https://user-images.githubusercontent.com/16757941/41134134-65f93e4c-6afd-11e8-80ca-1fd9ef077398.png)

**Comment by i5o** [comment]
Fixed by https://github.com/open-learning-exchange/planet/pull/1284
