### ISSUE TITLE
Clicking on profile image or username can take them to profile

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#1311]
We can take to user profile when user click on user image or username
![screen shot 2018-06-12 at 08 38 47](https://user-images.githubusercontent.com/2909490/41267692-2f6bbcf2-6e1c-11e8-8436-7814c98d9965.png)

**Comment by paulbert** [comment]
Merged #1317, but would we instead want to route to the profile when clicking anywhere on the row?

**Comment by i5o** [comment]
I like that better, but wondering if that would override the actions of the buttons in "Action"

**Comment by paulbert** [comment]
@ScottHuangNYU Clicking images routes to profile, but now we should update so clicking anywhere on the row (except a button) routes to the profile
