### ISSUE TITLE
Most of elements join next to each other

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#1336]
After we upgraded to Angular 6 it seems elements touch each other. Such as inputs, buttons.
![screen shot 2018-06-13 at 19 30 10](https://user-images.githubusercontent.com/2909490/41355110-6b8f1dda-6f40-11e8-96de-adddbde55ab2.png)

**Comment by paulbert** [comment]
This is maybe a little broader, but is very close to #1267

**Comment by paulbert** [comment]
Fixed in #1653
