### ISSUE TITLE
As a Developer, I want to have development dependencies available in a docker-compose.yml

### ISSUE THREAD

**Issue by empeje** [open-learning-exchange/planet#1340]
As a Developer, I want to have development dependencies available in a docker-compose.yml so that it is easier for new developers to join.

Approach:
* What our developer setup might be a feature for the **community**, **nation** or for the **earth**
* So, in our `docker-compose.yml` should have both working community, nation, and earth for the last release.
* Then, we have a minimal setup for our developers to start doing coding.
* An ability to preloaded the configuration for the app would be great. Prepopulate CouchDB settings perhaps?

Calling all the stakeholders @dogi, @paulbert, @lmmrssa, @i5o. What do you think?

**Comment by paulbert** [comment]
Closing, this is a bit stale.
