### ISSUE TITLE
Update Style-Guide.md

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#1342]
Update style guide to not use `i18n` attribute on tags which do not have any String (i.e empty tag or only contain Interpolation String)

**Comment by NirmalKumarJoshi** [comment]
Working on it.

**Comment by lmmrssa** [comment]
@NirmalKumarJoshi is there any update on this issue?

**Comment by gcantieni** [comment]
@lmmrssa So basically any html tag that doesn't wrap a string can't be translated into another language and thus doesn't need il8n?

**Comment by lmmrssa** [comment]
@gcantieni Yes any html which does not have text/string inside it does not require i18n. It gives issue while we compile application
