### ISSUE TITLE
docker: latest tag has to be always also latest commit

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/planet#1354]
right now every build on master triggered commit or tag will overwrite latest tag ... also in the case of rebuild of an older commit on travis ...

... in this case latest just points to the latest successful build but not to the latest commit,
which is wrong

ToDo:
make sure when latest tags get written that they are also lastest commits

**Comment by sahilph** [comment]
@dogi The latest tag only get written if a branch is merged with master. Shouldn't this be the expected behaviour ?

**Comment by mappuji** [comment]
As per discussion, it is something to do when we build not the latest commit in the master branch where it will trigger the creation of Docker image with `latest` tag.

One approach is we can use the GitHub API to check the latest commit and then compare the commit `sha` of the latest remote master to the `HEAD` of the one that we currently build.
