### ISSUE TITLE
Exam progress retaining some of other exam information

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1363]
After selecting a new exam from the dropdown some of the information shown is still from the previous exam:

![image](https://user-images.githubusercontent.com/9203229/41486338-16f73744-70b2-11e8-8484-01b4a3fbf9ba.png)

**Comment by i5o** [comment]
![image](https://user-images.githubusercontent.com/2650479/41686614-164889b2-74bb-11e8-9381-80945d1d4fd1.png)

this happens when selecting 2nd exam, which has no trials

**Comment by i5o** [comment]
so I guess that's the issue
