### ISSUE TITLE
Build time increased

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#1417]
After we merged multi language, build time increased. Will it be possible to shrink it. Or have multi language build for certain commit case only and for other have only built english.

**Comment by mappuji** [comment]
On it, sorry for the inconvenient.

**Comment by mappuji** [comment]
When I try to fix this issue I have a question:

* Do we want to have another kind of image: `treehouses/planet:i18n-latest`? Which contains build with multi-language and let `treehouses/planet:latest` same like before?

**Comment by lmmrssa** [comment]
@mappuji I don't think we should have that, as it will be better to have latest as production release and production release should have multi language

**Comment by mappuji** [comment]
Okay, if that's the expected solution, it will be simpler. I'll finish it soon. Thanks for clarification @lmmrssa

**Comment by mappuji** [comment]
Two approaches:

See 
* #1444 --> Don't compile on `arm` just copy from the `x86` artifact
* #1435 --> Normal way

**Comment by mappuji** [comment]
Solved in #1444
