### ISSUE TITLE
Travis latest is still not latest

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1420]
Not sure why, but the latest tag still does not match the tip of the master branch.  In the meeting today it was missing commits such as https://github.com/open-learning-exchange/planet/commit/9d58fbbd287c03cd4ea247b6f2a6a148a6c639d1 and https://github.com/open-learning-exchange/planet/commit/1c7a9dd9c55ffd21d113ae65414e195d4e46e108

**Comment by dogi** [comment]
disagree - it worked for me ;)
