### ISSUE TITLE
Attachment lost on resource update

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#1423]
Manage of resource does not show previously added attachment.
Also when we just submit resource again without any changes previous attachment gets deleted.
![sketch 55](https://user-images.githubusercontent.com/2909490/41728930-ba7b2f94-7597-11e8-8c68-865364226f0d.png)

**Comment by lmmrssa** [comment]
As we are currently using same database and updating doc means you have to push all details as well. That will result in large resource file being resubmitted. So for now we can just show previous attachment. Once we have different table of attachment it will be easier as we will just resend attachment_id.

**Comment by paulbert** [comment]
@lmmrssa Some things to clarify about this issue:

- As long as "Delete File" is not checked, the previous attachment remains in the database.
- As long as nothing is selected in the file upload input, no files are submitted with the form.

The only thing that needs to change is an indication that there is already a resource attached when updating.
