### ISSUE TITLE
Remove "Add Question" from ToolBar

### ISSUE THREAD

**Issue by nirojdyola** [open-learning-exchange/planet#1425]
There are two same buttons "Add Question" that does the same thing. We can remove from the toolbar.
![screen shot 2018-06-22 at 7 57 48 am](https://user-images.githubusercontent.com/7495421/41754534-71630178-75f2-11e8-8eb9-011579a839a7.png)

**Comment by paulbert** [comment]
Closing since we can keep this redundancy
