### ISSUE TITLE
"ng e2e --environment test" is test nothing after upgrading the Angular version

### ISSUE THREAD

**Issue by mappuji** [open-learning-exchange/planet#1436]
See this https://travis-ci.org/open-learning-exchange/planet/jobs/395550934#L891

After upgrading the Angular version seems karma test doesn't work.

<img width="1063" alt="screen shot 2018-06-23 at 12 09 30 am" src="https://user-images.githubusercontent.com/11813607/41789535-d71a82e8-7679-11e8-828e-f5dbf37c7e7a.png">

**Comment by paulbert** [comment]
Oh, that's the Proractor test, but still that's a problem.  I think it's now `--configuration=test` maybe

**Comment by mappuji** [comment]
Let's try
