### ISSUE TITLE
Do not change "createdBy" on update

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1450]
Found in MeetupsAddComponent.

If we are updating the document after creation, the `createdBy` field should not change

**Comment by lmmrssa** [comment]
@paulbert @nirojdyola @ArashDai This issue does not look valid anymore as we are only allowing to update meetup by its owner.

**Comment by paulbert** [comment]
Also retested and it seems to be working as it should now (and with the link not showing unless someone types update into the url only the creator will update meetups anyway)
