### ISSUE TITLE
Total errors not cleared for course progress

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1462]
When switching to a step with no exam, the total errors on the left is not cleared:

![image](https://user-images.githubusercontent.com/9203229/41885489-3717ee12-78c6-11e8-8b56-6e1f14208a55.png)

There are also errors in the console:

![image](https://user-images.githubusercontent.com/9203229/41885498-44e8f220-78c6-11e8-94b4-2933f0e67463.png)

**Comment by i5o** [comment]
@paulbert is it supposed to look like this when there is no exam?
![image](https://user-images.githubusercontent.com/2650479/42006589-15518d1a-7a51-11e8-8a52-aa6d87855b06.png)

**Comment by i5o** [comment]
![image](https://user-images.githubusercontent.com/2650479/42006597-20922928-7a51-11e8-82d7-251e7d24303b.png)

**Comment by i5o** [comment]
ping @paulbert
