### ISSUE TITLE
array response is shown in course - add or update exam

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#1507]
![course_update_exam](https://user-images.githubusercontent.com/27276132/42038222-1bfae0a8-7b0a-11e8-8bca-29ff86b43564.png)
 also it display console error as shown in attachment
![console_error](https://user-images.githubusercontent.com/27276132/42038403-93288a5e-7b0a-11e8-82d4-699f2cbc88ec.png)

**Comment by paulbert** [comment]
Ok I think we can remove the JSON output at the bottom (it was used for debugging).

The error in the console is unrelated and due to an issue with files not loading correctly.
