### ISSUE TITLE
non-mandatory drop down issue in Resource add / update form

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#1508]
-Non-mandatory drop down should be allowed with empty value.
If one of the option is selected there is no way to deselect them and reassigned the null or empty value.
- Some of the mandatory field is missing "*" in the label.

![resource_add](https://user-images.githubusercontent.com/27276132/42039465-26038462-7b0d-11e8-9e27-a5e05ea7e1ad.png)

**Comment by paulbert** [comment]
It's intended that these are required, but they should be marked as such with a `*`.  Required fields should have the `required` tag which tells Material to add the `*`
