### ISSUE TITLE
Refactor DialogsFormComponent & DialogsFormService

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1527]
DialogsFormComponent should not close from the component itself because it will not & should not have knowledge of the state of the form to know if it is valid.

**Comment by gcantieni** [comment]
### Plan:
- [ ] replace `confirm` function in DialogsFormService with `openDialog` and `closeDialog` functions
- [ ] add callback function in DialogFormService to be injected it into the DialogsFormComponent
- [ ] the callback function will make a request that we can subscribe to and error check, and only upon a successful request will we call `closeDialog`.

**Comment by paulbert** [comment]
To put them in one place, here's a list of all of the related issues that have come up since creating this one:

#3033 #2844 #2795 #2541 #2540 #2053
