### ISSUE TITLE
Search is not filterering most of the column except owner column

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#1535]
![feedback_search_1](https://user-images.githubusercontent.com/27276132/42194557-46073ed6-7e94-11e8-8ced-b41bd215b46a.png)
![feedback_search_2](https://user-images.githubusercontent.com/27276132/42194574-54ffc23c-7e94-11e8-8ff6-53f72bdc9ed4.png)

**Comment by lmmrssa** [comment]
Make filter work by title and owner
For type we could use dropdown or button filter like in community request
