### ISSUE TITLE
course view layout issue

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#1539]
![course-view-layout](https://user-images.githubusercontent.com/27276132/42195009-7fb2066e-7e96-11e8-83ee-dc19455cc292.png)
![course-view-layout-1](https://user-images.githubusercontent.com/27276132/42195012-8526082a-7e96-11e8-8508-425aa565f74f.png)

**Comment by paulbert** [comment]
The panels on the right should not expand beyond the height of the containing element.  We should make the `overflow-y: auto` (so a scrollbar appears) for that part of the view
