### ISSUE TITLE
Feedback radio first click does not select

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1542]
The first click on the radio does not select the choice, it simply makes the form "dirty" so the required message appears.  Clicking the radio button should select that option.

https://www.useloom.com/share/c102d443f1f24bb887f331e5dca288fd

**Comment by lmmrssa** [comment]
The issue is that it is not highlighting the feedback dialog. None of radio does get selected on first click. Even if you click on any part of the dialog except radio then after it works.
