### ISSUE TITLE
Option to accept or reject invitation of meetup

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#1543]
When user gets the invitation to join. They should see the option to accept or reject the invitation.
We can add a flag on the link that takes them to meetup from notification and show a special message to accept or reject invitation.

**Comment by i5o** [comment]
wondering if also button in notification would be greate "Accept/Decline"

**Comment by paulbert** [comment]
Let's change the join button to a `mat-raised-button` with `color="accent"` to make the join button stand out.
