### ISSUE TITLE
Update Configuration needs back button

### ISSUE THREAD

**Issue by ArashDai** [open-learning-exchange/planet#1548]
when updating the configuration from the manager dashboard, there is no back button like there is for the requests list and feedback list
![123](https://user-images.githubusercontent.com/8280071/42196614-c833b9f4-7e33-11e8-83bd-434e6c9123a9.png)
![456](https://user-images.githubusercontent.com/8280071/42196620-ce67fb82-7e33-11e8-818a-b4ea6ec5ac03.png)

**Comment by lmmrssa** [comment]
Make sure this only happens inside the manager-dashboard. It should not change for the first application setup as both uses same template page right now.
