### ISSUE TITLE
Exam question validator message does not get trigger

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#1578]
When Add Exam is clicked, it does not show the error message of question description even when it is not valid and stops from submission.
![sketch 70](https://user-images.githubusercontent.com/2909490/42326371-ad9aa9d4-8088-11e8-953b-368e04712f17.png)

When we get focus onto the description field then it shows the error message.
![sketch 71](https://user-images.githubusercontent.com/2909490/42326373-add5ed00-8088-11e8-9e00-411e8752b548.png)

**Comment by paulbert** [comment]
The issue is that the function that marks all of the form fields as touched only affects the first layer of FormControls. We need to also recursively run this function for all FormArrays and FormGroups in the examForm.
