### ISSUE TITLE
ResourcesAdd: How should languages be translated?

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1595]
In `resources-add.component.html` line 33 we have:
```
<mat-option i18n value="Spanish">Español</mat-option>
```
This is showing the native language name, but we tag it to be translated so for every language it will be translated into that language (i.e. our German translation file turns this into "Spanisch").

When setting an application language the best practice it to leave it in the native language, but I'm not sure for this menu here.

**Comment by lmmrssa** [comment]
On language change it might be good to use native language which is done so that even if you don't understand language showing up you can understand the language you want to switch, but within application features we can use translated language so that user can understand any language name showing.

**Comment by jessewashburn** [comment]
This line is no longer in this file.
