### ISSUE TITLE
Team member limit

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1634]
We should have a limit on number of users in a implemented.  Let's start with a limit of 12 for all teams.

Later we may add functionality for teams to be able to set their own limit.

**Comment by paulbert** [comment]
Didn't mean to close this.  #1634 partially fixes this.  Steps that remain are:

- Disable request to join button if team is at limit
- Do not allow members to be invited beyond limit

**Comment by lmmrssa** [comment]
@paulbert looking after the request you made, Member invite is not available in team so it will not be required.
For Disabling join request we can do it on view which is simpler for list of team it will require to query for all shelf so it does not look like more feasible. Can we allow user to request as we are already blocking them from being accepted if limit exceed.
