### ISSUE TITLE
Delete removed users from teams when deleting

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#1652]
When deleting users we might want to remove it from all the teams as well. As we are going to limit team with the number of users, deleted users may also keep occupying seat.

**Comment by singharpita** [comment]
@lmmrssa can you explain it further.

**Comment by lmmrssa** [comment]
Sorry @singharpita this issue seems to be from the scope of old structure. Now we are saving teamId in shelf so once user is deleted all trace of its related team will be gone. Before it was saving userId to multiple user shelf. I created this issue with that mindset. So closing this issue.
