### ISSUE TITLE
Rating additional comment bug in coursed and library

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#1672]
comment is not being saved for the same content as shown in following image

![3](https://user-images.githubusercontent.com/27276132/42744244-a9aabf8e-88ea-11e8-8c4a-9ff62a42ca57.png)
![2](https://user-images.githubusercontent.com/27276132/42744246-ab121fe8-88ea-11e8-98cb-20a040280aaa.png)
![1](https://user-images.githubusercontent.com/27276132/42744247-abbfef38-88ea-11e8-8522-46df08ad2625.png)

**Comment by singharpita** [comment]
in the given branch : 1356-course-rating
related to following PR : https://github.com/open-learning-exchange/planet/pull/1357

**Comment by paulbert** [comment]
Fixed
