### ISSUE TITLE
Meetup join message is wrong

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#1681]
Currently we get the message stating user wants to join meetup. But actually the user has already joined meetup as there is no request to join meetup.
![screen shot 2018-07-17 at 07 50 17](https://user-images.githubusercontent.com/2909490/42792666-3bbfa12c-8996-11e8-8496-be5117fd9761.png)
![screen shot 2018-07-17 at 07 50 26](https://user-images.githubusercontent.com/2909490/42792668-3c0dc7f8-8996-11e8-8e46-146768a86f97.png)

**Comment by lmmrssa** [comment]
Message just seems to be going for admin. May be we can send message to meetup creator as well as creator is the one that should be notified about the number of participants.

**Comment by lmmrssa** [comment]
Sorry for misreading the message. It was saying **would like you to join** but as notification didn't had any highlight it was difficult to find out the terms :)
May be we can update notification message such that it will have some highlights

**Comment by paulbert** [comment]
The message looks OK to me since one user invites another with the link leading the meetup page to join the meetup.

Other thought: should we limit invitations to meetup creator or at least people who have joined the meetup?  If more people can invite, then yes a notification for the creator would be good.

**Comment by lmmrssa** [comment]
@paulbert Yes I think we should not limit invitation or join request. If limit exceed then may be creator will be able to increase limit if meetup can accumulate more or remove not attending members.

**Comment by Mutugiii** [comment]
Feature is currently deprecated
