### ISSUE TITLE
Users - back arrow bug

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#1684]
Arrow back of User view page should return to its parent activity i.e user list page if it is called from User Profile.

Right now its redirecting to dashboard page.
![screenshot from 2018-07-17 08-14-31](https://user-images.githubusercontent.com/27276132/42793458-ea1c988a-8999-11e8-83b1-4a6ee3e27757.png)
![screenshot from 2018-07-17 08-14-17](https://user-images.githubusercontent.com/27276132/42793459-ea5b7fbe-8999-11e8-85b4-1782bf832fc9.png)
![screenshot from 2018-07-17 08-13-50](https://user-images.githubusercontent.com/27276132/42793462-ea98cd7e-8999-11e8-9cff-68d0b3c79b77.png)

**Comment by lmmrssa** [comment]
@singharpita is it still happening? @jiajunc please check if its happening. Or we can close this issue.
