### ISSUE TITLE
Make notification look more cleaner

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#1688]
Right now notification is plain with everything showing as just the text. We might want to make it more cleaner if we can add some styling out.
![screen shot 2018-07-17 at 08 15 48](https://user-images.githubusercontent.com/2909490/42793420-cc401800-8999-11e8-8ae0-ea03fbb1b220.png)
![screen shot 2018-07-17 at 08 16 38](https://user-images.githubusercontent.com/2909490/42793421-cc8475f4-8999-11e8-92c5-3743bf21bf23.png)

**Comment by paulbert** [comment]
Fixed #1759
