### ISSUE TITLE
Manage form empty space

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#1689]
We are currently using just some part of the page when creating some forms. We might be able to use the full space as we will be deploying smaller screen we need to manage all available space.
Right now I see it on resource and meetup manage view.

![screen shot 2018-07-17 at 08 48 33](https://user-images.githubusercontent.com/2909490/42794570-33d9b278-899f-11e8-975f-6d2237a04b6e.png)
![screen shot 2018-07-17 at 08 41 48](https://user-images.githubusercontent.com/2909490/42794569-33924c1c-899f-11e8-9950-5ed65c4f478e.png)

**Comment by paulbert** [comment]
I'm going to close this.  We can bring this up again in the future, but since we are targeting smaller screens we should focus on improving our design for tablets first.
