### ISSUE TITLE
Rating cancel button causes odd behavior 

### ISSUE THREAD

**Issue by gcantieni** [open-learning-exchange/planet#1709]
### Problem
After clicking the cancel button for a rating dialog while in resources-view or course-view blocks the next dialog from being created.

![image](https://user-images.githubusercontent.com/34512397/42947719-eccda684-8b3b-11e8-9149-62d18a0cfb7e.png)

### Steps to recreate problem
* click on a resource or course to bring you to the resource-view or course-view
* click one of the stars to give it a rating
* click cancel
* click on one of the stars again (could be any of them)
This time the dialog will not appear

Since this issue is not present while in the not in resource-view or course-view, the issue seems to be with `resource-view.component` and `course-view.component`.

**Comment by paulbert** [comment]
Doing a quick sweep of the code, one difference I can find is that the `parent` Input is not set for the view components (this hides the stars so you cannot rate resources & courses on the parent planet, just see their average rating).  That could be related.

**Comment by paulbert** [comment]
Fixed by #1721
