### ISSUE TITLE
Hide stars for parent rating in view components

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1714]
CoursesView & ResourcesView are still showing the stars in the lower left of the rating component when viewing items on the parent.  Since we should be able to see the rating but not add one, this should be hidden.

Fixing this may also fix #1709

![image](https://user-images.githubusercontent.com/9203229/42949602-177b2b46-8b40-11e8-9645-0b6c2b3f52a8.png)

**Comment by singharpita** [comment]
@paulbert 
In case of parent, it already hide the rating
![screenshot from 2018-07-20 16-17-06](https://user-images.githubusercontent.com/27276132/42997996-62c72e3a-8c38-11e8-9d72-0d6eebc9e690.png)
![screenshot from 2018-07-20 16-16-54](https://user-images.githubusercontent.com/27276132/42997997-630cd354-8c38-11e8-9c3f-329764f3d6ac.png)
![screenshot from 2018-07-20 16-16-44](https://user-images.githubusercontent.com/27276132/42997998-634e2052-8c38-11e8-952d-aa416140cd62.png)
![screenshot from 2018-07-20 16-16-17](https://user-images.githubusercontent.com/27276132/42997999-638ca7aa-8c38-11e8-9aa9-9b345c1e5600.png)



 :
