### ISSUE TITLE
Database access on subdomain rather than different port for production

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1716]
We'd like to change the production version of the application to connect to the database on a different subdomain (like `db.earth.ole.org`) rather than a different port (or in addition to).  Note this will also require changes to srv.

Hardcoding the port to 2200, for example, causes problems with SSH tunneling using a different port.  The app still tries to access on port 2200, but from the client the database is only available on another port.

We should discuss tomorrow.

**Comment by i5o** [comment]
```
        client_max_body_size 1g;
```
needs to be increased, the default is 1m

**Comment by paulbert** [comment]
Closing, this is working well
