### ISSUE TITLE
New video player

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1745]
Right now we are using the native HTML5 video element which doesn't seem to support many common video file formats.

We maybe need to use a flash player to support older file formats.  Otherwise we'd have to convert files in formats not supported by the HTML5 player.

**Comment by jessewashburn** [comment]
This may have been the case in 2018 but today I think the native video element works fine. Supported formats like MP4 (H.264), WebM (VP8/VP9/AV1), and some MKV are more than sufficient for most use cases.
