### ISSUE TITLE
action link on header should be made button

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#1766]
can be applied to entire application.
![action button](https://user-images.githubusercontent.com/27276132/43435647-a19d3c1a-94a0-11e8-8e21-1757e199688c.png)

**Comment by lmmrssa** [comment]
Yes we can make is something like raised button will have to check if we want to keep it for now or update.

**Comment by paulbert** [comment]
Let's see how `mat-raised-button` looks while keeping it the primary color.  We should only use the accent color sparingly.

**Comment by lmmrssa** [comment]
@jiajunc we want to see how it will look

**Comment by jiajunc** [comment]
@leomaxi Hey, does it mean that I should make the "Edit Profile" link into a button, and the form itself should be prefilled with user's original info?

**Comment by paulbert** [comment]
Closing since we mainly (if not completely) use raised or stroked buttons.  If we find another which is not we can open a new issue.
