### ISSUE TITLE
CORS problem when getting center/version || Docker message not shown as error

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/planet#1774]
![screenshot_20180731_000030](https://user-images.githubusercontent.com/13684059/43436970-c02c9d7a-9454-11e8-97f4-643a16541d85.png)

**Comment by i5o** [comment]
Failed to load https://dev.media.mit.edu/version: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.0.104' is therefore not allowed access.

**Comment by i5o** [comment]
https://enable-cors.org/server_nginx.html

**Comment by i5o** [comment]
https://serverfault.com/questions/162429/how-do-i-add-access-control-allow-origin-in-nginx
