### ISSUE TITLE
Course your progress still shown in course view even if course is not admitted

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#1805]
![course-admission](https://user-images.githubusercontent.com/27276132/43749860-82c7279a-9a15-11e8-9480-75da060c5583.png)
![course-admission-view](https://user-images.githubusercontent.com/27276132/43749861-830953a4-9a15-11e8-9b67-da1d5932a798.png)

**Comment by lmmrssa** [comment]
This looks bad when there is no step on course and it will just display label `Your progress` without any progress bar.
Will be nice to display progress bar only if user has taken course at any instance
