### ISSUE TITLE
Meetup view : left and right div proportion is uneven

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#1807]
since meetup doesn't contain any files unlike course or library to be shown, the left and right div should be partitioned proportionality.
Right now the right side has lots of unused space 
![meetup vew](https://user-images.githubusercontent.com/27276132/43750541-9f1dee08-9a18-11e8-8c15-c99626d7b257.png)

**Comment by paulbert** [comment]
That left space does get a little squished on the tablet resolution, too:

![image](https://user-images.githubusercontent.com/9203229/43801673-c789e56a-9a61-11e8-82b1-8c6cc71fb021.png)

I think it's right now `1fr 2fr` for the template columns, which we can change to `1fr 1fr`.
