### ISSUE TITLE
Header title overflow issue

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#1839]
found in library,meetups and team as  well.
![course-view](https://user-images.githubusercontent.com/27276132/44069005-91155038-9f9c-11e8-9ee1-a00f500773c5.png)
 Can we make separate partition for header title and action as left and right section respectively and assigned specific height -width to each?

**Comment by paulbert** [comment]
We should not change the height of the header.  Let's just limit the number of characters shown

**Comment by paulbert** [comment]
`text-overflow` should be usable here https://www.w3schools.com/cssref/css3_pr_text-overflow.asp

**Comment by jessewashburn** [comment]
We no longer have a meetups page

**Comment by Mutugiii** [comment]
deprecated
