### ISSUE TITLE
Fix multiple choice width for survey

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1869]
Width of choices for every other survey choice is too small.  It's using the same layout as exams, so these are the space for checkboxes (which are not needed for surveys).

![image](https://user-images.githubusercontent.com/9203229/44212156-9a135980-a138-11e8-896b-d6d114857e53.png)

**Comment by leahphuong** [comment]
<img width="1306" alt="screen shot 2018-08-21 at 2 45 40 pm" src="https://user-images.githubusercontent.com/13629659/44423339-e6ed9a80-a553-11e8-8062-608ddafcb481.png">
