### ISSUE TITLE
Create planetCode for every doc entered into replicator_users

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1880]
With the addition of surveys a new field was added to users: `planetCode`.  To avoid errors or missing users for sending surveys in case of a bugged user, we should add this field to every user when copying from _users to replicator_users.

**Comment by lmmrssa** [comment]
We should add planetCode to the ` return { ...repUser, ...userProps, _id: user.name + '@' + user.planetCode, couchId: user._id };` with configcode so that all broken users get fixed when its sent to nation
