### ISSUE TITLE
Localhost replication runs on wrong port

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1896]
I had a realization just now that the replication for localhost is set with the forwarded port, but since it is running from within the container it should be set within the Docker container.  See below successful replication with corrected port number

![image](https://user-images.githubusercontent.com/9203229/44296612-4451c500-a290-11e8-9061-697ba9eb0b9c.png)

Going further: we could set the local url in replication to `localhost:5984` always since the replication protocol is making the HTTP requests from the CouchDB container, correct?  That might help improve replication.

**Comment by lmmrssa** [comment]
@paulbert that's great
