### ISSUE TITLE
Cannot see the fields: multiple choice field not visible

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#1917]
<img width="1332" alt="screenshot 2018-08-21 08 22 18" src="https://user-images.githubusercontent.com/6964191/44377198-85a9d500-a51b-11e8-92d5-a442ebb0468c.png">

while adding the fields, the field is hidden and cannot able to add the text.

**Comment by lmmrssa** [comment]
@yuviii This is a survey question and it will not have correct answer regarding second input field being small there is already issue being worked on #1869
