### ISSUE TITLE
Duplicate Mymeetup : meetups is being added more than twice in dashboard

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#1934]
<img width="1069" alt="screenshot 2018-08-23 19 46 01" src="https://user-images.githubusercontent.com/6964191/44530105-683c5d00-a70d-11e8-988c-e37654bb3cd2.png">

Joined meetup at first , went back and again joined meetup again. Then same meetup is showing twice.

**Comment by lmmrssa** [comment]
@yuviii as per our finding its not duplication of meetup on dashboard but duplicated meetup on list itself.
Created new issue to remove duplicate mockup. Closing this issue.
