### ISSUE TITLE
Submission of survey and exam

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#1957]
We have all submissions showing up on **Submission** section. And it is not clear which is survey and which one is exam.
So either we should show survey submission on separate section or have something to identify it. May be filter toggle similar to what we have for users or requests. And also a icon or text on list
![sketch 98](https://user-images.githubusercontent.com/2909490/44698669-a84e6780-aaa0-11e8-9d6b-1a47fe73a77a.png)

**Comment by paulbert** [comment]
Should we also add user name here?  We could also add course name for exams, but that would be trickier (course is only referenced in parentId: it's <examId>@<courseId>)

**Comment by paulbert** [comment]
We'll need to hold off on adding the user because of #1960

**Comment by singharpita** [comment]
this issue is similar to this https://github.com/open-learning-exchange/planet/issues/1999.

**Comment by paulbert** [comment]
Fixed in #2016
