### ISSUE TITLE
Select all for tables: only select items viewed

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#1976]
In our tables clicking the select all button selects every resource/course/etc in the entire database, not just the ones viewed.  This leads to easy confusion & could result in deleting every resource from a community.

Right now we have a partial solution to warn when selected all before deleting.  We should better safeguard resources by only selecting the ones in view.

**Comment by BhargaviNadendla** [comment]
Still need to work to apply the same with courses and meetups. Will update shortly
