### ISSUE TITLE
validation: Year input field

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#1995]
<img width="707" alt="screenshot 2018-08-30 20 01 54" src="https://user-images.githubusercontent.com/6964191/44857598-dfcf3680-ac8f-11e8-8120-449de36076af.png">

The year field is accepting alphabet as well.

**Comment by lmmrssa** [comment]
Yes this is where we can add input masking

**Comment by paulbert** [comment]
Closing since years can have letters
