### ISSUE TITLE
Submission view - submitted identifier

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#1999]
isn't be helpful if we have User name who submitted the survey/course or datetime in submission list?
right now it just showing survey/exam title which is recorded/submitted multiple times.
![submission](https://user-images.githubusercontent.com/27276132/44859724-70a81100-ac94-11e8-8614-6e9738e69b5b.png)

**Comment by yuviii** [comment]
@singharpita I think we can add submitted by and submitted at field in the table.

**Comment by singharpita** [comment]
@paulbert  @lmmrssa  added submitted by column of the submitted user.
Submit datetime is not saved in submissions so should we add it during record survey or exam?
