### ISSUE TITLE
In Exam submission multichoice, multianswer doesn't submit

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2006]
Even the answer is correct.
![screenshot from 2018-08-31 12-12-09](https://user-images.githubusercontent.com/27276132/44896251-464b6780-ad17-11e8-8245-df5dbae9996e.png)

**Comment by paulbert** [comment]
This was only implemented for surveys, so the initial issue #1966 was left open and should be closed when this is fixed.
