### ISSUE TITLE
Course take exam- spinner keep on showing and exam not submitted

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2046]
to replicate the error, please follow following step:
- create two question ot type input
- one question of type multi choice single answer
- put two input field blank or empty
- move to the last multi choice question and submit the answer.
![course-stuck](https://user-images.githubusercontent.com/27276132/45164048-5b416280-b211-11e8-9173-62f35ff64eed.png)
![console](https://user-images.githubusercontent.com/27276132/45164062-61cfda00-b211-11e8-8543-74773469a19f.png)

**Comment by paulbert** [comment]
Tried to replicate this, and I believe this has been fixed
