### ISSUE TITLE
Change password with a wrong old password

### ISSUE THREAD

**Issue by BhargaviNadendla** [open-learning-exchange/planet#2053]
Though given a wrong old password, it says the new password is successfully updated though it is not. When tried to login again, it is only the old password that works

![image](https://user-images.githubusercontent.com/25775298/45167378-ae3dfa00-b1be-11e8-99c4-fce1226519e2.png)

![image](https://user-images.githubusercontent.com/25775298/45167554-fc52fd80-b1be-11e8-8bd2-662012bc8b8b.png)

**Comment by jiajunc** [comment]
I don't have this problem with wrong old password. But I cannot change it to a new password when I type in the correct old password.

**Comment by jessewashburn** [comment]
This has been fixed it looks like. Cannot replicate.

**Comment by Mutugiii** [comment]
Cannot replicate
