### ISSUE TITLE
Users list adding link in username

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2054]
<img width="1335" alt="screenshot 2018-09-06 21 07 15" src="https://user-images.githubusercontent.com/6964191/45167514-ff7ad780-b218-11e8-9aae-b33b392f6aae.png">

would be better to add the link in user name to show the profile detail as in view profile button.

**Comment by BhargaviNadendla** [comment]
@yuvii How about the 'view profile' button then, do we need to keep it?

**Comment by yuviii** [comment]
@BhargaviNadendla Yeah, would be better if you just add the link to go profile detail likewise we are doing on other.

**Comment by BhargaviNadendla** [comment]
@yuvii clicking on the profile image in the row takes to the user's profile though

**Comment by yuviii** [comment]
@BhargaviNadendla Oh yeah, i tried it with username. Its all good i guess.
