### ISSUE TITLE
Courses select all broken

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2080]
<img width="1347" alt="screenshot 2018-09-13 19 55 21" src="https://user-images.githubusercontent.com/6964191/45493843-6c4d1f00-b78f-11e8-842b-0af638c23fc3.png">

**Selecting and Unselecting**

<img width="1354" alt="screenshot 2018-09-13 20 02 00" src="https://user-images.githubusercontent.com/6964191/45494077-ff865480-b78f-11e8-9575-a1044fa7c7ad.png">
issues-

1. After doing check in all checkbox it shows correct count though the course in the table are not selected but the course item is checked the count goes increasing.
2. The original count remained same though all select checkbox is unchecked.

**Comment by paulbert** [comment]
This is an issue with the `masterToggle` which should select the `row._id` rather than the entire `row` object.  Same issue as #2079
