### ISSUE TITLE
on update of Course title, in submission it still reflect the old values

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2082]
![new test](https://user-images.githubusercontent.com/27276132/45494673-4e80b980-b791-11e8-8960-cee852d3f794.png)
![test](https://user-images.githubusercontent.com/27276132/45494685-550f3100-b791-11e8-82d9-38181d2ba401.png)

**Comment by singharpita** [comment]
i think i got confused in between "Step Title" and "Exam Title".
By default its same in both until and unless updated.

@paulbert @lmmrssa 
right now in Exam submission section, the column name create confusion about  its association to which step or course.
So can we have step title or course name column in exam section?

**Comment by paulbert** [comment]
Outdated, closing
