### ISSUE TITLE
does it valid to have empty value for select choice in course add exam?

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2084]
right now it allowed to enter empty value.
![empty choice](https://user-images.githubusercontent.com/27276132/45495415-f0ed6c80-b792-11e8-9d7c-47cf7867d028.png)
![empty choice1](https://user-images.githubusercontent.com/27276132/45495426-f5b22080-b792-11e8-91c2-3046b2579a82.png)

**Comment by lmmrssa** [comment]
Yes we don't want empty choices.
https://github.com/open-learning-exchange/planet/pull/2064 should have it fixed.

**Comment by paulbert** [comment]
Fixed in #2064
