### ISSUE TITLE
delete file option is visible though there is not any file

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2086]
<img width="649" alt="screenshot 2018-09-13 20 28 06" src="https://user-images.githubusercontent.com/6964191/45495782-acae9c00-b793-11e8-8075-712fb4de371e.png">

> Delete file should is visible though there is not any file uploaded. After clicking on it it says resources updated successfully.
It would be possibly more accurate  either by disabling the option or notify user with no file to delete.

**Comment by BhargaviNadendla** [comment]
@yuviii can you be specific where you are seeing this issue? I am unable to find it in add-resources or any other

**Comment by yuviii** [comment]
@BhargaviNadendla this is in resources -> manage -> and scroll to bottom please.
