### ISSUE TITLE
Add icon for Promote/Demote in user profile

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2108]
since all other action button has mat-icon .
![screenshot from 2018-09-18 06-58-14](https://user-images.githubusercontent.com/27276132/45658724-6f8a3700-bb10-11e8-85bc-ee19e06d0222.png)

**Comment by lmmrssa** [comment]
sure @singharpita we want icon for that as well. will have to search for relevant icon

**Comment by jessewashburn** [comment]
![image](https://github.com/user-attachments/assets/b442ffa4-c74d-43ff-b277-c9a14ed38509)
![image](https://github.com/user-attachments/assets/b3818d91-94cb-41f2-bc25-314b0b802536)

 we have them now.
