### ISSUE TITLE
The leave option should be change to join, once the user leaves from meetups

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2111]
<img width="1306" alt="screenshot 2018-09-18 07 30 25" src="https://user-images.githubusercontent.com/6964191/45659612-0822b600-bb15-11e8-869f-aa57c5cb9a6f.png">

Similarly, once the user left the meet up when detail is opened leave button should be disabled or hide.

**Comment by paulbert** [comment]
@yuviii The issue is not with the button changing.  You should check the user's document on the `shelf` database to make sure there are no duplicate ids.

**Comment by lmmrssa** [comment]
We are using couchdb2.2 and `get_bulk` which is returning deleted records as well. We need to filter deleted records so this error does not occur

**Comment by lmmrssa** [comment]
Problem here is that when we leave meetup its removing first item from the shelf.meetupIds not the id of the meetup we leave.
