### ISSUE TITLE
Adding resource to step doesn't show up immediately

### ISSUE THREAD

**Issue by BhargaviNadendla** [open-learning-exchange/planet#2119]
On adding a resource to the step, it doesn't show up immediately unless you return to the list and come back again

![image](https://user-images.githubusercontent.com/25775298/45662578-0ed70c00-bac8-11e8-8cb7-f262ecde2a15.png)

![image](https://user-images.githubusercontent.com/25775298/45662612-24e4cc80-bac8-11e8-8a08-14c577788cfa.png)

**Comment by jessewashburn** [comment]
Cannot replicate. This seems to have been fixed.  
[screen-recorder-wed-nov-13-2024-16-49-02.webm](https://github.com/user-attachments/assets/883919ba-0cc1-4e78-9c2b-82911fd0799d)
