### ISSUE TITLE
Survey title sorting

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2148]
sorting title is not filtering the number .
![screenshot from 2018-09-20 19-23-26](https://user-images.githubusercontent.com/27276132/45822297-dbd08a80-bd0a-11e8-82ab-476de33f3a90.png)
![screenshot from 2018-09-20 19-23-42](https://user-images.githubusercontent.com/27276132/45822308-e1c66b80-bd0a-11e8-836b-4107334218c8.png)

**Comment by lucy811** [comment]
fixed by #2173
