### ISSUE TITLE
same resource has add to library and remove from library

### ISSUE THREAD

**Issue by yubarajpoudel** [open-learning-exchange/planet#2154]
<img width="1357" alt="screenshot 2018-09-20 20 11 13" src="https://user-images.githubusercontent.com/6964191/45825290-a2e7e400-bd11-11e8-8dd3-e4df1f247ae2.png">

 is there anything we can fix up this?

**Comment by paulbert** [comment]
I think the best we could do is only include resources which are on the shelf in the count & activate the "Add to myLibrary" button when that count is >0.

**Comment by paulbert** [comment]
Fixed #2659
