### ISSUE TITLE
deletion count

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2156]
<img width="1266" alt="screenshot 2018-09-20 20 21 54" src="https://user-images.githubusercontent.com/6964191/45825840-e131d300-bd12-11e8-8607-6633680ca0f1.png">

It would be better to show the total count of selected resources.

**Comment by paulbert** [comment]
Documentation for dialogs: https://material.angular.io/components/dialog/overview

We can send a `count` property in the data object as well.
