### ISSUE TITLE
Meetup still showing empty records

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#2186]
It still shows **null** and also fields like **Location** **Recurring** which does not have any data
![screen shot 2018-09-25 at 07 22 18](https://user-images.githubusercontent.com/2909490/45987967-04061380-c094-11e8-88be-2618b2570dc3.png)

**Comment by paulbert** [comment]
Note this null is for the end date.  If there is only a start date, we should only show that (and no `-`)
