### ISSUE TITLE
Ratings popup: one OK button

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2192]
<img width="703" alt="screenshot 2018-09-25 08 06 00" src="https://user-images.githubusercontent.com/6964191/45989123-ecca2480-c099-11e8-8d66-26aaf007580d.png">

**Comment by paulbert** [comment]
For clarity: it is desired behavior to have the rating saved after the user clicks on a star and before the popup comes up.

I agree it is a little confusing to have a "Cancel" button because the rating is still recorded.  Maybe we can remove the cancel button and just have "Submit".

**Comment by yuviii** [comment]
@paulbert so if user do not press submit button, then it should show previously recorded rating or how does it work ?

**Comment by paulbert** [comment]
Closing this in favor of #3300
