### ISSUE TITLE
Team view : Name length overflow

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2213]
its already done for courses and library.
![screenshot from 2018-09-27 19-33-11](https://user-images.githubusercontent.com/27276132/46150613-a4268d00-c28c-11e8-956d-7aea07d2e3a0.png)
also can we add button for Add Members and Leave link similar to others.

**Comment by paulbert** [comment]
There are open PRs for courses & library.

We could consider a reusable component to reduce the duplication across the codebase.
