### ISSUE TITLE
Feedback : column header and value mismatch

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2218]
In feedback list, open time and close time only shows date.
![screenshot from 2018-09-27 19-49-34](https://user-images.githubusercontent.com/27276132/46151514-a984d700-c28e-11e8-9195-bc782c97b104.png)

**Comment by paulbert** [comment]
I think this is a simple change to the Date Pipe to something that shows the time: https://angular.io/api/common/DatePipe

**Comment by paulbert** [comment]
Let's just update the label instead to "Open Date" and "Close Date"
