### ISSUE TITLE
Feedback title edit field

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2222]
can title edit field be made little longer since we have plenty of space in header.
also can there be some border highlight to the reply?
![screenshot from 2018-09-27 20-01-53](https://user-images.githubusercontent.com/27276132/46152319-7cd1bf00-c290-11e8-9c7c-c4cba0133dbe.png)

**Comment by paulbert** [comment]
Ok, let's expand the feedback title edit field.

If you respond to feedback with a different user the bubble will be blue rather than white, so no change needed there
