### ISSUE TITLE
Meetup invite

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#2225]
Is it ok to allow user to invite other members to meetup even if they are not part of meetup themselves?
- Shall it be owner, admin who are able to invite even if not part of that meetup
- All other members should be part of meetup to invite others
OR
- It is free for anyone to invite anyone whatever the case is

**Comment by lmmrssa** [comment]
![screen shot 2019-01-10 at 20 44 04](https://user-images.githubusercontent.com/2909490/50976728-c4ffaf00-1518-11e9-8f9e-7ed7281f688c.png)

**Comment by paulbert** [comment]
Closing.  Meetups has changed into Calendar
