### ISSUE TITLE
Course take exam error

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2248]
In one of the course which is already created, take exam submit button keep on spinning with following error response.
Also looking into the update exam, there is no questions shows.
![screenshot from 2018-10-02 07-20-07](https://user-images.githubusercontent.com/27276132/46324620-1a701a00-c614-11e8-8215-d2908a281338.png)
![screenshot from 2018-10-02 07-20-22](https://user-images.githubusercontent.com/27276132/46324624-1fcd6480-c614-11e8-8450-95ec9acc31e3.png)
![screenshot from 2018-10-02 07-21-03](https://user-images.githubusercontent.com/27276132/46324626-25c34580-c614-11e8-929b-e2450bcfdd46.png)
![screenshot from 2018-10-02 07-21-12](https://user-images.githubusercontent.com/27276132/46324629-2b209000-c614-11e8-9e1b-abc60b3c0e86.png)

For new course created, there seems no such problem

**Comment by paulbert** [comment]
This is an error with the older exams because the data structure was modified recently.  Since we don't have any courses in the field that need modification, closing this issue.
