### ISSUE TITLE
Update exam title update

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2249]
can we have Update exam of [this] course/ steps?
right now it seems bit of lost when we look at the page.
![screenshot from 2018-10-02 07-36-35](https://user-images.githubusercontent.com/27276132/46325015-1fce6400-c616-11e8-99ca-0fcfb00959c8.png)

Also can we add "Delete" icon parallel to the question title in Add/Update Exam?
![screenshot from 2018-10-02 07-40-38](https://user-images.githubusercontent.com/27276132/46325625-eea36300-c618-11e8-9f28-f6faf9e40586.png)

Its done similar in Update course screen.
![screenshot from 2018-10-02 07-40-57](https://user-images.githubusercontent.com/27276132/46325629-f400ad80-c618-11e8-8c4f-9fd30d7b7fc4.png)

**Comment by paulbert** [comment]
For now let's just do the first part.  Add the course title to the blue toolbar so the course creator knows what they are working on.
