### ISSUE TITLE
Course step next navigation

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2253]
In case there is more than one step detail in course and exam in it.
Steps : 
1. Create first step with exam in it.
2.Create second step.
3. View the course step and take admission.
4. Go to first step and take exam.
Still next navigation icon is disabled.
So whats the condition to navigate next ?
![screenshot from 2018-10-02 08-19-33](https://user-images.githubusercontent.com/27276132/46326414-5313f180-c61c-11e8-959b-b5a237fc8ee3.png)

**Comment by paulbert** [comment]
Currently the condition is to have the exam be graded (can be done in "Submissions"), but as requested in  #2261 it should allow you to move on to the next step once you have completed the exam.
