### ISSUE TITLE
Courses admission button should show up when selecting course(s)

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/planet#2265]
![0 4 13-6](https://user-images.githubusercontent.com/13684059/46328024-c98c0180-c5d2-11e8-8a0e-0bb41b577bc4.png)

**Comment by singharpita** [comment]
can you elaborate it more?
admission button is shown on selecting courses.

**Comment by paulbert** [comment]
Closed based on images from @singharpita looks fixed
