### ISSUE TITLE
Course : your progress should not be shown when there is no step

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2276]
admission link is removed from individual course if there is no step.
But it get selected during bulk selection and then result in empty Your progress label.
![screenshot from 2018-10-04 19-16-17](https://user-images.githubusercontent.com/27276132/46477368-3e954c00-c80a-11e8-8d1a-3d6b14b104f5.png)
![screenshot from 2018-10-04 19-16-34](https://user-images.githubusercontent.com/27276132/46477388-47861d80-c80a-11e8-8cdd-55d6b3d0657c.png)

**Comment by lmmrssa** [comment]
approach should be to not do admission. As we only allow admission for course with exam we need to filter out course from admission if it does not have steps
