### ISSUE TITLE
Exam submission submit disabled bug

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2277]
in Submission exam,selecting any of the correct or incorrect choices is not enabling the submit button.

![screenshot from 2018-10-04 19-29-55](https://user-images.githubusercontent.com/27276132/46478189-1e668c80-c80c-11e8-9161-e9a077de2f46.png)

**Comment by singharpita** [comment]
its because submitted answer is showing blank in every case.

**Comment by paulbert** [comment]
Duplicate of #2262
