### ISSUE TITLE
View container should fit on screen

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#2283]
In some components the `view-container` is expanding beyond the screen size.  It should fit on one page.  There may be more situations where this needs to be fixed, but the issue is definitely on the following components:

ResourcesView
CoursesView
ReportsDetailComponent

Example:
![image](https://user-images.githubusercontent.com/9203229/46481530-93f93b00-c7c1-11e8-9a69-1cedd037ee9a.png)

**Comment by lmmrssa** [comment]
already fixed
