### ISSUE TITLE
Filter out satellite user in reports

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#2288]
It appears that the `satellite` user is being counted in reports in the user count.  We should filter that user out since it does not correspond to an actual registered member.

**Comment by nadaa** [comment]
Hi @paulbert, I will work on this, if possible?

**Comment by nadaa** [comment]
is there a component for repots?

**Comment by nadaa** [comment]
@Paul, can you please add more how to reproduce this issue?
What is a satellite user?
