### ISSUE TITLE
Add functionality for course buttons

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#230]
The following buttons in the list of courses need their own functionality (go to a new page or resign from course):

- [x] Open
- [x] Resign
- [x] Manage
- [x] View Course
- [ ] Credits
- [ ] Progress

**Comment by Pr0chin** [comment]
@paulbert do we need to add as same features as BeLL-App's course features or jst routing to new page for each button ???

**Comment by paulbert** [comment]
Let's add same features as BeLL-Apps where we are able with the course data that we are adding.  Otherwise route to a new page.

**Comment by yaoxing1990** [comment]
@paulbert @Pr0chin See https://github.com/ole-vi/planet/pull/248

**Comment by yaoxing1990** [comment]
@paulbert Are the course data ready?

**Comment by Pr0chin** [comment]
@paulbert  and @yaoxing1990 ok  :+1

**Comment by Pr0chin** [comment]
@paulbert I can start View Course Detail  as we have to render data that are added from Add course in to View Course Detail .

**Comment by yaoxing1990** [comment]
@paulbert @Pr0chin I have finished implementing "Manage course" button. See #259 .

**Comment by paulbert** [comment]
This is outdated
