### ISSUE TITLE
Courses: resource view which doesn't have file in it

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2304]
if choose the resources which doesn't have any file in it. opening up that resources result in page not found.

It should be redirected to the home page or the option should not be provided in Add resource list in case there is no file in the resources.

![screenshot from 2018-10-09 08-09-17](https://user-images.githubusercontent.com/27276132/46643228-e7d99a80-cb9a-11e8-8e3b-64988652fa75.png)

**Comment by svlesiv** [comment]
I created a new commit, but not sure what is the best way to redirect the page.

**Comment by svlesiv** [comment]
I will try a new approach: will disable/hide a 'View resource' button for a resource with no attachment in it.
