### ISSUE TITLE
Ignore blank data on reports

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#2312]
For ratings & resource_activities blank is log without `title` and for login_activities blank is log without `user` field.

**Comment by nadaa** [comment]
@paulbert, I am trying to produce this issue, I opened the report from the admin account, this is how it looks like:
![](https://i.imgur.com/xcES5Al.png)

there are some fields which are empty like (average rating, highest rate,..etc), shall we add a value such as 'no rating' or 0 instead?

**Comment by paulbert** [comment]
What I'm referring to is the below, where there are lines in the reports with visits/rating on the right but blank on the left.  We should filter out the data where `user` or `title` is blank so those lines do not show up.

![image](https://user-images.githubusercontent.com/9203229/46886663-89761b80-ce29-11e8-8d79-35b431c1a285.png)
