### ISSUE TITLE
Quick double click on rating can result in duplicate rating

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#2350]
Sometimes on ratings a quick double click can result in two ratings recorded for the same user.

We should maintain only one rating per user per.  Maybe adding the `planetSubmit` directive to the star click will help stop double clicks from happening.

**Comment by nadaa** [comment]
Hi @paulbert, I checked this, only one rating is saved for each user on a specific course!.

**Comment by paulbert** [comment]
@nadaa This works most of the time, but two ratings will be counted after a quick double click.  I will say the issue maybe only appears with specific hardware.

**Comment by paulbert** [comment]
Closing.  Not seeing this anymore.
