### ISSUE TITLE
Gender field is not replicated into child_users

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#2354]
The replication for user information from child -> parent is a little more complicated to keep passwords secure.

1. `_users` documents are pulled excluding password fields.
2. Those documents are inserted into the `replicator_users` database
3. The `replicator_users` database is replicated to the `child_users` database on the parent CouchDB.

In Step 1 if the admin did not fill out the full profile then it also excludes the `gender` field.

The root if the issue is in the `UserService.setUserAndShelf` method.  When setting `userProperties` we use only the properties for the currently logged in user, not all users.  We should check all users because the admin shouldn't be required to fill out the full profile.

**Comment by nadaa** [comment]
Hi @paulbert, I still couldn't reproduce this, I tried to create a new user and I found the gender property in _users!.

**Comment by paulbert** [comment]
Fixed in #2347
