### ISSUE TITLE
The program hangs when submitting an answer on an arithmetic question

### ISSUE THREAD

**Issue by svlesiv** [open-learning-exchange/planet#2355]
## Description
When submitting arithmetic related answer typed in an input field, the program is hanging.

## Screenshot
![screen shot 2018-10-18 at 10 01 24 am](https://user-images.githubusercontent.com/35533801/47161024-25d36e80-d2bf-11e8-9fe1-a83181296a94.png)

**Comment by paulbert** [comment]
Need to update the format of these exams on the dev so we don't see this issue in the future.

**Comment by paulbert** [comment]
Finished this by updating those documents on `dev`
