### ISSUE TITLE
Feedback title for users update form and profile page

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2371]
right now its showing as "Question regarding /users/profile/arpita" and "Bug regarding /users/update/arpita".
I think title should be managed for User.
![screenshot from 2018-10-23 07-35-15](https://user-images.githubusercontent.com/27276132/47330046-93ecac80-d696-11e8-94d1-77abf3c920ab.png)

**Comment by paulbert** [comment]
The title can be edited in the conversation, and I think leaving it as this auto generated message to start will help the person responding get a quick idea of the feedback
