### ISSUE TITLE
Invite member does nothing

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#2378]
On meetup we have **Invite Member** button. When trying to click on it does nothing. 
![screen shot 2018-10-23 at 08 08 47](https://user-images.githubusercontent.com/2909490/47331314-52aacb80-d69b-11e8-928f-de0bc6136d5d.png)
![screen shot 2018-10-23 at 08 11 29](https://user-images.githubusercontent.com/2909490/47331316-52aacb80-d69b-11e8-92cb-1b3227c5c143.png)

**Comment by paulbert** [comment]
Related to and will be fixed in #2347
