### ISSUE TITLE
Adding the view icon in password field

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2381]
<img width="556" alt="screenshot 2018-10-23 08 26 30" src="https://user-images.githubusercontent.com/6964191/47331963-84bd2d00-d69d-11e8-8d50-ee7c3fb796df.png">

I think it is better to put the view icon in the password field.

**Comment by paulbert** [comment]
Sounds like a good addition.  For an example of a similar icon in form field see `exams-question.component.html`.

And to clarify clicking this icon should switch the password from hidden to viewable.
