### ISSUE TITLE
Manager dashboard : Total ratings shows object object

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2396]
![screenshot from 2018-10-25 19-53-48](https://user-images.githubusercontent.com/27276132/47506588-20ae8a80-d890-11e8-8598-102ac6757d97.png)

**Comment by paulbert** [comment]
@lmmrssa @yuviii @dogi I cannot reproduce this error.  Can you try?

**Comment by jessewashburn** [comment]
Cannot reproduce.

**Comment by Mutugiii** [comment]
Cannot reproduce
