### ISSUE TITLE
Using filter does not clean selection

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#2399]
When we try to send survey. After filtering user list, and submitting.
It makes feel user that he/she is submitting only those which are visible but it is submitting all selected records.
https://drive.google.com/open?id=1ICOA8kR2qCV4HFRRO0gW8DvsWsat-WFa

**Comment by lmmrssa** [comment]
It seems to be case with filter in all cases. May be it will be better to show at least number of users selected so user knows there is still something which is being selected.

**Comment by paulbert** [comment]
Or a list of users at the bottom showing all of the selected users.  Note this should only happen for the DialogsListComponent.

**Comment by paulbert** [comment]
Let's have text with the number of selected items, and use a tooltip to show the list of items.

https://material.angular.io/components/tooltip/overview
