### ISSUE TITLE
Survey number of taken

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#2401]
Immediately after you send survey to someone. **Number of Times Taken** does not get updated.
But after you refresh it will show up

Immediately after Sending survey
![screen shot 2018-10-25 at 21 02 48](https://user-images.githubusercontent.com/2909490/47511288-9bc86e80-d899-11e8-9516-61e9bd2d3072.png)

After returning back to survey page
![screen shot 2018-10-25 at 21 04 30](https://user-images.githubusercontent.com/2909490/47511293-9cf99b80-d899-11e8-8ed4-f1f4c564065b.png)

**Comment by paulbert** [comment]
Another thought: maybe we should only count submissions that do not have `status: pending`?  Then it wouldn't update immediately after sending anyway.

**Comment by paulbert** [comment]
Regardless of my comment above, we can fetch the `submissions` again to update that number after sending the survey.
