### ISSUE TITLE
Resource Add/Update heading update

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2402]
Add/Update Heading should be "Add new Resource" / "Update Resource"
Right now its showing as "Add new resource" / "Update resource"

**Comment by BhargaviNadendla** [comment]
@singharpita can you please give more specific details about this issue as I cannot reproduce it

**Comment by lmmrssa** [comment]
@BhargaviNadendla its just case that needs to be changed.

**Comment by singharpita** [comment]
@BhargaviNadendla yes its about upper case and lowercase of resource
