### ISSUE TITLE
Survey/Exam submission status color codes

### ISSUE THREAD

**Issue by leahphuong** [open-learning-exchange/planet#2404]
<img width="1410" alt="screen shot 2018-10-25 at 11 25 58 am" src="https://user-images.githubusercontent.com/13629659/47512059-685df380-d849-11e8-941a-05071bab33ae.png">

<img width="1408" alt="screen shot 2018-10-25 at 11 25 48 am" src="https://user-images.githubusercontent.com/13629659/47512174-9e9b7300-d849-11e8-8ac3-89a1fdabbabb.png">

would be nice to have different colors for survey & exam submission statuses like in feedback status list.

**Comment by paulbert** [comment]
Sure.  It'll need to change based on surveys/exams.  For both gray for pending, then
**Exams**
* complete = yellow (accent)
* graded = blue (primary)
**Surveys**
* complete = blue (primary)
