### ISSUE TITLE
Add long answer option to exams/courses

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#2407]
We should have an option for a long text answer that will use the markdown text editor for surveys and exams.

**Comment by svlesiv** [comment]
Currently, it looks like this:
![screen shot 2018-10-29 at 2 25 08 pm](https://user-images.githubusercontent.com/35533801/47673688-bc3f4400-db8b-11e8-80b9-5a4bbf7aedb9.png)

![screen shot 2018-10-29 at 2 25 28 pm](https://user-images.githubusercontent.com/35533801/47673692-c2cdbb80-db8b-11e8-987d-6b6ce250b28c.png)
