### ISSUE TITLE
Report Detail: Most visited resource count is increased by 2 

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2415]
Most Visited Resources count increased by 2 rather than 1 on single visit to the particular resource.

**Comment by paulbert** [comment]
I'm unable to reliably reproduce this.  Could you provide some more details?

**Comment by lmmrssa** [comment]
@paulbert I was able to reproduce it. If you view any resource it is adding log twice.

**Comment by nadaa** [comment]
I checked it, only admin entries are doubled in resource_activties db.
