### ISSUE TITLE
Improve layout of a Feedback view page

### ISSUE THREAD

**Issue by svlesiv** [open-learning-exchange/planet#2418]
## Screenshot
![screen shot 2018-10-29 at 10 13 46 pm](https://user-images.githubusercontent.com/35533801/47691330-06461b00-dbc8-11e8-9ef0-56d663292d24.png)

**Comment by svlesiv** [comment]
Received feedback can be yellow:
![screen shot 2018-11-01 at 4 56 05 pm](https://user-images.githubusercontent.com/35533801/47880451-ae8ef600-ddf9-11e8-9c98-cc3b5e116509.png)

Written by a member feedback can be blue:
![screen shot 2018-11-01 at 4 56 37 pm](https://user-images.githubusercontent.com/35533801/47880550-e5650c00-ddf9-11e8-852c-f2c379e37d8e.png)

**Comment by lmmrssa** [comment]
@svlesiv I think full width message is good but let's keep the message section as grid so user do not have to scroll down to reply.
