### ISSUE TITLE
Full screen on editor

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#2420]
There is full screen mode on markdown editor which if confusing to use.
![screen shot 2018-10-30 at 07 59 13](https://user-images.githubusercontent.com/2909490/47691502-6bc2f780-dc1a-11e8-9338-9aab47123b99.png)
Button on image leads to look like this on next image. And its not clear how to return back. You have to press **Esc** key get back
![screen shot 2018-10-30 at 07 59 32](https://user-images.githubusercontent.com/2909490/47691415-11299b80-dc1a-11e8-8a10-707351bb53b2.png)

So we might want to clean some of these action

**Comment by paulbert** [comment]
Easiest fix is to remove full screen button until we find a better fix.

**Comment by svlesiv** [comment]
I fixed fullscreen overlap and will be working on some alternative way of exiting fullscreen, or will remove the button.

![screen shot 2018-11-05 at 6 22 14 pm](https://user-images.githubusercontent.com/35533801/48033664-33478000-e12a-11e8-974e-f2ed5c785c58.png)
