### ISSUE TITLE
Upgrade log extends beyond width of screen

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#2427]
This makes the top navigational menu flow off screen as well.  Log should have a horizontal scrollbar if some of the messages are too long.

![image](https://user-images.githubusercontent.com/9203229/47729149-07ae2c80-dc36-11e8-90c3-e5b49a56624c.png)

**Comment by yuviii** [comment]
@paulbert Could you please elaborate it more. If it needed to scroll horizontally when the logs text are longer, It has scroll auto and scrollbar is showing in my case when text are long.
