### ISSUE TITLE
course delete confirmation

### ISSUE THREAD

**Issue by yubarajpoudel** [open-learning-exchange/planet#2440]
It would be better to show the confirm dialog when delete option is clicked in the courses

**Comment by yuviii** [comment]
courses > manage

**Comment by paulbert** [comment]
Maybe we can have an undo button instead in CoursesAdd and ExamsAdd so the deletion can be reverted?

First step for that would be to just revert to the initial data when the user clicked manage.

Then we can think about more advanced undo that reverts each specific change.

**Comment by jessewashburn** [comment]
There is already a confirmation popup. If you want to implement being able to revert a deletion, we should create a new issue. Doesn't seem worth it though IMO.
