### ISSUE TITLE
Cannot create the new user : user becoming member

### ISSUE THREAD

**Issue by yubarajpoudel** [open-learning-exchange/planet#2470]
<img width="773" alt="screenshot 2018-11-07 12 06 25" src="https://user-images.githubusercontent.com/6964191/48114047-9a2d7c00-e285-11e8-910d-b6a3e313798a.png">
<img width="558" alt="screenshot 2018-11-07 12 06 10" src="https://user-images.githubusercontent.com/6964191/48114055-a1ed2080-e285-11e8-9942-fe48d302d866.png">

**Comment by svlesiv** [comment]
I was able to create a new member after deleting opts parameter in a signup method (pouch-auth.service.ts).
```
signup(username, password) {
    return from(this.authDB.signUp(username, password)).pipe(
      catchError(this.handleError)
    );
  }
```
![screen shot 2018-11-07 at 6 37 14 pm](https://user-images.githubusercontent.com/35533801/48168578-c5cc5880-e2bd-11e8-8f52-a8c165d5e43f.png)

But then I got some errors with authorization:
![screen shot 2018-11-07 at 6 49 51 pm](https://user-images.githubusercontent.com/35533801/48168613-f8765100-e2bd-11e8-9dc3-d590e1f06ed3.png)

I will try to solve this issue.

**Comment by yuviii** [comment]
@svlesiv Thank you. Did you manage to create the new member without deleting it?

**Comment by yuviii** [comment]
@paulbert @lmmrssa could you please check on this issues, i am unable to create the member after deleting the vagrant file and configuring again.

**Comment by svlesiv** [comment]
Hi @yuviii. No, I couldn't create the new member.

**Comment by paulbert** [comment]
Hi @svlesiv the opts parameter is very important to allow communities to auto accept members as learners.

The issue is that in the development environment the `couchdb-setup.sh` script doesn't appear to be updating the `_users` design document.
