### ISSUE TITLE
occupied space unnecessarily

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2476]
Back arrow is taking the whole screen space, It would be better to keep that option just left side of the toolbar befor OLE Test.

<img width="1440" alt="screenshot 2018-11-08 21 21 50" src="https://user-images.githubusercontent.com/6964191/48209100-714bda80-e39c-11e8-98ac-6b4d4d5e8935.png">

**Comment by YuserahN** [comment]
Do I, as an intern, have the option of updating an exam? I'd like to work on this issue, but I can't see this page in my dev planet.

**Comment by lmmrssa** [comment]
@YuserahN I don't understand your question as a intern option to update exam. It is the application and it is same application everyone is using.
Regarding not seeing this page. This is under course. So you need to add new course, and on course you can add steps. there you will get option to add exam

**Comment by YuserahN** [comment]
@lmmrssa I actually asked that question when I first started the internship, so I was a bit confused. I've figured out how to navigate the application since then.
