### ISSUE TITLE
Notify Learner re Feedback reply waiting in mailbox

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#2510]

**Comment by dogi** [comment]
Let's check how feedback is doing when there is an answer ...
bigger question is how many use cases we have to think about when testing

N(ation) C2 C(ommunity)

N to N
C to C
N to C
C to N
C to C2

more ?

**Comment by lmmrssa** [comment]
Right now feedback is shared between parent (Nation) and child (Community) based on where feedback is generated from. So feedback generated on one community will not be synced to another community.

**Comment by dogi** [comment]
what about E(arth) ?

**Comment by lmmrssa** [comment]
Current implementation will work for all cases below.
 - E to N
- N to E
- N to N
- N to C
- C to N
- C to C
- E to C
- C to E

Cases that does not work
- C to C2
- N to N2
