### ISSUE TITLE
Course Take Exam/Submission: Question title clarification

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2521]
In course take exam and submission form, question title is not shown.
Only question description and step title is shown.

![screenshot from 2018-11-15 20-37-21](https://user-images.githubusercontent.com/27276132/48560721-926d7780-e916-11e8-9cdd-1993163000fc.png)
![screenshot from 2018-11-15 20-37-57](https://user-images.githubusercontent.com/27276132/48560744-a3b68400-e916-11e8-84a9-adb9bc453755.png)

**Comment by paulbert** [comment]
Yes, that needs to be communicated better on the form.  Question title is only for organizational purposes for the course creator.

Maybe a tooltip on the title field when creating that says "Used only for organizational purposes".  Long term we can add this in to a course creation course and/or videos.

**Comment by svlesiv** [comment]
PR #3704
