### ISSUE TITLE
Join conflicts: courses

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2522]
On courses more option there is not option of join but when selected it highlight the join selected with count 1.

<img width="1408" alt="screenshot 2018-11-15 20 42 16" src="https://user-images.githubusercontent.com/6964191/48561001-23445300-e917-11e8-82f4-6e5995d6363d.png">
<img width="1409" alt="screenshot 2018-11-15 20 42 32" src="https://user-images.githubusercontent.com/6964191/48561002-23dce980-e917-11e8-8b56-a3a3ec3e5990.png">

**Comment by lmmrssa** [comment]
@yuviii can you look into course that does not have **Join** my initial assumption is that it does not have any steps. If you could add detail of course, it will help to implement that condition on **Join selected**

**Comment by yuviii** [comment]
Course does not have the step so it is not showing the join option, condition for the availability of the steps should be checked in join selected as well.
