### ISSUE TITLE
Notification "mark as read" toggle 

### ISSUE THREAD

**Issue by BhargaviNadendla** [open-learning-exchange/planet#2524]
Should there be a toggle button for "Mark as read" to "Mark as Unread" as well?

**Comment by lmmrssa** [comment]
@BhargaviNadendla **See All** only shows full list, so it shows whatever status notification has before.
Regarding toggle, right now we are not sure we will need this feature. **Mark as read** is there as there could be some notification which does not require action but we want it not to highlight on **Notification bell** anymore.

**Comment by paulbert** [comment]
I'm going to close this.  It's a good idea, but I don't think we will be ready to implement this in a helpful way in the short term.
