### ISSUE TITLE
Sort by rate not working properly: Resources

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2525]
<img width="617" alt="screenshot 2018-11-15 20 56 01" src="https://user-images.githubusercontent.com/6964191/48561864-0577ed80-e919-11e8-8cf2-f250690e304b.png">

**Comment by lmmrssa** [comment]
@yuviii Can you upload another image with sorting active. This image does not have any sorting implemented. If sorting is done then it should have icon showing on header. It seems to work for me and it is sorting based on **Average Rating** not rating you submit

**Comment by yuviii** [comment]
@lmmrssa  Here is the screenshot after clicking the rating to descending.

<img width="248" alt="screenshot 2018-11-15 22 30 49" src="https://user-images.githubusercontent.com/6964191/48567822-21ce5700-e926-11e8-8d2f-89d72c6d54dd.png">

**Comment by paulbert** [comment]
It appears the issue is occurring when there are alternating rated/unrated/rated resources.
