### ISSUE TITLE
Team: adding member notifications fixes

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2527]
1. User who is responsible for adding members to the team should not get notification regarding added members .
2. right now while adding new member, it only display "1 member(s) has been added to [teamname] team".
it is not clear which member is added to team when the team contain more number of members.
![screenshot from 2018-11-15 21-58-05](https://user-images.githubusercontent.com/27276132/48566131-28f36600-e922-11e8-9094-28d473cc30f6.png)
![screenshot from 2018-11-15 21-58-32](https://user-images.githubusercontent.com/27276132/48566143-2e50b080-e922-11e8-997e-a592441766f6.png)

**Comment by lmmrssa** [comment]
I think message is ok. But we might want to keep track of which member is added when. It will be new feature and will have to think about it if we want to implement it @paulbert @dogi

**Comment by paulbert** [comment]
I agree, 1 above we should fix, but 2 we should leave as is
