### ISSUE TITLE
Change title in rating popup window

### ISSUE THREAD

**Issue by svlesiv** [open-learning-exchange/planet#2538]
Connected #2192 

Currently, might be not clear what is the role of cancel and submit buttons in a rating popup window. Since the rating is recorded before popup appears and the most significant usage of the popup window is to leave a comment, I suggest changing the title of the popup window.

The title might look like this:
![screen shot 2018-11-19 at 6 18 18 pm](https://user-images.githubusercontent.com/35533801/48740977-8ab81680-ec27-11e8-965b-68d3292644f0.png)

**Comment by lmmrssa** [comment]
Also thinking about changing position of rating. So that it will state
**You rated** Rating stars
Then **Would you like to leave comment?**
@paulbert @dogi does that sound good?

**Comment by svlesiv** [comment]
Thanks for your suggestions @lmmrssa.
