### ISSUE TITLE
Password change issues: change password

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2540]
Entering the wrong old password it prevents from changing the password, but eventually displays wrong message box #2053
 
<img width="1440" alt="screenshot 2018-11-20 08 23 43" src="https://user-images.githubusercontent.com/6964191/48748161-f50b9e00-ec9d-11e8-82a3-632215459f31.png">
<img width="1440" alt="screenshot 2018-11-20 08 23 49" src="https://user-images.githubusercontent.com/6964191/48748184-09e83180-ec9e-11e8-9f33-0731d4b34deb.png">

**Comment by paulbert** [comment]
Related to #1527
