### ISSUE TITLE
Teams: Requested/Invited user should be removed from Add member list

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2561]
![screenshot from 2018-11-22 20-26-22](https://user-images.githubusercontent.com/27276132/48909263-ed621a00-ee94-11e8-8bf0-2f6775e51340.png)
![screenshot from 2018-11-22 20-26-30](https://user-images.githubusercontent.com/27276132/48909280-f3f09180-ee94-11e8-98bb-d9688c94195b.png)

There is similar issue for this and is not resolved i think.
https://github.com/open-learning-exchange/planet/issues/1674

**Comment by lmmrssa** [comment]
![screen shot 2018-11-22 at 20 31 07](https://user-images.githubusercontent.com/2909490/48910110-35823c00-ee97-11e8-880f-b20e4686c957.png)
Replicated closed old issue
