### ISSUE TITLE
"Next" button is not working on course step if that step has a resource attached

### ISSUE THREAD

**Issue by BhargaviNadendla** [open-learning-exchange/planet#2565]
There are 3 steps in total and the "next" is not working on step-2 since it is holding a resource

![image](https://user-images.githubusercontent.com/25775298/48911439-494a8580-ee38-11e8-9f6b-1beea85fba14.png)

**Comment by lmmrssa** [comment]
@BhargaviNadendla can you check if it has exam on step? It could be exam is added but does not have any questions.

**Comment by BhargaviNadendla** [comment]
Also the steps which doesn't have the exam are the same

**Comment by lmmrssa** [comment]
@BhargaviNadendla able to navigate with resource on course. So will have to further investigate on issue.
![screen shot 2018-11-22 at 21 36 50](https://user-images.githubusercontent.com/2909490/48912844-c9a3d180-ee9e-11e8-807e-cb3d440612b5.png)
![screen shot 2018-11-22 at 21 38 53](https://user-images.githubusercontent.com/2909490/48912927-0cfe4000-ee9f-11e8-949b-11f3d7169d36.png)

**Comment by yuviii** [comment]
@BhargaviNadendla @lmmrssa cannot generate this issues.
@lmmrssa @BhargaviNadendla @paulbert in case of multiple checkbox, it is generating the issue in next as the exam form is allowing us to be save or update without selecting correct answer.

**Comment by paulbert** [comment]
Closing. Can't replicate so I think this is fixed
