### ISSUE TITLE
Issue with pre taken exam

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#2570]
When you take exam that you have already taken. And you jump questions and submit. You will see **Continue Exam** And later even if you complete whole set of questions, it still gives you **Continue Exam**
![screen shot 2018-11-22 at 22 44 20](https://user-images.githubusercontent.com/2909490/48916041-daf1db80-eea8-11e8-89b8-33af4f8d2317.png)
![screen shot 2018-11-22 at 22 44 58](https://user-images.githubusercontent.com/2909490/48916013-c6adde80-eea8-11e8-8b4b-c0358f82403b.png)

**Comment by paulbert** [comment]
@lmmrssa So did you take an exam but only submit the last answer?  I think that would leave a pending submission open indefinitely.

@nadaa I think the practical thing would be to not allow the user to submit the last question if all questions have not been filled out.

**Comment by lmmrssa** [comment]
@paulbert Don't remember if it was last question but I did jumped some questions and take other questions. Which was never completing the exam even if i take all questions later

**Comment by nadaa** [comment]
@lmmrssa, do I need to create a new course with an exam to reproduce this?
