### ISSUE TITLE
Course exam: no validation on single multiple choice(single & multiple answer)

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2594]
![screenshot from 2018-11-28 07-22-40](https://user-images.githubusercontent.com/27276132/49122978-eb59ea00-f2de-11e8-902c-d57abbec7c4d.png)

**Comment by paulbert** [comment]
@singharpita Please open two issues rather than mentioning a separate issue in the comment.

**Comment by paulbert** [comment]
Is this issue about no validation on the questions when creating an exam?  If so I'll take this one.

**Comment by singharpita** [comment]
yes and also the multiple value field is saved as null
