### ISSUE TITLE
Some kind of text message of button: suggestions

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2600]
I think it would be better to show some text message for not having any question rather than blank view toggle after clicking it.

<img width="718" alt="screenshot 2018-11-28 08 35 56" src="https://user-images.githubusercontent.com/6964191/49125611-b783c200-f2e8-11e8-81aa-b068334bb54c.png">

**Comment by paulbert** [comment]
The blank part is due to no description of the step.  I agree we could improve this, maybe if there is no description just have the `button` in a regular `div` rather than `mat-action-row`?  And no expansion if there is no description, exam, or resource?

**Comment by paulbert** [comment]
For a step which has no description, exam, or resources we should show:

"There is no content for this step"

For a step which has no description, but has an exam or resources we should show:

"There is no description for this step.  There are X resources and the exam has Y questions."
