### ISSUE TITLE
Meetup : minor fixes.

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2616]
1. when only date present ,alignment is not proper.
![screenshot from 2018-11-29 20-47-29](https://user-images.githubusercontent.com/27276132/49230715-6d99f980-f418-11e8-844b-36e9140a5da9.png)
2. "-" should be removed when only start date is present.
3. add border to the invite member button so that it doesn't look like some heading or link.
![screenshot from 2018-11-29 20-47-13](https://user-images.githubusercontent.com/27276132/49230786-8b675e80-f418-11e8-96fe-d4ba7a933a99.png)

**Comment by paulbert** [comment]
For #3 it's `mat-stroked-button` instead of `mat-button`
