### ISSUE TITLE
Course: remove reousrces with no attachment from Add resource list.

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2619]
there was an issue for that https://github.com/open-learning-exchange/planet/issues/2304
but hiding the resources of no attachment from the course view ,gives the sense of confusion to the user.

I think better idea will be not to provide the given resource option that has no attachment in the Add resource list.

**Comment by lmmrssa** [comment]
@paulbert We can go with this approve for now. Later we might want to consider that some resource might have external resource not attachment, when we will be showing resource detail or external resource to view.
