### ISSUE TITLE
Course with video resources in multiple steps do not change

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#2621]
See below video for example.  The course has a different video on each step, but the video is always the same as you go through the steps.

The player should switch between the different videos.

https://www.useloom.com/share/7364c0655a4a445b93ba3d2c97297374

**Comment by nadaa** [comment]
@paulbert, I joined the Addition and Subtraction course, I can only view the first step, the next icon is disabled!
![](https://i.imgur.com/x5Grv6k.png)
