### ISSUE TITLE
Course Take Exam : multiple choice multiple answer fixes

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2622]
Steps to replicate:
Create an exam of type multiple choice multiple answer of atleast 3 or 4 choices.
Check every choice and submit the exam.
Take exam ,now choose only first option and click on submit.
it will show incorrect answer
continue doing this with remaining option and click submit after selecting a single value

Observed:
When last option is checked and submit then it will submit the answer.
'Expected:
the exam should only be submitted when all the option is checked.

**Comment by paulbert** [comment]
On ExamsViewComponent we should update `this.answers` when we click "Submit Answers" for the question type `multipleSelect`
