### ISSUE TITLE
Send Survey: question not updated 

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2624]
Steps to replicate:
Create a survey.
send it to any user.
Update the survey (Change question type)
Send it to the same user again.

Observed:
Question is not being updated.

Expected:
Question should be updated.

**Comment by svlesiv** [comment]
Also, the survey doesn't update if to add more questions. User will see only the first version of the survey.

**Comment by paulbert** [comment]
I don't think updating the submissions of other users on update is a good idea.  If one person sends the survey, and then another changes it the survey that is taken would not be the same as the initial person intended.

We should require that the survey is resent after changing, and show the latest version only in the member's "Surveys" page.  This will require a few changes:

- Sending the survey checks to see if a survey with that _id has already be sent to the member.  We should also check if the _rev matches.
- We'll have to reduce the survey list to only show the latest rev (in rev string the digits before the first `-` are a version number)

**Comment by paulbert** [comment]
Oh we should also add `createdDate` and `updatedDate` to surveys so we can keep better track of versions.
