### ISSUE TITLE
Courses: leave selected

### ISSUE THREAD

**Issue by svlesiv** [open-learning-exchange/planet#2643]
Maybe it would be nice to have a button which allows leaving multiple courses at the same time.

![psd009653e84856eb976202bb76401b8f660759b00a31d3d5dd8 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/35533801/49479159-030a0480-f7f0-11e8-821f-eb9c15694c63.jpg)

**Comment by paulbert** [comment]
We have space for it now, so I think we can add it.  It may be removed in the future since there may be more useful actions we want in that toolbar.
