### ISSUE TITLE
Submission: autoFocus shown for multiple choice single/multiple answer only

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2646]
autofocus or default value as correct is shown for multiple choice single/multiple answer but for short/long answer its missing.
i think consistency should be maintained. either show for all of them or not.
![screenshot from 2018-12-05 07-06-57](https://user-images.githubusercontent.com/27276132/49483840-f1127b00-f85c-11e8-9011-8e01e16469f4.png)
![screenshot from 2018-12-05 07-07-09](https://user-images.githubusercontent.com/27276132/49483841-f1ab1180-f85c-11e8-8680-4cdd97d30d05.png)
![screenshot from 2018-12-05 07-07-20](https://user-images.githubusercontent.com/27276132/49483842-f1ab1180-f85c-11e8-8a7a-f7298bf4e335.png)

**Comment by paulbert** [comment]
The multiple choice questions are auto-corrected so they are already filled in.  Closing, since there's nothing more to do here.
