### ISSUE TITLE
Exam answer issue

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#2651]
After creating exam with single choice, long text then multi choice
It disabled submit at last question (multi choice) then moving back to old question does not show previous answer
![screen shot 2018-12-05 at 07 57 44](https://user-images.githubusercontent.com/2909490/49485593-9fb9ba00-f863-11e8-9137-a3203c94980c.png)
![screen shot 2018-12-05 at 07 58 06](https://user-images.githubusercontent.com/2909490/49485594-9fb9ba00-f863-11e8-9331-2e15bf6e6a8b.png)

**Comment by paulbert** [comment]
@lmmrssa This is two separate issues, I think.  Initializing the question with the previously filled in answer hasn't ever worked, but we should make sure exams of different configurations are able to be finished first.

**Comment by paulbert** [comment]
Error is below.  My guess is that when switching questions `this.answer` isn't reset from the markdown.  Tested with the other three question types before the multiple answer and they all worked.

![image](https://user-images.githubusercontent.com/9203229/49487000-93574200-f80e-11e8-85ff-fd3daa5f13f0.png)

**Comment by nadaa** [comment]
Also I got this error when submitting:
![](https://i.imgur.com/6bUSaLQ.png)

**Comment by nadaa** [comment]
@paulbert, I have checked this, it's a binding issue in markdown, it's only one-way. Any suggestion how to solve this!

**Comment by paulbert** [comment]
Update above: #2667 only fixes showing the previous answer.  Does not fix `long text -> multiple answer` breaking issue.

**Comment by paulbert** [comment]
2nd update: #2667 now fixes this as well.
