### ISSUE TITLE
ResourcesAdd: Label shown as id

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#2653]
See below.  The label name should be shown, not the id.

![image](https://user-images.githubusercontent.com/9203229/49486566-f942ca00-f80c-11e8-9a0c-8025bbb78fdd.png)

**Comment by paulbert** [comment]
Happens when first opening the page when the tag has already been added.

**Comment by nadaa** [comment]
@paulbert, I can't reproduce this. The name appears no the id!

**Comment by lmmrssa** [comment]
@nadaa Steps to follow.
* Create resource with label
* Manage that resource
* It will show ID of label on edit page, but after you click on **Add Labels** button it will show tag again.
