### ISSUE TITLE
Resource: fixes

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2654]
- Resoruce Add form is allowing space " " in mandatory field.
Possible outcomes of this:
1. Resource is seen as blank in resource list page.
2. There is no option to open the resource ,as link is not there in options as well.(even there is attached file in it.)

![screenshot from 2018-12-05 08-23-22](https://user-images.githubusercontent.com/27276132/49486636-5ff4d180-f867-11e8-8843-d58c69d17a9f.png)

**Comment by paulbert** [comment]
Closing it's being worked on in #2390
