### ISSUE TITLE
Course View step: space needed between past attempts and page number

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2669]
when open in new tab button is not there, there is no space between past attempts and page number.
![screenshot from 2018-12-06 20-05-47](https://user-images.githubusercontent.com/27276132/49589896-a6931a80-f992-11e8-8fd8-649449a50ca2.png)

**Comment by paulbert** [comment]
Should use one of the `margin-lr-*` classes (where * = number of pixels for left/right margin)

**Comment by svlesiv** [comment]
Sorry, I assigned this issue before testing if I can reproduce it. After testing, seems that everything works well for me.

No attempts have been made:
![screen shot 2018-12-10 at 11 28 51 am](https://user-images.githubusercontent.com/35533801/49747043-899b6780-fc70-11e8-9312-067586583bdc.png)

Some attempts:
![screen shot 2018-12-10 at 11 25 42 am](https://user-images.githubusercontent.com/35533801/49747100-a46ddc00-fc70-11e8-9e2f-cb572419f92c.png)

When no exams present:
![screen shot 2018-12-10 at 11 25 56 am](https://user-images.githubusercontent.com/35533801/49747001-71c3e380-fc70-11e8-90fc-9b0d7727dd51.png)

**Comment by singharpita** [comment]
@svlesiv  steps to replicate:
-join any course which has step and exam.
- take the exam.
- leave that course.
-go to step view again.
