### ISSUE TITLE
Resource: file upload type fixes

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2673]
Scenario:
- Add resource.
- in the given resource , add the file of type .pptx.
- files get upload and resource is saved.
 - View/open the given resource detail.
- try to open or download the given uploaded file.
file is not being opened.  
Hence there should be some validation regarding supported format to upload the file at the time of saving the resource.

**Comment by paulbert** [comment]
It's a problem creating the link for download.  I'm not sure the root cause because it works on Chrome on Windows.  Tested with a file name with & without spaces.

**Comment by jessewashburn** [comment]
Cannot reproduce.

**Comment by Mutugiii** [comment]
Unable to reproduce
