### ISSUE TITLE
Title for my progress

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#2675]
When looking at progress of his/her own title of progress should not give name of user.
This is happening on 'My Progress' section. It should be 'My Course Progress'. If its showing progress of other user then it should have name of user.
![screen shot 2018-12-06 at 20 40 46](https://user-images.githubusercontent.com/2909490/49591767-7306bf00-f997-11e8-9e40-f9f9bbe3b1cc.png)

**Comment by svlesiv** [comment]
Hi @lmmrssa, in my version 0.6.9, the title doesn't have a username but a name of the course. Also, even so, I logged in under 'test' username, it shows the progress of another user - 'svlesivdev'.

![screen shot 2018-12-10 at 1 37 40 pm](https://user-images.githubusercontent.com/35533801/49753396-43023900-fc81-11e8-9b8f-c8098629c316.png)

**Comment by lmmrssa** [comment]
![screen shot 2019-01-10 at 20 49 46](https://user-images.githubusercontent.com/2909490/50977006-68e95a80-1519-11e9-822b-0947f95a3c9a.png)
![screen shot 2019-01-10 at 20 49 33](https://user-images.githubusercontent.com/2909490/50977012-6dae0e80-1519-11e9-9091-9bdf4c78767a.png)

**Comment by svlesiv** [comment]
Thanks for the response. Now I see the issue.

**Comment by svlesiv** [comment]
The above commit fixes issue when a title is undefined. 
But I'm not sure how to look at the progress of another user.
