### ISSUE TITLE
Creating Label trigger validation

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#2710]
Creating Label now makes form empty. But it is still triggering the validation and gives error message
![screen shot 2018-12-12 at 07 38 22](https://user-images.githubusercontent.com/2909490/49841777-02b9cc80-fde1-11e8-92cc-0e445391b3b5.png)

**Comment by paulbert** [comment]
Reference for AbstractControl.  One of these methods might work:
https://angular.io/api/forms/AbstractControl
