### ISSUE TITLE
Fetching resources/courses clicking on checkbox does not select

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#2711]
Need to use `$event.stopPropagation()` because clicking on the row & clicking on the checkbox both toggle value, meaning it quickly goes from `false -> true -> false` and appears to not change at all.

https://www.useloom.com/share/ec39b06e3d1f454b87fc28f970a3103d

**Comment by paulbert** [comment]
The important part got cut off in the video, so let me know if you have any questions about what the error is.

**Comment by lmmrssa** [comment]
#2862
