### ISSUE TITLE
Meetup update date issue

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#2712]
While trying to update meetup with the valid date
![screen shot 2018-12-12 at 07 45 21](https://user-images.githubusercontent.com/2909490/49842025-131e7700-fde2-11e8-97f2-34cfdbe9b412.png)
If we change date by key press with invalid date such as **29/11/2018** it shows error. If I revert it back to valid old date **11/29/2018** error remains and form does not submit
![screen shot 2018-12-12 at 07 45 11](https://user-images.githubusercontent.com/2909490/49842024-131e7700-fde2-11e8-836a-74dcd7b24ba4.png)

**Comment by singharpita** [comment]
i think that error shows because start date validate against current date.
so either we have to disable the start date on update or let the user submit the old value on update.

@paulbert @lmmrssa please provide feedback.

**Comment by paulbert** [comment]
Closing in favor of #3993
