### ISSUE TITLE
Angular update: 7.1

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#2722]

**Comment by AngelsProjects** [comment]
Can I take this issue? I'm working on it.

**Comment by paulbert** [comment]
Hi @AngelsProjects thanks for your interest working on the project.  Please check out issues labeled "Newbie Friendly" to start.  We also have an onboarding process if you want to work on the project continuously.  To start that you should join our Gitter room (https://gitter.im/open-learning-exchange/chat) and say hello to @/all

**Comment by paulbert** [comment]
Fixed in #2730
