### ISSUE TITLE
ManagerDashboard update nation layout

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2737]
It would be better to show the courses or resources counts available or disable the button if not any available .
<img width="1438" alt="screenshot 2018-12-13 20 40 26" src="https://user-images.githubusercontent.com/6964191/49946625-78c04f80-ff17-11e8-9b0c-49ada371f14c.png">

**Comment by lmmrssa** [comment]
@yuviii It is the list of resources or courses that are in nation (parent). Not related to something that community will get or keep track of. So this might not be required, it will just increase traffic to nation server.

**Comment by paulbert** [comment]
We can make this more clear that this lists all resources/courses on the nation.

We should make a few changes:
- Have a header to clearly denote this as nation/center resources/courses
- Remove the meetups button.  This functionality is not a priority.
