### ISSUE TITLE
Causing error when survey is clicked from non admin user

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2738]
I did
 - logout from the admin user
 - login from other user
 - clicked in the survey

<img width="781" alt="screenshot 2018-12-13 20 50 01" src="https://user-images.githubusercontent.com/6964191/49947258-e7ea7380-ff18-11e8-970b-da7ac68dba9a.png">

**Comment by paulbert** [comment]
This is an error related to #2050 and not due to the actions listed above.
