### ISSUE TITLE
Survey: correct choice error should not block add

### ISSUE THREAD

**Issue by svlesiv** [open-learning-exchange/planet#2741]
![screen shot 2018-12-13 at 10 15 47 am](https://user-images.githubusercontent.com/35533801/49947880-40d9ed80-fec0-11e8-8399-24a2de59f183.png)

**Comment by paulbert** [comment]
That error should not be possible on surveys.  I'm going to modify the title to add clarity to the issue

**Comment by svlesiv** [comment]
Everything works now. Cannot reproduce this bug again.
