### ISSUE TITLE
Deleted user if tries to login, throws username/pswd incorrect

### ISSUE THREAD

**Issue by BhargaviNadendla** [open-learning-exchange/planet#2744]
When a member is deleted by the admin and if the same user tries to login, it shows "username/password donot match" If would be better if shown "unauthorized' or something clearer

![image](https://user-images.githubusercontent.com/25775298/49948469-281a0980-feb9-11e8-8bef-59080ea143a9.png)

**Comment by paulbert** [comment]
Let's make the message: `Member <username> is not registered`

Note that the error message from CouchDB does not include information on whether or not the user exists.  You will need to do another request to get the user information to see if it exists.
