### ISSUE TITLE
Resource: console error in dev

### ISSUE THREAD

**Issue by svlesiv** [open-learning-exchange/planet#2754]
If to open resource page in a **dev**, it will give console error. Moreover, I am unable to create a lable or to see existing labels in a **dev**.

![screen shot 2018-12-13 at 11 51 33 am](https://user-images.githubusercontent.com/35533801/49954349-43434400-fece-11e8-957f-4255d356b2ee.png)

**Comment by paulbert** [comment]
The issue is appearing because the PlanetTagInputComponent cannot handle the case where there are no labels on the Planet.  We need to fix that so we don't have errors and we can add labels on a resource.

**Comment by svlesiv** [comment]
Now everything works for me without console errors.
