### ISSUE TITLE
Manage Sync: show in progress/loading when click on run sync

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2781]
right now ,one is able to click multiple times until the Admin Confirmation dialog box appear.
Which result in multiple dialog box appending to the screen one after another.

**Comment by paulbert** [comment]
We can fix this with the DialogsLoadingService now (start & stop methods).  We would start the spinner when the button is clicked and stop before the `confirmPasswordAndRunReplicators` function runs

**Comment by paulbert** [comment]
The changes should be made to the ManagerSyncComponent.
