### ISSUE TITLE
Filter specific fields on tables

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#279]
The basic filter for Material tables will match the string passed in by the user to any field in the data (including CouchDB ids).

Looking deeper into the [Material docs](https://material.angular.io/components/table/api), we can specify a `filterPredicate` which can customize how the table filters.

Let's add a function to the shared folder which takes an array of strings and returns a `filterPredicate` function that filters data on any fields matching those strings to be used on all of our tables.

Labeling this as MVP because it is a minimum requirement for the resources & feedback tables.

**Comment by lmmrssa** [comment]
Please look after the last PR https://github.com/ole-vi/planet/pull/369 and implement same for other list views

**Comment by paulbert** [comment]
Closing since this is implemented
