### ISSUE TITLE
Member login (visit) not updating correctly

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#2800]
When user logged in and logout and again login it is not changing the count. Both Dashboard visit and manager report is not reflecting it.
In image below user **e** has been logged in and logged out couple of times but it is still showing 1 count.
![screen shot 2018-12-20 at 20 09 18](https://user-images.githubusercontent.com/2909490/50290315-6011e580-0493-11e9-85e6-b11bc3b14482.png)

**Comment by paulbert** [comment]
A new session will be created if you refresh the browser, so the issue is that the service is set to retain old information, but it doesn't get reset on logout.

To fix we should set `sessionRev` and `sessionId` to `''` in `UserService.unset()`
