### ISSUE TITLE
FeedbackView: Close/open button not updating

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#2803]
The close/open button on Feedback view is not updating after the change on the database to reflect the new status.

After the database success message, the text of the button should toggle to open or close to reflect the new status.

https://www.useloom.com/share/104e56b8579e415b95ffe009ec0dd9ca

**Comment by lmmrssa** [comment]
Feedback data is not updated in this case. So clicking it again causes document conflict error as well.
