### ISSUE TITLE
Member visit on dashboard

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#2827]
Initially there is **32** visits. Even after logout and login it shows same.
![screen shot 2018-12-26 at 07 13 27](https://user-images.githubusercontent.com/2909490/50428357-30be0700-08df-11e9-90bc-f1287ba1a54e.png)
Only after refresh visit count change to **33**
![screen shot 2018-12-26 at 07 14 02](https://user-images.githubusercontent.com/2909490/50428360-387dab80-08df-11e9-8240-2e544dcf5e2d.png)

**Comment by yuviii** [comment]
@lmmrssa cannot generate this issue in dev. 
 i logged in and logged out and found the visit count is increasing.

**First**


<img width="365" alt="screenshot 2018-12-27 15 46 55" src="https://user-images.githubusercontent.com/6964191/50476040-b1b7f400-09ee-11e9-86c6-f02589fce66e.png">

**After login and logout**

<img width="466" alt="screenshot 2018-12-27 15 47 08" src="https://user-images.githubusercontent.com/6964191/50476047-b7add500-09ee-11e9-98c4-f9ee3913a09b.png">

**Comment by jessewashburn** [comment]
This is no longer part of the UI. Cannot reproduce the issue in the No. of visits shown in the manager dashboard.
