### ISSUE TITLE
visit count does not update

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#2828]
On manager dashboard under single line summary Resource visit does not change. Last login, upgrade etc are updating.
![screen shot 2018-12-26 at 07 14 21](https://user-images.githubusercontent.com/2909490/50428396-8397be80-08df-11e9-9ef3-6ca8697ee26a.png)
NOTE: Resource visit shows changes on Report Details

**Comment by singharpita** [comment]
Also Total Ratings count is not correct.
Can the label of Total Visits label should be changed to Total Visits(Resource)?
