### ISSUE TITLE
Exam/Survey: do not allow answer with just spaces

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2845]
Steps to replicate:
-create an exam in such a way so that first question will be multiple choice single answer, second will be short answer or long answer.
- join the particular course.
- take the exam but in short answer enter only space.
- go to submissions.
- grade the exam.

Observed:
short answer will show the value of multiple choice single answer instead of blank value.
![screenshot from 2018-12-27 20-27-00](https://user-images.githubusercontent.com/27276132/50483878-d07db100-0a15-11e9-9ed3-f7ed79732226.png)
![screenshot from 2018-12-27 20-26-49](https://user-images.githubusercontent.com/27276132/50483879-d07db100-0a15-11e9-9165-4d14a9e3a1dd.png)

**Comment by paulbert** [comment]
We should instead fix the answers so that an answer that is just a space is invalid.

There is an open PR for that #2390 which could fix this as well

**Comment by lmmrssa** [comment]
#2390 did not fixed it.
