### ISSUE TITLE
Team archive

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#2846]
Team is not archiving when last user leaves. It works fine when done from team list view #1623 but when done from Dashboard it just remove user from team and does not archive.
Also this can be related to #1708.

**Comment by lmmrssa** [comment]
![screen shot 2018-12-27 at 20 39 53](https://user-images.githubusercontent.com/2909490/50484386-6dd9e480-0a18-11e9-96c6-75115b2ca49e.png)
![screen shot 2018-12-27 at 20 39 59](https://user-images.githubusercontent.com/2909490/50484387-6e727b00-0a18-11e9-9643-7b27a9c3b6fe.png)

**Comment by paulbert** [comment]
Yeah, this is related but different than #1708.  Please work on in different PRs
