### ISSUE TITLE
Meetup: layout fixes

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2851]
1. Meetup title is showing in header as well in body of the meetup.
2. Recurring and Recurring days should be placed together.
![screenshot from 2018-12-27 21-16-37](https://user-images.githubusercontent.com/27276132/50485324-f22e6680-0a1c-11e9-8512-1adfd5994f88.png)

**Comment by paulbert** [comment]
For 2 please change the order of the elements so recurring is followed by recurring days
