### ISSUE TITLE
More info on progress char

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#2856]
On leader progress chart we can click on steps to filter progress report based on that step. But it is not clear for users that it can be clicked and it will filter report. So may be having title on boxes which will show when hovered over and explain filter report by step 2 will be nice to have.
![screen shot 2018-12-27 at 21 34 04](https://user-images.githubusercontent.com/2909490/50486056-1f304880-0a20-11e9-8214-97f2c6eb03df.png)

**Comment by paulbert** [comment]
We can have a tooltip with "Click to see exam detail"
