### ISSUE TITLE
Request to join button is not updating : Team

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2861]
I did
 - clicked the team which is already joined
 - clicked leave and request to join from team detail
 - when pressed back in team list page, the request to join button is not updated.

Team name 'another-team' in this case 

**Team leaved and request to join is clicked**

<img width="1418" alt="screenshot 2018-12-27 22 25 25" src="https://user-images.githubusercontent.com/6964191/50487683-65d57100-0a27-11e9-8687-106c52c3013d.png">

**After navigation back to team list**

<img width="1274" alt="screenshot 2018-12-27 22 25 54" src="https://user-images.githubusercontent.com/6964191/50487675-5d7d3600-0a27-11e9-81d2-821300001ce5.png">

**Comment by lmmrssa** [comment]
Could not replicate on production as well. closing this issue
