### ISSUE TITLE
Member list not showing for nation and center

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#2879]

**Comment by lmmrssa** [comment]
![screen shot 2019-01-02 at 07 26 00](https://user-images.githubusercontent.com/2909490/50578288-dc2b0680-0e5f-11e9-81a8-a9f5cb5c34f3.png)

**Comment by paulbert** [comment]
Due to old users without `planetCode` field.  Fixed on `dev`

**Comment by dogi** [comment]
need to fix stuff on:
- [ ] dev
- [ ] somalia
- [ ] earth
- [ ] vi

**Comment by dogi** [comment]
also do touch `satellite` user ... planetcode needed there ;)
