### ISSUE TITLE
Dropdown filter for table handling undefined fields

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2885]
![screenshot from 2019-01-02 08-10-29](https://user-images.githubusercontent.com/27276132/50578766-45ae1380-0e66-11e9-8024-b2ab18fb24f6.png)

**Comment by paulbert** [comment]
Error is caused by filter values for the table that are undefined.  See `dropdownString` in `table-helpers.ts`

We should handle the case of undefined as if the value is an empty string.
