### ISSUE TITLE
Exams: Error in continuing exams

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2888]
Steps i did to test:
 - First take the exam
 - Selected the multiple answer in second question but not submitted and clicked back
 - Again try to retake the same exam
 
After, Following screen shows up with following console error

<img width="1385" alt="screenshot 2019-01-02 08 56 49" src="https://user-images.githubusercontent.com/6964191/50579494-747bb800-0e6d-11e9-865c-c61701b23cce.png">

**Comment by paulbert** [comment]
Could you copy the submission document from the database into a comment here?

**Comment by paulbert** [comment]
Ok I will close this issue, then.  Thanks!
