### ISSUE TITLE
Update Survey: validation the options are checked or not

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2909]
I did
 - Added the new survey
 - Edit the survey
 - Without adding the title i tried to update to create the validation false
 - Clicked the add question
 - First question i added short answer
 - Return to list
 - Again added new question
 - This time when selected the multiple or single choice it ends up with validation message

<img width="1424" alt="test" src="https://user-images.githubusercontent.com/6964191/50646469-3b8f3080-0f9e-11e9-9e67-37e90ad67e87.png">

**Comment by paulbert** [comment]
Survey should not see that error at all, so that's also an issue.
