### ISSUE TITLE
Delete empty network (hub)

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#2911]
If we create any hub (network) and want to delete or edit. There is no option right now.
Hub should only be deleted if there is no spoke connected.
![screen shot 2019-01-03 at 21 38 44](https://user-images.githubusercontent.com/2909490/50647202-14d1f980-0fa0-11e9-9bae-a2fcb284c020.png)

**Comment by paulbert** [comment]
I think we can allow deletion regardless of whether there are any spokes connected as long as they revert to the Sandbox after deletion.
