### ISSUE TITLE
Clearing off multiple collections when trying to clear one

### ISSUE THREAD

**Issue by BhargaviNadendla** [open-learning-exchange/planet#2912]
Can start to see from 0:25 Minute

https://www.useloom.com/share/01cc954259774016a91cfd3c2c74acde

**Comment by BhargaviNadendla** [comment]
@paulbert I found that the collections are being mis-placed and couldn't replicate it again. Thank you!

**Comment by paulbert** [comment]
Ok I can't replicate either, so closing
