### ISSUE TITLE
Courses: Rating stars are not highlighted

### ISSUE THREAD

**Issue by yubarajpoudel** [open-learning-exchange/planet#2920]
In Image below though course title 'test course'  has 4 rating showing in right side the stars are not highlighting

<img width="932" alt="screenshot 2019-01-04 22 37 48" src="https://user-images.githubusercontent.com/6964191/50700034-a198b800-1071-11e9-99f2-3ca932399ff0.png">

**Comment by paulbert** [comment]
@yuviii The stars highlighted are for the currently logged in member's rating.  If the "4" rating is not from that member, then no stars will be highlighted.

**Comment by lmmrssa** [comment]
Not valid
