### ISSUE TITLE
CourseAdd: validation error on course title is still showing on addition of new course

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2939]
![screenshot from 2019-01-09 07-33-25](https://user-images.githubusercontent.com/27276132/50870646-fe350380-13e0-11e9-83a5-bc1d7f476988.png)
its the case of adding new courses

**Comment by paulbert** [comment]
The course is added to the database when adding an exam (so the exam changes are saved every time that we exit that form).  The problem is that when adding a new course the validator doesn't take that into account so the title now exists on the database throwing this error.
