### ISSUE TITLE
Resource Add to Library: add success message fixes

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2940]
right now after adding resources to library it shows message "Resource added to library"
![screenshot from 2019-01-09 08-04-42](https://user-images.githubusercontent.com/27276132/50871910-6ab20180-13e5-11e9-9574-55eeb7ce854c.png)

It will be better if it shows the count of resource added to Library.

**Comment by YuserahN** [comment]
@singharpita I think this issue has already been resolved. 
![image](https://user-images.githubusercontent.com/21087353/52656391-de02d380-2ebb-11e9-901f-b01721968172.png)
