### ISSUE TITLE
Add resource: gray color for added by 'author name'

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2961]
It would be better to make author name in added by section color gray since this field cannot be edited.

<img width="1022" alt="screenshot 2019-01-10 21 00 49" src="https://user-images.githubusercontent.com/6964191/50977799-23c62800-151b-11e9-971e-bce706019f2e.png">

**Comment by paulbert** [comment]
Let's make this a broader change for all `readonly` inputs

I'd recommend also checking [material.io](https://material.io) for guidelines on how this could look
