### ISSUE TITLE
Resource: Create new collection taking space result in empty collection/label in list

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2964]
add space in Collection input field. It allows to add the space and result into this
![screenshot from 2019-01-10 21-38-22](https://user-images.githubusercontent.com/27276132/50980248-5f172580-1520-11e9-8b5a-32d7aa0b0c1b.png)

**Comment by paulbert** [comment]
Closing, already working on the broader issue & new validator in #2390
