### ISSUE TITLE
Home navigation link active highlight

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2986]
home navigation link should be highlighted when selected as similar to other navigation link.
![screenshot from 2019-01-16 07-11-05](https://user-images.githubusercontent.com/27276132/51220629-14e9d600-195e-11e9-90ea-7ef2395a81fd.png)
![screenshot from 2019-01-16 07-10-51](https://user-images.githubusercontent.com/27276132/51220630-14e9d600-195e-11e9-83f4-d4084ad377b2.png)

**Comment by paulbert** [comment]
Make sure to use the exact route for home (`/`), otherwise it will match every route.
