### ISSUE TITLE
Sipnner Loading 

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#2987]
Spinner was worked on #2051 There are still some pages we could use spinner on data loading. 
Such as submissions, surveys.

**Comment by paulbert** [comment]
#3012 fixed some of these.  There are reports & other manager pages that could still use a spinner during loading.

**Comment by BhargaviNadendla** [comment]
Sure! Will fix them soon

**Comment by paulbert** [comment]
Closing. Outdated.
