### ISSUE TITLE
Resource: Edit collection cancel message

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2990]
when cancel is clicked , it still shows **Collection Updated**
![screenshot from 2019-01-16 07-48-37](https://user-images.githubusercontent.com/27276132/51221853-4b761f80-1963-11e9-96ca-c98f54152cd1.png)
![screenshot from 2019-01-16 07-48-27](https://user-images.githubusercontent.com/27276132/51221854-4b761f80-1963-11e9-95cc-ba9dba054b4a.png)

**Comment by paulbert** [comment]
This may be related to #1739. If so we should work on that refactor to make this change easier.

**Comment by paulbert** [comment]
And to clarify, after clicking "Cancel" there should not be a message at all.

**Comment by jessewashburn** [comment]
This has been fixed.
