### ISSUE TITLE
Submission: Updated on showing in timestamp both in exam and survey

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2994]
![screenshot from 2019-01-16 08-23-19](https://user-images.githubusercontent.com/27276132/51222971-128c7980-1968-11e9-8f71-3171f3ec0b0d.png)

**Comment by paulbert** [comment]
Hmm https://github.com/open-learning-exchange/planet/blob/master/src/app/submissions/submissions.component.html#L51

Maybe the pipe is only applying to the false part (null) of the ternary expression?
