### ISSUE TITLE
course progress label

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3006]
There is tooltip on hover over label of progress if label is long as can be seen on image below.
![screen shot 2019-01-17 at 20 28 41](https://user-images.githubusercontent.com/2909490/51326224-b6744300-1a96-11e9-9825-19246e5a1d7d.png)
But for some reason hovering over second last course is not showing tooltip. 
![screen shot 2019-01-17 at 20 28 32](https://user-images.githubusercontent.com/2909490/51326200-a8bebd80-1a96-11e9-99e4-dc3f2ac6eebd.png)
May not be case of it being on second last but its title being short. Its title is **Second**. Either we need to show its full title or have tooltip

**Comment by singharpita** [comment]
couldn't replicate this issue.
@lmmrssa 
![screenshot from 2019-01-28 21-46-12](https://user-images.githubusercontent.com/27276132/51848694-28297800-2346-11e9-8ecc-cc7251491e4b.png)

**Comment by jessewashburn** [comment]
Couldn't replicate. 
![image](https://github.com/user-attachments/assets/c57475d1-fef4-4d18-8a69-3754934d5a38)

**Comment by Mutugiii** [comment]
Unable to reproduce
