### ISSUE TITLE
Add collection: button text update

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3034]
While adding/updating the collection, button has text "OK".
Can it be changed to "Add" or "update" or "Submit".
![screenshot from 2019-01-24 20-44-46](https://user-images.githubusercontent.com/27276132/51686853-58f17080-2019-11e9-9919-569634bcb2ee.png)

**Comment by paulbert** [comment]
Since we don't add, update, or submit anything until the resource form is completed and submitted, I think OK is the best word to use here.  Closing.
