### ISSUE TITLE
AchievementsUpdate: Reorder & delete for lists

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3035]
can there be delete option for the section that can be added number of times?

![screenshot from 2019-01-24 21-03-14](https://user-images.githubusercontent.com/27276132/51688020-c7373280-201b-11e9-80a4-6a71917b1c49.png)

**Comment by paulbert** [comment]
Let's also add functionality to reorder these lists in the same PR.

Ideally, let's look into modifying `planet-step-list` for this page since it has delete & reorder functionality built in.

**Comment by paulbert** [comment]
Hi @svlesiv I'd like to keep this moving along so I'm sorry, but I'll take this one.

**Comment by svlesiv** [comment]
Hi @paulbert, sure. I was planning to finish it tomorrow, but it will be interesting to see how you implement this feature.
