### ISSUE TITLE
Feedback: show default title when blank

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3036]
Feedback by default has title which you can edit. If you completely remove title of feedback it still shows as below on feedback page.
![screen shot 2019-01-24 at 21 05 32](https://user-images.githubusercontent.com/2909490/51688248-49bff200-201c-11e9-8fa8-1d83dd35090d.png)
Which if you look on edit will show empty
![screen shot 2019-01-24 at 21 05 38](https://user-images.githubusercontent.com/2909490/51688250-49bff200-201c-11e9-970a-5dd2d669d5fa.png)
Also list page will not show it.
![screen shot 2019-01-24 at 21 05 22](https://user-images.githubusercontent.com/2909490/51688247-49275b80-201c-11e9-9112-da9773ac17d3.png)
Shall we show default title even on list or not allow to make the field empty?

**Comment by paulbert** [comment]
I think we should show the default title on the list if blank as well.

Not sure how to best communicate that when editing the title.  Maybe look into what options Material has.
