### ISSUE TITLE
Change Add Resource to Link Resource

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3071]
Right now on Courses we have **Add Resource** looks like user try to add resource from there not knowing it only link old available resources. So we might want to change that button into **Link Resource** or something appropriate.

**Comment by paulbert** [comment]
I think for nontechnical people "Link" is confusing/may not convey the right information.

Let's leave this as is.  Once we get some more feedback from the field we can reassess if needed.
