### ISSUE TITLE
Resource Detail: N/A when fields are empty

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3086]
to maintain consistency, its better to have N/A in all empty fields.
![screenshot from 2019-01-31 20-39-12](https://user-images.githubusercontent.com/27276132/52062319-6cac5200-2598-11e9-85b1-4f1525e28a8f.png)

**Comment by paulbert** [comment]
Rather than showing `N/A`, let's simply hide the header for any field that is empty.
