### ISSUE TITLE
Achievements: There is no way to see the full description if a description is long.

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3087]
<img width="1438" alt="screenshot 2019-01-31 20 36 51" src="https://user-images.githubusercontent.com/6964191/52062432-98c7d300-2598-11e9-9df0-7ff4e1aeb2cc.png">

**Comment by paulbert** [comment]
https://stackoverflow.com/questions/42023559/angular-2-material-show-full-text-for-the-list-items

I think this change will fix it in a way that still looks good.  Note we should make sure this CSS change is limited to this component.
