### ISSUE TITLE
Team : Request to join conflict

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3092]
- Add new Team.
- Go to the View Team.
- Leave the team (before adding any members in it).
- Request to join the team.
It shows console error and also not changing the status to Request Pending.
![screenshot from 2019-01-31 21-13-15](https://user-images.githubusercontent.com/27276132/52064785-68cefe80-259d-11e9-9554-5a9a699072a8.png)
Now Refresh the page and click on Request to join.
Status will change to Request Pending

**Comment by paulbert** [comment]
This is the same root error as #3080.  When the change is made to the `teams` document the revision is not updated in the app.
