### ISSUE TITLE
Achievements: Update failing, spinner keeps on loading

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3111]
![screenshot from 2019-02-06 07-20-06](https://user-images.githubusercontent.com/27276132/52315591-a4bff480-29df-11e9-958b-e3150b6b9269.png)

**Comment by paulbert** [comment]
Need to call the `onSubmit()` function as a click handler of the **Update** button instead of as a submit handler of the form.

We should also then change the **Update** button to `type="button"`
