### ISSUE TITLE
FeedbackView continuous feed not working

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#3117]
For the feedback message page we are checking the _changes endpoint with the continuous option (see https://docs.couchdb.org/en/stable/api/database/changes.html) to update messages in real time.  That worked in previous versions, but it no longer works now.

To see the issue, open two windows & log in as different users.  Go to the same feedback conversation & write a message from one of the users.  Now the other user can no longer add new messages to the conversation because of a conflict.

**Comment by lmmrssa** [comment]
looks like its working right now.
