### ISSUE TITLE
Achievement Add Resources: UI fixes

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3135]
Can Edit, Delete and move button is aligned properly and next to Achievement title?
![screenshot from 2019-02-07 20-00-17](https://user-images.githubusercontent.com/27276132/52417144-4d22a580-2b13-11e9-81ef-9045ef931c2a.png)

**Comment by singharpita** [comment]
Also spacing between last Achievement's Resource tag and Add Other Information.
![screenshot from 2019-02-07 20-08-19](https://user-images.githubusercontent.com/27276132/52417565-46486280-2b14-11e9-9ede-9accc01d6a57.png)

**Comment by paulbert** [comment]
For the first, alignment question we can try vertically aligning these buttons to the top, but it may mess up the alignment when there is only one line of text.  I think it may be best to leave it aligned in the center.

For the second comment:
1. Let's make sure to not simply arbitrarily increase the spacing there.  If we change this it should match the spacing between the first achievement and the Add Achievement button
2. We can add a little more space between the list items (0.25rem) so the buttons no longer touch.
