### ISSUE TITLE
Achievements: change title edit to add achievement when achievement has not added.

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3137]
I think it would be better the change the button label `edit achievement` to `Add achievement` when user has not entered any achievement. Also the icon + instead of pen icon in add like as in resources and courses.

**Comment by paulbert** [comment]
Let's not change the icon, but the text can change.  We also need to make sure the text in the `achievementNotFound` block is updated based on this change.

**Comment by YuserahN** [comment]
If there are no achievements, the user profile does not display the Achievements button at all. Otherwise, it displays 'View Achievements,' rather than 'Edit Achievements.'
