### ISSUE TITLE
Achievement: Space handling in Add Achievement and Add other information

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3138]
right now it allows to enter space in text field. Could there be validation similar to Course or Library when entering space only in text field?
![screenshot from 2019-02-07 20-39-36](https://user-images.githubusercontent.com/27276132/52419742-cf619880-2b18-11e9-880e-998c90c5c496.png)
![screenshot from 2019-02-07 20-39-25](https://user-images.githubusercontent.com/27276132/52419743-cf619880-2b18-11e9-95ae-681a671fe0b2.png)

**Comment by paulbert** [comment]
OK, we should use our custom required validator in the form in the dialog for Achievements and Other Information
