### ISSUE TITLE
Achievement: show the selected resources in dialog

### ISSUE THREAD

**Issue by yubarajpoudel** [open-learning-exchange/planet#3140]
I think it would be better to show something like `two resources selected` when resources is selected in the dialog.

<img width="1429" alt="screenshot 2019-02-07 20 53 30" src="https://user-images.githubusercontent.com/6964191/52420649-94f8fb00-2b1a-11e9-83d9-9bf2f192ea84.png">

**Comment by paulbert** [comment]
Requires a change in the DialogsFormComponent.  Can probably include something similar to the implementation for showing selected collections.

**Comment by paulbert** [comment]
Closing in favor of #3786
