### ISSUE TITLE
Member Profile : Add the icon of view in view achievement

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3141]
I think it would be better to add the icon in view achievements button and make the button like rest two.

<img width="724" alt="screenshot 2019-02-07 21 02 06" src="https://user-images.githubusercontent.com/6964191/52421253-cde59f80-2b1b-11e9-95d7-e3182ab9a9c7.png">

**Comment by YuserahN** [comment]
Can you tell me which file this is in?
