### ISSUE TITLE
Achievements: View child achievements

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#3142]
After syncing from a community the link to view an achievement on the nation does not work.

For child users the link to view the profile includes the full id with the community code in it (i.e. user **paul** on community **pb** would have the id in `child_users` **paul@pb**).  In the component the `@parentCode` is being added again for the queries, which is causing the incorrect id to be queried for with child users (see request in image below).

![image](https://user-images.githubusercontent.com/9203229/52421354-e5903a00-2ac1-11e9-8947-0ad4073a3e14.png)

**Comment by paulbert** [comment]
And to specify, let's change the `AchievementsComponent` to handle this condition.  If the `name` parameter already has an `@` symbol in it we should not add it again.

**Comment by lmmrssa** [comment]
@paulbert  I was able to see user lax@lprod achievement on dev.

**Comment by paulbert** [comment]
This problem only arises when navigating to the user's achievements through the "Associated" list of members.  This includes the admins from the various children attached to the planet.  The admin users should not be used as a "learner", so should not have achievements in the field anyway.  In case they do get used for this purpose, we should still fix the link.

Based on this removing the "priority" label.
