### ISSUE TITLE
UsersProfile: do not show Achievements link if no doc

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#3143]
On the UsersProfile the **View Achievements** link is always present no matter what.  If there is no achievements doc for that user we should hide this button.

**Comment by YuserahN** [comment]
Paul, the View **Achievements link** is not present on my profile and I don't think I have an achievements doc. 
![image](https://user-images.githubusercontent.com/21087353/52497919-f3ff5400-2b9c-11e9-9b36-f45a559c9e44.png)

**Comment by YuserahN** [comment]
Paul, my profile does not display the **View Achievements** link. And I don't think I have an achievements doc. 

![image](https://user-images.githubusercontent.com/21087353/52497992-2ad56a00-2b9d-11e9-9ffc-a653bc5fa7f8.png)

**Comment by yuviii** [comment]
@YuserahN yes if you don't have achievement , the view achievement button become invisible. It will show only if the user has achievement.
