### ISSUE TITLE
Page load issue

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3145]
**I did**

 1. close the page from browser without logged out
 2. Again opened the page in browser

After that navigation menu is not working throwing the error

<img width="746" alt="screenshot 2019-02-07 21 44 57" src="https://user-images.githubusercontent.com/6964191/52424333-e5c02200-2b21-11e9-8ace-31874b9f23c6.png">

**Comment by paulbert** [comment]
Duplicate of #2050
