### ISSUE TITLE
Feedback: error once the feedback is close and try to send again

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3170]
Steps i did:
 1. open the feedback view
2. press the close button
3. And try to reply

The close button should be change to re-open after close button is pressed and should give the message to user if the user try to send message after closing the feedback.

<img width="1440" alt="screenshot 2019-02-13 08 30 05" src="https://user-images.githubusercontent.com/6964191/52683204-3bedf480-2f6a-11e9-8d3e-9193484a251c.png">

**Comment by singharpita** [comment]
could not replicate this error. When closing button is changing to 'Re-open' and once replied it will open the feedback again. That should be intended functionality

**Comment by yuviii** [comment]
@singharpita please try to reply without navigating to the back

**Comment by singharpita** [comment]
@yuviii  its not updating the page when close or re-open button is clicked

**Comment by ArashDai** [comment]
I had trouble recreating this as well, it only seems to happen sometimes. following your steps @yuvii exactly did not cause it to happen, but going back and forth between opening and closing the feedback did cause it to happen for me at some point

**Comment by ArashDai** [comment]
so far as i can tell sometimes the close/re-open button gets "stuck" on close sometimes which is causing this to happen
