### ISSUE TITLE
Dashboard : Long title in resource 

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3187]
After renaming the existing resources with litter longer text, the view of dashboard changed to make it unreadable. 

<img width="1439" alt="screenshot 2019-02-14 20 34 06" src="https://user-images.githubusercontent.com/6964191/52794927-e19f8180-3098-11e9-96e3-5ec7a9c30958.png">

**Comment by paulbert** [comment]
Need to look into options in HTML/CSS for breaking up text with no spaces when needed.
