### ISSUE TITLE
Update Achievement : clearing all the fields shows Full Name of the user only

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3188]
Steps to replicate:
- Go to Edit Achievements.
- Clear all fields
- Click on Update
Its only shows Full Name of user, no description about achievement.
But View Achievement button is still available in User Profile section.

So even if there is no achievement (except Full Name), does View Achievement button need to be still shown in User Profile section?

**Comment by paulbert** [comment]
This case should count as no achievements, we just didn't add code to handle that.  We need to set `achievementNotFound` to true if all object/key pairs are empty.

**Comment by paulbert** [comment]
To clarify, `achievementNotFound` is for the UsersAchievementsCompontent, `hasAchievement` is for the UsersProfileComponent.

We should fix both so they count as no achievements in this case
