### ISSUE TITLE
Edit Achievement: New Member without updating their profile result in spinner keep on loading

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3191]
- Create a new Member.
- it will take to the Member update profile page.
- do not update the profile (click on cancel button).
- Go to Achievement.
- Click on Edit Achievement button.
- Update the Achievement.
it shows following console error
![screenshot from 2019-02-14 21-05-55](https://user-images.githubusercontent.com/27276132/52796667-5b853a00-309c-11e9-9d74-ec3f0956992d.png)

**Comment by yuviii** [comment]
@singharpita i found the same issues for old member as well, when i try to add the achievement in existing member.

**Comment by paulbert** [comment]
The problem line of code is line 9 of users-achievements.component.html.  We do not need to use concat and should test if `firstName` exists for the user
```
<span>{{user.firstName.concat(' ', user.lastName).trim() || user.name}}</span>
```
