### ISSUE TITLE
Record survey incomplete submission

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3192]
When user goto **Record survey** and do not answer all questions. Survey stil gets submitted.
![screen shot 2019-02-14 at 21 12 01](https://user-images.githubusercontent.com/2909490/52797287-ad7a8f80-309d-11e9-84c0-7022d6102797.png)
But when going to submision list it will show pending. And there is no way to get back to that survey to complete it as it is not associated to any user.
Nor can we see submission being pending status.
![screen shot 2019-02-14 at 21 11 27](https://user-images.githubusercontent.com/2909490/52797282-a94e7200-309d-11e9-845e-db84b5867f01.png)

**Comment by paulbert** [comment]
Two things we can do to help fix this:
1. Number of Times Taken could only count complete surveys
2. Filter out pending surveys with no user

Calling this one low priority since the main functionality used in Planet is the "Send Survey"
