### ISSUE TITLE
Feedback: show blank dialog

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3193]
When the feedback is opened from the myachievement page the feedback dialog becomes blank but works ok in other pages.

<img width="1440" alt="screenshot 2019-02-14 21 22 33" src="https://user-images.githubusercontent.com/6964191/52797891-eff09c00-309e-11e9-9710-66ad144f7fe6.png">

**Comment by paulbert** [comment]
Haven't been able to replicate.  I will leave this open for a week since we need feedback to work every time in the field.

**Comment by paulbert** [comment]
Looks like the same error as #3191. It should be fixed with that one, but leaving open in case it is not.

**Comment by singharpita** [comment]
![screenshot from 2019-02-14 22-20-37](https://user-images.githubusercontent.com/27276132/52801938-03076a00-30a7-11e9-9425-fa66eb06a7f8.png)

**Comment by yuviii** [comment]
@paulbert @singharpita @lmmrssa 
Looks like this issues is solved after fixing the concat issues in `user-achievements.component.html`

![screenshot 2019-02-16 15 53 55](https://user-images.githubusercontent.com/6964191/52898216-555d9d80-3203-11e9-8167-8ecdd568528b.png)

**Comment by yuviii** [comment]
@paulbert fixes #3201

**Comment by paulbert** [comment]
Closing, fixed
