### ISSUE TITLE
Member Profile : Make the Back button similar to browser back button

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3195]

**Comment by paulbert** [comment]
For clarity, this back button is what needs to be changed:
![image](https://user-images.githubusercontent.com/9203229/52801991-02da8080-304d-11e9-8ec1-9fcca772d3a7.png)

**Comment by lmmrssa** [comment]
Looks like it is related to https://github.com/open-learning-exchange/planet/issues/3221

**Comment by BhargaviNadendla** [comment]
@paulbert I will create a pull request on this by tomorrow

**Comment by paulbert** [comment]
More than related, this is a duplicate of #3221
