### ISSUE TITLE
Can user wtih role admin/manager edit the achievement of user with role manager or learner or admin

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3214]
also View Achievement button is not shown for user with role Learner in member Profile.
![screenshot from 2019-02-20 07-24-40](https://user-images.githubusercontent.com/27276132/53059994-fc328a00-34e0-11e9-89c7-aabc232fbe85.png)

**Comment by paulbert** [comment]
Only allowing members to update their own achievements was intended, so I will close this issue
