### ISSUE TITLE
UI differences

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3215]
There is difference between survey list page and other list pages.
![screen shot 2019-02-20 at 07 31 03](https://user-images.githubusercontent.com/2909490/53060167-9a265480-34e1-11e9-8cb7-f46a6cf00f53.png)
![screen shot 2019-02-20 at 07 31 12](https://user-images.githubusercontent.com/2909490/53060168-9a265480-34e1-11e9-8547-226e21ed9da3.png)

**Comment by paulbert** [comment]
@lmmrssa You mean the background, correct?  That is still controlled in HomeComponent (backgroundRoutes function) in what was intended to be a short term fix while all the routes were updated to look good with the background.  I don't think we're there yet, but ideally we could remove this step and just apply the `gradient-background` class always.

**Comment by lmmrssa** [comment]
@paulbert yes. background
