### ISSUE TITLE
Achievements : Need to handle if the resources is deleted.

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3216]
I think it is good to show message like `resource not found or deleted`, if the resource added in achievement is deleted.

Steps I did
 1. attach the resources in the achievement 
 2. opened the resources list
 3. deleted the resource file from the attached resource in the achievement.
 3. opened the achievement again

<img width="1439" alt="screenshot 2019-02-20 07 35 38" src="https://user-images.githubusercontent.com/6964191/53060321-2cc6f380-34e2-11e9-8631-334dc9e1dc09.png">

**Comment by paulbert** [comment]
Let's try two things:
1. Ignore any resources that do not exist in the Achievements view (removing the button if that means there are no resources on a particular achievement).
2. When the member next edits their achievements & submits the changes to CouchDB we should make sure the deleted resources are removed.

Thinking about this a little more, we can use the same function on an achievements service to do both, and filter the data after we do the get request for achievements.  We can do this in the `getAchievements` function in `UsersAchievementsService`

**Comment by svlesiv** [comment]
Sorry, but I cannot reproduce the issue. 
I tried on dev and prod VM with admin and non-admin users, and if a resource has been deleted it doesn't appear in the list; if no resources have been found - there will be no button to view the resource. CouchDB also perfectly reflects the state of attachments.

**Comment by svlesiv** [comment]
The above version in the commit also works. But I still cannot make use of `resourcesListener`. Resources are undefined during subscription, and after they have been populated with `requestResourcesUpdate`, the function returns. 
Initially, I planned to include `this.couchService.get(this.dbName + '/' + id)` inside `forkJoin` instead of `of(userAchievements)`, but I got an error that function should return observable and not a subscription.
I would appreciate any suggestion about this issue.

```
getAchievements(id) { 
    return this.couchService.get(this.dbName + '/' + id).pipe(
      map((userAchievements: any) => {
        forkJoin([
          of(userAchievements),
          of(this.resourcesService.resourcesListener(false)
          .pipe(
            takeUntil(this.onDestroy$),
            map((resources) => {
              return this.setupList(resources, this.userService.shelf.resourceIds);
          }))
          )
        ]).subscribe(([ userAchievements, resources ]: [ any, any ]) => {
          resources.forEach(r => this.rArr.push(r._id))
          userAchievements = userAchievements.achievements.map((achievement: any) => {
            if(achievement.resources.length !== 0) {
              achievement.resources = achievement.resources.filter((res: any) => this.rArr.indexOf(res._id) !== -1)
            }
          })
        }, (err) => { console.log(err); }
        );
        this.resourcesService.requestResourcesUpdate(false)
        return userAchievements;
      })
    );
  }

setupList(resourcesRes, myLibrarys) {
    return resourcesRes.map((resource: any) => {
      myLibrarys.findIndex(resourceId => {
        return resource._id === resourceId;
      });
    });
 }
```
