### ISSUE TITLE
New user production error

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#3217]
There is a permissions error when creating a new user on my production (created at v0.7.8 and upgraded to v0.7.10):

![image](https://user-images.githubusercontent.com/9203229/53060216-a087e280-3487-11e9-8449-3e0bd244cbba.png)

Checking the database, the `configuration` is set to add the learner role to new members, but the **_users** database does not have the "openlearner" role set which is required to allow adding/removing the learner role without admin privileges.

![image](https://user-images.githubusercontent.com/9203229/53060503-c792e400-3488-11e9-9547-39ebcb729105.png)

The error is corrected by going to the manager dashboard & resubmitting the configuration with no changes (auto accept is already selected).  This makes me think the error is in the initial configuration of Planet.

**Comment by svlesiv** [comment]
I'm able to create a new member and user has a role of 'learner', but getting next console error:

![screen shot 2019-02-19 at 6 29 44 pm](https://user-images.githubusercontent.com/35533801/53063599-7cbda000-3479-11e9-8a44-42fd65b40848.png)

**Comment by paulbert** [comment]
Closing.  This is working now.
