### ISSUE TITLE
Achievement: change button text

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3218]
Instead `Enter an achievement` would be better to say `Add an achievement`.

<img width="1035" alt="screenshot 2019-02-20 07 46 49" src="https://user-images.githubusercontent.com/6964191/53060927-305b7a00-34e4-11e9-979c-cdc5673a97f8.png">

**Comment by paulbert** [comment]
This was requested to be changed from "Add Achievement", so I'll close this
