### ISSUE TITLE
Achievement: Change the label in the dialog

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3220]
In both case for adding new and edit it says `add personal achievement or information`. I think for the edit case it should display as `Edit achievement or information` in the dialog box tittle.

<img width="1439" alt="screenshot 2019-02-20 07 53 50" src="https://user-images.githubusercontent.com/6964191/53061084-cbecea80-34e4-11e9-96b9-4a404f8f9c57.png">

**Comment by lmmrssa** [comment]
Let's make this changes on our new Achievement structure.
