### ISSUE TITLE
Back button reusable component

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3221]
- Go to any feedback view of resource/course/teams.
- Click on resource/course/teams icon present on top right hand side.
- it will take to the particular course, resource or team detail page
- click the back button.
- It will redirect to the list page rather than feedback page.

It should be same as of browser back button.

**Comment by paulbert** [comment]
I'm open now to changing the back button so it always mimics the browser back.  The main reason we changed it was to avoid a logged in user ending up on the login page, but that is no longer possible.

We should create this as a reusable component which will save some duplication across our other components.

**Comment by yuviii** [comment]
@ArashDai I think it supposed to take me to the feedback list as i navigated through the feedback, but it is routing to the list for eg if it is course detail then to course list or same case for resource as well.

[Screen navigating video here on this link ](https://www.useloom.com/share/f4195306f85a41e1b61fd586adaa576e)

**Comment by paulbert** [comment]
Closing.  We found another special case that I think is a little more important than this where after completing the "Add Course/Resource/etc" page, the back button would then go to the form.  In that situation it's better to go up a level.

When we have some more time to add polish, we can revisit.
