### ISSUE TITLE
Achievements: my Reference

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3239]
I think it would be better to show as in My Reference

Name: xx
Relationship: xx
Email : xx@xx.com
phone: 123xx

<img width="721" alt="screenshot 2019-02-21 20 21 17" src="https://user-images.githubusercontent.com/6964191/53176573-79135000-3616-11e9-9f84-1852538883e9.png">

**Comment by paulbert** [comment]
Let's add the descriptor for everything except name:
```
{{name}}
Relationship: {{relationship}}
Phone Number: {{phoneNumber}}
Email: {{email}}
```
