### ISSUE TITLE
Submit disabled on editing 'Achievements' and updating resources 

### ISSUE THREAD

**Issue by BhargaviNadendla** [open-learning-exchange/planet#3241]
After editing an achievement, unable to update the resources

![image](https://user-images.githubusercontent.com/25775298/53178637-d88e4300-35b7-11e9-9dfe-4e797feff010.png)

![image](https://user-images.githubusercontent.com/25775298/53178668-e8a62280-35b7-11e9-8478-d16ff30cdf4b.png)

**Comment by lmmrssa** [comment]
This is the effect of https://github.com/open-learning-exchange/planet/pull/3231 If someone make any changes to input field then only it is triggering form touched.
We need to make sure making attachment also trigger it.
