### ISSUE TITLE
Achievement: profile values (name & birthdate) not validated

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3242]
although First Name and Last name is showing as Mandatory field.
One is able to save the achievement by keeping First name and Last name blank.
![screenshot from 2019-02-21 20-57-48](https://user-images.githubusercontent.com/27276132/53179341-a31b4100-361b-11e9-8b16-74f9f23fa1f1.png)
![screenshot from 2019-02-21 21-00-02](https://user-images.githubusercontent.com/27276132/53179369-aca4a900-361b-11e9-8260-36d3bcb2c5fe.png)

**Comment by paulbert** [comment]
The profile items are under a separate form which is not being checked for validation, so this also relates to the birth date validation not working
