### ISSUE TITLE
Achievement button on my profile view

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3245]
We are adding view achievement for other users profile when manager is looking through. So can we have same when I am looking at my own profile?

**Comment by lmmrssa** [comment]
![screen shot 2019-02-21 at 20 52 03](https://user-images.githubusercontent.com/2909490/53179595-191fa800-361c-11e9-9112-8e2b9e857cbe.png)

**Comment by paulbert** [comment]
Does that user have achievements?  I can see my own achievements on my community:

![image](https://user-images.githubusercontent.com/9203229/53181507-a97ece00-35c5-11e9-8a27-1803f9184aaa.png)

**Comment by lmmrssa** [comment]
Yes looks like that is the issue. After updating admin user achievement was able to see button.
But tried to update achievement for non admin new users and found another issue. So could not verify with non admin. #3250

**Comment by lmmrssa** [comment]
@paulbert this seems to be issue. do not see view achievement of own profile.
![screen shot 2019-02-28 at 20 21 52](https://user-images.githubusercontent.com/2909490/53573972-c05d8b80-3b96-11e9-8569-6781399e63ee.png)
