### ISSUE TITLE
Achievement : birth date for future date is also being saved

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3246]
even though in Edit Achievement Birth date highlights the warning.
but still allows to submit the achievement.
![screenshot from 2019-02-21 21-05-00](https://user-images.githubusercontent.com/27276132/53179823-964b1d00-361c-11e9-8cb8-798e2b7c05f8.png)
![screenshot from 2019-02-21 21-04-49](https://user-images.githubusercontent.com/27276132/53179825-964b1d00-361c-11e9-8c50-a95873fbdae6.png)

**Comment by paulbert** [comment]
This is the same root issue as #3242, so closing this one
