### ISSUE TITLE
Survey of user being merged.

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3247]
Right now survey of same user submitted for each survey is being reduced to one.
In the image below we have only 2 submissions shown.
![screen shot 2019-02-21 at 21 17 04](https://user-images.githubusercontent.com/2909490/53180955-bd0a5300-361e-11e9-8146-dc14d7e36daf.png)
But in database there are 4 submissions (3 for one and 1 for another)
![screen shot 2019-02-21 at 21 18 33](https://user-images.githubusercontent.com/2909490/53180919-a95eec80-361e-11e9-8ea3-ad45eeb6dedd.png)
We should not collapse unknown user into 1 as Unknown users are separate users.

**Comment by paulbert** [comment]
We should only collapse if `user.name` of submission is not undefined
