### ISSUE TITLE
There should be a back button for 'upgrade' view?

### ISSUE THREAD

**Issue by BhargaviNadendla** [open-learning-exchange/planet#3248]
![sn](https://user-images.githubusercontent.com/25775298/53181103-86035580-35bc-11e9-8548-e14ca3d8de14.PNG)

**Comment by paulbert** [comment]
Yes, let's add the toolbar and back button

**Comment by BhargaviNadendla** [comment]
@paulbert I will create a pull request on this by tomorrow
