### ISSUE TITLE
Achievement update breaks user database

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3250]
Step to reproduce.
* Create new user
* Login with user (You can even logout and login any number of times)
* Update achievement

Output
* User get logged out
* User not able to login
![screen shot 2019-02-21 at 21 39 17](https://user-images.githubusercontent.com/2909490/53182371-78cc8200-3621-11e9-8af3-a3e0a85d2f65.png)

Inspection
* Initial Database
![screen shot 2019-02-21 at 21 33 34](https://user-images.githubusercontent.com/2909490/53182396-8255ea00-3621-11e9-9c9e-6e812d17126a.png)
* After achievement update
![screen shot 2019-02-21 at 21 42 02](https://user-images.githubusercontent.com/2909490/53182551-ca750c80-3621-11e9-800a-2e2cbc98719f.png)

**Comment by yuviii** [comment]
@lmmrssa @paulbert having this issue in my case as well.

**Comment by paulbert** [comment]
I'll take this one. Note this is big enough to call 0.7.11 unreleasable.
