### ISSUE TITLE
Achievements: Show description/attachments icon

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3251]
On our new achievement view, we have achievement collapsable. So we do not see attachment until we click on each achievement.
![screen shot 2019-02-21 at 13 30 02](https://user-images.githubusercontent.com/2909490/53183536-a3b7d580-3623-11e9-8bb4-5f7cb56c8d38.png)
![screen shot 2019-02-21 at 13 30 09](https://user-images.githubusercontent.com/2909490/53183539-a4506c00-3623-11e9-8866-f28b36bb62ed.png)

**Comment by paulbert** [comment]
I think we should have some sort of icon to show the achievement is collapsed for ones with description and/or resource.

Let's also make achievements without description or resource not clickable.
