### ISSUE TITLE
Achievements: showing N/A or hiding title at all if data not avaialable

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3273]
**Relationship** in this case 

<img width="1175" alt="screenshot 2019-02-27 07 25 47" src="https://user-images.githubusercontent.com/6964191/53459188-fdbffd00-3a60-11e9-9f41-d7e50043a97f.png">

**Comment by paulbert** [comment]
We should not show the headers (**Relationship**, **Phone Number**, or **Email**) if there is nothing included in that field
