### ISSUE TITLE
Achievement: Add Reference email validation if email is not empty

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3274]
since email is not mandatory field, so when email is not empty can there be validation of this field?
![screenshot from 2019-02-27 07-27-55](https://user-images.githubusercontent.com/27276132/53459304-65764800-3a61-11e9-97f5-8e1f0ecbf606.png)

**Comment by paulbert** [comment]
I think that would be a good thing to add, but it's a low priority change
