### ISSUE TITLE
Survey: spacing between action buttons when disabled

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3275]
there should be spacing between actions button when disabled similar to when all other buttons are enabled.
![screenshot from 2019-02-27 07-33-05](https://user-images.githubusercontent.com/27276132/53459477-18df3c80-3a62-11e9-9f42-c597eddcdd6c.png)

**Comment by paulbert** [comment]
The margin is there, but the shadow and the button blend in.  I think we can increase the bottom margin for the buttons to `0.25rem`
