### ISSUE TITLE
cannot create a meetup for current day

### ISSUE THREAD

**Issue by ArashDai** [open-learning-exchange/planet#3276]
When creating a current meetup, we are unable to select the current day as the start day. a red error message states "Cannot be before current date". either change so that the current day can be selected or change the error message to say something like "Cannot begin on or before today" or something like that.

**Comment by ArashDai** [comment]
![meetupimg](https://user-images.githubusercontent.com/8280071/53459729-ab92c380-39ef-11e9-8edf-be52dc1b2c80.png)

**Comment by paulbert** [comment]
Looks like an update is required for `currentTime` in **CouchService**:
```
  currentTime() {
    return this.getUrl('time').pipe(
      catchError(() => of(Date.now())),
      map(res => res as number)
    );
  }
```
