### ISSUE TITLE
Why is "change password" separate from edit profile?

### ISSUE THREAD

**Issue by ArashDai** [open-learning-exchange/planet#3278]
Would it be better for the change password modal to be inside of the edit profile page instead of being separate on the drop down?
![passwordq](https://user-images.githubusercontent.com/8280071/53460933-be0efc00-39f3-11e9-995b-165762f7e212.png)

**Comment by paulbert** [comment]
I don't think there's enough benefit to make this change, so I'll close this.  Maybe we can revisit if we get feedback about the edit profile page.
