### ISSUE TITLE
Course: showing no detail instead of blank

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3279]
If the course do not have steps it better to show `No steps available` instead of blank similar to the way of resources.

**Course**  for blank case 

<img width="1430" alt="screenshot 2019-02-27 08 07 56" src="https://user-images.githubusercontent.com/6964191/53460989-264af580-3a67-11e9-9837-804961b4102b.png">

**Resource** for blank case

<img width="1433" alt="screenshot 2019-02-27 08 11 21" src="https://user-images.githubusercontent.com/6964191/53461054-5a261b00-3a67-11e9-9cd3-5007509c8852.png">

**Comment by lmmrssa** [comment]
@paulbert If there is no steps, then we might expand detail by default. Does that sound good enough?
