### ISSUE TITLE
Achievements: Sort by date

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#3281]
There is a request to have achievements sorted automatically by date.  I think we should implement this as follows:

1. A button which will sort the achievements by date
  - If the achievements are already sorted it will toggle ascending/descending
  - If they are not sorted the button should sort ascending
2. When the achievements are sorted already, when adding or editing an achievement we should automatically sort the achievements so they remain sorted
3. When the member first creates their achievements they should start sorted ascending by default

**Comment by lmmrssa** [comment]
@paulbert Does date here means date of achievement? If that's the case then Date of achievement is optional.

**Comment by paulbert** [comment]
@lmmrssa Yes good point let's have achievements with no date at the bottom sorted alphabetically by title.
