### ISSUE TITLE
Able to register using uppercase

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3285]
User is able to register using Camelcase or Uppercase but while login we are converting it to lowercase only. And couchdb is case sensitive, so user will not be able to login.
We should restrict user from registering using uppercase letters.

**Comment by yuviii** [comment]
@lmmrssa cannot create the user with the uppercase. user input is itself making the uppercase to small while typing the user name. I tried in password with uppercase and it works. Could not replicate the issue. Please correct me if i am wrong thanks.
