### ISSUE TITLE
Team detail: Joined members can make as link

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3297]
can joined members can be made as link similar to that in meetups?
![screenshot from 2019-02-28 20-59-27](https://user-images.githubusercontent.com/27276132/53576549-0ff28600-3b9c-11e9-8f6d-bdd385303d37.png)

**Comment by paulbert** [comment]
The text of members in the "Joined Members" list should link to their profile page.

**Comment by YuserahN** [comment]
@paulbert I'm not sure if this issue has already been worked on, but I am able to click on the text of members in the "Joined Members" list and it links to their profile page.
