### ISSUE TITLE
Separator on course step

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3299]
On course view, on each step there is a separator showing even when there is no attachment or exam. It was set there to show button for Resource and Exam but it will be better to remove that section if there is nothing.

**Comment by paulbert** [comment]
Need to remove the action row entirely when all of the buttons are removed

**Comment by paulbert** [comment]
More specifically, the `mat-action-row` element should be hidden if there are no resources or exams

https://material.angular.io/components/expansion/overview
