### ISSUE TITLE
Resources: rating dialog should have one button

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3300]
It would be better to disable the submit button if comment is empty in the resource detail page as well.

**Resourcelist page**

<img width="969" alt="screenshot 2019-02-28 21 15 37" src="https://user-images.githubusercontent.com/6964191/53577812-711b5900-3b9e-11e9-96d0-285435f6becf.png">

**Resource detail**

<img width="966" alt="screenshot 2019-02-28 21 15 54" src="https://user-images.githubusercontent.com/6964191/53577976-c192b680-3b9e-11e9-854f-5ad2a5129d3e.png">

**Comment by paulbert** [comment]
We've made this issue many times before & nobody has picked this up.  It would be better to simply have one 'OK' button for this dialog instead of the two 'Submit' & 'Cancel' since the rating has already been submitted when clicking the star
