### ISSUE TITLE
Achievements export as PDF

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#3302]
Started PR here to explore libraries & how difficult this will be: #3293 

Instead of using the markdown converter (showdown) as in the PR we could maybe grab the DOM element with Angular (see [ViewChild](https://angular.io/api/core/ViewChild) and [ElementRef](https://angular.io/api/core/ElementRef) for reference on ways to get the HTML)

I think we are limited on font options, so let's just use a sans serif option.  The main thing will be to make sure the styling is similar (headings with larger font & text centered).

I'm going to pass this PR off an move on to other things, but can help out if needed.

**Comment by paulbert** [comment]
https://rawgit.com/MrRio/jsPDF/master/docs/

**Comment by jessewashburn** [comment]
This is what Print Achievements does.
