### ISSUE TITLE
Member edit profile : Spinner keeps on rotating when user try to update profile

### ISSUE THREAD

**Issue by yubarajpoudel** [open-learning-exchange/planet#3303]
<img width="1421" alt="screenshot 2019-02-28 21 52 40" src="https://user-images.githubusercontent.com/6964191/53580232-4089ee00-3ba3-11e9-89f7-f805b446c5e0.png">

**Comment by paulbert** [comment]
Also affecting achievements. The configuration document is returning a 409 conflict error from couchdb

**Comment by yuviii** [comment]
@paulbert I think this issue is raised because of the older version of the couch db. After updating the version of database this problem is resolved.
Seems like this issues can be closed.

**Comment by paulbert** [comment]
Ok. @lmmrssa @dogi the peacebuilders still have 2.1.2, so this may be an issue for them

**Comment by lmmrssa** [comment]
@paulbert sure we will update all pb when we next time ask them to upgrade

**Comment by paulbert** [comment]
Outdated, closing.
