### ISSUE TITLE
Achievement: Header shows inconsistency in terms of username

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3319]
Can header of Achievement and Edit Achievement page be same?
right now in Achievement page it showing full name and in edit Achievement page it shows username only.

![screenshot from 2019-03-06 07-28-46](https://user-images.githubusercontent.com/27276132/53849968-d8436e00-3fe1-11e9-82ea-0ef1933ab3a4.png)
![screenshot from 2019-03-06 07-28-21](https://user-images.githubusercontent.com/27276132/53849969-d8dc0480-3fe1-11e9-9a00-9305f8c382e6.png)

**Comment by paulbert** [comment]
Ok in AchievementsUpdate let's also have `firstName + middleName + lastName` in header.
