### ISSUE TITLE
mySurvey: Survey count should be equal to the survey list.

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3320]
right now its also considering the case when a survey is updated and again send to the user.
so it counts both the one before update and another after update.
![screenshot from 2019-03-06 07-42-17](https://user-images.githubusercontent.com/27276132/53850528-adf2b000-3fe3-11e9-8e0d-db3e92c966f1.png)
![screenshot from 2019-03-06 07-42-06](https://user-images.githubusercontent.com/27276132/53850529-adf2b000-3fe3-11e9-8a99-34833c470693.png)

**Comment by paulbert** [comment]
Ok the Surveys view is using `SubmissionsComponent` as a note, so we need to make sure the filtering that is done on the pending submissions is also used for the `DashboardComponent` count.
