### ISSUE TITLE
Team view: Requested member list is not showing

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3322]
even though count is 1.
![screenshot from 2019-03-06 08-05-24](https://user-images.githubusercontent.com/27276132/53851443-d29c5700-3fe6-11e9-86e9-dead7734f88a.png)

**Comment by paulbert** [comment]
Problem is with the else of the two *ngIf elements are both pointing to the same element `#requestedList`.  The courses should have a different tag `#coursesList`
