### ISSUE TITLE
Notification link should be disable for user with no role

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3324]
user with no role has no access to any view (Course, Resource, Team, Meetup, Survey).
there might be case when User (with learner role) has requested to join meetups and then that User role has been updated to no Role.
In such case notification link is still visible and clickable that redirects to the corresponding detail page.
![screenshot from 2019-03-06 07-40-12](https://user-images.githubusercontent.com/27276132/53851963-6c183880-3fe8-11e9-996f-c120baf6d721.png)

It might be better if notification link is disabled for user with no role.

**Comment by coder8102** [comment]
Should this link be disabled or should not be shown in this case? What would be the value showing disabled link with value as undefined?
