### ISSUE TITLE
Meetup: start time required

### ISSUE THREAD

**Issue by svlesiv** [open-learning-exchange/planet#3326]
Could be nice to have a **meetup time** field marked as required.

![screen shot 2019-03-05 at 6 50 31 pm](https://user-images.githubusercontent.com/35533801/53852820-26238c00-3f78-11e9-9702-aaec1bc8e9ec.png)

![screen shot 2019-03-05 at 6 55 42 pm](https://user-images.githubusercontent.com/35533801/53852867-50754980-3f78-11e9-8f49-074e2f4f609a.png)

**Comment by paulbert** [comment]
Leaving this optional for "All Day Events", so closing.
