### ISSUE TITLE
need proxy update for couchdb 2.3.0

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3336]
With couchdb 2.3.0, replication is requesting to _sessions with domain name only not any additional path and that is breaking replication.
```
{"timestamp":"2019-03-07T05:18:13Z","type":"crashed","reason":"{replication_auth_error,\n    {session_unexpected_result,\"405\",\n        \"https://planet.somalia.ole.org/_session\",\"peace@peacebuilder7\"}}"}
```
So we will have to add proxy to direct _sessions to db/_sessions

**Comment by dogi** [comment]
https://github.com/open-learning-exchange/planet/blob/master/docker/planet/default.conf#L113-L118
