### ISSUE TITLE
List Resource, course of nation missing

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3341]
Condition to list resource and course is not working anymore. Button is always hidden. Need to fix the condition.
![screen shot 2019-03-07 at 20 16 23](https://user-images.githubusercontent.com/2909490/53963905-4be69780-4116-11e9-9538-23426bdaaf51.png)

**Comment by paulbert** [comment]
`displayDashboard` should be removed entirely as it is outdated.
