### ISSUE TITLE
Adding `edit` button on survey questions

### ISSUE THREAD

**Issue by BhargaviNadendla** [open-learning-exchange/planet#3344]
Can we add `Edit` button for questions in survey just like achievement update to maintain uniformity?

![image](https://user-images.githubusercontent.com/25775298/53966697-43ac3f00-40b9-11e9-9429-8fbfcfae41cf.png)

**Comment by paulbert** [comment]
Clicking on the row for exams, surveys, course steps, etc. switches the view to edit mode as opposed to the achievements which opens a dialog to edit.  Closing.
