### ISSUE TITLE
"add survey" button should be renamed to "save survey"

### ISSUE THREAD

**Issue by ArashDai** [open-learning-exchange/planet#3354]
![screenshot from 2019-03-07 17-37-33](https://user-images.githubusercontent.com/8280071/54001355-dff93480-40ff-11e9-9a89-cdb4f6852dff.png)
in the top left a button called "add survey" can be confusing, it should be renamed to save survey or something like that.

**Comment by coder8102** [comment]
I think "Add Survey" seems better than "Save Survey" ! Not sure if we should change!

**Comment by lmmrssa** [comment]
Let's keep as it is for now. If we decide to change it to Save then we will have to also change on Exam.

**Comment by paulbert** [comment]
This has been changed to "Save" in #3686
