### ISSUE TITLE
Achievements: error on update for admin and monitor users

### ISSUE THREAD

**Issue by svlesiv** [open-learning-exchange/planet#3373]
Error after pressing on **update** button. Nevertheless, If to reload the page and navigate to Achievement view - achievement is saved. I cannot reproduce the error for a user with a *learner* role.

![Screen Shot 2019-03-12 at 6 30 43 PM](https://user-images.githubusercontent.com/35533801/54247176-27633480-44f5-11e9-9348-8c455d8c1939.png)

**Comment by paulbert** [comment]
On UserService the `user` object for admins now has `_admin` in the `roles` array.

That cannot be included when we try to POST the new user document to the database.

**Comment by svlesiv** [comment]
Cannot reproduce this console error anymore.
