### ISSUE TITLE
CoursesView: Exam should not be available until previous completed

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#3376]
Any exam can be taken from the CoursesView page with all of the steps in expansion panels (see below image).

Exams should only be available after all previous exams have been completed.  If there are still exams for the learner to complete, we should disable this button and have a tooltip with the message "All previous exams must be completed before taking this exam"

![image](https://user-images.githubusercontent.com/9203229/54248288-83888180-4512-11e9-8929-83b9b4789410.png)

**Comment by Mutugiii** [comment]
![image](https://github.com/user-attachments/assets/ae5053de-1afc-405a-b0dc-a6fca5bdd3e1)
