### ISSUE TITLE
Change domain name of nations

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3380]
We are still using `media.mit.edu:2200` as domain name of server. We should shift to `planet.nation.ole.org/db` domain

**Comment by paulbert** [comment]
* planet.dev.ole.org/db
* planet.vi.ole.org/db
* planet.ghana.ole.org/db
* planet.somalia.ole.org/db
* planet.nepal.ole.org/db

We should also change earth, which will require some manual changes and some changes to the configuration component.
