### ISSUE TITLE
ourNews: Delete or edit by creator of post

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3399]
1. Can there be delete action for every post which can be deleted by admin and creator of that post?
2. Can there be edit action for every post which can be modified by creator only?

**Comment by paulbert** [comment]
I think adding the functionality for the creator of a post is OK, but including for admins we need to consider the implications of.

**Comment by paulbert** [comment]
For edit: Open a dialog to edit the post
For delete: Open a dialog to confirm the user wants to delete the post
