### ISSUE TITLE
Our News : user name and image on same horizontal axis

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3406]
Looks like it would be better to align the user name and profile image in the same horizontal axis. It will reduce the extra line space and make the card height smaller.

![Screenshot 2019-03-14 20 31 41](https://user-images.githubusercontent.com/6964191/54366689-31be3380-4699-11e9-9bb1-388ef68dda40.png)

**Comment by paulbert** [comment]
Styles in material example might help: https://material.angular.io/components/card/examples
