### ISSUE TITLE
Achievements: new entries break sorting

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#3408]
In the below video "Test 2" and "Test 3" were already on the achievements doc while "Test" & "Test 4" were just created.  The date is in a different format than what is saved to the database.

This change: https://github.com/open-learning-exchange/planet/commit/4e6f44d7aca5227614b8e376fc4ee69418d127f3 removed the `.toJSON()` method which would fix this but was causing another error.  We need to modify this line to fix sorting AND avoid #3342 

https://www.useloom.com/share/a5faa96cfba44a019608cfbb13e54085

**Comment by yuviii** [comment]
@paulbert I am having problem in updating the achievement in dev. Cannot replicate the issue.

[https://www.useloom.com/share/c57ded5aad894c87bd5115a939a97bf7](https://www.useloom.com/share/c57ded5aad894c87bd5115a939a97bf7)
