### ISSUE TITLE
Meetups : Hide the meetups from the list if its end date is behind the current date

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3410]
![Screenshot 2019-03-14 21 33 52](https://user-images.githubusercontent.com/6964191/54371290-3dadf380-46a1-11e9-810a-b48f79cc051c.png)

**Comment by yuviii** [comment]
@paulbert Or user can be prevented to join the meetup if its end date is behind the current date with a toast message.

**Comment by paulbert** [comment]
I think preventing a user from joining an old meetup and maybe having a note that the meetup is in the past.

Note that another case is if the end date doesn't exist we should base this on the start date

**Comment by lmmrssa** [comment]
Join button is disabled on List now. But 3-dot still has Join option
![Screen Shot 2019-04-25 at 20 01 29](https://user-images.githubusercontent.com/2909490/56742813-2c263400-6795-11e9-9e8f-f1e07730d9b6.png)
