### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3431]
As **Manage Team** is just updating team info we can change it to **Edit** or **Update**
Also **View Team** is actually managing team so we can keep **View Team** if user is not part of team else **Manage Team**
![Screen Shot 2019-03-19 at 07 41 26](https://user-images.githubusercontent.com/2909490/54575011-9d4a2d00-4a1a-11e9-9af3-35af015f63fd.png)
**Link Course** does linking and unlinking of course. So may be we can change it to **Associated Course** or **Team Course**
![Screen Shot 2019-03-19 at 07 45 26](https://user-images.githubusercontent.com/2909490/54575139-0df14980-4a1b-11e9-831a-646fe1c6ba03.png)

**Comment by paulbert** [comment]
I think "Set Courses" or "Manage Courses" is better.  It's an action so I think it's better to have a verb
