### ISSUE TITLE
ourNews: Edit on post should change wrote on date?

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3432]
can wrote one date should be changed to updated date when user update their post?
![Screenshot from 2019-03-19 07-41-52](https://user-images.githubusercontent.com/27276132/54575057-d5ea0680-4a1a-11e9-8b6c-80f4cbfc3a51.png)

**Comment by paulbert** [comment]
Add an `updatedDate` field to the document on edit & if it exists on the post show `(edited on {{date}})`

Note the way to add the current time to a document is to use the `this.couchService.datePlaceholder` as the value for the form.

**Comment by YuserahN** [comment]
@paulbert Should I display the 'wrote on' date as well as the edited date? (Like the example below.) Or should I replace 'wrote on' if an edit date exists? 

![newsPostDates](https://user-images.githubusercontent.com/21087353/54630975-06e13000-4a49-11e9-9afe-1d62370bf137.PNG)
