### ISSUE TITLE
ourNews: Edit title should be changed to "New Post"

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3433]
to maintain consistency, **News** title of edit dialogbox should change to **ourNews**.
![Screenshot from 2019-03-19 07-35-26](https://user-images.githubusercontent.com/27276132/54575792-9cff6100-4a1d-11e9-9135-85786c6f8be6.png)

**Comment by paulbert** [comment]
Let's change the title to "New Post" instead
