### ISSUE TITLE
Resources: Adding My Resource filter in resource list

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3450]
I think it would be good to have the My Resource filter button in the toolbar, so it would allow the user to see the resource list added only by them.

**Comment by paulbert** [comment]
Also on the dashboard when the learner clicks "myLibrary" they should see this view with only the resources they have selected

**Comment by paulbert** [comment]
Lets have a `mat-stroked-button` next to the Library heading that switches between the two views
