### ISSUE TITLE
Member Search : Change search filter placeholder

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3457]
Looks like placeholder `type text to search` seems more confusing and fail to explain what actually it searches. Instead it would be better to use `username` or `type username to search` as a placeholder.

![Screenshot 2019-03-21 20 51 30](https://user-images.githubusercontent.com/6964191/54762114-92aab600-4c1b-11e9-84ae-65789cf9a824.png)

**Comment by paulbert** [comment]
Be careful with the limited space so the text fits.

If `Type username to search` doesn't fit just `Search username` would work, though.
