### ISSUE TITLE
Team Detail: Show 'No description available' text for empty description instead blank

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3461]
![Screenshot 2019-03-21 21 29 41](https://user-images.githubusercontent.com/6964191/54765359-7742a980-4c21-11e9-8002-df7fcc780fe4.png)

**Comment by paulbert** [comment]
Or maybe 'The team has no description.' and if the current user is a member there is an 'Add one' button or link which opens a dialog to edit the team details
