### ISSUE TITLE
Validation message of gender comes below beta toggle

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3490]
Required message for gender on user profile shows below toggle button of Beta functionality. It should show after gender and beta function should be below that.
![Sketch](https://user-images.githubusercontent.com/2909490/55166751-c9427c80-5197-11e9-8061-e8b241f1f38a.png)

**Comment by paulbert** [comment]
Looks like the slide toggle is included as a child of the radio group for the gender, but it should be below the radio group.
