### ISSUE TITLE
Achievements: Error when accessing the resources added in achievement if the the user has not role

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3493]
It is raising the error when the user that has not assigned any role when try to add the the resources in the achievement.

**Steps to replicate the issue**

- remove the roles of user
- login through that user
- go to Edit achievement
- Open the Enter achievement dialog and try to add the resources

It will end up with generating error and spinner keep loading.

<img width="1440" alt="Screenshot 2019-03-28 21 09 51" src="https://user-images.githubusercontent.com/6964191/55170346-78825200-519e-11e9-8b49-ec8edeeda6e8.png">

**Comment by paulbert** [comment]
For this we should hide the **Add Resources** button for a user without roles (similar to the other issues with `*planetAuthorizedRoles="'learner'"`).  A user without roles does not have access to the `Resources` database so they cannot add resources here.

**Comment by paulbert** [comment]
Fixed in #3531
