### ISSUE TITLE
Resource language options

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#3497]

**Comment by yuviii** [comment]
@paulbert I think it would be nice to  show list of language of planet with `others` for the `resource  language option` other than listed.

![Screenshot 2019-04-01 20 31 40](https://user-images.githubusercontent.com/6964191/55337040-a7116d00-54bd-11e9-84cd-703104c5f0d8.png)

**Comment by paulbert** [comment]
I think it would be useful to have a write in option.  I imagine scenarios where we have some resources in local languages and it would be good to have that info cataloged rather than just thrown into an "other" bucket.

**Comment by paulbert** [comment]
Let's start with adding the languages that are in the top menu (ones we support for translation). There is a file in the shared directory with an array of these languages.

**Comment by paulbert** [comment]
Closing this, because I think the write in option is very far off

Application language options added in #3709
