### ISSUE TITLE
Logout: Logout not working in offline

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3507]
Logout works  in online but not working if the system is offline.

![Screenshot 2019-04-01 20 13 44](https://user-images.githubusercontent.com/6964191/55336386-8bf22d80-54bc-11e9-82d5-2a5caa804ee8.png)

**Comment by paulbert** [comment]
Note this only occurs for the admin because an error is thrown as it tries to delete the session on the parent.

**Comment by paulbert** [comment]
We need to gracefully handle this error with `catchError` in the observable stream.
