### ISSUE TITLE
Survey/mySurvey: Updated on format

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3513]
in Survey, Created/Updated on only shows date where as in mySurvey, Updated on shows datetime.
Can this field be made similar?
![Screenshot from 2019-04-02 07-28-09](https://user-images.githubusercontent.com/27276132/55370106-14062080-5519-11e9-9c75-1143a56cd1da.png)
![Screenshot from 2019-04-02 07-27-59](https://user-images.githubusercontent.com/27276132/55370107-149eb700-5519-11e9-9fa3-3f1651443b08.png)

**Comment by paulbert** [comment]
I think date & time makes sense for showing exactly when a person took the survey.  For when the survey was created we only need to see the day.  Closing
