### ISSUE TITLE
Library filters: misspelling

### ISSUE THREAD

**Issue by svlesiv** [open-learning-exchange/planet#3515]
Instead of `Medium` should be `Media`. We need to fix the misspelling.

![Screen Shot 2019-04-01 at 6 52 17 PM](https://user-images.githubusercontent.com/35533801/55370505-88a47500-54af-11e9-84bd-05136ceaf7fa.png)

**Comment by paulbert** [comment]
Medium is the singular form of media, so this is correct. Closing
