### ISSUE TITLE
Surveys: Send notifications on completion

### ISSUE THREAD

**Issue by svlesiv** [open-learning-exchange/planet#3522]
Should we include survey submission to the total number of submissions?
Right now it shows only the number of exam submissions.

![Screen Shot 2019-04-01 at 7 42 18 PM](https://user-images.githubusercontent.com/35533801/55372614-3404f800-54b7-11e9-90ed-9c14329bd7ac.png)

**Comment by paulbert** [comment]
This number is there to indicate "action items", as in the number of exams that require grading.

We could send a notification to the survey creator and the survey sender that learners completed the survey.
