### ISSUE TITLE
Courses: Take Survey button only shows when step also has exam

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3534]
Survey has been linked with course on #3328 but there is no way to look through surveys from course nor it is possible to take survey from course. It is just listed under surveys as it was before. And needs to be sent to members. All who join course should be able to take survey just as they take exam.

**Comment by lmmrssa** [comment]
**Take Survey** is there on course step view but it only shows where we also have **Exam**

**Comment by paulbert** [comment]
Need to make ngIf condition for "Take Survey" independent of the exam button

**Comment by jessewashburn** [comment]
This seems to have been corrected. 
![image](https://github.com/user-attachments/assets/b1b080c1-df6c-4be9-abcb-b04cbad8cc48)
