### ISSUE TITLE
Teams: Button spacing

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3536]
![Screenshot 2019-04-04 20 57 57](https://user-images.githubusercontent.com/6964191/55567086-b80be980-571c-11e9-963c-d4f5d314a7d4.png)

**Comment by lmmrssa** [comment]
There is `Manage Team` or `View Team` button which was supposed to show there but it looks like `userStatus` is returning a condition which cause this button to be empty. That's why there is button but its showing empty causing the empty space between **Request pending** and **Feedback**
