### ISSUE TITLE
ourNews: while editing, cursor focus should be present in markdown editor

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3537]
![Screenshot from 2019-04-04 21-09-44](https://user-images.githubusercontent.com/27276132/55567804-29986780-571e-11e9-980f-e73f23ff3500.png)
- when click on Edit, user has to click on markdown editor again to make any changes.
- same should be case when we click on ourNews from Dashboard, focus on markdown editor is missing

**Comment by lmmrssa** [comment]
Looks like we can implement this on other pages as well where there is only one input field.
