### ISSUE TITLE
myPlanet upgrade: Notify when download completes.

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#3562]
I think here the script should respond when the download completes, not when it starts.  Right now it immediately shows "New file found" and there is no indication when the download completes, or if it is even in progress.

This can lead to us making a component in the app for the manager to get the latest version of myPlanet.

**Comment by lmmrssa** [comment]
@paulbert It is already resolved. Script now have more detail of process and also does verify after download. If failed it give error message
