### ISSUE TITLE
Course: Past attempts is flickering for few seconds

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3565]
take an exam from course detail , on submit of it Past Attempts flickered for few seconds.

**Comment by paulbert** [comment]
This is a symptom of the variable changing & causing rerenders of the page which is not good.

@YuserahN Let me know if you have any questions.  From the looks of it, it seems like we may reassign a property multiple times causing the `ngIf` on that text & the `disabled` on the next step arrow to switch between true and false states.
