### ISSUE TITLE
Achievements: Make "Add Achievement" text to link

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3570]
![Screenshot from 2019-04-09 08-14-59](https://user-images.githubusercontent.com/27276132/55769238-b7b67a00-5a9f-11e9-8b5f-000d3223391f.png)

**Comment by paulbert** [comment]
@singharpita I think I get it, but could you confirm that you mean the "Add Achievements" in "Click Add Achievements to add your achievements!" should be change to a link?
