### ISSUE TITLE
Survey: Checkbox selection after survey filter

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3571]
**Steps to replicate the issue:**
 1. Select all survey
 2. filter the survey
 3. toggle the all selection checkbox

[https://www.loom.com/share/6b82a914ebf6480a8c9c7faa6f5c7056](https://www.loom.com/share/6b82a914ebf6480a8c9c7faa6f5c7056)

**Comment by paulbert** [comment]
We only implemented the fix for this on resources.  We could try to create a reusable function so in a later issue we can refactor the other tables to use that (instead of duplicating code).
