### ISSUE TITLE
Upgrade myplanet script: install jq on RasPi

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#3576]
![image](https://user-images.githubusercontent.com/9203229/55812167-75e5fd80-5ab8-11e9-8c6d-39f2a2705e6e.png)

jq is not included in the Raspberry Pi image currently.  We need it for the **fromnation** script

**Comment by dogi** [comment]
https://github.com/open-learning-exchange/planet/blob/master/docker/planet/nginx/upgrade_planetapk.sh#L12-L14

**Comment by lmmrssa** [comment]
It has been added on https://github.com/open-learning-exchange/planet/commit/4ab4f84d08de735f2bfd2ea371368af90d5c193b so closing this issue.
