### ISSUE TITLE
CourseDetails : indicators for already attempted steps in Stepslist

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3587]
I think it would be a good idea to color the row or use some kind of icon to distinguish the attempted and unattempted steps in step list as now progress bar shows. Particularly when we have many steps number this can be useful for the user to visualize more clearly which steps are accomplished so far.

<img width="912" alt="Screenshot 2019-04-11 20 27 38" src="https://user-images.githubusercontent.com/6964191/55966877-f6635480-5c98-11e9-916c-4ca11d3467d4.png">

**Comment by paulbert** [comment]
Putting this as low priority since we already have a progress indicator.  It might improve readability to have the color indicators on the lower list as well, so if someone has an idea they can make it into a PR to try it out.
