### ISSUE TITLE
CourseProgress : Progress bar color disappears

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3588]
Steps to replicate this issue
 1. Click in `show details`
 2. Do rating
 3. When the page loads the color of steps progress disappears.

**Comment by yuviii** [comment]
[https://www.loom.com/share/3c82718692c84608b5b4e6ffad803ff7](https://www.loom.com/share/3c82718692c84608b5b4e6ffad803ff7)

**Comment by paulbert** [comment]
Related to how course information is updated from CoursesService.  I think the course on the component is replaced completely, deleting the progress information that it received in initialization.

**Comment by paulbert** [comment]
Related to how course information is updated from CoursesService.  I think the course on the component is replaced completely, deleting the progress information that it received in initialization.
