### ISSUE TITLE
Course Progress: step's course progress label is misleading

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3590]
- go to course progress of any step.
- Label Steps should be changed to "Questions" or "No of Questions"
![Screenshot from 2019-04-11 21-03-12](https://user-images.githubusercontent.com/27276132/55969428-7e4b5d80-5c9d-11e9-8c1a-7ff319319e20.png)
It might be misleading because full course also shows same label and it shows count of steps in it while within step's course progress it shows count of question in that particular step.

**Comment by diabagatekelly** [comment]
It seems like it's the same chart for both pages. Could we change it to something generic and applicable to both pages like "Item Number". Or maybe "Question No." could work for both.

**Comment by paulbert** [comment]
It should be steps when viewing a course or courses and let's do "Questions" for exams.
