### ISSUE TITLE
Creating Exams: Question Title is No Longer Required

### ISSUE THREAD

**Issue by YuserahN** [open-learning-exchange/planet#3594]
https://www.loom.com/share/59548416f733482e9ccdc9813a58a5ad

**Comment by paulbert** [comment]
I think making the requirement either Title or Description would be the best thing to do here.  It's a little more complicated, but adds more flexibility for the course creator.

**Comment by svlesiv** [comment]
connects PR #3704

**Comment by paulbert** [comment]
Closing, no longer relevant since we removed question titles.
