### ISSUE TITLE
CourseDetails: icon for a survey

### ISSUE THREAD

**Issue by svlesiv** [open-learning-exchange/planet#3611]
We could have an icon for an attached to the course survey. 
For example, a survey is attached to Step 2, but no indication is present.

![Screen Shot 2019-04-15 at 6 42 35 PM](https://user-images.githubusercontent.com/35533801/56175982-536b4d00-5fae-11e9-9b65-d8407c9bbdde.png)

**Comment by paulbert** [comment]
Add the icon to this view (CoursesView) and to CoursesStep, which is used in CoursesAdd
