### ISSUE TITLE
Exams: "Complete" button changes back after wrong answer

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#3612]
After an incorrect error is submitted, the "Complete" button (shows up when every other question has a submitted answer) changes back to the default text, "Submit Answer".

The last question to be completed should always have the button text "Complete".  I think the problem may be that an incorrect answer gets added to the submission in the `answer.value`.  We could instead add the value as `undefined` with an incorrect answer since we do not allow that as an answer, anyway.

https://www.loom.com/share/67bffba96e36484d976460c302900c8a

**Comment by paulbert** [comment]
@ArashDai Try this one out, and let me know if you have any questions

**Comment by ArashDai** [comment]
Having trouble recreating this one, i made a test with 6 multiple choice questions, all of them having a correct answer, and i didn't see this bug

**Comment by paulbert** [comment]
Looks like this was fixed in #3639, so I'll close this.
