### ISSUE TITLE
Take Survey/Exam: Button label is inconsistent

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3613]
Steps to replicate:

- Go to take survey (of atleast two question in it)

- Submit answer for first question.( shows button as **Submit answer**)

- Navigate to second question.(It will show button as **Complete** now)

- don't answer the second question and navigate back to first question.

- now first question's button shows as **Complete** which means that user is about to complete the survey but in actual after clicking on **Complete** it will take user to second question.

**Comment by paulbert** [comment]
The button text checks if all but one questions have been answered.

Needs an improvement to check if the current question had already been answered.  If all questions have been answered (learner is redoing the survey) & it's the last question button should say "Complete" as well.

**Comment by paulbert** [comment]
Fixed in #3639
