### ISSUE TITLE
CourseDetail: show NA for empty values

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3616]
**Method** and  **Language of instruction** in this case

<img width="816" alt="Screenshot 2019-04-16 07 56 36" src="https://user-images.githubusercontent.com/6964191/56177095-3457d400-601d-11e9-967f-e22f2c75e522.png">

**Comment by paulbert** [comment]
Just **Language of Instruction**.  **Method** is being removed entirely
