### ISSUE TITLE
CourseDetails: take survey button doesn't work

### ISSUE THREAD

**Issue by svlesiv** [open-learning-exchange/planet#3617]
If to take a survey from a CourseDetails view - it will redirect to PageNotFound.

![Screen Shot 2019-04-15 at 7 17 56 PM](https://user-images.githubusercontent.com/35533801/56177362-36854880-5fb3-11e9-95c5-478461ff992d.png)

https://www.loom.com/share/1a83a85c6093430984168aa919c577d9

**Comment by paulbert** [comment]
Route is incorrect, it needs to have `step/{stepNum}` as well.  See the **Take Exam** button as an example
