### ISSUE TITLE
easier way to delete a "course-step exam question"

### ISSUE THREAD

**Issue by ArashDai** [open-learning-exchange/planet#3618]
I'm inside course and i'm adding a question to an exam within a step. If i create a question accidentally, the only way to remove it is to press "return to list" where you can see all the questions and then press the trashcan to delete the incomplete step. There should be a way to cancel or delete the current step from the "course: add exam step page"  without having to go back to the "list".

![course-delete-one](https://user-images.githubusercontent.com/8280071/56177429-72201280-5fb3-11e9-8f58-1a7d8b167abe.png)

the only place to delete a question:
![delete-course-2](https://user-images.githubusercontent.com/8280071/56177435-79dfb700-5fb3-11e9-8e0a-57d3a83d894f.png)

**Comment by paulbert** [comment]
This is good.  This is a shared component `PlanetStepListComponent` so if we add it here we should make sure it fits the other components using it.
