### ISSUE TITLE
Dashboard Course My progress shows undefined on empty profile

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3621]
when the user profile is blank/empty, Course my progress shows "undefined undefined" in header.
![Screenshot from 2019-04-16 08-09-59](https://user-images.githubusercontent.com/27276132/56177694-45094980-601f-11e9-8e8a-aaaddeb70baf.png)

**Comment by paulbert** [comment]
If `firstName` is undefined, then we can use the `name` property
