### ISSUE TITLE
view-course bugs

### ISSUE THREAD

**Issue by ArashDai** [open-learning-exchange/planet#3624]
a couple small bugs with accessing a course through the view-course page.

![one](https://user-images.githubusercontent.com/8280071/56178970-fc1eaa00-5fb8-11e9-854f-c8c1e320f02b.png)

1. select "take exam" from a step, in the top right the arrows for moving back and forth through 
steps, but no number indicates the number of steps in the course and the arrows are greyed out.

![two](https://user-images.githubusercontent.com/8280071/56178990-10fb3d80-5fb9-11e9-8870-c4201ecafee5.png)

2.select "take exam" but change your mind and press back button, takes you to wrong page

![three-back](https://user-images.githubusercontent.com/8280071/56179005-19ec0f00-5fb9-11e9-95e2-dda1bd027215.png)

3. select "take survey" from a step, page not found

![4-nosurvey](https://user-images.githubusercontent.com/8280071/56179019-1fe1f000-5fb9-11e9-9a0b-883dd032d3fc.png)

**Comment by paulbert** [comment]
Number 3 is #3617 

I can't replicate number 1, but we can try again

Number 2 is related to #3221.  I'd rather avoid hardcoding something here, so I think we can take a broad approach on that issue.

If we can replicate number 1 let's fix that, otherwise I'll close this.

**Comment by paulbert** [comment]
Figured out #1, the number of questions is on the left (Question _ of _), and this exam has one question which means the arrows are not needed and grayed out.

I'll close this now.
