### ISSUE TITLE
Resources: search bar changes

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#3626]
1. Change "Reset" to "Clear"
2. Change "Collections" to "Search Collections"
3. Change margin for collections form field.  Let's try `margin-lr-3` to `margin-lr-8`

![image](https://user-images.githubusercontent.com/9203229/56225165-d9cf6f80-603e-11e9-82b4-7f30d8f75eb5.png)

**Comment by paulbert** [comment]
A few more things:
4. Change "Title" to "Search Title"
5. Change "Show Filters" to "Search Profile"
6. Change order of the buttons/elements to "Search Title" "Search Profile" "Search Collection" "Clear"

**Comment by paulbert** [comment]
@coder8102 Sorry, I'm going to close this.  I received some changes to these requests Friday and went ahead and made them without realizing we already had an issue for updates to the search bar.

**Comment by coder8102** [comment]
No problem Paul. I will take some other issue.
