### ISSUE TITLE
Course progress: set passed to true on complete

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3645]
I was able to see complete (Tick) icon on one of the course and it remain so even after re taking exam.
But with course shown on image even when all questions are multiple choice it remained in progress status. Not sure what is referencing this status. Also does it just check exam or even survey? It seems confusing
![Screen Shot 2019-04-18 at 20 15 51](https://user-images.githubusercontent.com/2909490/56368609-7d737800-6217-11e9-9c6d-5067f7bac151.png)

**Comment by paulbert** [comment]
Related to #3058.  I think I'll close that in favor of this one, because it's broader.

Whenever an exam is graded or completed, if all answers are correct it should modify the document on `courses_progress` to `passed: true`.
