### ISSUE TITLE
Add Exam: Add Choice often below scroll for multiple choice

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3672]
When type is changed from multiple single choice or multiple, the Add choice button is shown in bottom and its kind of hidden so can page be scroll to bottom when type changes to Multiple choice single or multiple answer?

**Comment by paulbert** [comment]
Not sure how best to handle this since.  Maybe having "Add Choice" between title & description is easiest so everything is shown on most screens.
