### ISSUE TITLE
Resources: Move selected collections text

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#3699]
We have a request to move the selected collections text on the resources view so that it is next to (above or to the right of) the X of Y Resources Shown text here:

![resourcesbar](https://user-images.githubusercontent.com/9203229/56767317-6b468c00-6779-11e9-8eea-b33aed38ec29.png)

This will be a challenge because the text and the button are part of their own reusable component.  A possible good solution is:

- Move the text into its own reusable component that takes the value of PlanetTagInputComponent as an @Input.
- Add that component in the blue toolbar and use a [template reference variable](https://angular.io/guide/template-syntax#template-reference-variables--var-) to pass the value of PlanetTagInputComponent in to this new component.
- We already have a `helperText` variable available to hide the text if set to `false`
- If this works, we should also use the new component in PlanetTagInputComponent

**Comment by svlesiv** [comment]
TODO: convert tag Id into name.
![Screen Shot 2019-05-06 at 5 41 34 PM](https://user-images.githubusercontent.com/35533801/57264510-264b1100-7027-11e9-9ef1-f4d137823e0a.png)
