### ISSUE TITLE
Course Add: should clear the question form after question is saved

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3714]
Currently the form still remains filled up after the question is saved success.

<img width="1414" alt="Screenshot 2019-04-30 06 22 03" src="https://user-images.githubusercontent.com/6964191/56935401-8108d800-6b10-11e9-999e-e99a59f6239f.png">

**Comment by lmmrssa** [comment]
It is just saving to database all questions of the exam will still be on the same page. Cleaning record on form means next time you save, it will make question empty.
NOTE: It is not saving just one question, it is saving whole exam.
