### ISSUE TITLE
Resource Detail: Add the link on username

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3717]
I think it would be better to add the link in the author to view details like in other sections.

<img width="1437" alt="Screenshot 2019-04-30 07 01 35" src="https://user-images.githubusercontent.com/6964191/56936245-08a51580-6b16-11e9-8394-89d3c8728c70.png">

**Comment by lmmrssa** [comment]
@yuviii author is a plain text, it does not need to be username.
