### ISSUE TITLE
ExamQuestion: validation error message 

### ISSUE THREAD

**Issue by svlesiv** [open-learning-exchange/planet#3722]
Validation message is visible after pressing Save button even if validation errors have been fixed.

https://www.loom.com/share/d5dceaaf53534794a70e3ec706bd1dc9

![Screen Shot 2019-04-29 at 6 47 48 PM](https://user-images.githubusercontent.com/35533801/56937137-f7c1b900-6aaf-11e9-9b65-a89b94d14e3f.png)

**Comment by lmmrssa** [comment]
We need to clean validation message when form is valid, before we send save request. It should be same for both **Save** and **Return** button
