### ISSUE TITLE
Teams: console error

### ISSUE THREAD

**Issue by svlesiv** [open-learning-exchange/planet#3726]
Console error if to press on View or Manage Team buttons.

![Screen Shot 2019-04-29 at 7 31 35 PM](https://user-images.githubusercontent.com/35533801/56938199-70774400-6ab5-11e9-92e4-e78b12a2e8f9.png)

**Comment by lmmrssa** [comment]
Functionality is working, But there is error log looking for `requests` property. We should try to remove this error.
