### ISSUE TITLE
Possible infinite loop/loading when value entered and submit button pressed (is this a known issue)

### ISSUE THREAD

**Issue by simily00** [open-learning-exchange/planet#3738]
![Screen Shot 2019-05-01 at 3 44 24 PM](https://user-images.githubusercontent.com/17802123/57048600-80b03000-6c29-11e9-9e34-c2844a56a7cb.jpg)

**Comment by paulbert** [comment]
This is actually an issue with an old version of that course ending up on our development communities.  I changed the courses we automatically replicate on dev to fix this
