### ISSUE TITLE
Survey: Would be nice to have option to send multiple survey

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3741]
Currently we need to send survey one to one for the user. I think it would be lot easier if we can send many survey at once for the user.

**Comment by lmmrssa** [comment]
Use case will be more like sending survey to multiple users not multiple survey to user. It will be very rare case when you have to send 4-5 surveys to user.

**Comment by paulbert** [comment]
We can come back to this if there is a use case, but right now I think we need to prioritize other issues.  Closing.
