### ISSUE TITLE
Not able to create survey

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3743]
When trying to survey on its own, it is looking for course title. This seems to be because of the changes made on exam to remove title field.
It works if we try to add survey from inside course, but when we try to add it from survey page, it has error.
![Sketch (13)](https://user-images.githubusercontent.com/2909490/57083461-4e313080-6d18-11e9-8ba3-5b007e383928.png)

**Comment by paulbert** [comment]
This is related to assigning a name to the survey when attached to the course.  We should make sure if `coursesService.course` is undefined we do not try to access the `courseTitle` property.
