### ISSUE TITLE
Course Survey: "-" between Course name and incrementor

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3746]
right now it just append the count with Course name which might confuse.
![Screenshot from 2019-05-02 20-37-39](https://user-images.githubusercontent.com/27276132/57084614-5ab68880-6d1a-11e9-8cbd-c9ff30bdba8c.png)

It better to add "-" in between Course Name and Counter.

**Comment by paulbert** [comment]
Fix is needed in `src/app/exams/exams-add.component.ts` on the `name` variable in the `addExam` method

**Comment by paulbert** [comment]
Looking a little more the fix should be applied to the `newExamName` method
