### ISSUE TITLE
MySurveys: Empty step title shows blank in name of mysurveys

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3753]
Default title of step can be shown in the case of empty.

<img width="1422" alt="Screenshot 2019-05-02 21 31 10" src="https://user-images.githubusercontent.com/6964191/57088391-eaac0080-6d21-11e9-9489-21f8af485c41.png">

**Comment by paulbert** [comment]
Related, maybe the same internally, as #3744 (both are SubmissionsComponent)

**Comment by YuserahN** [comment]
It seems to be having the same problem with exams.

**Comment by lmmrssa** [comment]
https://github.com/open-learning-exchange/planet/pull/3761

**Comment by paulbert** [comment]
Fixed in #3761
