### ISSUE TITLE
Course edit conflict

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3770]
Edit course exam. When it comes back to course edit page, update title and then try to save. It will cause conflict and keeps spinner loading.
Now if you try to refresh page url will look like http://localhost:3100/eng/courses/update/cf0e7737788b5db88aa2f7b88a0004b6;continue=true and when course edit is called with continue=true it will make form empty.
And this will lead to #3718

**Comment by lmmrssa** [comment]
#3768

**Comment by paulbert** [comment]
This appears to be fixed, closing.
