### ISSUE TITLE
Meetup Update: margin in recurring frequency

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3788]
I think it would be better to add the margin left in radio button 

<img width="1434" alt="Screenshot 2019-05-09 22 27 47" src="https://user-images.githubusercontent.com/6964191/57470968-dc259200-72a9-11e9-9275-20ba4c1c3961.png">

**Comment by paulbert** [comment]
@simily00 I'm going to pass this one on to @Liew211
