### ISSUE TITLE
Course collection: updated collection from filter doesn't reflect in change collections

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3796]
- create a collection.
- go to filter collection and edit that collection.
- do not refresh the page and click on change collection
- it shows the older values.
![Screenshot from 2019-05-14 07-16-04](https://user-images.githubusercontent.com/27276132/57664609-a28db780-7618-11e9-8393-93aca6e016d4.png)
 i think its problem of page refresh. after page refresh it shows the updated value

**Comment by singharpita** [comment]
#3772

**Comment by svlesiv** [comment]
I noticed the same behavior in older version also.

**Comment by paulbert** [comment]
Fixed as part of #3772
