### ISSUE TITLE
Submissons: Test and survey button not switching the page.

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3801]
<img width="1438" alt="Screenshot 2019-05-14 08 20 55" src="https://user-images.githubusercontent.com/6964191/57666914-690d7a00-7621-11e9-96e2-f4d0169c53b6.png">

**Comment by yuviii** [comment]
Found another issue related this,
When the page loads the `status filter` works but upon clicking the `tests` and `survey` button , `status filter` stops working.

<img width="1439" alt="Screenshot 2019-05-14 08 24 30" src="https://user-images.githubusercontent.com/6964191/57667069-05d01780-7622-11e9-83fc-64992f702164.png">

**Comment by yuviii** [comment]
Error message

<img width="545" alt="Screenshot 2019-05-14 08 28 21" src="https://user-images.githubusercontent.com/6964191/57667165-4af44980-7622-11e9-9f16-a53566924e53.png">

**Comment by lmmrssa** [comment]
it was error on previous survey where it did not had title. which is already resolved so once old data is cleaned it will just work fine.
