### ISSUE TITLE
Collections: Back Arrow To Return To Original List

### ISSUE THREAD

**Issue by YuserahN** [open-learning-exchange/planet#3802]
Once a user has clicked on a collections tag and all the resources with that tag are displayed, should there be a back arrow to return to the list of all resources? Or is it enough to be able to do that by clicking on 'Collections' and unchecking the box?
https://www.loom.com/share/782e68dd324740cba85432ec5c4b2250

**Comment by paulbert** [comment]
@YuserahN Clicking the button adds the collection to the search, so the way to go back to the full list is by clicking the "Clear" button.

Maybe it would be more readily apparent if the button is disabled when there is nothing selected to search and enabled in blue (`color="primary"`) when there is a search?
