### ISSUE TITLE
Collections: not display collection names on select list

### ISSUE THREAD

**Issue by ScottHuangNYU** [open-learning-exchange/planet#3811]
![collections not display](https://user-images.githubusercontent.com/31773567/57740870-d09de680-766e-11e9-9956-0b9a36eef6f8.jpg)

**Comment by lmmrssa** [comment]
@ScottHuangNYU can you test it with new code. We have introduced new changes on collection recently few hours back

**Comment by ScottHuangNYU** [comment]
@lmmrssa cool, it work right now! Thanks
