### ISSUE TITLE
Issue on sending courses and resources with older tag.

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3813]
We recently change way tag works but sending (fetch) has not been updated to reflect that which is causing issue.

**Comment by paulbert** [comment]
It's not an issue with the tags, but how the data is organized in the table that has changed

The below is an example of a document in `send_docs` created with 0.7.39.  The value in `item.doc` should be the value for `item` for the fetch on the community end to work.
![image](https://user-images.githubusercontent.com/9203229/57864865-9ea19700-77ca-11e9-875d-932034fb0cba.png)
