### ISSUE TITLE
on Nation Resource Header action link overflow

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3821]
![Screenshot from 2019-05-16 20-12-02](https://user-images.githubusercontent.com/27276132/57861959-45ac2000-7817-11e9-96ed-368435695f44.png)

**Comment by lmmrssa** [comment]
@paulbert as we are adding more activities, It could be good time to only show more frequently used action and put others under dropdown menu.

**Comment by paulbert** [comment]
Missed this when creating #3828. Closing since the details are there.
