### ISSUE TITLE
Reset should be consistent in overall application

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3823]
- In Library there is "Clear" rather than "Reset"
- In Feedback, "Reset" is not disabled by default
![Screenshot from 2019-05-16 20-21-19](https://user-images.githubusercontent.com/27276132/57863190-59588600-7819-11e9-9337-edd3a727809d.png)
![Screenshot from 2019-05-16 20-21-31](https://user-images.githubusercontent.com/27276132/57863191-59588600-7819-11e9-8565-a7b4c94a97db.png)
![Screenshot from 2019-05-16 20-21-45](https://user-images.githubusercontent.com/27276132/57863193-59f11c80-7819-11e9-8ff6-9dfd46d5e91e.png)

**Comment by lmmrssa** [comment]
#3820 can be worked along with this

**Comment by paulbert** [comment]
We should fix #3820 first, then implement this in the same way using the fix on courses
