### ISSUE TITLE
Collections: Edit only subcollection gives "Value already exists"

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3825]
Steps to replicate:
- Go to collection list and click on Edit
- Put the cursor in collection name field.
- "Value already exist" validation shows and it doesn't allow to submit the collection.
![Screenshot from 2019-05-16 20-43-57](https://user-images.githubusercontent.com/27276132/57865031-996d3800-781c-11e9-9e2a-363a3b60ef22.png)

**Comment by paulbert** [comment]
Since the `_id` for a collections is generated based on the name. We'll also need to modify `updateTag` in `TagsService` to handle the case where the name does not change.
