### ISSUE TITLE
Adding resource on course

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3829]
Trying to link resources on course is showing empty resource.
![Screen Shot 2019-05-16 at 21 19 57](https://user-images.githubusercontent.com/2909490/57867393-cb809900-7820-11e9-8459-e05aa89f907e.png)

**Comment by paulbert** [comment]
The same issue we see popping up.  The resources in the table now have the document in the `doc` property rather than spread across the object.  We should make sure we are adding the selected `resource.doc` to courses.
