### ISSUE TITLE
DialogsList: Hover on number of courses or other items

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3831]
When hovering over number of courses selected, it only shows courses currently selected. 
If there are courses already selected (in case of edit) it does not show that on hover.
![Screen Shot 2019-05-16 at 21 29 20](https://user-images.githubusercontent.com/2909490/57867968-d4259f00-7821-11e9-9ace-7795dd9435e2.png)

**Comment by paulbert** [comment]
Adding courses to teams is used as an example, but this is broadly an error for DialogsList.  The number of selected is initializing correctly, but the tooltipText is not
