### ISSUE TITLE
Manager Actions: In 'Send Resource,' Show Number Of Selected Resources

### ISSUE THREAD

**Issue by YuserahN** [open-learning-exchange/planet#3856]
Under 'Manager Actions,' 'Send Courses' shows the number of selected courses. The same should be done for 'Send resource.' 

![send_courses_planet](https://user-images.githubusercontent.com/21087353/58062755-28da5a00-7b41-11e9-8b49-e4f66b5509ae.PNG)

In this case, the following should display 'Send Resources (1).' 

![send_resources_planet](https://user-images.githubusercontent.com/21087353/58062760-2e37a480-7b41-11e9-8c64-29dd4d865162.PNG)

**Comment by paulbert** [comment]
Modifying the same area of the code as #3853 

If both are open, feel free to fix in same PR
