### ISSUE TITLE
Editing and saving already associated tag is saving it twice.

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3878]
If we edit and save the tag, it is adding that tag to course or resource. To see this, you should try to edit tag but make the name same.

**Comment by lmmrssa** [comment]
![Sketch (37)](https://user-images.githubusercontent.com/2909490/58260445-2886cc80-7d96-11e9-9107-9567804dc2b9.png)

**Comment by paulbert** [comment]
In general the tag is being selected an additional time in the background.  When editing from the filter button, this changes the filter without changing the selection.

https://www.loom.com/share/b6b2a0df57a146008c50a997e24120ad
