### ISSUE TITLE
Course: selected collection tag can be made similar to resource

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3879]
To maintain consistency, selected collection tag can be placed in similar position as that of resource collection tag.
![Screenshot from 2019-05-23 20-04-29](https://user-images.githubusercontent.com/27276132/58260493-46543180-7d96-11e9-82b7-df332d635ad8.png)
![Screenshot from 2019-05-23 20-04-16](https://user-images.githubusercontent.com/27276132/58260494-46543180-7d96-11e9-8d31-84660a307274.png)

**Comment by lmmrssa** [comment]
Refer to #3699

**Comment by paulbert** [comment]
Also PR for resources implementation #3776

**Comment by paulbert** [comment]
We could add the collection text to `FilteredAmountComponent` to reduce repetition, too.
