### ISSUE TITLE
Course manage: Preview Test when empty shows inconsistent UI

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3880]
![Screenshot from 2019-05-23 20-25-58](https://user-images.githubusercontent.com/27276132/58262017-23774c80-7d99-11e9-84c7-ab7769412bcd.png)
- there should be space between "questionof"
- Question of should be hidden and empty message should be shown.
- Close preview button should be replaced by "X" icon.

**Comment by paulbert** [comment]
This is breaking the UI it appears, and nothing should show, anyway.  If there are no steps or there are form validation errors, we should not allow Preview.
