### ISSUE TITLE
Course manage: Preview Test submit validation message keeps on showing

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3881]
- Add Test of multiple choice- single answer.
- Preview test.
- Select wrong option.
- It will show message  " Incorrect answer"
- Select right option. but message keep on showing.
![Screenshot from 2019-05-23 20-39-14](https://user-images.githubusercontent.com/27276132/58263255-60dcd980-7d9b-11e9-95e3-4ccedc2d92bb.png)
In Preview Test, do we allow submit of answer as well?

**Comment by paulbert** [comment]
Closing.  This is a smaller part of #3885.  Once we implement changing the message for the final question on preview mode this will be fixed.
