### ISSUE TITLE
ExamsAdd: Preview message after last question

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#3885]
We need to have some sort of UI feedback when the exam is completed in preview mode in the dialog in ExamsAdd

Maybe where the incorrect answer shows we could just have a message that says "Exam complete" after clicking the button to submit the last answer.

**Comment by diabagatekelly** [comment]
Can I try working on this issue?

**Comment by paulbert** [comment]
Note there are two important booleans for this `previewMode` & `isDialog`.  `isDialog` currently only true when `previewMode` is also true, and is specifically for the preview from ExamsAdd.
