### ISSUE TITLE
Course: take test multiple times doesn't increase count of Past attempts

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3901]
Take Test only increase the Past attempts count to 1.
after we take test multiple times, Past attempts remains 1.
Also submitted answer from take test is also not showing in Submission.
It is just showing for First test.
![Screenshot from 2019-05-28 07-48-59](https://user-images.githubusercontent.com/27276132/58445633-1651b900-811d-11e9-9a97-787e07f4c09b.png)
![Screenshot from 2019-05-28 07-48-48](https://user-images.githubusercontent.com/27276132/58445634-16ea4f80-811d-11e9-8164-72e107ca5cff.png)

**Comment by paulbert** [comment]
There appears to be issues posting the submission document to CouchDB for a test. Trying to replicate, I see that test submissions aren't added to the database at all.

**Comment by paulbert** [comment]
Looks like this was actually the issue reported in #4017 and was fixed in #4023
