### ISSUE TITLE
Exams: Member Cannot Skip Over A Multiple Choice Question

### ISSUE THREAD

**Issue by YuserahN** [open-learning-exchange/planet#3908]
Using the next arrow, a member can skip over short answer and long answer questions while taking an exam. But cannot skip over multiple choice questions. The correct choice needs to be selected before the member can move on to the next question. Is that intentional?

**Comment by paulbert** [comment]
Currently the right arrow submits the answer, but maybe we don't need that.  Changing so only the "Submit Answer" button submits would help.  We would want to save the state of the answer somewhere, though, so a learner doesn't lose work in the middle of a test.

**Comment by paulbert** [comment]
Closing in favor of the newer issue.
