### ISSUE TITLE
Team: Edit message on Team feedback should be change

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3931]
When we edit the Team message or post, success message right now shown as 
![Screenshot from 2019-05-30 20-01-53](https://user-images.githubusercontent.com/27276132/58639114-07822680-8316-11e9-9b5d-4fd1e78975ee.png)

where as on delete, message is
![Screenshot from 2019-05-30 20-02-37](https://user-images.githubusercontent.com/27276132/58639143-1537ac00-8316-11e9-8a45-7c3819a6dfaf.png)

**Comment by paulbert** [comment]
Let's change the messages for teams to
- "Thank you for posting" for new message
- "Post has been updated successfully" for edited message

**Comment by paulbert** [comment]
For NewsListComponent it will require a new input variable we can call `editSuccessMessage`.

See https://angular.io/guide/component-interaction#pass-data-from-parent-to-child-with-input-binding for info on `@Input` binding.

**Comment by Liew211** [comment]
@paulbert I know this is a bit of a nitpick, but since they're called messages, wouldn't it make more sense to say "Message has been posted successfully", "Message has been updated successfully", and "Message has been deleted successfully"?

**Comment by paulbert** [comment]
@Liew211 Sounds good about using "Message" as the term consistently
