### ISSUE TITLE
MarkdownTextbox: Full screen not expanding fully

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3932]
![Screenshot from 2019-05-30 20-08-10](https://user-images.githubusercontent.com/27276132/58639494-bde60b80-8316-11e9-9179-f163952342ca.png)

**Comment by paulbert** [comment]
The new css for `planet-markdown-textbox` #3927 affected full screen.  Need to make sure there is another css definition specifically for full screen mode.

**Comment by paulbert** [comment]
Text editor docs if needed:
https://teradata.github.io/covalent/#/components/text-editor
