### ISSUE TITLE
Courses: Paginator bug

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#3935]
Noticed when I opened courses the paginator shows 0 of 0.  No errors in console, so this will need replication & debugging.

![image](https://user-images.githubusercontent.com/9203229/58640150-733ca300-82c6-11e9-8fc0-b406bcc8f5cf.png)

![image](https://user-images.githubusercontent.com/9203229/58640160-7768c080-82c6-11e9-9312-f0839382766c.png)

**Comment by svlesiv** [comment]
I was able to replicate this bug by accomplishing the next steps:
* refresh any page of the application and then click on Courses Page or refresh just Courses Page;
* paginator will show `0 of 0`;
* if to start navigating between pages, the bug will disappear.

To fix the issue, I added `this.courses.paginator = this.paginator` inside ngOnInit() of the courses.
