### ISSUE TITLE
Feedback title for take exam url

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3936]
right now feedback is submitted for the current page.
in case of take exam from course step, title seems quite long.
![Screenshot from 2019-05-30 21-09-56](https://user-images.githubusercontent.com/27276132/58643742-96e00780-831f-11e9-8b69-8d98236b9188.png)

its following default functionality but  seems bit confusing.

**Comment by paulbert** [comment]
To make this view look a little better, we should convert the parameters (separated by `;` at the end) into an object and display that separately from the rest of the url.
