### ISSUE TITLE
After title search if Collection is triggered it does not filter for title

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3952]
<img width="1149" alt="Sketch (42)" src="https://user-images.githubusercontent.com/2909490/58844988-317e7480-8699-11e9-9fa7-8a51fae019ea.png">

**Comment by lmmrssa** [comment]
After this even if **Grade** or **Subject** filter is triggered it will not filter based on **title** unless you reset

**Comment by paulbert** [comment]
Affects both Courses & Library pages.  Once "Collections" is clicked the filter resets.

**Comment by lmmrssa** [comment]
<img width="1145" alt="Sketch (53)" src="https://user-images.githubusercontent.com/2909490/59238625-846aa580-8c1e-11e9-80fc-fdaab14d05a5.png">
<img width="957" alt="Sketch (52)" src="https://user-images.githubusercontent.com/2909490/59238628-8896c300-8c1e-11e9-96a8-774fd0adad8a.png">
<img width="1146" alt="Sketch (54)" src="https://user-images.githubusercontent.com/2909490/59238635-93515800-8c1e-11e9-8860-4f856d3e4bfd.png">
