### ISSUE TITLE
Markdown Textbox: adjust bottom margin

### ISSUE THREAD

**Issue by svlesiv** [open-learning-exchange/planet#3956]
ExamQuestion: would be nice to decrease margin between `Add Choice` button and textarea.

![Screen Shot 2019-06-03 at 6 25 32 PM](https://user-images.githubusercontent.com/35533801/58845682-e597e500-8630-11e9-9261-30ec34782572.png)

ExamsView: it might look better if to decrease margin between `Submit Answer` button and textarea.

![Screen Shot 2019-06-03 at 6 43 52 PM](https://user-images.githubusercontent.com/35533801/58845712-0c561b80-8631-11e9-99f9-e32831ec57d7.png)

**Comment by paulbert** [comment]
I think in general the `planet-markdown-textbox` can have its bottom margin reduced
