### ISSUE TITLE
Collections: Add "Delete Collection"

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#3960]
We should add a button in the collections dialog allowing managers to delete a collection.

Note the changes to the database after clicking should be to delete from the tags database (1) the doc with the `_id` matching and (2) any other doc with `tagId` equal to that _id

**Comment by paulbert** [comment]
The dialog is `PlanetTagInputDialogComponent` and the function for deleting can go in to `TagsService`

**Comment by lmmrssa** [comment]
Associated to #3692
