### ISSUE TITLE
Rating bar gets hidden

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#3961]
Row selection and Rating bar for undefined is using same color. So rating bar seems hidden when row is selected.
<img width="1130" alt="Sketch (45)" src="https://user-images.githubusercontent.com/2909490/58847063-4e1eaa80-86a1-11e9-9490-0e637ded2261.png">
<img width="1147" alt="Sketch (46)" src="https://user-images.githubusercontent.com/2909490/58847064-4eb74100-86a1-11e9-94b0-5fc1e5bce373.png">

**Comment by paulbert** [comment]
As an added research task you could try to incorporate the new color into `_variables.scss` using the Material theming.  You can use hue 200 or 300 for the new color and please use the new color on the rating bar only

**Comment by samuelchen1213** [comment]
@paulbert I have added a new hue to _variables.scss, but I was wondering which file I have to use this hue. I checked the scss and html files in view-courses and I am confused on where to change the colour. Thank you for the help!

**Comment by lmmrssa** [comment]
@samuelchen1213 https://github.com/open-learning-exchange/planet/blob/baf89faa28438eca329574c5c05940afd8d3d756/src/app/shared/forms/planet-rating.component.ts#L75 is adding class `.primary-light-color` to stack-bar. Class is defined on **styles.scss**

If you have created new class then change given line on planet-rating.component.ts to use new class. Or you can just change `.primary-light-color` class background-color on **styles.scss**

_NOTE:_ Please do not change `mat-table .highlight` style

**Comment by samuelchen1213** [comment]
@lmmrssa Thank you very much!

**Comment by paulbert** [comment]
@samuelchen1213 Thinking about the naming for this a little more, I think the new hue should use the `primary-light-color` name and we should refactor so the other hue uses the term `lighter`.  Please make this change for both the primary and the accent light variables.  Let me know if you have any questions about this change.

Also, I didn't mention it during the meeting but we like to see code early and often!  As a general rule we say you should push your changes once you finish in a coding session and create a PR if you haven't already.  You can add the `WIP` label to let us know that you're still working on it, but it makes it easier for us to help you with questions or see if you are going in the wrong direction early.
