### ISSUE TITLE
Changing "Return" to "Save & Return"

### ISSUE THREAD

**Issue by samuelchen1213** [open-learning-exchange/planet#3967]
<img width="1269" alt="Screen Shot 2019-06-04 at 11 35 45 AM" src="https://user-images.githubusercontent.com/43349314/58893474-3efa2580-86be-11e9-89e9-bc86dc569bb9.png">
After saving the survey, the page is not routed back to the "surveys" page. I kept thinking it would route me back to surveys. After working around, I realized "Return" actually does save and route you back to surveys. I think this should be cleared up and just change "Return" to "Save & Return"

**Comment by svlesiv** [comment]
connects #3719

**Comment by samuelchen1213** [comment]
@svlesiv Thank you! will close this issue
