### ISSUE TITLE
Survey text answers automatically turn red

### ISSUE THREAD

**Issue by Liew211** [open-learning-exchange/planet#3978]
![image](https://user-images.githubusercontent.com/43839884/59042438-7563ac00-8848-11e9-84af-b0d46a18db59.png)
![image](https://user-images.githubusercontent.com/43839884/59042446-78f73300-8848-11e9-8da5-c4fcc3093681.png)
When taking a survey and reaching a text answer question, the boxes automatically turn red before you even click into the box.  This happens for all text answer questions that are not the first question in the survey.

**Comment by Liew211** [comment]
![image](https://user-images.githubusercontent.com/43839884/59042838-279b7380-8849-11e9-911e-391363365854.png)
![image](https://user-images.githubusercontent.com/43839884/59042847-2bc79100-8849-11e9-8933-8ebf76105cd9.png)
The same is also true for tests.

**Comment by paulbert** [comment]
Looks like a good issue.  Need to make sure the FormControl validation is reset, I think with `markAsUntouched`

https://angular.io/api/forms/FormControl
