### ISSUE TITLE
No button margins on certain pages

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#3985]
The "Add new Course" page and the "Update Course" pages should have margins between the buttons of "Submit", "Cancel", and "Add Step".

![Capture](https://user-images.githubusercontent.com/22685147/59044565-5b2bcd00-884c-11e9-975d-4d275080dad0.PNG)

![Capture2](https://user-images.githubusercontent.com/22685147/59044615-74cd1480-884c-11e9-890a-cad6c0563a95.PNG)

**Comment by paulbert** [comment]
We have some app wide styles for margins: `margin-lr-X` where X can be 1-10 and is a px value for the margins.

In this example, adding to the middle button would create spacing while maintaining the left alignment of the "Submit" button.
