### ISSUE TITLE
Collections: on update of course, update form shows empty

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3987]
Steps to replicate:
- create a course and save.
- Click on Change collection and add collection to above course.
- Click on Manage of given course.
- Update form shows empty with console error.
![Screenshot from 2019-06-06 21-01-21](https://user-images.githubusercontent.com/27276132/59044839-9eaf2700-889e-11e9-8425-0d616d99c0b4.png)
its working fine for courses who doesn't have collection

**Comment by paulbert** [comment]
Seems like any course with a collection throws this error.
