### ISSUE TITLE
Unable to create a collection that's not a subcollection upon creating a subcollection

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#3991]
Upon creating a subcollection of any collection, it becomes impossible to create a collection that is not a subcollection of another collection.

https://www.loom.com/share/e15a956dd6674564aa4e7ad4716af1aa

**Comment by paulbert** [comment]
This is actually the same issue as #3984.  Good to know that it also happens for newly created collections, but I'm going to close this.
