### ISSUE TITLE
Meetup date issue

### ISSUE THREAD

**Issue by Liew211** [open-learning-exchange/planet#3993]
Is a copy of #2712, was wondering if there have been any fixes for this yet?
Also, this issue occurs both when adding and updating a meetup.
![image](https://user-images.githubusercontent.com/43839884/59046985-fe7ee100-8850-11e9-9e52-333fb3257d85.png)

**Comment by paulbert** [comment]
#2712 has not been fixed.  I'm going to close that issue.

If I remember correctly sometimes the error even gets thrown when the next day is selected.
