### ISSUE TITLE
Forgot Password?

### ISSUE THREAD

**Issue by nirojdyola** [open-learning-exchange/planet#40]
I think request need to send to the Manager only. Manager can approve or reject the request. Please check the process from Bell App.

**Comment by nirojdyola** [comment]
@dog , @paulbert  Do I need to do the same process as done in Bell App. In Bell app the request is send to the manager internally, and the manger check for approve/ reject inbox mail.

**Comment by lmmrssa** [comment]
we might not be using this feature most probably so closing it
