### ISSUE TITLE
Surveys not showing up in mySurveys

### ISSUE THREAD

**Issue by samuelchen1213** [open-learning-exchange/planet#4006]
After creating surveys, they do not show up in `mySurveys`

<img width="1278" alt="Screen Shot 2019-06-08 at 3 10 43 PM" src="https://user-images.githubusercontent.com/43349314/59151359-b2be6a00-89ff-11e9-8473-b3516f1a271d.png">
<img width="1279" alt="Screen Shot 2019-06-08 at 3 10 49 PM" src="https://user-images.githubusercontent.com/43349314/59151360-b4882d80-89ff-11e9-8c65-ea5f0318f746.png">

**Comment by lmmrssa** [comment]
@samuelchen1213 mysurveys show survey sent to you not survey you created.
