### ISSUE TITLE
Making the feedback button design more user-friendly

### ISSUE THREAD

**Issue by ChiragAwale** [open-learning-exchange/planet#4012]
### Problem
 This might not be a problem for everyone but I personally had a problem finding the feedback button which I later found out after clicking a few buttons that the button with two arrows in a circular form is the feedback button. I think it will be more user-friendly if the button was to be changed to something different.

### Steps to reproduce the problem

N/A

### Screenshots

<img width="115" alt="Screen Shot 2019-06-10 at 1 00 11 AM" src="https://user-images.githubusercontent.com/19680263/59175668-058d4400-8b1c-11e9-90a4-61bf8a9ca0b4.png">
<img width="129" alt="Screen Shot 2019-06-10 at 1 00 31 AM" src="https://user-images.githubusercontent.com/19680263/59175669-058d4400-8b1c-11e9-856c-3d7cda85330a.png">
<img width="129" alt="Screen Shot 2019-06-10 at 1 01 39 AM" src="https://user-images.githubusercontent.com/19680263/59175670-0625da80-8b1c-11e9-8b5a-7c4353ba045c.png">
<img width="133" alt="Screen Shot 2019-06-10 at 1 00 22 AM" src="https://user-images.githubusercontent.com/19680263/59175671-0625da80-8b1c-11e9-8045-416dbb936bef.png">

### Proposed solution

The above screenshots are a few examples which might a bit more user-friendly.

**Comment by dogi** [comment]
thanks @Liew211 :P

**Comment by ChiragAwale** [comment]
Thanks for the feedback @sjson421. Thank you @Liew211. 😄 

So should i work on the pull request for this issue?

**Comment by ChiragAwale** [comment]
Is working on this fine or do I need to work on an issue on the other repository?

**Comment by Liew211** [comment]
@ChiragAwale This is a good issue, but try to find another one in the First Steps :)

**Comment by ChiragAwale** [comment]
@Liew211 Will do :D

**Comment by paulbert** [comment]
@ChiragAwale Where is that icon from?  We use svg icons, so we are able to use it in SVG format then we can use it otherwise we should look to see if there is a similar one here: https://material.io/tools/icons/?style=baseline

**Comment by ChiragAwale** [comment]
@paulbert I have attached the one I created to this comment. Please check if the resolution is good enough or are there any changes you would like me to make. Thank you.

https://drive.google.com/open?id=1R0jpzAbw9Px2UZjRGJAfCXmh9F6u1Yvp
