### ISSUE TITLE
Team: Change "detail" placeholder to "description"

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4016]
right now link says "Add Description" and in Update Team dialog box, placeholder named as "Detail". 
1. Change "Detail" placeholder to "Description" to maintain consistency within team and overall application.
2. cursor focus on "Detail" placeholder when adding description.
![Screenshot from 2019-06-11 07-45-35](https://user-images.githubusercontent.com/27276132/59238331-62bcee80-8c1d-11e9-891b-1f1c53042c35.png)

**Comment by sjson421** [comment]
@paulbert Could you explain what the second point means?

**Comment by sjson421** [comment]
@paulbert The Update Team modal is used for both the "Edit" and "Add Description" buttons; the two buttons actually have identical functionality, including name change. It would be easier to autofocus on the name (and this is already done) and I also think it makes sense, in the case that we are clicking the "Edit" button over the "Add Description" button, which only appears when a team has no description. What do you think?
