### ISSUE TITLE
Course Add Resource: collection filter result in resize of Profile layout inconsistently

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4020]
- In course manage, click on add resource.
- select/filter any collection.
- expand profile.
- In level column , full text is not shown.
![Screenshot from 2019-06-11 08-12-47](https://user-images.githubusercontent.com/27276132/59239320-c1379c00-8c20-11e9-943e-4abb12266556.png)

**Comment by paulbert** [comment]
Need to supply a width for `this.dialog.open`.  80vw or maybe 90 would be good I think.

See Material Dialogs:
https://material.angular.io/components/dialog/overview
