### ISSUE TITLE
Team reply of message does not sync

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#4036]
Right not message on news are syncing for team. But replies for those message does not sync

**Comment by paulbert** [comment]
They are missing values for `messagePlanetCode` (should match `teamPlanetCode` of the team) and `messageType` (should match `teamType` or equal `'sync'` for teams that "Connect with nation")

**Comment by paulbert** [comment]
Closing since #4120 repeats this and now has a PR.
