### ISSUE TITLE
moving sync button to easily accessible place

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#4037]
Right now it is required to go to manager page and then do sync. As we will require sync to be done often now we might want to put it somewhere it is easily accessible. May be on top menubar

**Comment by paulbert** [comment]
Ok I like this.  Ideally we could click on a sync button in the menu bar & just have the dialog to verify password then it'll start the sync in the background.

On another note: maybe another reason to change the feedback icon since that is very similar to the sync icon (#4012)

**Comment by ChiragAwale** [comment]
Yes indeed moving sync on the top menubar is a pretty good idea.
