### ISSUE TITLE
Date time on news message has two comma

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#4039]
Format of news time is Jun 13, 219, 8:35:13 PM Right now it is using medium format. Not sure if we want to change it, but may be it could use some better formatting.
![Sketch (56)](https://user-images.githubusercontent.com/2909490/59443445-b5fc9000-8e1b-11e9-89cc-10661d20d8b4.png)

**Comment by jessewashburn** [comment]
I think replacing the second comma with "at" looks cleaner, but obviously it's fine as is.

**Comment by Mutugiii** [comment]
Think we could use the short format, might be more concise
