### ISSUE TITLE
Team message: Viewing replies for message highlight

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4040]
- margin between "Add message" and "show main conversation"
- right now it says "Viewing Replies for" which contain main message alongwith its replies.
It would be better to highlight or differentiate main message from the given replies.

![Screenshot from 2019-06-13 20-44-20](https://user-images.githubusercontent.com/27276132/59444035-dda02800-8e1c-11e9-8692-b3ebab740c40.png)

**Comment by paulbert** [comment]
The first bullet point is #4038, so let's just work on the second one as part of this issue.

Currently there is minimal separation between the main message and the replies below.  I agree that should be clearer.

Ideas:
- Full border for the main message
- Use a background color to denote the difference (check https://material.io for the design specs on cards)

**Comment by diabagatekelly** [comment]
I tried to change the background color for the message box itself but I wasn't able to, so I tried something a bit different. I hope this works too, but  if not, I can keep working on it.
