### ISSUE TITLE
Team: Adding message inside any other message replies stays there

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4041]
Steps to replicate:
- Add new message and also add replies to it.
- click on show replies.
- message along with replies will be shown.
- Now in the current page click on Add message button.
- Message will be added but it stays in the current page.

**Comment by lmmrssa** [comment]
We can remove **Add message** during we are on reply. When we reach back to main message then it will be visible. This is confusing right now as message is actually added to main message.

**Comment by paulbert** [comment]
Same thing on "ourNews" we can remove the "Post" part when viewing replies.
