### ISSUE TITLE
Teams: Creator as Team Leader

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#4042]
We would like to have the creator of a team set as the "Team Leader"

The "Team Leader" should be able to
- Remove members of the team
- Archive the team
  - "Leave Team" button should be replaced with "Delete Team" for the leader so the team always has a leader.  "Delete Team" when clicked will open a prompt to confirm then archive the team.

Maybe we can add this as a property of the "membership" document for the creator of the team.  That would make it a little cleaner if in the future we want to implement changing team leadership.

Note that for "Connected teams" this will likely create a greater possibility of conflicts. 
- Member on the nation requests membership
- Community syncs
- On community that member is accepted then is deleted by leader
- On nation that member is accepted
- Community syncs -> conflict

**Comment by Liew211** [comment]
@paulbert I think leave team should be available unless the leader is the only member left in the team, only then should the leader be able to delete the team.
