### ISSUE TITLE
Tab functionality inconsistency

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4056]
The tab key functions differently based on the page, specifically on the input fields.

On most pages, I believe the intended behavior is for the tab key to skip to the next field if you are typing in a text field. This works on the creation of a course, etc.

However, as one example, when you are editing your achievements, the tab key will "tab" the line that you are on, even if your cursor is focused on the end of the line.

![Capture](https://user-images.githubusercontent.com/22685147/59646826-97153b00-9146-11e9-901a-3d45dc3aa25e.PNG)

This tabbing happened even when my cursor was on the end of the "Test" text field.

**Comment by lmmrssa** [comment]
@sjson421 It is the richtext and it will just work as you are working on any text-editor.
