### ISSUE TITLE
Clicking preview on exam in course results in question 1/0

### ISSUE THREAD

**Issue by DavidMcKissick** [open-learning-exchange/planet#4058]
## Steps to reproduce
1. Open a course
2. Click on an exam
3. Click preview

### Images
![issuex](https://user-images.githubusercontent.com/25361438/59646983-2eba5f80-912e-11e9-8f21-b3c53e98d693.gif)

### Relevant error
![issuex](https://user-images.githubusercontent.com/25361438/59647025-688b6600-912e-11e9-8a70-0a883c14c04b.PNG)

**Comment by lmmrssa** [comment]
@DavidMcKissick it looks like there is no exam synchronized for these courses. It could be because these are old exams or synced with old structure. New courses created should work fine.

**Comment by DavidMcKissick** [comment]
Alright let me test a new course and if it goes away I'll close the issue.

**Comment by DavidMcKissick** [comment]
@lmmrssa yup, confirmed to be the issue. Closing.
