### ISSUE TITLE
Reopening feedback does not match standard behavior

### ISSUE THREAD

**Issue by DavidMcKissick** [open-learning-exchange/planet#4061]
When feedback is closed, the window redirects. When reopened the window remains idle and the button can be re-clicked infinite times to generate the following error:
![issuey](https://user-images.githubusercontent.com/25361438/59647666-ec465200-9130-11e9-9e80-4cb8872decc2.PNG)

## Steps to reproduce
1. Open manager 
2. Open feedback
3. Open a feedback
4. Close feedback
5. Reopen feedback
6. Click reopen button again

**Comment by lmmrssa** [comment]
@DavidMcKissick it will be good to disable button immediately usually when system is not responding quickly. 
Re-open should just change button to close after updating feedback status.
Fix that can be implemented here is to disable button or show spinner to prevent user from further action until request is complete.
