### ISSUE TITLE
Extremely long names do not wrap

### ISSUE THREAD

**Issue by DavidMcKissick** [open-learning-exchange/planet#4063]
Extremely long names for teams, courses, etc do not wrap but rather get cut off.

![issueA1](https://user-images.githubusercontent.com/25361438/59648126-cfab1980-9132-11e9-8571-a1ca3caa417d.PNG)

![issuez](https://user-images.githubusercontent.com/25361438/59648127-cfab1980-9132-11e9-8c6a-3e13803d3bfa.PNG)

![issueB1](https://user-images.githubusercontent.com/25361438/59648128-cfab1980-9132-11e9-82d0-409e7febef57.PNG)

All names were alphanumeric strings with a length greater than 200 characters

**Comment by lmmrssa** [comment]
@DavidMcKissick if you have multiple words it will work fine and very long word is not the ideal usecase.

**Comment by DavidMcKissick** [comment]
@lmmrssa Makes sense. I reported mostly for edge case uses. In the future, should I avoid edge-case issues or continue to report them?

**Comment by lmmrssa** [comment]
@DavidMcKissick you can raise issues as some of them could be important to take care of.

**Comment by DavidMcKissick** [comment]
@lmmrssa Alright, understood.
