### ISSUE TITLE
Course: console error when I submit a survey.

### ISSUE THREAD

**Issue by ScottHuangNYU** [open-learning-exchange/planet#4065]
![image](https://user-images.githubusercontent.com/31773567/59648823-0179ab80-9146-11e9-9ff4-d19819f293cf.png)

https://www.loom.com/share/4275226340ae416082c67d1a8929cc19

**Comment by lmmrssa** [comment]
@ScottHuangNYU we will have to check what is the actual case of this happening. It looks like survey was submitted correctly. So it could be course view trying to update attempts. need some debugging to find out actual case.

**Comment by ScottHuangNYU** [comment]
@lmmrssa I attached a video about the issue And I can see the survey in mySurvey page, so I think it was submitted correctly.

**Comment by paulbert** [comment]
Likely this is the same issue fixed in #5676
