### ISSUE TITLE
For myplanet upgrade do not show reboot message.

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4081]
A "Success!" dialog box appears even when no upgrade has been made, prompting a reload. This could be confusing for first-time users.

![Capture](https://user-images.githubusercontent.com/22685147/59856444-ea54dc80-9344-11e9-8a00-99ec64827080.PNG)

**Comment by lmmrssa** [comment]
This is myplanet upgrade not planet upgrade based on image posted here. Also message shows that myplanet was upto date.
Yes we can update the message on Success as myplanet upgrade will not require to have reboot.

**Comment by paulbert** [comment]
@samuelchen1213 This change should occur on the route `/upgrade/myplanet` which you will need to manually go to in the dev environment since the link to it will never show up there.
