### ISSUE TITLE
Sync: Admin confirmation success message shows "[Object][Object]

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4082]
![Screenshot from 2019-06-20 20-04-38](https://user-images.githubusercontent.com/27276132/59856513-c28e6480-9396-11e9-847a-3694f907c5eb.png)

**Comment by lmmrssa** [comment]
@singharpita looks like there was error on sync which is causing this message to show. May be some replicator not completed before or new not being able to create.

**Comment by lmmrssa** [comment]
We should try to update the error message instead of showing **Object**
