### ISSUE TITLE
Feedback re-open infinite spinner

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4083]
Maybe a resurgence of Issue #4061.

## Steps to reproduce
1. Open manager 
2. Open feedback
3. Open a feedback
4. Close feedback
5. Reopen feedback
6. Click reopen button again

Re-opening the issue will successfully re-open the issue after a spinner, but the button will not change to "Close", allowing it to be clicked on again and cause an error. This will also cause an infinite spinner.

Works fine on dev.

**Comment by sjson421** [comment]
I wonder if this has anything to do with this:

`this.feedbackServive.openFeedback(feedback).subscribe(() => this.getFeedback(feedback.id));`

Being changed to this:

`this.feedbackServive.openFeedback(feedback).subscribe(() => {
      this.getFeedback(feedback.id);
      this.dialogsLoadingService.stop();
    });`

Shouldn't `this.getFeedback(feedback.id);` be `return this.getFeedback(feedback.id);` to have the same functionality?

**Comment by lmmrssa** [comment]
@sjson421 subscribe does not need to return. Previous code was closing spinner without waiting for response. But we as this is case of error, we can add error condition.
