### ISSUE TITLE
Teams: Multiple request notifications

### ISSUE THREAD

**Issue by samuelchen1213** [open-learning-exchange/planet#4087]
After a member requests to join a team. The admin would get three notifications of this request.

### Steps to reproduce this issue
1. Create a new team, or have an existing one
2. Create a member, or login to an existing one
3. Request to join team
4. Log back into admin or another team member (Here you will see the **three** notifications)

<img width="812" alt="Screen Shot 2019-06-20 at 11 23 46 AM" src="https://user-images.githubusercontent.com/43349314/59861004-fbeeb200-934d-11e9-81e2-a39be913d7f1.png">

**Comment by lmmrssa** [comment]
@samuelchen1213 can you reconfirm or reproduce it. As this does not seem to be the case.

**Comment by samuelchen1213** [comment]
@lmmrssa I have tested it multiple times, locally and synced with nation

**Comment by lmmrssa** [comment]
looks like this is in consistent issue. But it looks like there is more than one notification send (which is not always a case) so we need to check for which is causing it.
