### ISSUE TITLE
Gender ratings percentage

### ISSUE THREAD

**Issue by Liew211** [open-learning-exchange/planet#4089]
I think that even though two percentages from 100% is easy to calculate, the ratings bar should still display both percentages for either gender, i.e. 33% ------- 67%, 50% ------ 50%, etc
![Screenshot_2019-06-20 Planet Learning](https://user-images.githubusercontent.com/43839884/59862166-496c1e80-9350-11e9-8a24-502c009c8536.png)

**Comment by lmmrssa** [comment]
@Liew211 Don't think you have any male person doing rating. It looks like just female and those whose gender is not unspecified.
