### ISSUE TITLE
Make beta dashboard as default dashboard

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#4103]
Dashboard should have label of their community such as somalia should have Somalia Planet. And make the Kismayo Community center to be dynamic

**Comment by lmmrssa** [comment]
We need to implement Submissions, mySurvey in this view as well.

**Comment by paulbert** [comment]
@anishregmee This needs a lot more work.  I'll be taking over on it today.  Thanks for starting on it.
