### ISSUE TITLE
Team: on user reject, no notification is send to the user

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4111]
- it will be good if user is notified that s/he is rejected from the above team.
- while rejecting user, dialog box for reason for rejection of particular user should be display so that it will clarify user why s/he is rejected.

Question:
- once a user is rejected from team, does s/he allowed to request for the given team again?

**Comment by lmmrssa** [comment]
Yes they can request again. Regarding reason for rejection we will talk on system meeting if we want that. But yes there is a huge change coming in with team as we will implement team leader.

**Comment by lmmrssa** [comment]
Lets just start with sending notification to member whose request has been rejected
