### ISSUE TITLE
Collection: edit of collection from course/library result in spinner loading

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4113]
although collection has been updated, but spinner keeps on loading in manage page.
![Screenshot from 2019-06-25 07-38-16](https://user-images.githubusercontent.com/27276132/60063316-3ffe0000-971c-11e9-9550-9660b0046038.png)

**Comment by lmmrssa** [comment]
as #4117 has more detail and is same issue closing this one.
