### ISSUE TITLE
"Message" button on navbar goes to Feedback list

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4114]
![image](https://user-images.githubusercontent.com/22685147/60063773-07ced100-96cc-11e9-999b-ccb0140965ae.png)

Clicking on the Message button goes to the Feedback list.

This is the same for regular members, not just managers, who should not see a list of feedbacks in the first place.

![Capture2](https://user-images.githubusercontent.com/22685147/60063862-68f6a480-96cc-11e9-82a6-bed78b9ee02f.PNG)

**Comment by lmmrssa** [comment]
Oh members will see feedback they have posted. So they can follow up on feedback
