### ISSUE TITLE
Registration: small suggestion to change repeated username message

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4115]
![Capture](https://user-images.githubusercontent.com/22685147/60064059-3600e080-96cd-11e9-87a4-a0f5c16b7386.PNG)

It's rather unusual to have "Value already exists" for something as common as a repeated username. 

**Proposed Solution**:
I think just for the sake of people who are not as used to these kinds of messages, the message should be changed to something along the lines of "Your username is already taken. Please select a different username."

**Comment by lmmrssa** [comment]
Yes good point, we are currently using general message in most places. For specific cases as username it will be better to have different message.
