### ISSUE TITLE
Add new Course: Infinite spinner on changing subcollection status

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4117]
![Capture](https://user-images.githubusercontent.com/22685147/60064477-8e84ad80-96ce-11e9-850c-c6b4176008ea.PNG)

Changing the subcollection status of a collection while creating a new course will cause an infinite spinner

**Steps to Reproduce**:

1. Courses
2. (+) Button to add new course
3. Collections button
4. Click on "Edit" on any collection
5. Change the dropdown under "Subcollection of"
6. Click OK

This will cause an infinite spinner.

Might be the same issue as #4113, just on a different page. For me, I can update the collection from the Collections button on course.

**Comment by lmmrssa** [comment]
@sjson421 Yes it same as #4113.
We need to close the dialog there seems not to have dialogloading being closed
