### ISSUE TITLE
Members: Clicking on Lock button makes roles invisible to manager

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4119]
Locking the role status of a member will make his or her roles invisible to the manager. This includes all roles other than manager, meaning all three of learner, leader, and manager. 

![Capture](https://user-images.githubusercontent.com/22685147/60065459-e5d84d00-96d1-11e9-8cf8-9b753b3ac953.PNG)

In the above screenshot, *test2* has all three roles; however, because the roles are invisible, you cannot tell how he or she has which role.

**Comment by lmmrssa** [comment]
This is making user inactive. So he will not have any role after than not able to use system functionalities.

**Comment by sjson421** [comment]
@lmmrssa If this is so, there should be some indication as to what the lock buttons do, maybe on hover. I was under the impression that it locked promotion capabilities.

**Comment by lmmrssa** [comment]
We can introduce text saying Unlock or Lock user.
