### ISSUE TITLE
Collection: Deleting subcollection deletes parent collection and not subcollection

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4139]
Deleting a subcollection also deletes its parent collection.

**Steps to Reproduce**

1. Courses
2. Collections button next to title
3. Open the dropdown next to a collection with a subcollection
4. Delete subcollection

The parent subcollection is deleted in this case, with the "deleted" subcollection staying.

Creating a new collection with the same name as the parent collection results in this new collection inheriting the deleted one's subcollections.

**Comment by paulbert** [comment]
In the template for **PlanetTagInputDialogComponent** you can see the second delete button should delete `subTag` but is deleting `tag`
