### ISSUE TITLE
Show News in team

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#4144]
Inside team when we toggle between Description and Message by clicking **Show Description** button changes to **Show News** Inside team we call it as Message so it should be **Show message**
![SharedScreenshot1](https://user-images.githubusercontent.com/2909490/60276361-30003f00-991b-11e9-8bc9-e2ee972bd2be.jpg)

**Comment by paulbert** [comment]
Let's make the text **Show Messages**
