### ISSUE TITLE
Sync: Syncing from navbar and entering password doesn't close modal

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4145]
![Capture](https://user-images.githubusercontent.com/22685147/60276945-98730000-98ca-11e9-9958-bcd6e30bb4dc.PNG)

The above screenshot is after I've entered my password and clicked submit. The syncing starts, but the modal resets to its default state, with an additional error message saying the password field is required. Re-entering my password and pressing submit will close the modal.

**Comment by paulbert** [comment]
Same as #3870
