### ISSUE TITLE
Collection: Changing name orphans subcollections

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#4149]
When collection is edited its sub collection are not updated
https://www.loom.com/share/ed3505c53fa74655a915597d93acaded

**Comment by paulbert** [comment]
Changing the name for clarity.  Note video also shows issue #4155

**Comment by paulbert** [comment]
Need to change the value of `attachedTo` for subcollections to match the new id of the edited collection.

**Comment by jessewashburn** [comment]
confirmed.
