### ISSUE TITLE
Library search filter

### ISSUE THREAD

**Issue by Liew211** [open-learning-exchange/planet#4153]
Similar to #3563 
When professional is selected, it jumps to the top of the level list. When any other level is selected, professional jumps to the bottom of the level list.

**Comment by paulbert** [comment]
Let's make these alphabetically ordered for now.

**Comment by paulbert** [comment]
So for each of Subject, Level, Medium, and Language we should sort them alphabetically (make sure also to make the sort not case sensitive) as they change when we select items.

**Comment by paulbert** [comment]
Specifically you're looking at an additional sort step for `items` in `createSearchList` of **ResourcesSearchComponent**
