### ISSUE TITLE
Team message: should be show more/show less button for long message

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4170]
it would be nice to have show more /show less button for long message so that action button edit /reply/delete should always be visible at first.
![Screenshot from 2019-07-02 07-09-59](https://user-images.githubusercontent.com/27276132/60475748-9a590c80-9c98-11e9-8ad6-2ca14ea3cc4d.png)
![Screenshot from 2019-07-02 07-14-50](https://user-images.githubusercontent.com/27276132/60475868-20755300-9c99-11e9-9fca-5a708e476666.png)

**Comment by paulbert** [comment]
Let's show approximately 6-8 lines when it is minimized
