### ISSUE TITLE
Team/News : same success message for reply and edit 

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4171]
same message is shown when user reply to message or edit any message.
![Screenshot from 2019-07-02 07-17-11](https://user-images.githubusercontent.com/27276132/60476060-ce80fd00-9c99-11e9-90d9-e99ba57270b6.png)
![Screenshot from 2019-07-02 07-17-23](https://user-images.githubusercontent.com/27276132/60476061-ce80fd00-9c99-11e9-8d68-f6fc153a5da2.png)

**Comment by paulbert** [comment]
Reply can use the same snackbar message as the one for creating a new message/post

**Comment by paulbert** [comment]
Or it would be better to say "Reply has been posted successfully"
