### ISSUE TITLE
Dashboard: mySurvey number not showing

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#4176]
Similar to #4175, but instead the indicator is not on the old dashboard, but is on the beta dashboard:

![image](https://user-images.githubusercontent.com/9203229/60476698-88e91380-9c4a-11e9-9c0e-6a247952830a.png)

![image](https://user-images.githubusercontent.com/9203229/60476680-7969ca80-9c4a-11e9-84f9-ec34ae186cbc.png)

**Comment by anishregmee** [comment]
https://github.com/open-learning-exchange/planet/pull/4206/commits/19c97ed28800ba58d36da0447b7b8835e8a77ad8
