### ISSUE TITLE
Question: why is reboot needed after myPlanet update?

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/planet#4178]
![0 8 17-8](https://user-images.githubusercontent.com/13684059/60476707-8f778b00-9c4a-11e9-88a7-d385a14299fe.png)

by the way I <3 the verify button

**Comment by paulbert** [comment]
@dogi I didn't realize you were talking about **my**planet upgrade in the meeting.  I also do not think the restart message is required for this.

**Comment by paulbert** [comment]
There is an issue for this: #4081 so closing
