### ISSUE TITLE
Change collection is unavailable for User of role learner.

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4181]
User with role learner might want to change collection of bulk resource/course from the list.
Change collection option should be available hiding add feature similar to Collection or Add Collection.
![Screenshot from 2019-07-02 07-38-15](https://user-images.githubusercontent.com/27276132/60477011-6f24ec00-9c9d-11e9-9542-d20859114bdc.png)
![Screenshot from 2019-07-02 07-44-22](https://user-images.githubusercontent.com/27276132/60477012-6fbd8280-9c9d-11e9-91d6-aa326302bb7f.png)

**Comment by paulbert** [comment]
We hide that button since a learner can only modify collections for a resource/course they created.  It would be a little opaque to allow them to select many items, click change collections, and only modify a subset of those items.

Closing
