### ISSUE TITLE
Why create a profile each time a survey is completed?

### ISSUE THREAD

**Issue by samuelchen1213** [open-learning-exchange/planet#4183]
After a survey is "recorded" it promts you to input the same information as when you created the account (As you can see below). 

I believe it would be much more efficient if the information was just taken from when you initially created the account. 

Is there a reason for inputting information again?

<img width="1280" alt="Screen Shot 2019-07-01 at 10 02 48 PM" src="https://user-images.githubusercontent.com/43349314/60477303-c484dd00-9c4c-11e9-905e-e78862133b45.png">

**Comment by paulbert** [comment]
@samuelchen1213 The record survey feature is there so a person who has an account can get information from people who do not have accounts.  The Planet member can take their tablet or laptop out and ask people to complete the survey who don't have an account, and then at the end they can fill in optional data about themselves.

**Comment by samuelchen1213** [comment]
@paulbert Would a possible solution to implement a checkbox so that the user can select it if they are the one submitting the survey? The form is pretty time consuming with specifics such as email and phone numbers

**Comment by paulbert** [comment]
Closing since the "Record Survey" feature should not be used if the person taking the survey is the member logged in to Planet
