### ISSUE TITLE
Team messages viewable for nonmembers

### ISSUE THREAD

**Issue by Liew211** [open-learning-exchange/planet#4184]
![Screen Shot 2019-07-01 at 10 10 43 PM](https://user-images.githubusercontent.com/43839884/60477433-2f361880-9c4d-11e9-8fda-8e98c2d11628.png)
This is from a screen recording.  When a nonmember goes to view a team, the messages page loads and displays for a split second before showing the description page.

**Comment by paulbert** [comment]
This has to do with the initial values of the variables controlling which view is shown.

We should make sure that before the membership status of the currently logged in user is received the message view is not shown.

**Comment by paulbert** [comment]
Note I wasn't able replicate this issue, but that doesn't mean it's not there

**Comment by Liew211** [comment]
@paulbert I was able to fix this issue, but now it displays a default team display (no team name, empty members list, no description) for a split second.  Is this ok or can I do something about it?
