### ISSUE TITLE
Bring centers into planet

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/planet#42]
port | server | nation | communities
---|---|---|---
5989 | hammock.media.mit.edu | [earthbell.ole.org](http://earthbell.ole.org:5989/_utils/database.html?nations/_design/bell/_view/getAllNations) | [public](http://earthbell.ole.org:5989/_utils/database.html?communityregistrationrequests/_design/bell/_view/getAllCommunities)
5997 | hammock.media.mit.edu | [nbs.ole.org](http://nbs.ole.org:5997/_utils/database.html?nations/_design/bell/_view/getAllNations) | [dev](http://nbs.ole.org:5997/_utils/database.html?communityregistrationrequests/_design/bell/_view/getAllCommunities)
5985 | hammock.media.mit.edu | [old.vi.ole.org](http://old.vi.ole.org:5985/_utils/database.html?nations/_design/bell/_view/getAllNations) | [vi](http://old.vi.ole.org:5985/_utils/database.html?communityregistrationrequests/_design/bell/_view/getAllCommunities)
5983 | qa.ole.org | [center.qa.ole.org](http://center.qa.ole.org:5983/_utils/database.html?nations/_design/bell/_view/getAllNations) | [qa](http://center.qa.ole.org:5983/_utils/database.html?communityregistrationrequests/_design/bell/_view/getAllCommunities)

are our center s which are right now using 2 databases:
- nations
- communityregistrationrequests

- [ ] we should make a special usertype `planet` which is able to see, edit, create and delete new nations ...
- [ ] communityregistrationrequests will help us to show everything about communities on each nation

**Comment by lmmrssa** [comment]
[] Add nations
[] List nations and its configuration/settings
[] List all communities of nations
[] View requested, rejected, accepted community list
[] Get overview of publications, resources, courses, etc of each nation/community
[] Create graphical charts for reports
[] Ability to enable disable any nation
[] Communicate with nation
