### ISSUE TITLE
Teams: Deleted members still exist on team

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4210]
Members deleted by the manager still exist on the teams they were in previously, making deletion of said team impossible.

**Steps to Reproduce**:

1. Create a team
2. Have a member join this team
3. Have the manager delete that member
4. The member will still be "on" the team although he or she has been deleted from the system, making deletion impossible since there will always be that deleted member on the team.

**Comment by paulbert** [comment]
Good catch.  When deleting a member we should also delete the membership docs in the team database.

**Comment by paulbert** [comment]
Specifically in the teams database you would delete docs that match: `{ docType: 'membership', userId: user._id }`

**Comment by paulbert** [comment]
Also, use the `bulkDocs` method supplying the `_delete: true` property to delete.
