### ISSUE TITLE
Teams: Leader can delete, not leave

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4211]
I think before the team leader leaves a team, he or she should be forced to designate another team leader if there are still other members left in the team. Otherwise, the team is left without a team leader.

**Comment by paulbert** [comment]
Since we want to give team leaders the ability to delete the team outright, let's start by replacing **Leave Team** with **Delete Team** for the leader.

Note that **Delete Team** should archive the team (set `status: archived`), not delete it.
