### ISSUE TITLE
Teams: Re-invited team leader is still team leader

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4212]
If a team leader decides to leave a team and is re-invited into the team afterwards, he or she will still be considered a team leader. Not sure if we want that.

**Steps to Reproduce**:

1. Create a team as User A.
2. Have another member join this team.
3. Have User A leave this team.
4. Have User A request to join this team again.
5. Have the second member accept this request.
6. User A will still be considered the team leader, whereas the second member will not be. (Relates to #4211)

**Comment by paulbert** [comment]
This is a good question, but the solutions for #4211 will make this obsolete.  Closing.
