### ISSUE TITLE
Teams: Set leader in membership doc

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#4214]
Right now in teams the Team Leader is just the user in the `createdBy` field of the team.  We should keep that field, but add a `leader: true` to the membership document of the creator.

This will allow us to pass leadership between members if required in the future.

**Comment by paulbert** [comment]
@diabagatekelly I want to keep this one moving so just posted the fix for it.  Reassigning you to this issue #4233.  Thanks in advance!

**Comment by diabagatekelly** [comment]
Got it.
