### ISSUE TITLE
Teams: UI change suggestion

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4233]
I think courses should be split into a separate column so that you don't have to scroll so quickly when additional courses are added.

![image](https://user-images.githubusercontent.com/22685147/60852785-31f1ba00-a1c7-11e9-8f75-7cb5749fe750.png)

**Suggested Solution**:

Create a new column for courses as the second column, with the third column holding member info.

**Comment by paulbert** [comment]
Messages could get long, so I like having a lot of space for that.

I would suggest we could see if using tabs would make this view less cluttered:
https://material.angular.io/components/tabs/overview
