### ISSUE TITLE
Leaving team confirm dialogue

### ISSUE THREAD

**Issue by Liew211** [open-learning-exchange/planet#4236]
I think there should be a dialogue box confirming when a user wants to leave a team.  In the same vein, there could also be a similar dialogue box when joining, that allows a user to send a join request message.

**Comment by paulbert** [comment]
Yes for the dialog to confirm leaving.

I think we can tackle joining later, but it would be better to just implement #2071 and allow them to cancel the request

**Comment by paulbert** [comment]
The dialog that we use for confirmation is `DialogsConfirmComponent`
