### ISSUE TITLE
Team: add timestamp in Team list page similar to Team detail page

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4239]
![Screenshot from 2019-07-09 07-24-41](https://user-images.githubusercontent.com/27276132/60853224-c89b9680-a21a-11e9-8c0d-769243f6be68.png)
![Screenshot from 2019-07-09 07-24-50](https://user-images.githubusercontent.com/27276132/60853226-c9342d00-a21a-11e9-8e0a-cf670bba34a5.png)

**Comment by paulbert** [comment]
Documentation for Material Table, which will help for adding a column:
https://material.angular.io/components/table/overview
