### ISSUE TITLE
Reports: Filter both shows no data

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#4240]
Toggle on myPlanet is giving **Both** and Both is filtering for **myPlanet**

**Comment by lmmrssa** [comment]
Looks like myPlanet and Planet are filtering but **Both** is returning empty.
Other point is chart when hovering changes value which is making it confusing.
**Filtering Both**
![SharedScreenshot-both-filter](https://user-images.githubusercontent.com/2909490/60854033-6a70b280-a21e-11e9-9fb8-8d137c397005.jpg)
**Filtering myPlanet**
![SharedScreenshot-myplanet-filter](https://user-images.githubusercontent.com/2909490/60854034-6b094900-a21e-11e9-83f8-76a158dacb66.jpg)
**Filtering Planet**
![SharedScreenshot-planet-filter](https://user-images.githubusercontent.com/2909490/60854035-6b094900-a21e-11e9-9eb1-c01fc21bd67d.jpg)

**Comment by paulbert** [comment]
Request for both should use ave `androidId: undefined` (so that property actually is not sent to the server in that case.
```
selector: {createdOn: "dev", androidId: {}}
```

**Comment by paulbert** [comment]
Please limit this issue to fixing the Both option so we can get that fix in quickly
