### ISSUE TITLE
Tick icon of myLibrary does not seem so visible

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#4251]
Right now we show **Tick** icon next to resource that we have added to our library. It will look more visible if we use icon like **favorite** or **bookmark**

**Comment by lmmrssa** [comment]
Additional NOTE: We could probably implement **Add to myLibrary** or **Remove from myLibrary** by clicking this icon instead of having it hidden under **3-dot**

**Comment by paulbert** [comment]
We can use filled in bookmark and not filled in.  I think we can leave the button in the three dot menu for now in case people use that.
