### ISSUE TITLE
Display team type

### ISSUE THREAD

**Issue by Liew211** [open-learning-exchange/planet#4253]
Should we display the team type in the list view?

**Comment by paulbert** [comment]
The text should read **Local** or **Connected with Nation**

**Comment by paulbert** [comment]
Table documentation (will be helpful for adding a column):
https://material.angular.io/components/table/overview

**Comment by paulbert** [comment]
@AlekseiKorolev The request is to add a column with the `teamType` in this table in **TeamsComponent**:
![image](https://user-images.githubusercontent.com/9203229/60928351-0defb080-a27b-11e9-8566-d4975defd538.png)
