### ISSUE TITLE
Teams: Make resources into mat-cards

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4280]
![image](https://user-images.githubusercontent.com/22685147/61057996-62eb0e00-a3c4-11e9-92b7-064dd40b3333.png)

Would be nice to fit the list of resources in buttons so it's more noticeable that they are clickable.

**Comment by lmmrssa** [comment]
with #4233 we are trying to move to tabular section for Members, courses and resources. Then we might be able to change the UI for Resource List

**Comment by paulbert** [comment]
Let's make these `mat-card` elements like the rest of the items.

Also good point on the rearrangement.  I think we can work on these at the same time.  It will likely case a small conflict, but not too bad.
