### ISSUE TITLE
Dashboard always show learner as one of role for all active users

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#4283]
![SharedScreenshot-dash](https://user-images.githubusercontent.com/2909490/61060530-6315f880-a41a-11e9-8489-449ca7f41748.jpg)

**Comment by paulbert** [comment]
Edit: fixing title.  Every active member should show learner, not necessarily leader

**Comment by paulbert** [comment]
Learner should be first role, also
