### ISSUE TITLE
Courses/resources bookmark button

### ISSUE THREAD

**Issue by Liew211** [open-learning-exchange/planet#4291]
![image](https://user-images.githubusercontent.com/43839884/61066848-4e167680-a3d4-11e9-84d1-442645499b99.png)
I think the bookmark button is in an awkward position, a little too close to the clickable title of the item.  I recommend moving it to below the checkbox, or to the left of the 3-dot details button

**Comment by paulbert** [comment]
Closing.  Needs design help and may reconsider when we have the resources.
