### ISSUE TITLE
Surveys: Order arrow requires double click on ordering up

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4292]
Probably low priority. Changing the direction of the sorting arrow from down to up will erase the arrow icon upon first click and requires another click to update the icon to pointing back up.

![image](https://user-images.githubusercontent.com/22685147/61067064-bfeec000-a3d4-11e9-8b9a-220cb0c21624.png)

**Steps to reproduce**:
1. Go to the Surveys page.
2. Click on the arrow button until the arrow is pointing down. (should be default)
3. Click on the arrow button once. The icon will disappear but the list will order correctly.
4. Click on the arrow again. The icon will update.

**Comment by paulbert** [comment]
@sjson421 I think there is an option to have the sort not cycle through the default unordered list.  I like it this way, but I think the 2 click might be preferable for others.

Could you also make this change for Library, Courses, Teams, and Meetups?  Thanks!

https://material.angular.io/components/sort/overview
