### ISSUE TITLE
Dashboard: If no resources or courses, no teams shown

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#4306]
If the logged in user hasn't marked any resources or courses in myLibrary/myCourses, then no teams they are a part of will show up on the dashboard

![image](https://user-images.githubusercontent.com/9203229/61149119-5fcc4c80-a4ae-11e9-9789-0a5594b8c69b.png)

**Comment by Liew211** [comment]
![image](https://user-images.githubusercontent.com/43839884/61231540-50d9da00-a6fa-11e9-8f1b-2487f7da82b4.png)
@paulbert I'm unable to duplicate this issue.
