### ISSUE TITLE
Menu: Hide sync button if planet not accepted

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#4308]
If a Planet system has not been accepted by its parent (community -> nation or nation -> earth), then we should not show the sync button since we do not want to allow that data transfer until the system has been accepted

**Comment by leahphuong** [comment]
Hi!
Somehow I have been added to this
Please remove me
Probably @poiuy999

**Comment by lmmrssa** [comment]
@leahphuong issue has not assigned to you. You might have subscribed for **planet** repository, you can unwatch yourself.

**Comment by lmmrssa** [comment]
This issue is no longer valid
