### ISSUE TITLE
Meetups - Information UI

### ISSUE THREAD

**Issue by samuelchen1213** [open-learning-exchange/planet#4322]
<img width="1261" alt="Screen Shot 2019-07-15 at 9 21 54 PM" src="https://user-images.githubusercontent.com/43349314/61259088-a4721500-a746-11e9-8056-b04dc2d76a51.png">

Titles such as Date, Recurring, and Location should be bolded for a clearer UI

It would look like:

**Date:** Wednesday, June 19, 2019 - Wednesday, June 19, 2019 at 10:00 - 21:00
**Recurring**:  None
**Location**: Online

**Comment by Mutugiii** [comment]
Meetups is deprecated
