### ISSUE TITLE
Team creator still sees make leader button when not in team

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4325]
- create a team.
- add 2-3 members to team.
- assign make leader to one of the team say Member aa.
- login through member aa and remove team creator from team.
- login with team creator credential.
- team creator still see make leader button. and also can change leader
![Screenshot from 2019-07-16 07-23-05](https://user-images.githubusercontent.com/27276132/61259681-f2b10380-a79a-11e9-84c0-90f260da59c4.png)

once team creator assigned another member as Team leader, does that "make Leader" option still show for Team creator or does team creator still can change Team leader?

**Comment by lmmrssa** [comment]
@singharpita is the user admin? Admin will always be able to change leader of team. Even if not in team.
Tested and it only seem to be case of admin

**Comment by singharpita** [comment]
yes user is admin in this case

**Comment by paulbert** [comment]
This is desired behavior to allow the admin to change the leader of the team always.  Closing.

**Comment by leahphuong** [comment]
Hi!
Who manages this GIT repo?
I need to have a user updated or removed to I don’t get all the wrongly addressed notifications;
