### ISSUE TITLE
ResourcesAdd: Updating private resource doesn't show Private Resource checkbox

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4327]
- Create a resource within a team 
- check Private resource.
- From team page, click on Edit action of that resource.
- you will see Private resource checkbox is checked.
![Screenshot from 2019-07-16 07-40-27](https://user-images.githubusercontent.com/27276132/61260351-8a175600-a79d-11e9-80e0-5860a4908f8e.png)

- Now click on that resource.
- Resource detail page is open in Library.
- from there, click on Edit resource.
- Private Resource option is unavailable.
![Screenshot from 2019-07-16 07-40-56](https://user-images.githubusercontent.com/27276132/61260341-808dee00-a79d-11e9-9849-27d8658b196a.png)

**Comment by paulbert** [comment]
We should always show this checkbox if the `private` property is true.
