### ISSUE TITLE
User with role manager is unable to take any action on other user

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4335]
on clicking of any action on another user such as demote/promote/deactivate,
console error shown and no action took place.
![Screenshot from 2019-07-16 08-12-35](https://user-images.githubusercontent.com/27276132/61261772-a10c7700-a7a2-11e9-8ce9-e4a6245e3816.png)

All these action is working fine for User with admin role.

**Comment by paulbert** [comment]
This is the same internal issue as #4281. I'm going to close this now, but we should make sure this is also fixed after #4281 is fixed.
