### ISSUE TITLE
Member: user with manager role warning message.

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4358]
1. Manager role warning message.
- Select user with manager role.
- Set roles to leader /learner.
- Since manager role can't be changed into either, clicking on set roles result in nothing.
- It will be better to show warning or informative message as "manager role cant be set to learner or leader.
![Screenshot from 2019-07-18 20-08-58](https://user-images.githubusercontent.com/27276132/61466074-fa3dfb80-a998-11e9-93d1-5545968f85fe.png)

2. Place the Clear button at top right rather than in between Role filter and name filter.
![Screenshot from 2019-07-18 20-12-01](https://user-images.githubusercontent.com/27276132/61466059-f316ed80-a998-11e9-8f07-ea5669d14a25.png)

**Comment by paulbert** [comment]
Let's start by disabling the button if only managers are selected.  A message that says something like "some members are managers so they don't get other roles" could be confusing unless we get the wording right.

Making 2 into a separate issue

**Comment by paulbert** [comment]
@Liew211 So the "Set Roles" button is disabled in the initial state, and should only be enabled if there are non-managers selected.  If it's not too difficult, we could also only enable it if one or more of the selected members would change based on the selected roles.
