### ISSUE TITLE
Team Create: remove mandatory "*" from description label

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4360]
While creating team, Description field is non-mandatory. But "*" mandatory sign is still showing in Description label.
![Screenshot from 2019-07-18 20-25-32](https://user-images.githubusercontent.com/27276132/61466897-6e2cd380-a99a-11e9-8c2a-8002b630fedd.png)

**Comment by paulbert** [comment]
The data supplied to `DialogsFormService` should include a required property which can be removed to fix this.

**Comment by paulbert** [comment]
@AlekseiKorolev The dialog is opened in `TeamsService.addTeamDialog`
