### ISSUE TITLE
Teams: Team leaders see two lines of buttons

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4366]
![image](https://user-images.githubusercontent.com/22685147/61471215-62b4ba80-a950-11e9-9bf3-8ac04b795ca0.png)

The addition of the delete key adds an extra line to the last column.
Adjusting the column sizes a bit should fix this.

**Comment by paulbert** [comment]
Let's adjust the width of the `createdOn` column to be smaller since that should be a constant width.  On smaller screens there will likely still be two lines of buttons, but it will clear up some whitespace at least
