### ISSUE TITLE
Team: Can't see member names other than manager

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4385]
![Capture](https://user-images.githubusercontent.com/22685147/61675199-54a2c900-acc5-11e9-9558-2cf99db7f058.JPG)

Teams can't see member names unless the said member is the manager. As an example, the members above are members "a", "b", and "c"

**Comment by paulbert** [comment]
Ah, this is because of a piece of code I used for display that should not have been included because it was incomplete.  For now the name shown should fallback to `member.name` if `member.userDoc.firstName` does not exist.
