### ISSUE TITLE
Team : top margin is required in Plan tab

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4393]
![Screenshot from 2019-07-23 07-15-59](https://user-images.githubusercontent.com/27276132/61675937-eb00da00-ad19-11e9-87b0-b4cf16a766cf.png)

**Comment by paulbert** [comment]
Would rather we had a more general top margin rather than adding one for each tab individually.

**Comment by paulbert** [comment]
Closing in favor of #4465
