### ISSUE TITLE
Deleted team is accessible through Notification link

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4399]
- Click on any deleted team from notification list.
- it will open deleted team profile and user can perform any action.
![Screenshot from 2019-07-23 07-46-13](https://user-images.githubusercontent.com/27276132/61677198-5e0c4f80-ad1e-11e9-99f2-890ea3ffba8b.png)

**Comment by paulbert** [comment]
A solution for this would be in **TeamsViewComponent** if the team has `status: 'archived'` route back to the Teams list and show a message that says "This team no longer exists"
