### ISSUE TITLE
Course Step: Add new resource infinite spinner

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4417]
Clicking the OK button before all the required fields have been filled out results in an infinite spinner.

![Capture](https://user-images.githubusercontent.com/22685147/61885144-5ccc5580-aecb-11e9-9b0d-e2784b0baa4e.JPG)

**Comment by paulbert** [comment]
This is a broad issue with `DialogsAddResourcesComponent` since it is happening in teams as well.
