### ISSUE TITLE
Report Detail: sub heading should be differentiated

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4418]
Can Members by Visits, Total Visits by Member,Most Visited, Total Visits by Resource, Highest Rated and Average Rating be differentiated using underline or font-bold.
![Screenshot from 2019-07-25 20-51-45](https://user-images.githubusercontent.com/27276132/61885878-53b8a400-af1e-11e9-8cfe-f37934d76d11.png)

**Comment by paulbert** [comment]
Yes I think we can have all of the headings (lines without an icon at the start) in bold.
