### ISSUE TITLE
Dashboard: removing a team has the team persist until refresh

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4419]
This is not an issue with myLibrary or myCourses.

Leaving a team from the dashboard by clicking the X button has the team persist on the dashboard until refresh. The team is properly removed; this is only a visual bug.

![Capture](https://user-images.githubusercontent.com/22685147/61886256-57700a80-aecd-11e9-99f3-b80df26e1189.JPG)

**Comment by diabagatekelly** [comment]
I'm having some trouble with this. I thought I might have to change something in dashboard-tile.component.ts (removeFromShelf), but I'm not sure if that's correct.
