### ISSUE TITLE
Course Resource: no resource found blank page shown

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4426]
Steps to Replicate:
- create new course.
- Add new resource by creating new resource
- now join the course.
- From course detail page click on view resource button.
![Screenshot from 2019-07-25 21-42-45](https://user-images.githubusercontent.com/27276132/61889453-29b6b000-af25-11e9-8626-b9dc81161956.png)

- Blank page will shown.
![Screenshot from 2019-07-25 21-40-48](https://user-images.githubusercontent.com/27276132/61889465-2f13fa80-af25-11e9-967e-82ed751415c5.png)

NOTE: Its working fine for older resource or if adding new resource in older course.

**Comment by paulbert** [comment]
Ok so when adding a resource from the dialog it attaches the first revision without the file information to the course document.

We need to modify `ResourcesAddComponent` so the attachment information is included in `this.afterSubmit.next()`
