### ISSUE TITLE
Survey: multiple choice question convenience

### ISSUE THREAD

**Issue by samuelchen1213** [open-learning-exchange/planet#4443]
1. Go to survey
2. Add a new survey
3. Name the survey
4. Add a multiple choice question
5. Now, every time you try to add an option, you will have to click on the new text box to type the choice. This will be annoying and tiresome if there are several choices

Proposed Solution: to improve the UX of this, after user clicks "Add choice", the new text box will automatically be highlighted and the user can input an option

**Comment by paulbert** [comment]
The component for this is `ExamsQuestionComponent`
