### ISSUE TITLE
Notification links should use routerLink, not href

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#446]
Notification links, found in `home.component.html`, should use `routerLink` to utilize the Angular router.

**Comment by lucy811** [comment]
Does this pull request fix this issue ? #443

**Comment by lmmrssa** [comment]
Looks like #443 removed link from navigation. We might want notification to take to you certain pages.
@paulbert @dogi shall we add that feature?

**Comment by paulbert** [comment]
This is now fixed, closing.
