### ISSUE TITLE
TeamView: Add top margin for plan & new message

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4465]
There should be some margin between the tabs at the top and the New message button.

![Capture](https://user-images.githubusercontent.com/22685147/62303192-aed02680-b449-11e9-92c1-c81a2ec94e26.JPG)

**Comment by paulbert** [comment]
Editing title to combine with #4393 and closing that issue

**Comment by paulbert** [comment]
The note from the #4393 applies here, too.  Please try to make a general top margin for the content in each of the tabs, not an individual one for each

**Comment by paulbert** [comment]
Closing.
