### ISSUE TITLE
Course collection: random behavior while creating collection for courses

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4470]
i have deleted all previous collection from Course collection and start adding new one.
I added course-01 as main collection and course-001 as subcollection.
but course-02 is automatically shown as subcollection under course-01.
Next i try to add course-02 as collection which is not allowed but it allows me to add duplicate collection.
further i tried to add course-03 but it says value already exist even though list doesn't have course-03
![Screenshot from 2019-08-01 20-49-48](https://user-images.githubusercontent.com/27276132/62304615-0bf5c780-b49e-11e9-9d3b-a2a3397fad41.png)

there are lot more scenario showing each time
![Screenshot from 2019-08-01 20-56-59](https://user-images.githubusercontent.com/27276132/62305112-051b8480-b49f-11e9-88a1-90141778ad27.png)

**Comment by paulbert** [comment]
I'm seeing some issues with how the validation works.  When trying to add a subcollection it's testing the validation against a collection type id.  The below the id created would be `courses_new_sub`, but the validation is testing `courses_sub`

![image](https://user-images.githubusercontent.com/9203229/62307780-36219800-b452-11e9-8fa0-5f411f3d6418.png)

![image](https://user-images.githubusercontent.com/9203229/62307799-3d48a600-b452-11e9-9b15-b83bb7db4caa.png)

**Comment by paulbert** [comment]
The subcollection showing up without being added may be an issue with deleting subcollections (as in, maybe it was not actually deleted in the database)

**Comment by paulbert** [comment]
Not seeing this issue anymore.  Closing
