### ISSUE TITLE
Surveys in compact view

### ISSUE THREAD

**Issue by Liew211** [open-learning-exchange/planet#4476]
![image](https://user-images.githubusercontent.com/43839884/62306643-3ae54c80-b450-11e9-84ea-2a947c02b552.png)
In the normal view, surveys is among courses, resources, etc, but in this view it has been separated.  I think the position of surveys should be consistent, so either move it to below meetups in the compact/mobile view, or move it as an icon to next to feedback.

**Comment by paulbert** [comment]
Let's move surveys up to be below meetups in compact view
