### ISSUE TITLE
Course: Adding a step creates two steps

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4480]
**Note: This issue only appears with Angular 8**

**Steps to replicate**:

1. Courses
2. Click the + Button
3. Add Step button
4. Click the Add Step button on the right side. To distinguish the step you create, add a title.

Two steps are created, with the second step being a default step with default fields.

**Comment by lmmrssa** [comment]
@sjson421 based on your steps you are clicking **Add Step** twice. That is expected to add two steps. Both of those button act as same, just provided two place to make it easier for user to add steps.

**Comment by sjson421** [comment]
@lmmrssa I am not. The button on the right side adds two steps. The first step is just to open up the interface on the right side.

**Comment by sjson421** [comment]
I tried this again and it doesn't seem to be happening anymore. I'll close it for now because I'm confused.
