### ISSUE TITLE
Message button locations should be consistent

### ISSUE THREAD

**Issue by Liew211** [open-learning-exchange/planet#4498]
Applies to news and team messages, reply button, edit, delete buttons should all be consistently on the same spot for all messages.  Currently, if there's a show more button, it pushes all other buttons to the right, and if there's a show replies button, it pushes edit and delete to the right.

**Comment by paulbert** [comment]
Let's just start by changing the "Show More/Show Less" to be blue text just below the message text and above the buttons.

All three could show up independently of the others, so there is no one order to put them in.

**Comment by paulbert** [comment]
Class for blue text is `primary-text-color`
