### ISSUE TITLE
new user goes to inactive state

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#450]
Once we tried to have learner role to newly created user. But now we create user as inactive i.e. without role.
So was there any reason why we did so. Or can we make user active when user register.

**Comment by dogi** [comment]
I think both every new user should be automatically a lerner, also our first user the admin should have same role

**Comment by lmmrssa** [comment]
It will require the validation of _users to be updated so need to check if we can implement it on our couchsetup

**Comment by lmmrssa** [comment]
If not admin there there is the condition as end of _auth design doc
`else if (newDoc.roles.length > 0) {
			throw({forbidden: 'Only _admin may set roles'});
		}`
This does not allow to add role on creating user. So we need to update this design doc if we want default userrole.

**Comment by paulbert** [comment]
Fixed in #1947
