### ISSUE TITLE
Surveys: the number icon of surveys should not be in mySurveys section?

### ISSUE THREAD

**Issue by ScottHuangNYU** [open-learning-exchange/planet#4506]
![image](https://user-images.githubusercontent.com/31773567/62506775-85a3f300-b7c7-11e9-9306-a8a180d526fa.png)
when a member received a survey, he should click `Surveys` to complete it instead of `mySurveys`. So I think the number icon should be in `Surveys`.
![image](https://user-images.githubusercontent.com/31773567/62506849-d4ea2380-b7c7-11e9-90b5-d1157679b95c.png)

**Comment by lmmrssa** [comment]
@ScottHuangNYU mySurveys display surveys sent to that user. So it is like notification for user to say he/she has some surveys to fill up.

**Comment by ScottHuangNYU** [comment]
@lmmrssa ok, but I clicked the mySurveys, there are nothing on it.

**Comment by lmmrssa** [comment]
@ScottHuangNYU yes created issue for that #4510

**Comment by paulbert** [comment]
Ok closing
