### ISSUE TITLE
ResourcesView: Bounce to library if resource does not exist

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4509]
Steps to replicate:
- Create a team
- create new resources with private resource checkbox 
- open that resource and copy the url
- - delete that team.
- now press the browser back button
- It will redirect to the deleted private resources and also allowed to submit it
- paste the above url and hit enter
- deleted private resource shown

can deleted private resource be still accessible through link or browser back button ?

**Comment by paulbert** [comment]
Editing title since we should just route to the library from ResourcesView link to a resource that does not exist on the database

**Comment by sjson421** [comment]
@paulbert I get the feeling that your comment is something completely different from the issue that arpita's presented. I will work on your issue.
