### ISSUE TITLE
Team: Include team name in request to join message

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4530]
1. on click of Request to Join Team by member it only says "request to join team sent"
it would be good if team name should be added in message as
"request to join Team-A sent"
![Screenshot from 2019-08-08 20-48-46](https://user-images.githubusercontent.com/27276132/62714375-2986dc00-ba1e-11e9-88b5-ba1b0f8d06fe.png)

2. Remove sorting descending sign from "Created on" by default.
![Screenshot from 2019-08-08 20-51-18](https://user-images.githubusercontent.com/27276132/62714513-7965a300-ba1e-11e9-9567-6232c5352f79.png)

**Comment by paulbert** [comment]
1 is OK, but 2 was a deliberate change to sort the most recently created teams by default
