### ISSUE TITLE
Team: joined members count is not incrementing

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4531]
- Create a team from admin
- add two member "C" and "B" 
- "C" and "B" visit count at the time of signup is atleast 1 visit still member "C" and "B" visit count in Team shows as 0
- now from admin change the Team leader to "B"
- now "B" start showing visit count.
- but "C" still shows as count 0 in Team
![Screenshot from 2019-08-08 20-59-17](https://user-images.githubusercontent.com/27276132/62715296-f0e80200-ba1f-11e9-9690-ae50d69b7157.png)
![Screenshot from 2019-08-08 20-59-26](https://user-images.githubusercontent.com/27276132/62715298-f0e80200-ba1f-11e9-9149-46d911ed98bd.png)

**Comment by lmmrssa** [comment]
@singharpita this is visit of team by that member. Thing that I think we can improve here is that, non-member always see visit as zero. If so then we can just hide visit as we are not showing visit to non-members
