### ISSUE TITLE
Update Private resources shows empty form

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4553]
- Create a private resource within  a team
- add collection to that resources
- open that resource from Team resource tab
- click on Edit button from resource detail page
- update Resource page shows empty
![Screenshot from 2019-08-13 07-53-13](https://user-images.githubusercontent.com/27276132/62910318-cb505500-bd9f-11e9-95f1-0d8aac5b31b5.png)

**Comment by paulbert** [comment]
This is unrelated to creating a collection.  A private resource does not appear to be editable after clicking on the pencil icon on ResourcesView.

**Comment by paulbert** [comment]
This is not limited to private resources.  Any resource created with the latest version cannot be edited.
