### ISSUE TITLE
Dashboard: Tile color for white

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4554]
The first tile created is white in color, making it a little bizarre to distinguish with the background. This is worse with the team tile, which has no X button to show where the tile begins and ends.

![Capture](https://user-images.githubusercontent.com/22685147/62910656-62d98780-bd4f-11e9-8428-286f5862b32c.JPG)

I suggest a change in color of the white tile to another color. Maybe another shade of gray.

**Comment by paulbert** [comment]
Either a background color change or a border would be helpful, yes.

Use `$light-gray` in `_variables.scss` for the background color change.
