### ISSUE TITLE
Teams: Is necessary to have a feedback button in teams?

### ISSUE THREAD

**Issue by ScottHuangNYU** [open-learning-exchange/planet#4564]
The different between the feedback button in teams section and the feedback button in navigation bar is the title of this feedback. Can we add a drop down list to let user to pick the category feedback in feedback dialog instead of add the feedback button in teams?

**Comment by paulbert** [comment]
We want to keep the feedback buttons & expand on their functionality.  Will make new issue when we're ready to improve that.
