### ISSUE TITLE
Dashboard: minimize font of total visits

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4586]
right now visit count font seems bigger and dominating than name and role.
can it be minimized such that bold property of count visit can be removed or font height can be minimized.
![Screenshot from 2019-08-15 20-17-17](https://user-images.githubusercontent.com/27276132/63102048-10d87200-bf9a-11e9-8341-a37995976649.png)

**Comment by paulbert** [comment]
Checked with RRR, and he would like this to remain as is.  Closing.
