### ISSUE TITLE
TeamsView: Resource actions as menu

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4590]
Can resource action items ( delete/Edit) be placed similar to Member action list?
![Screenshot from 2019-08-15 20-25-03](https://user-images.githubusercontent.com/27276132/63102508-066aa800-bf9b-11e9-8903-2293a2ad82b8.png)
![Screenshot from 2019-08-15 20-25-14](https://user-images.githubusercontent.com/27276132/63102509-066aa800-bf9b-11e9-919b-0c3b1998232b.png)

**Comment by paulbert** [comment]
I like this idea.  Then we can maybe add the description of the resource to the mat-card.
