### ISSUE TITLE
Task: Unassigning team member

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4598]
There is currently a way to add a team member to a task but not a way to unassign one. Deleting the task may be a way to achieve this, since that's not possible as of now.

**Comment by paulbert** [comment]
Removing a member is good, but I'm not sure if we'll want to delete a task.  Marking as "Complete" serves as a sort of deletion.

Removing "Delete task" from the title, but I may make that into a new issue after getting feedback from the larger team.
