### ISSUE TITLE
Team: when User with role admin create a team, it says request to join team

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4600]
- user with role admin created a team
- in list , it shows joined team tick mark
![Screenshot from 2019-08-15 21-23-28](https://user-images.githubusercontent.com/27276132/63106769-52b9e600-bfa3-11e9-9a46-1450aac9b7e4.png)
- but on team detail page, it shows request to join button with other feature disabled
![Screenshot from 2019-08-15 21-23-42](https://user-images.githubusercontent.com/27276132/63106815-682f1000-bfa3-11e9-90f0-b02137e702dd.png)

**Comment by paulbert** [comment]
This is actually the same issue as #4589 because when you create a team you also join it.
