### ISSUE TITLE
Meetups: No member message

### ISSUE THREAD

**Issue by samuelchen1213** [open-learning-exchange/planet#4608]
<img width="1268" alt="Screen Shot 2019-08-19 at 9 21 13 PM" src="https://user-images.githubusercontent.com/43349314/63310105-675ded00-c2c7-11e9-9224-49f64404ce7d.png">

Occurs if you have a meetup with no members
Solution: Capitalization should be consistent and "member" should be members.

**Comment by paulbert** [comment]
Let's set the message to
**No members have joined this meetup**
