### ISSUE TITLE
Team: task's user list is not showing

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4637]
![Screenshot from 2019-08-22 20-12-43](https://user-images.githubusercontent.com/27276132/63523186-61f7e100-c519-11e9-833f-350e6adf2d71.png)
even though member is added to the Team.

**Comment by paulbert** [comment]
`Cannot read property 'userId' of undefined` is the error
![image](https://user-images.githubusercontent.com/9203229/63523741-adce6a00-c4c8-11e9-995d-4e9fba8a7519.png)

**Comment by paulbert** [comment]
When a task is created it should have an `assignee` property set to an empty string
