### ISSUE TITLE
Team: on expand of task shows deadline row only

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4638]
create a task within team
- click on task to expand it
![Screenshot from 2019-08-22 20-21-01](https://user-images.githubusercontent.com/27276132/63524128-2cec8e00-c51b-11e9-8026-9b57fc8b3b01.png)

**Comment by paulbert** [comment]
Clicking a task changes its completion state.  Closing because this is due to the same error as #4637
