### ISSUE TITLE
mySurvey: survey list is blank 

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4639]
- Create a survey from user
- send survey to other users
- login to those user for which survey has sent
- in dashboard count is shown but mySurvey list is empty
![Screenshot from 2019-08-22 20-53-35](https://user-images.githubusercontent.com/27276132/63526469-311aaa80-c51f-11e9-9568-38414a2b48d4.png)
![Screenshot from 2019-08-22 20-53-45](https://user-images.githubusercontent.com/27276132/63526471-324bd780-c51f-11e9-9255-d7a9b08dd27a.png)

**Comment by paulbert** [comment]
Duplicate of #4510
