### ISSUE TITLE
Team: Add task count on tab

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4640]
There should be a count of tasks on the tab, just like there are on the right side of the Members and Join Request tabs.

![Capture](https://user-images.githubusercontent.com/22685147/63527690-8dee7480-c4cf-11e9-9660-27dfb8a38193.JPG)

**Comment by paulbert** [comment]
The count should be of tasks in progress.  Total if the logged in user is the team leader, and specific to the user logged in if not.

Let's also use a yellow `mat-badge` so this stands out as an action item.

https://material.angular.io/components/badge/overview
