### ISSUE TITLE
Infinite spinner when grading tests

### ISSUE THREAD

**Issue by Liew211** [open-learning-exchange/planet#4643]
When text-answer test questions are submitted, and the admin goes to grade the answers, an infinite spinner comes up after Submit Answer is clicked.
![image](https://user-images.githubusercontent.com/43839884/63528619-41a43400-c4d1-11e9-919f-ba0ca15f6fd5.png)

**Comment by paulbert** [comment]
Error in console:
![image](https://user-images.githubusercontent.com/9203229/63532225-2e489700-c4d8-11e9-850f-091042bbffa2.png)
