### ISSUE TITLE
Feedback: updating feedback title gives error

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4648]
![Screenshot from 2019-08-22 21-37-13](https://user-images.githubusercontent.com/27276132/63529884-33800300-c525-11e9-9b18-a53e5a5df449.png)

**Comment by paulbert** [comment]
The error is that the feedback document stored in the application is not updated with a new `_rev` after the title is updating.

You will only see this error when trying to update the title twice.  In addition, there will be errors adding a new message or closing the feedback after editing the title.

**Comment by perryc85** [comment]
Hey Paul, can you tell me if I'm on the track fixing this issue? Thank you for your feedback in advance.
