### ISSUE TITLE
Ordering of toolbar buttons in resources and courses

### ISSUE THREAD

**Issue by Liew211** [open-learning-exchange/planet#4649]
The toolbar button locations aren't consistent between resources and courses.

Resources:
![image](https://user-images.githubusercontent.com/43839884/63530613-ce9cbc80-c4d4-11e9-8b92-e790cf41b5a2.png)

Courses:
![image](https://user-images.githubusercontent.com/43839884/63530630-d65c6100-c4d4-11e9-9fe0-d05aaaa5bdc0.png)

**Comment by paulbert** [comment]
Let's go with the order in **Resources**

**Comment by dogeTheCoder** [comment]
Resolved the issue in the following pull request => https://github.com/open-learning-exchange/planet/pull/4688
