### ISSUE TITLE
Courses, Resources: Icon for joined course or resource

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4666]
I suggest adding a small column right after the options button (the three dots) for having icons to signify resources added to myLibrary or myCourses. There should be an easy way to distinguish between joined and unjoined courses/resources at first glance looking at the tables. It's enough to just have a "+" icon for joined ones.

**Comment by lmmrssa** [comment]
@sjson421 there is already icon to identify if you have joined courses or not. Same for resources. next to title you will see small bookmark which is specifying that.

**Comment by paulbert** [comment]
I'm going to close this since I don't think it'll raise to a high enough priority level to work on in the short-medium term.  We may revisit that icon at a later date.
