### ISSUE TITLE
Fix labels of Enterprise from Team to Enterprise

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#4693]
Adding enterprise is showing label as team because it is using same component. So we need to add condition to show it as enterprise

**Comment by paulbert** [comment]
Specifically the snackbar at the bottom which says "Team created successfully" should be "Enterprise created successfuly" when on the Enterprises page.

![image](https://user-images.githubusercontent.com/9203229/63956367-48dcbc00-ca54-11e9-8e91-1fb512e4b04b.png)

**Comment by paulbert** [comment]
Closing in favor of #4916
