### ISSUE TITLE
Teams: couldn't see Add course option

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4694]
![Screenshot from 2019-08-29 20-15-25](https://user-images.githubusercontent.com/27276132/63949279-dd1d4200-ca99-11e9-87bb-70ee79252be5.png)

**Comment by paulbert** [comment]
Oops it was removed when adding enterprises.  Check v0.8.40 for the HTML element which should be readded and make sure to add a condition that it is not shown for Enterprises.
