### ISSUE TITLE
Team: Add Plan using Create Team dialog

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4695]
The Add Plan button, used if the team is created without a description, should instead be using the Update Team dialog.

![Capture](https://user-images.githubusercontent.com/22685147/63950478-0ca45e00-ca4a-11e9-9ba5-58d817d9a1af.JPG)

**Comment by paulbert** [comment]
I think we can broadly update this to

- Autofill current team name & type
- Change terms for Team vs. Enterprise depending on which is being edited
- Title says "Update" instead of "Create"
