### ISSUE TITLE
enterprise: placing of negative budget is not appropriate

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4703]
![Screenshot from 2019-08-29 20-44-48](https://user-images.githubusercontent.com/27276132/63951806-1f488280-ca9e-11e9-96ef-8c95fe34f051.png)
negative sign should be placed first and then $ sign and amount for budget

**Comment by paulbert** [comment]
Let's switch to using [currency pipe](https://angular.io/api/common/CurrencyPipe) instead of manually adding in the dollar sign
