### ISSUE TITLE
Surveys: Tooltip to clarify "Record Survey"

### ISSUE THREAD

**Issue by Liew211** [open-learning-exchange/planet#4704]
When surveys are completed, a form to fill out a profile is displayed.  I think this is unnecessary if the user has already filled out their profile information, unless accounts are meant to be widely shared.

**Comment by paulbert** [comment]
This is an intended feature of "Record Survey" since the use case for that is to get information from people in the community who are not members of Planet.

We could make this clearer with a tooltip, maybe?

"Record survey information from a person who is not a member of {{configuration.name}}"
