### ISSUE TITLE
Enterprise: All members on enterprise list page is not required

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4709]
![Screenshot from 2019-08-29 21-04-45](https://user-images.githubusercontent.com/27276132/63953261-bdd5e300-caa0-11e9-9ea2-f7cae1c2151f.png)
and also clicking on add members redirect to the team url

**Comment by paulbert** [comment]
Ok let's remove the **All Members** button in Enterprises

**Comment by paulbert** [comment]
The component here is **TeamsComponent**
