### ISSUE TITLE
Enterprise balance form validation/rounding

### ISSUE THREAD

**Issue by Liew211** [open-learning-exchange/planet#4711]
<img width="1642" alt="image" src="https://user-images.githubusercontent.com/43839884/63956490-83deef80-ca54-11e9-99dd-3fb33de3f155.png">

Should either cap decimal places or round to nearest cent in case of overflow errors

**Comment by paulbert** [comment]
Let's round to the nearest cent.  There may be a Pipe for that.

**Comment by paulbert** [comment]
Fixed in #4718
