### ISSUE TITLE
enterprise tab in beta mode is still meetup tab

### ISSUE THREAD

**Issue by wanglihe2010** [open-learning-exchange/planet#4722]
I enabled the beta mode and narrowed window to make the tool bar on the left side. Then enterprise tab became meetup tab. 

![image](https://user-images.githubusercontent.com/11765890/64072297-ab4edb80-cc51-11e9-8ab5-976724962356.png)

**Comment by lmmrssa** [comment]
@wanglihe2010 we would need to decide which image to use for enterprise. Current image is used for myLife so may be we change myLife image to something else

**Comment by paulbert** [comment]
Let's use the `business` icon for the Enterprises link
