### ISSUE TITLE
UsersProfile: Can't change password twice

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4729]
- change password of any user .
- it says password succesfully updated.
- that user still is logged in the system
- go to change password again and try to change the password 
- this time it says " error changing password" sometimes.

**Comment by paulbert** [comment]
After using the dialog to change a password you should remain on the same page.  The issue is that when changing from `UsersProfileComponent` the new `_rev` for the user is not applied so the second time it will throw a document conflict error.

Changing the title to reflect this.
