### ISSUE TITLE
Refactor: Services declaration

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#4753]
Services no longer need to be set in the providers array in a Module file, they can just include `providedIn: 'root'` in their Injectable options (see ConfigurationService as an example)

Let's migrate to this syntax by removing our Services from AppModule and using `providedIn: 'root'`.

**Comment by dogeTheCoder** [comment]
refactored in pull request: https://github.com/open-learning-exchange/planet/pull/4778
