### ISSUE TITLE
Enterprise delete from detail page refirects to team list page

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4761]
- create an enterprise.
- click on that enterprise.
- click on delete within enterprise detail page
![Screenshot from 2019-09-05 20-56-28](https://user-images.githubusercontent.com/27276132/64354835-e2d9d100-d01f-11e9-969f-36df9cbffa70.png)

- it will redirect to the team list page
- it should redirect to the enterprise list page.

**Comment by paulbert** [comment]
If there isn't already, we should have a `goBack` function in `TeamsViewComponent` that redirects to the correct route based on `mode`.
