### ISSUE TITLE
Feedback: Fix required asterisk

### ISSUE THREAD

**Issue by ghost** [open-learning-exchange/planet#4784]
![image](https://user-images.githubusercontent.com/52227513/64511108-71588780-d298-11e9-9008-c1e8362e5f8b.png)

**Comment by paulbert** [comment]
Note the above screenshot was not taken from the latest version.  There was a change to `mat-radio-group` labels which had the unintended consequence of adding asterisks to each option for the feedback selections:

![image](https://user-images.githubusercontent.com/9203229/64580823-c3abae00-d355-11e9-8714-8d919fbee32f.png)

We should still have general CSS for this, but the above template needs to be adjusted so it uses that.
