### ISSUE TITLE
Create enterprise dialogue box wrong title

### ISSUE THREAD

**Issue by ChiragAwale** [open-learning-exchange/planet#4785]
<img width="1440" alt="Screen Shot 2019-09-09 at 11 21 03 AM" src="https://user-images.githubusercontent.com/19680263/64548328-06d53500-d2f4-11e9-9713-c6312236ace0.png">

**Comment by lmmrssa** [comment]
@ChiragAwale it is already fixed on new release

**Comment by paulbert** [comment]
Closing, outdated.
