### ISSUE TITLE
Calendar: Event time should be 24 hour

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4819]
![Screenshot from 2019-09-12 20-31-34](https://user-images.githubusercontent.com/27276132/64794664-8dac3b00-d59c-11e9-9ade-be58f36e8ac8.png)

**Comment by anishregmee** [comment]
@paulbert please suggest me something for this issue..

**Comment by paulbert** [comment]
Looks like the setting for FullCalendar can be found here: https://fullcalendar.io/docs/eventTimeFormat

**Comment by paulbert** [comment]
Rethinking this, I think we should use 24 hour time regardless.

Editing the title to reflect this.
