### ISSUE TITLE
No error message displayed when not able to create event in calendar

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#4845]
Create meetup with date older than today. And it neither save nor give any warning

**Comment by paulbert** [comment]
Need to replicate & get more detail.  In my calendar I get the correct validation:
![image](https://user-images.githubusercontent.com/9203229/65008240-b141ef00-d8d6-11e9-9c4c-f0c87a33da61.png)

**Comment by RheuX** [comment]
![image](https://github.com/user-attachments/assets/f540a0d6-88e1-4e58-a00a-599482658697)

cannot replicate the issue, theres a validator for old dates
