### ISSUE TITLE
Calendar: inconsistency in recurring events

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4846]
- created an event as following below
![Screenshot from 2019-09-17 07-25-40](https://user-images.githubusercontent.com/27276132/65004568-8ed2c480-d91c-11e9-80cf-c63529db226b.png)
- event is created on calendar which seems kind of inconsistent
![Screenshot from 2019-09-17 07-26-03](https://user-images.githubusercontent.com/27276132/65004583-a0b46780-d91c-11e9-9937-f8ca64cc3f09.png)
because deadline is upto 18-21 september.

**Comment by paulbert** [comment]
The end date does not appear to be included in the repeat events.
