### ISSUE TITLE
Teams View: Removing members with additional admin accounts

### ISSUE THREAD

**Issue by perryc85** [open-learning-exchange/planet#4850]
I’m currently experiencing an issue removing members from a team. The option is not there when you log into the additional account. It appears for certain members after I spend a few seconds switching team leadership, but not all of them. 

![image](https://user-images.githubusercontent.com/19641684/65006824-41ca0080-d8d2-11e9-8e15-5a4fed57e327.png)

**Comment by paulbert** [comment]
For admins the only option should be make leader.  Only the "Team Leader" will have the option to delete members.  Closing.
