### ISSUE TITLE
Meetup

### ISSUE THREAD

**Issue by nirojdyola** [open-learning-exchange/planet#486]
We need  full calendar to add the event. Please check the BELL-App for the referecnce.

![screen shot 2018-03-07 at 2 54 23 pm](https://user-images.githubusercontent.com/7495421/37083432-6b1665da-21e7-11e8-9d60-57bb78e3af41.png)
![screen shot 2018-03-07 at 2 54 57 pm](https://user-images.githubusercontent.com/7495421/37083433-6b53a2e2-21e7-11e8-89f3-eec4893f7cf9.png)

**Comment by razu9861** [comment]
@paulbert and @dogi regarding meetup calander we have this reference https://mattlewis92.github.io/angular-calendar/#/kitchen-sink
please give some feedback regarding this and please do suggest if you guys have other idea about it

**Comment by nirojdyola** [comment]
In the mean time while deciding about the calendar process,  we can work on the following 
- [] Add fields in meetup (Please check it from BELL-App)

**Comment by paulbert** [comment]
Merged #545, but that did not add the "Request member to join meetup" task.
