### ISSUE TITLE
Event: Description overflown

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4869]
![Screenshot from 2019-09-19 20-42-12](https://user-images.githubusercontent.com/27276132/65255762-310dca80-db1e-11e9-95b5-969d7ae8c14d.png)

i think it would be better if text should use all space and also scroll is present in event dialogbox.

**Comment by paulbert** [comment]
Need to implement scroll for this dialog.  That can be the scope of this issue.

Using the horizontal space is already another issue #4829
