### ISSUE TITLE
DatePicker: Use Somali week

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#4878]
In Somalia the week starts on Saturday, but we only have this implemented for the calendar not the MatDatepickers.

We need to find the best way to set that:
https://material.angular.io/components/datepicker/overview

**Comment by wanglihe2010** [comment]
@paulbert  
I tried to add a custom `DateAdapter` to set first day of week as showed in the this [example](https://stackblitz.com/edit/angular-dateadapter-example-stackoverflow1-oarzsz?file=app%2Fdatepicker-overview-example.ts), but it does not work. Do you know the reason? Please check this [commit](https://github.com/open-learning-exchange/planet/commit/aaaaaa0934c4beec666fffb65b18c0cd3cbbd9cd)
