### ISSUE TITLE
Calendar: no. of recurrence decimal error

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4894]
- add an event to any enterprise such that recurring is Daily and recurrence is set to whole number (integer).
![Screenshot from 2019-09-24 08-13-25](https://user-images.githubusercontent.com/27276132/65476665-63fbe980-dea3-11e9-8558-00586de5388d.png)
- now update the same event such that update the recurrence with decimal value. it doesnot throw any error and save it saying updated successfully though no change can be seen in calendar.
![Screenshot from 2019-09-24 08-13-45](https://user-images.githubusercontent.com/27276132/65476717-8db51080-dea3-11e9-9bf3-2b24d595bbdc.png)
- now again update the same event. opening the dialog shows same previous integer value. now try to save with any integer value. spinner get stuck with following console error.
![Screenshot from 2019-09-24 08-14-03](https://user-images.githubusercontent.com/27276132/65476758-acb3a280-dea3-11e9-887b-587e97c1a2f1.png)

NOTE: after that refresh the page , calendar date wont appear. and try to add new event, nothing will show

**Comment by paulbert** [comment]
This field should be required as an integer.
