### ISSUE TITLE
Calendar: No of occurance exceed limit should show warning error message

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4913]
right now it allows to enter any range and result in spinner loading
![Screenshot from 2019-09-26 20-34-31](https://user-images.githubusercontent.com/27276132/65699101-4a25f680-e09d-11e9-828b-769ccd0f5b1c.png)

**Comment by paulbert** [comment]
We can refactor `CalendarComponent.weeklyEvents` to remove the recursion.  I thought the limit for modern browsers had increased significantly, but 800 is not enough.
