### ISSUE TITLE
Enterprise: Editing success message shows "Team" instead of "Enterprise"

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4916]
on creation of Team/enterprise, message shows as "Team updated successfully"
For team it should show "Team created successfully"
For enterprise it should show "Enterprise created successfully"

**Comment by paulbert** [comment]
Changing the title to be a little more specific.

Note this is the same as #4693, but I'll close that one since this has a clearer title.

**Comment by paulbert** [comment]
@smitshrestha101 Once you feel like you're ready to work on something, you can give this issue a try.
