### ISSUE TITLE
Submission: survey redirect button leads to blank survey list page

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4918]
- go to mySubmission
- click on survey tab ( here Test tab is empty)
![Screenshot from 2019-09-26 21-21-36](https://user-images.githubusercontent.com/27276132/65703559-ae988400-e0a4-11e9-973f-9fe3a786283e.png)

- go to any survey detail
- now click on back button inside survey detail
![Screenshot from 2019-09-26 21-22-04](https://user-images.githubusercontent.com/27276132/65703571-b9531900-e0a4-11e9-8448-59f661c27b4a.png)

- it will redirect to the survey list page but with empty list
![Screenshot from 2019-09-26 21-22-15](https://user-images.githubusercontent.com/27276132/65703589-c53edb00-e0a4-11e9-991d-860d97f31c37.png)

- try to refresh the page but still blank survey list is shown.

**Comment by paulbert** [comment]
The "Status" filter is defaulting to "Not Graded" which is not an option for Surveys.  We should change that to "All" if the initial submission type is surveys.

**Comment by paulbert** [comment]
Closing in favor of #4920
