### ISSUE TITLE
Submissions: Redirection after viewing/grading

### ISSUE THREAD

**Issue by perryc85** [open-learning-exchange/planet#4920]
This is similar to `#4918`. Should we also change the `Status` filter default to `All` instead of `Not Graded`? 

After submitting an exam, it automatically redirects you to the `Not Graded` tab.

**Comment by paulbert** [comment]
Linking this to the other issue #4918

**Comment by paulbert** [comment]
I think this includes part of the solution for #4918 in that we could add a `status` parameter when we redirect back to the submission list that can be set to `All`.  For tests, we would only want to set it to `All` if the test has been fully graded, but for surveys this should always be set to `All`.

**Comment by paulbert** [comment]
Seems this also causes an error where the paginator is no longer active, also, making it impossible to see past the first 50 exams/surveys

![image](https://user-images.githubusercontent.com/9203229/67116751-1b3c0580-f1af-11e9-85be-16a37db08a60.png)
