### ISSUE TITLE
Searchbar Placeholder

### ISSUE THREAD

**Issue by choiwhmarco** [open-learning-exchange/planet#4927]
### Problem
On Teams, Surveys, Meetups page, the search bar placeholder text is still English after I selected a different language.

### Steps to reproduce the problem
* Select a language that is not English on top right next to the icon.
* Click Teams or Surveys or Meetups tabs on top.
* The  search bar placeholder text is English.

### Screenshots

![Capture](https://user-images.githubusercontent.com/22423089/65920064-dd5b7680-e392-11e9-82b4-33896fae7bf2.PNG)
![111](https://user-images.githubusercontent.com/22423089/65920067-dfbdd080-e392-11e9-99c8-76eb305fbb47.PNG)
![222](https://user-images.githubusercontent.com/22423089/65920071-e2202a80-e392-11e9-978f-b542b443439d.PNG)

### Proposed solution

N/A

**Comment by lmmrssa** [comment]
@choiwhmarco there is a translation already added. We don't have all words translated. Once words are translated in crowdin: https://crowdin.com/project/ole-planet it will show up
