### ISSUE TITLE
Team/Enterprise: task stil shows current task even on entering old time values with current date

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4930]
![Screenshot from 2019-10-01 07-32-56](https://user-images.githubusercontent.com/27276132/65928529-0aa13680-e41e-11e9-8283-9aa95ae2c1de.png)
![Screenshot from 2019-10-01 07-33-08](https://user-images.githubusercontent.com/27276132/65928530-0b39cd00-e41e-11e9-99ca-4d4f967e58ab.png)

**Comment by paulbert** [comment]
The color for tasks on the calendar will only change after the task has been checked off as completed.  Closing.
