### ISSUE TITLE
Task: Task title on members tile overlaps

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4931]
![Screenshot from 2019-10-01 07-43-50](https://user-images.githubusercontent.com/27276132/65928875-4d174300-e41f-11e9-8618-8596a2b52cd4.png)

**Comment by paulbert** [comment]
We should have a max characters/words and cutoff with an ellipsis `...`

**Comment by paulbert** [comment]
The cards have variable width, so the cutoff will likely need to take that into account
