### ISSUE TITLE
Task: on completion of task, information in popup dialog should be maintained 

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4935]
![Screenshot from 2019-10-01 08-05-28](https://user-images.githubusercontent.com/27276132/65929610-856c5080-e422-11e9-946c-b7b2994da319.png)
right only color code is available in calendar for task completion.
information in calendar dialog box should be maintained.

**Comment by paulbert** [comment]
Above **Deadline** we could have **Completed on...** with the date the task was completed.

**Comment by lmmrssa** [comment]
@sjkadali This can be seen in both team and enterprise. After you create **Task** you can see under **Calendar**.
If you click on task seen on calendar it will pop up detail of that  task. We would like to add **Completed On** in that popup.
To complete task you can click on any Task from Task tab or click checkbox.

**Comment by sjkadali** [comment]
@lmmrssa thanks. will start working on it.
