### ISSUE TITLE
Tasks: Deleted tasks still appear on the calendar

### ISSUE THREAD

**Issue by perryc85** [open-learning-exchange/planet#4936]
If you create a task and set the deadline for a future date, it still shows up on the calendar after it's deleted.  Should we fix this? 

These are tasks that I created and deleted :

![image](https://user-images.githubusercontent.com/19641684/65929657-eec37380-e3d0-11e9-9480-e40f8855a627.png)

**Comment by paulbert** [comment]
Yes, we should remove these from the calendar.

This is because we don't delete tasks so we still have their information, we archive them.  We need to filter archived tasks before they are included in this view.

**Comment by paulbert** [comment]
Archived tasks will have `archived: true`
