### ISSUE TITLE
Survey Invalid Input Message.

### ISSUE THREAD

**Issue by choiwhmarco** [open-learning-exchange/planet#4942]
# Problem
When I type the  after taking the survey, I tried to put letters into phone number field. There should be a reminder of typing numbers instead of others.

# Steps to reproduce the problem
* Visit OLE
* Typing user's info

# Screenshots
![Capture](https://user-images.githubusercontent.com/22423089/66005367-131a6100-e460-11e9-9cfd-6604bb1732cb.PNG)

# Proposed solution
Set the input type to tel and create a reminder message for phone number and birth date.

**Comment by paulbert** [comment]
@choiwhmarco In many countries phone numbers are not limited to numbers or even alphanumeric, so we do not limit the phone number field.

The lack of message for the invalid birth date is an issue, however.
