### ISSUE TITLE
TeamsViewFinances: Deleting final transaction throws error

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#4953]
This is also causing issue that if you try to edit on same transaction which is not removed from screen you will see conflict on request :)

**Comment by paulbert** [comment]
Looking at it if there is only one transaction left deleting it will throw an error.

Updating the title to reflect this.

![image](https://user-images.githubusercontent.com/9203229/66143394-197e1980-e5d5-11e9-9b86-cf490d1b6010.png)
