### ISSUE TITLE
Enterprise: Deleted message of Documents

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4956]
- it should be "Are you sure you want to remove the following documents?"
![Screenshot from 2019-10-03 20-55-58](https://user-images.githubusercontent.com/27276132/66139582-69360280-e620-11e9-9806-4ed60863288f.png)

**Comment by paulbert** [comment]
Should be singular *document*, but otherwise this change is good.

Need to change the options for **DialogsPromptComponent** to make this change.
