### ISSUE TITLE
Private resource with no document attached result in empty dialog box

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4957]
![Screenshot from 2019-10-03 21-00-20](https://user-images.githubusercontent.com/27276132/66139911-eeb9b280-e620-11e9-9d9b-15f2104be244.png)

**Comment by paulbert** [comment]
Doesn't need to be a private document.

We should only allow clicks on documents/resources with an attachment.  If they do not have an attachment, we should show a tooltip message "There is no content for this document/resource"
