### ISSUE TITLE
Feedback: Default title missing url

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4960]
![Screenshot from 2019-10-03 21-12-37](https://user-images.githubusercontent.com/27276132/66140968-badf8c80-e622-11e9-8147-88b7eaad3112.png)
![Screenshot from 2019-10-03 21-12-52](https://user-images.githubusercontent.com/27276132/66140969-badf8c80-e622-11e9-99a5-4e306d449b70.png)
which may cause confusion which part of application feedback comes from
or else remove "regarding" text

**Comment by paulbert** [comment]
Changing the title of this to reflect the issue.  The default title for feedback should come in the form `{type} regarding {url}`.  Looks like we are missing the url part now.
