### ISSUE TITLE
MeetupsAdd: Input 24 hour time

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#4969]
We should change the below time inputs to use 24 hour rather than 12 hour time, if possible.

![image](https://user-images.githubusercontent.com/9203229/66337192-b1993d00-e90c-11e9-8e5c-97d8360651b3.png)

**Comment by wanglihe2010** [comment]
@paulbert I searched the 24hour format and it looks like the time format depends on the locale system setup. I am using the OSX and change the system time to 24hour format and then the meetup time also becomes 24hour format, showed in the below. If we want to force it to be 24 hour format, maybe we can change it like [this](https://stackoverflow.com/a/40464191)
![image](https://user-images.githubusercontent.com/11765890/66419524-e6b79500-e9c9-11e9-8e76-7f1e8fa74cf5.png)

**Comment by paulbert** [comment]
@wanglihe2010 Ok a library might be best, but it should fit in with the Material theme.

Try this one: https://www.npmjs.com/package/angular-material-time-picker

**Comment by paulbert** [comment]
@wanglihe2010 An alternative would be to use a text mask library like this one: https://www.npmjs.com/package/ngx-mask
