### ISSUE TITLE
Reports Detail: Date range dialog validation

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#4977]
There should be some validation/limitations on the start/end dates for export:

1. The minimum value for the fields should be the `minDate` value.
2. The maximum value should be the current day
3. The **End Date** should not be before the **Start Date**

**Comment by wanglihe2010** [comment]
@paulbert  Hey, Paul. I was trying to create a new validator for min date in `custom-calidators.ts`. I want to give an error message like "From date cannot be earlier than xxx " which xxx is `minDate`. May I know what is the best way to add that message to a custom validator?
