### ISSUE TITLE
Community: message notification undefined.

### ISSUE THREAD

**Issue by wanglihe2010** [open-learning-exchange/planet#4989]
A member post a new message and other members received notification showed as below. 
![image](https://user-images.githubusercontent.com/11765890/66579324-49cc3780-eb42-11e9-8723-5617097ce6a6.png)

**Comment by paulbert** [comment]
The notification for the team when `team.type=== 'services'` should not include the team name.

I'm not sure what terms we should use here.  Possibilities:

- Community name & "Services Directory"
- "Community Directory"
- "Services Directory"
- "Community Services"
etc...

**Comment by paulbert** [comment]
Went with "Community Services Directory"

This may not be on the nation or earth/center, so I don't think we need to handle those cases yet
