### ISSUE TITLE
Community: message reply does not show up

### ISSUE THREAD

**Issue by wanglihe2010** [open-learning-exchange/planet#4990]
community(only) message does not have `show replies` after adding some replies. 
![image](https://user-images.githubusercontent.com/11765890/66579860-19d16400-eb43-11e9-9782-5fbeed062e66.png)

**Comment by paulbert** [comment]
I was making what I thought was a different issue, but after some digging looks like this is the same one.  When you add a reply, `viewableId` is set to the correct value.  All of the messages being shown have this set incorrectly to `null`.

Below is the issue I was about to create:

After editing a message, it is removed from the messages feed entirely.

Digging into the database, it looks like when a message is created it has `viewableId: null` and then when it is edited it has the correct `viewableId: {teamId}`.  We should make sure the messages are setting this value correctly and showing all messages that match this value.

https://www.loom.com/share/9d3df0bad83c49758ea13ad97279b366
