### ISSUE TITLE
TeamsView: Profile image not matching

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#5012]
In the below image you will see there is one member of the team that is logged in, but the image in the member list does not match the image in the upper right.

Something is causing the **attachments** database (currently used only for user profile images) to become out of sync with the **_users** database (which is used for the image in the upper right).

These are kept separate to minimize the images synced with the nation to profile images for members that are a part of synced teams/enterprises.

![image](https://user-images.githubusercontent.com/9203229/66797069-9368a980-eed7-11e9-9b3c-bfa750ee3925.png)

**Comment by RheuX** [comment]
![image](https://github.com/user-attachments/assets/4f7cbcda-f23c-4b57-9d70-1d3d3de24ca0)

Can't seem to replicate the issue, considering closing, if no one can't replicate this issue
