### ISSUE TITLE
Team: Add event date validation 

### ISSUE THREAD

**Issue by wanglihe2010** [open-learning-exchange/planet#5032]
I suggest to change date validation to `min date` to make invalid date cannot be selected, similar to what we did in the summary report. 

Current : 

![image](https://user-images.githubusercontent.com/11765890/67018112-5e6b7b00-f0c0-11e9-820e-8ec03320d2a9.png)

Desire: 

![image](https://user-images.githubusercontent.com/11765890/67018210-835fee00-f0c0-11e9-84a5-0726f8ee5758.png)

**Comment by paulbert** [comment]
Looks good.  Let's make sure the error message is still **Cannot be before current date** instead of the `matDatepickerMin` **The date cannot be before _X_**

**Comment by paulbert** [comment]
Closing since we decided to remove the validation for meetup start date
