### ISSUE TITLE
Team course remove adding duplicate

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#5090]
If you try to remove course under team.
It will add more course (duplicating it)
It works fine for resources
![courseduplicate](https://user-images.githubusercontent.com/2909490/67731658-141fbd80-fa21-11e9-9da4-ab399a5b4546.jpg)

**Comment by paulbert** [comment]
When I tried to replicate, I did not see duplication but the course was not removed.  Either way there is something that needs fixing here.
