### ISSUE TITLE
Show user roles in better format across app

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5124]
![Screenshot from 2019-10-31 20-45-01](https://user-images.githubusercontent.com/27276132/67958565-7d6d1f80-fc1f-11e9-9dac-35384f31a127.png)

**Comment by paulbert** [comment]
We could make a component similar to **FormErrorMessagesComponent** that takes the database role and converts it to the more formal format (i.e. learner => Learner, health => Health Provider).  Creating it as a component allows us to use the `i18n` tags as well.  This component should be declared in **SharedModule**

We should also use this in **UsersComponent** for the role chips and the role dropdowns.
