### ISSUE TITLE
Survey menu bar showing for User with role learner

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5138]
in admin role, Survey menubar is not there
![Screenshot from 2019-11-05 08-18-06](https://user-images.githubusercontent.com/27276132/68174102-f6180700-ffa4-11e9-8cfc-47dfb9c4042e.png)
but in learner role, it is present
![Screenshot from 2019-11-05 08-17-41](https://user-images.githubusercontent.com/27276132/68174112-029c5f80-ffa5-11e9-9e19-a96366a59234.png)

**Comment by paulbert** [comment]
Closing.  Figured out that this was because "beta mode" was turned out for admin, but not for other member.
