### ISSUE TITLE
Community: Task notification incorrect link

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5139]
- go to user with admin role and create a task under Community
- assign that task to user with role learner
- login to user with role learner
- that user will get notification
![Screenshot from 2019-11-05 08-20-43](https://user-images.githubusercontent.com/27276132/68174210-5e66e880-ffa5-11e9-965a-229575dbc27c.png)
-click on that notification
![Screenshot from 2019-11-05 08-20-53](https://user-images.githubusercontent.com/27276132/68174218-6757ba00-ffa5-11e9-8e03-2a8c8b2ff8c2.png)
it will show page not found

**Comment by paulbert** [comment]
We are changing the community page, but we should fix this in case we add tasks back in.

The issue is that the url should be `community;activeTab=taskTab` instead of what is in the picture above.
