### ISSUE TITLE
Health birthdate and birthplace autocomplete

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#5144]
Birth date and birth place fields of health are on autocomplete. Do we require it? Because of it, field got suggested for google password once ;) Later it did not happen though.

**Comment by paulbert** [comment]
@lmmrssa Birthdate is set to an input with datepicker and birthplace is set to a normal input field.  There's nothing special on either of those form fields to notify the browser that they are password fields.

I think Chrome was just being quirky with a form you've filled out a few times.
