### ISSUE TITLE
Dashboard: Survey dialog at first can load many times

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5152]
- create a survey and save
- send survey to other user (A)
- login using other user (A)
- two survey dialog box is shown at first
NOTE: logout the given user and again logged in. this time two dialog box won't appear.

**Comment by paulbert** [comment]
Seems to load one dialog for each time a member that does not have a survey logs in.  Resets once the dialogs load so the logout/login for the member with the dialog will only load one the second time.

**Comment by paulbert** [comment]
This was also fixed in #5549
