### ISSUE TITLE
Event dialog box doesn't close on click  of member link

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5153]
- create a team
- create an event in calendar
- open that event
![Screenshot from 2019-11-07 20-23-09](https://user-images.githubusercontent.com/27276132/68398338-aa2fb280-019c-11ea-93d2-d45a484cd8e2.png)

- click on member link in the given event.
- member profile open up but event dialog box is still showing in background
![Screenshot from 2019-11-07 20-23-21](https://user-images.githubusercontent.com/27276132/68398398-c16ea000-019c-11ea-9b15-0fc1747bb248.png)

**Comment by paulbert** [comment]
You can use the `mat-dialog-close` attribute to close the dialog

https://material.angular.io/components/dialog/overview
