### ISSUE TITLE
deleted survey still shows on sending survey dialog box

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5156]
- create a survey
- send survey to different user
- delete the given survey and create new one
- send this survey to above user as well
- deleted survey still shows in the survey dialog box on login
![Screenshot from 2019-11-07 20-49-29](https://user-images.githubusercontent.com/27276132/68400580-5fb03500-01a0-11ea-981a-1a16d63f97b9.png)
![Screenshot from 2019-11-07 20-49-59](https://user-images.githubusercontent.com/27276132/68400582-5fb03500-01a0-11ea-97ba-a00721dfccec.png)

**Comment by paulbert** [comment]
Two steps to implement this:

1. We should store the Planet that the survey is created on in the `sourcePlanet` property of the document.  That can be added in **ExamsAddComponent**
2. When a survey is deleted & its `sourcePlanet` matches `configuration.code`, delete all submissions where `status === 'pending'` and `parent._id === survey._id`
