### ISSUE TITLE
When deleting link from community add spacing between links

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#5175]
![Screen Shot 2019-11-12 at 8 13 15 AM](https://user-images.githubusercontent.com/2909490/68636666-58808280-0524-11ea-8377-e0f5cbd37244.png)

**Comment by paulbert** [comment]
Let's add a margin between the buttons always, no need to make it conditional on delete mode being on.

**Comment by anishregmee** [comment]
I am training robin for the issues to work with... So this issues is completely done by robin. Now i will set the project in his laptop and will assign some issues. For now, please check it out. thank you in advance. @lmmrssa @paulbert
