### ISSUE TITLE
login failed message shown even on successful login each time

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5197]
![Screenshot from 2019-11-14 20-44-07](https://user-images.githubusercontent.com/27276132/68868451-a8776900-071f-11ea-937c-9790460e4f1f.png)

**Comment by paulbert** [comment]
I noticed this while testing something else, but now can't replicate.  Will need more testing.

**Comment by paulbert** [comment]
From what I saw it happened because Planet is looking for the couchperuser database and not finding it.

Adding priority since our deployments do not currently have couchperuser enabled and will see this error on every login.
