### ISSUE TITLE
Dashboard: Tile overflow breaks vertical alignment

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5198]
- create a team with title longer enough to fit in 2 lines.
- go to Dashboard and scroll down to myTeams section
- team tile is overflown and for other teams title is not shown
![Screenshot from 2019-11-14 20-47-55](https://user-images.githubusercontent.com/27276132/68868889-6ac71000-0720-11ea-9ead-8af734690903.png)

**Comment by paulbert** [comment]
This is the same issue as #3427.  Keeping this one since the other is very old.
