### ISSUE TITLE
Conflict on wording between Message (News/Chat) and its reply

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#5201]
When we try to reply for Chat or News it says reply to post and title is Story. We should also make it related to Chat or News as we do while creating new message.

**Comment by paulbert** [comment]
For Teams/Enterprises (Chat) the title should be **Add Message** or **Reply to Message** and the text box should always say **Message**.

For Community news the title should be **Add Story** and **Reply to Story** and the text box should always say **Your Story**.  The button should also say **New Story**.
