### ISSUE TITLE
When editing message and story Edit Post comes.

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#5210]
When we try to edit  for what we have written on message or news Edit Post pups up on dialog form as title.Should we change to Edit Message and Edit Story or edit news.

![edit 2](https://user-images.githubusercontent.com/45058288/69032359-5e82d180-0a04-11ea-8624-559a5a7a7264.PNG)

**Comment by paulbert** [comment]
On this screen the header should **Edit Message** and the placeholder should be **Your Message**

**Comment by paulbert** [comment]
In the community section, the heading for editing a story needs to change from Edit Post to **Edit Story**
