### ISSUE TITLE
new users not showing up on user list

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#5230]
Created few new users and they did not show up on user list.

**Comment by paulbert** [comment]
The users show up after a refresh, so this isn't highest priority.  There were some changes to how the users are loaded which appear to require some adjustments.

**Comment by paulbert** [comment]
Replicated the issue once, but tried a few more times and was not able to replicate.

I'll leave this open for a week in case we are able to replicate again.

**Comment by paulbert** [comment]
Fixed in #5244 and #5281
