### ISSUE TITLE
Enterprise: Checkmark icon hover text is "Joined Team"

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5231]
![Screenshot from 2019-11-21 20-12-03](https://user-images.githubusercontent.com/27276132/69346771-758f2100-0c9b-11ea-9675-0bac04ae6be4.png)
It should show  "Joined Enterprise"

**Comment by paulbert** [comment]
We should try to fix this in a way that works with the `i18n-title` tag.
