### ISSUE TITLE
Health: username should be shown in Health Care Profile when no other details is present

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5233]
Its kind of confusing to know, which user information we are updating in case User information is missing.
![Screenshot from 2019-11-21 20-31-15](https://user-images.githubusercontent.com/27276132/69348515-6a89c000-0c9e-11ea-9301-f81728ce202d.png)
![Screenshot from 2019-11-21 20-32-20](https://user-images.githubusercontent.com/27276132/69348516-6a89c000-0c9e-11ea-970f-180acc3728e5.png)

Can username should be displayed at top similar member profile?
![Screenshot from 2019-11-21 20-34-52](https://user-images.githubusercontent.com/27276132/69348551-79707280-0c9e-11ea-8a32-015da31b6124.png)

**Comment by paulbert** [comment]
Let's show `Member login: {{user.name}}` after the **Add Examination** button.
