### ISSUE TITLE
Health Care: search is not filtering one letter/digit based firstname

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5235]
![Screenshot from 2019-11-21 20-50-07](https://user-images.githubusercontent.com/27276132/69349938-c6eddf00-0ca0-11ea-9a23-f22ac8a9e92a.png)
![Screenshot from 2019-11-21 20-50-19](https://user-images.githubusercontent.com/27276132/69349939-c7867580-0ca0-11ea-9ff1-e4c880d100f1.png)
![Screenshot from 2019-11-21 20-50-29](https://user-images.githubusercontent.com/27276132/69349943-c81f0c00-0ca0-11ea-800c-f935796a5471.png)

**Comment by paulbert** [comment]
This is being fixed in #5227
