### ISSUE TITLE
new admin course list issue

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#5249]
sync and admin promote seems to work. list of nation course is still giving unauthorized to dayabase such as ratings, course_progress etc

**Comment by lmmrssa** [comment]
looks like working could be sometime session not properly set

**Comment by paulbert** [comment]
I am seeing this issue as well, so I am going to reopen

**Comment by paulbert** [comment]
Note that resources from nation is also not working

**Comment by paulbert** [comment]
Working now.  Closing.
