### ISSUE TITLE
Community: Should there be a notification when a member/admin adds a new story ? 

### ISSUE THREAD

**Issue by perryc85** [open-learning-exchange/planet#5252]
The message shows up in the feed, but there is no notification to the team/community members. 

<img width="523" alt="notifications" src="https://user-images.githubusercontent.com/19641684/69598962-477e4980-0fd9-11ea-8550-e73a1a9afa9e.PNG">

**Comment by paulbert** [comment]
Every member of Planet should have a notification after community news is added.  If a member already has a notification for new community news, then we should not add another.
