### ISSUE TITLE
Community link: Cancel button should be placed in pop-up

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5268]
in case to cancel the popup for any reason or when there is no team or enterprise listing,
there should be Cancel button placed right to OK button.
![Screenshot from 2019-11-28 20-12-02](https://user-images.githubusercontent.com/27276132/69814051-90254500-121b-11ea-8b99-8a3a4c361c4a.png)

**Comment by paulbert** [comment]
Cancel should be to the left of the OK button.

**Comment by paulbert** [comment]
Here's the button to open that dialog:

![image](https://user-images.githubusercontent.com/9203229/80645117-ad637700-8a38-11ea-9489-11f98e6df785.png)

**Comment by Haoran-Hu** [comment]
@paulbert Thanks. I know how this works. I am just kind of exploring the entire website and reviewing the code. So I asked that question on gitter.
