### ISSUE TITLE
Community: Library's delete and add icon should have fixed style

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5270]
In case when there is lot of icon present, horizontal scroll bar is shown which hides the delete and add link icon.

![Screenshot from 2019-11-28 20-18-01](https://user-images.githubusercontent.com/27276132/69815753-1abb7380-121f-11ea-81e1-def584f8cf8b.png)
![Screenshot from 2019-11-28 20-18-09](https://user-images.githubusercontent.com/27276132/69815755-1abb7380-121f-11ea-9d08-79f9059f6207.png)

**Comment by lmmrssa** [comment]
yes this is a nice enhancement that can be done.
