### ISSUE TITLE
Surveys: bulk delete is not working

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5271]
![Screenshot from 2019-11-28 21-16-17](https://user-images.githubusercontent.com/27276132/69818252-71777c00-1224-11ea-97af-85d1b026a75d.png)

**Comment by lmmrssa** [comment]
This seems to be caused when there is no pending survey to be submitted. And when we are deleting survey we are trying to delete pending surveys.

**Comment by paulbert** [comment]
I think the problem is with the `this` context in the `reduce` function.  We could try `.bind(this)` for `submissionDeleteReq`.

I do not think the issue has anything to do with the number of pending surveys.
