### ISSUE TITLE
Users: After changing role list not updating

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#5283]
After changing the roles of a member of Planet with the **Set Roles** button or clicking the **X** next to the role in the `mat-chip`, the list does not update to reflect the new roles of that member.  If you try to change again, there will be a conflict error.

**Comment by paulbert** [comment]
![image](https://user-images.githubusercontent.com/9203229/70727045-ffe00900-1ccc-11ea-8911-c9ce76863ed2.png)

**Comment by paulbert** [comment]
@sjkadali Removing you from this since we need to have this fixed.

**Comment by sjkadali** [comment]
@paulbert , okay.
