### ISSUE TITLE
Community shows the link of deleted Team/Enterprises.

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5327]
![Screenshot from 2019-12-05 21-36-15](https://user-images.githubusercontent.com/27276132/70251271-4acabf80-17a7-11ea-9962-f7ced53a78c1.png)

**Comment by paulbert** [comment]
Steps to reproduce:
1. Add link of team to community
2. Go into team page & delete
3. Link will still appear on the community page & clicking will send you to the team list page with the above error
