### ISSUE TITLE
DialogsResourcesViewer: Images with modified aspect ratio

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#5329]
In **TeamsViewComponent** resources can be viewed with a click that opens **DialogsResourcesViewer**.  In this view it appears that the aspect ratio of the image is being modified which we should avoid:

![image](https://user-images.githubusercontent.com/9203229/70253262-df560300-1750-11ea-875e-b8c7fcd520b6.png)

![image](https://user-images.githubusercontent.com/9203229/70253274-e54be400-1750-11ea-9d6a-93cb0d2f05ac.png)

**Comment by robinGiri** [comment]
Dublicate of #6192 which already fixed.
