### ISSUE TITLE
Do not count communities already deleted

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#5400]
![Screen Shot 2019-12-19 at 8 16 45 PM](https://user-images.githubusercontent.com/2909490/71181606-98155980-229c-11ea-9ba1-6b6d4e957823.png)
On dev we see some communities have not downloaded resources but when looking at list there is no community. So we should not count communities where are not in the list.

**Comment by paulbert** [comment]
On **dev** it still lists 7 communities on the dashboard but I only see one with pending courses/resources in the list.

Looks like there's a problem on line 84 of `manager-dashboard.component.ts`.  `items.sendTo` should be `item.sendTo`.  I think `p.code` should actually be `p.doc.code`, also, but I'm not 100% sure of that.
