### ISSUE TITLE
Recurring event delete

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#5401]
On description of recurring event it is not explained about number of times it is repeating. Also while deleting it does not explain recurrance of event will be deleted.
As on calendar each recurrance are shown as separate event, it is confusing which of these events will be deleted.
![Screen Shot 2019-12-19 at 8 23 58 PM](https://user-images.githubusercontent.com/2909490/71182203-c47da580-229d-11ea-9f73-421a468b2049.png)
![Screen Shot 2019-12-19 at 8 24 08 PM](https://user-images.githubusercontent.com/2909490/71182214-c9425980-229d-11ea-9bc7-aba99182c54b.png)

**Comment by jessewashburn** [comment]
Splitting this into 2 issues. Adding recurrence info to event view is fixed by #7863. However, adding recurrence info to the delete confirmation popup is more complicated due to differences between Event and Meetup data types.
