### ISSUE TITLE
myPlanet Reports: Sort by device name not working

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5407]
either community name should be sorted in ascending manner or sorting should be present in columns.
![Screenshot from 2019-12-19 21-21-23](https://user-images.githubusercontent.com/27276132/71186737-d105fc00-22a5-11ea-831e-1ef2b43fc916.png)

**Comment by lmmrssa** [comment]
it is already sortable by planet name

**Comment by lmmrssa** [comment]
I am seeing issue on dev with myPlanet report sort because of some log which are missing detail of device because emulators were connected.

**Comment by paulbert** [comment]
The myPlanet reports were not fixed in #5427.  Check dev the reports are not sortable by name.

**Comment by paulbert** [comment]
Changing the title of the issue so it better reflects the final change we decided to implement.
