### ISSUE TITLE
myHealth: N/A should be shown in case of empty value

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5431]
right now blank value is shown.
![Screenshot from 2019-12-26 19-59-59](https://user-images.githubusercontent.com/27276132/71479152-5a27b080-281b-11ea-831b-592e40b58a3b.png)
![Screenshot from 2019-12-26 20-00-23](https://user-images.githubusercontent.com/27276132/71479154-5ac04700-281b-11ea-9bf7-48e9dbbe0522.png)

**Comment by lmmrssa** [comment]
This is good suggestion but putting on hold for now

**Comment by paulbert** [comment]
We removed fields from the dialog.  In the table I think we should leave spaces blank.  Otherwise it becomes difficult to scan values.
