### ISSUE TITLE
myHealth: markup editor is not working as expected

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5432]
in special needs markup editor field, bold or italic font is not showing as expected.
![Screenshot from 2019-12-26 20-12-49](https://user-images.githubusercontent.com/27276132/71479495-c3f48a00-281c-11ea-8326-5a09eb1789ec.png)
![Screenshot from 2019-12-26 20-13-54](https://user-images.githubusercontent.com/27276132/71479496-c48d2080-281c-11ea-8b68-c44928b500c8.png)

**Comment by lmmrssa** [comment]
This happening with special needs and notes.

**Comment by paulbert** [comment]
Duplicate of #5181
