### ISSUE TITLE
Survey CSV: Remove markdown tags

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5450]
either Font properties should be removed for excel report or it should be implemented properly.
right now it shows like this
![Screenshot from 2019-12-31 08-49-39](https://user-images.githubusercontent.com/27276132/71608688-221dc600-2bab-11ea-9207-581e0850d241.png)
 and also if Excel report column can be minimized to certain length of character for long text

**Comment by paulbert** [comment]
Yes, we should strip the markdown elements for this view because they are simply confusing.

It's not possible to put Excel/LibreOffice column width information into a CSV file.

**Comment by paulbert** [comment]
@singharpita I would look at what we do when adding questions to an exam.  The markdown for the question detail is stripped for the list of questions.
