### ISSUE TITLE
Community: empty enterprise/teams are added to the links

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5465]
1. click on add links.
![Screenshot from 2020-01-02 20-23-08](https://user-images.githubusercontent.com/27276132/71672517-48f01e00-2d9e-11ea-8821-1ab178c7c7a3.png)

2. go to type of link and select enterprise/team (such that team/enterpise list is empty).
![Screenshot from 2020-01-02 20-23-13](https://user-images.githubusercontent.com/27276132/71672522-52798600-2d9e-11ea-9eb8-e236dc69aee2.png)

3. It will show No Enterprises Found

4. Now Click on title and enter title.
![Screenshot from 2020-01-02 20-23-25](https://user-images.githubusercontent.com/27276132/71672570-776df900-2d9e-11ea-81e3-e7269729d292.png)

5. go back to enterprise/team tab
![Screenshot from 2020-01-02 20-23-39](https://user-images.githubusercontent.com/27276132/71672578-82c12480-2d9e-11ea-84d2-d1950c95f140.png)

6. then again click on title. this time it shows as highlighted field.
![Screenshot from 2020-01-02 20-23-43](https://user-images.githubusercontent.com/27276132/71672586-89e83280-2d9e-11ea-9ddf-6f1d525628bd.png)

7. now enter the title. ok button will be enabled.
![Screenshot from 2020-01-02 20-30-44](https://user-images.githubusercontent.com/27276132/71672663-c6b42980-2d9e-11ea-8288-dcf4cfe6a486.png)

8. click on OK.
9. new enterprise/team link is added in the list.
![Screenshot from 2020-01-02 20-23-52](https://user-images.githubusercontent.com/27276132/71672678-cfa4fb00-2d9e-11ea-9c19-fdf4429f5f6c.png)

10. clicking on add link throws error.
![Screenshot from 2020-01-02 20-24-14](https://user-images.githubusercontent.com/27276132/71672687-d6337280-2d9e-11ea-8f34-42f30f55fb95.png)

**Comment by paulbert** [comment]
We should disable going to the title at all unless a team or enterprise was selected.
