### ISSUE TITLE
Certifications: clicking on save button multiple times result in adding rows for same certificate

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5466]
1. Add new certificate
![Screenshot from 2020-01-02 20-47-22](https://user-images.githubusercontent.com/27276132/71673648-6e325b80-2da1-11ea-93fa-116ab02f8c63.png)

2. Enter certificate name
3. click on save multiple times (2,3 or 4)
4. then click on Save & Return.
5. In Certification list, as many times save is clicked same no. certificate is shown .
![Screenshot from 2020-01-02 20-47-42](https://user-images.githubusercontent.com/27276132/71673656-738fa600-2da1-11ea-8bdc-1aad5710df5f.png)

**Comment by paulbert** [comment]
Once we save the first time, the id and rev should be updated in the CertificationsAddComponent so it updates rather than creates.
