### ISSUE TITLE
Survey: in case of unanswerd multiple choice single/multiple answer shows "undefined"

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5482]
1. create a survey with one type of question say short answer.
2. record that survey
3. now edit the above survey such that add new type of question say multiple choice single answer. save it
4. now do not record that survey
5. print the above survey
6. it shows undefined as answer
![Screenshot from 2020-01-07 08-44-57](https://user-images.githubusercontent.com/27276132/71865338-8a7c2280-312a-11ea-8cd8-c9d8775b7f7b.png)

**Comment by paulbert** [comment]
See #5091 this is expected behavior currently.

We are working on the fix to lock a survey version in once it has been taken once.
