### ISSUE TITLE
CertificationsComponent: Certification List is not displayed.

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#5494]
1.Add a certification
2. Now go back to certification page.
3. Certification page is empty.

![2](https://user-images.githubusercontent.com/45058288/71902753-cf37a600-318a-11ea-8c75-95fca74c79ae.png)

**Comment by paulbert** [comment]
@robinGiri The table is hidden as a beta feature, but it should not be.

Removing `*planetBeta` will fix this
