### ISSUE TITLE
Transaction filter placeholder inconsistency

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5530]
right now it shows as " Pick Starting date" and "Pick End date"
it should be either "Pick Starting date" "Pick Ending date"
or "Pick Start Date" "Pick End Date"
![Screenshot from 2020-01-14 08-17-36](https://user-images.githubusercontent.com/27276132/72309977-9dea3900-36a8-11ea-9cd6-865cbfdd8c38.png)

**Comment by paulbert** [comment]
Let's go with **Pick Start Date**
