### ISSUE TITLE
myDashboard: Tile leads to Sorry, page not found page.

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#5532]
In myDashboard page if we click tiles it leads to page not found page

![Screenshot from 2020-01-14 08-35-42](https://user-images.githubusercontent.com/45058288/72310084-e6a1f200-36a8-11ea-8f7a-7322829d3e72.png)
 
This is the url of selected tile.

![newpic](https://user-images.githubusercontent.com/45058288/72309972-9b87df00-36a8-11ea-9d69-b69fd53c2a62.png)

**Comment by paulbert** [comment]
Let's make these absolute links in case that route changes again.  I don't foresee a situation where we'd want the resource/course/team routes to be relative to the dashboard route.
