### ISSUE TITLE
View Transaction: not working as expected

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5534]
1. Transaction has this record
![Screenshot from 2020-01-14 08-44-48](https://user-images.githubusercontent.com/27276132/72310629-4d73db00-36aa-11ea-8e5b-97d62a8d0ea3.png)
2. Applying the date filter in such a way that it doesn't consist of transaction list result in empty record and enables the view transaction
![Screenshot from 2020-01-14 08-45-10](https://user-images.githubusercontent.com/27276132/72310670-67adb900-36aa-11ea-9b97-906ca1c736ac.png)
3. Clicking on View Transaction doesn't populate any list and then button get disabled
![Screenshot from 2020-01-14 08-45-15](https://user-images.githubusercontent.com/27276132/72310700-7a27f280-36aa-11ea-8b46-bc997aadf24b.png)

NOTE: View Transaction works fine if there is atleast one record from filter.

**Comment by paulbert** [comment]
Need to set `emptyTable` to false when that is clicked.
