### ISSUE TITLE
Enterprise: "Public" toggle button is not initializing correctly

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5560]
even though i turned toggle on and success message shown, reopening again will disabled the toggle
![Screenshot from 2020-01-16 20-12-59](https://user-images.githubusercontent.com/27276132/72533133-bfac1180-389c-11ea-957d-89a10900466d.png)

**Comment by paulbert** [comment]
Editing title to clarify the issue.

The form is not initializing the value of Public correctly.  It's just setting it to false.  It is saved as Public after hitting submit, however.
