### ISSUE TITLE
Teams/Enterprise: Inconsistency of "OK" button in Add members during search

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5562]
1. Highlight/select any member. it enables the OK button.
![Screenshot from 2020-01-16 20-26-56](https://user-images.githubusercontent.com/27276132/72534914-bec8af00-389f-11ea-9e2e-045eaf324c8d.png)
2. Now in search bar type anything that doesn't matches the list and hence result in empty list.
now ok button is still enabled.
![Screenshot from 2020-01-16 20-27-03](https://user-images.githubusercontent.com/27276132/72534965-d6a03300-389f-11ea-8d4a-ac652dcbd7ab.png)
3. Click on OK button. it will get clicked and success message is shown.
![Screenshot from 2020-01-16 20-27-09](https://user-images.githubusercontent.com/27276132/72535013-e61f7c00-389f-11ea-8eac-4852a902f1e6.png)

NOTE: enabling/disabling of OK is fine until and unless success message wont show for no action.
hiding/remove message on click of OK will be fine.

**Comment by paulbert** [comment]
Note the **1 member selected** next to OK.  The members stay selected even when the filter or the page changes so you can search multiple times, click on various members, and select all of them.

**Comment by paulbert** [comment]
Outdated.  This dialog is no longer used to select members to add to a team/enterprise.
