### ISSUE TITLE
Disable Mark All as Read if all notifications are already read

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#5567]
Right now we can click on **Mark All Read** even when all notifications has been read.
Even if we allow them to click it, we should prevent from sending request to database. As we are sending bulk update request with empty array and then fetching notifications.
We can just send request if array is not empty.

**Comment by paulbert** [comment]
Here's a video to show what's going on:

https://www.loom.com/share/867573f432e64c1bb26c356b62699493

**Comment by paulbert** [comment]
Let's disable the button if all of the notifications are read.
