### ISSUE TITLE
Notifications: Notification message  link  of community .

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#5580]
1.add new story in community
2.log in as another user
3. go to notification and click on notification from community.

![Screenshot from 2020-01-21 08-26-02](https://user-images.githubusercontent.com/45058288/72771073-d7322400-3c27-11ea-85d8-6309245b7444.png)

url link is /notifications/community

![Screenshot from 2020-01-21 08-27-47](https://user-images.githubusercontent.com/45058288/72771103-edd87b00-3c27-11ea-8729-f33bb483dc68.png)

**Comment by paulbert** [comment]
Note clicking from the menu in the top leads to `/community`.  This should not be a relative path and always go to `/`
