### ISSUE TITLE
Community: Add header

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5581]
when shifting to small screen, only icons are shown for community, which sometimes might be confusing that in which page are we landed specially in case of default redirect to this page.
![Screenshot from 2020-01-21 08-40-14](https://user-images.githubusercontent.com/27276132/72771729-e914c680-3c29-11ea-9bb7-4ba115901adb.png)

**Comment by paulbert** [comment]
Let's add a header above the gray toolbar with the community name.  Changing the title to reflect that.
