### ISSUE TITLE
Preview test on completion shows "Exam complete......" message

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5635]
it should show "**Test** complete, you can close the preview"
![Screenshot from 2020-01-28 08-14-09](https://user-images.githubusercontent.com/27276132/73230799-803bca00-41a6-11ea-9dda-97baec490df8.png)

**Comment by RheuX** [comment]
The current issue is solved already

`<ng-container i18n>{examType, select, survey {Survey is complete.} exam {Test is complete.}}</ng-container>`

but I can't seem to replicate the issue since previewing a test, doesnt give me a feedback when im done, its just close the preview test

**Comment by Mutugiii** [comment]
That is as intended for the test preview
