### ISSUE TITLE
Tasks: Not showing member profile image

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#5660]
Found an issue where the member profile image is not found for a task.  It will need replication to find the exact cause, but the issue is related to the fact that when changing profile images the file name is set to either `img` or `img_` to force the overwrite of the file.

The member in this example has an image in the `attachments` database saved as `img_`, but the app is looking for `img`.

![image](https://user-images.githubusercontent.com/9203229/73462199-64245e00-4349-11ea-81b5-7f0e5023bf04.png)

**Comment by jessewashburn** [comment]
Related to #4735
