### ISSUE TITLE
Community: Service & Finances editing not available

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#5661]
Add Transaction button disappear after adding transaction.
![Screen Shot 2020-01-30 at 8 58 32 PM](https://user-images.githubusercontent.com/2909490/73462228-8fd43200-43a3-11ea-8e66-6cd25d3efcbe.png)

**Comment by paulbert** [comment]
Expanding the scope of this a little to include **Services**

These two tabs should be editable if the logged in member is an admin and the planet being viewed is the one logged in to.
