### ISSUE TITLE
TeamsViewFinancesComponent: Edit Transaction header and message

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#5672]
**Steps to replicate**
1. Go to enterprise
2. Add transaction
3. Try to edit Transaction

The header of dialog form shows **Add Transaction**.

![Screenshot from 2020-01-31 15-07-28](https://user-images.githubusercontent.com/45058288/73527650-80082c80-443b-11ea-8e02-1519b8dadd9e.png)

&nbsp;
&nbsp;
&nbsp;
After Editing Transaction error message shows **Transaction Added**

&nbsp;
&nbsp;
&nbsp;
![Screenshot from 2020-01-31 15-11-35](https://user-images.githubusercontent.com/45058288/73527940-058bdc80-443c-11ea-875c-05f0d2b98be7.png)

**Comment by paulbert** [comment]
Not an error message, just a normal message so edited the title.
