### ISSUE TITLE
Community: Services links & Transactions not showing

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5678]
- add any team/enterprise through add link
or
add any transaction.
- link has not been added and result in console error
![Screenshot from 2020-02-04 07-59-02](https://user-images.githubusercontent.com/27276132/73707743-7b39c600-4724-11ea-9399-f0da34337dd7.png)

**Comment by paulbert** [comment]
The console error relates to the **Community Leaders** tab.

No links or transactions are showing up, so no need to Add them.  It's possible that fixing the console error will fix this data not showing, so I'll put this one on hold while I create an issue for the error.

**Comment by paulbert** [comment]
After checking this out, this console error was causing the missing links & transactions.  Closing the other issue.
