### ISSUE TITLE
Teams/Enterprise: In collection filter, create collection is not needed

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5738]
While adding courses/resources to any Team/Enterprise, Collection filter also shows Create collection option which is not needed as it doesn't allow to add existing collection to any course or resources.
It would be better to remove this section.
![Screenshot from 2020-02-11 08-29-30](https://user-images.githubusercontent.com/27276132/74207805-1db7f300-4ca9-11ea-9660-9de0bac14392.png)

**Comment by paulbert** [comment]
This will only show up for an admin, and was a specific request for the collections dialog.

Taking that in mind and the fact that this is low priority, I'm just going to close this.
