### ISSUE TITLE
Selection collection list name is not shown in Courses/Resources

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5741]
1. select any collection title from collection.
2. nothing is shown
![Screenshot from 2020-02-11 08-35-28](https://user-images.githubusercontent.com/27276132/74207938-b8b0cd00-4ca9-11ea-8ca3-1bf0819f1cd1.png)
![Screenshot from 2020-02-11 08-34-54](https://user-images.githubusercontent.com/27276132/74207939-ba7a9080-4ca9-11ea-9ee9-c4349b5d6a1c.png)

**Comment by paulbert** [comment]
There's an error in the console `TypeError: Cannot read property 'find' of null` on this line:

![image](https://user-images.githubusercontent.com/9203229/74210216-c12ce780-4c58-11ea-8bab-1bf8e2559477.png)

**Comment by paulbert** [comment]
The error is in `TagsService.findTag`
