### ISSUE TITLE
Courses: Empty placeholder when we edit.

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#5745]
Go to courses
Select one course
Edit course

The placeholder are empty which were supposed to be filled with data.

![Screenshot from 2020-02-11 08-54-00](https://user-images.githubusercontent.com/45058288/74208651-9c625f80-4cac-11ea-8984-8b59b7a21f31.png)

**Comment by paulbert** [comment]
I can't replicate in Chrome or Firefox, but it is happening on all courses in Firefox for @robinGiri

**Comment by robinGiri** [comment]
@paulbert I cleared the cache of my Firefox browser and i can't find this issue any more.

**Comment by paulbert** [comment]
OK, I will close this issue, then.  Thanks!
