### ISSUE TITLE
Notification: list should be sorted using latest date at top

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5768]
notification list should be sorted and shown using date as descending order.
right now ordering via date is random and its kind of confusing when looking for recent unread notification.
![Screenshot from 2020-02-13 20-04-06](https://user-images.githubusercontent.com/27276132/74443860-055bfa00-4e9c-11ea-85e2-1d5e8322b6d1.png)

**Comment by paulbert** [comment]
Checked the database, and this is the error where dates were stored as a string with a newline character.  Issue was fixed, so sorting should be OK for future notifications.
