### ISSUE TITLE
Community Add News dialog box is not closing on submit

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5770]
- go to community add news
- click on add news
- add news dialog box appear
- write a news and submit it
- news has been posted but dialog box doesn't close automatically.
![Screenshot from 2020-02-13 20-10-02](https://user-images.githubusercontent.com/27276132/74444516-19542b80-4e9d-11ea-9228-5bf1a998feb0.png)

**Comment by paulbert** [comment]
Based on the error, it looks like after a refactor we try to access `this.user.currentUser._id`, but it should be `this.user._id`.

Error in the console:
![image](https://user-images.githubusercontent.com/9203229/74445062-c8641900-4e43-11ea-84ba-a1782165a702.png)

**Comment by paulbert** [comment]
Seems like it closes for the admin, so make sure you are logged in as a regular member for testing.
