### ISSUE TITLE
Collection: on delete shows inconsistency of validation message

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5776]
- create a new collection e.g: "addnew"
![Screenshot from 2020-02-13 21-13-11](https://user-images.githubusercontent.com/27276132/74450294-f7ab7200-4ea5-11ea-8655-26b1dd54d0a0.png)
- now creating collection with same name again disabled the "Add collection" button
![Screenshot from 2020-02-13 21-14-12](https://user-images.githubusercontent.com/27276132/74450375-13167d00-4ea6-11ea-93f5-3b520b5cfd5e.png)
- Click on Delete button of already created collection. A delete warning pop up appears with validation message in background of Created collection.
![Screenshot from 2020-02-13 21-14-25](https://user-images.githubusercontent.com/27276132/74450489-3f31fe00-4ea6-11ea-85a3-bc24df0636b3.png)
- Click on OK. now that collection doesn't exist on list but that validation message keeps on showing until making any changes in Add collection name field.
![Screenshot from 2020-02-13 21-14-34](https://user-images.githubusercontent.com/27276132/74450559-57098200-4ea6-11ea-86b4-9b0789683ca5.png)

**Comment by paulbert** [comment]
Adding low priority since this is a little bit of an edge case, but this is a good refinement for Collections.
