### ISSUE TITLE
News: Add label to message while viewing replies conflict

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5790]
- Create a new post/message.
- reply to that message
- add label to Reply
- now try to add label to main message
- Console error shown
![Screenshot from 2020-02-18 07-57-47](https://user-images.githubusercontent.com/27276132/74698014-890f4100-5224-11ea-9723-a0ffd319ed96.png)

**Comment by paulbert** [comment]
You don't need to add a label to the reply to see this issue.

You just need to view the replies of a message, then add a label twice to the main message.  The first time you will see "Label added", but the label won't be there.  The second time you will see the conflict error.

It appears the metadata for the main message is not updated after adding the label.
