### ISSUE TITLE
Messages/News: on adding of all label, message still says "Label added"

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5792]
- Create a message/post
- Add all the three labels "Help wanted","Offer","request for advice"
- message shown will be "Label added"
- again add any of these label in same messgae.
- same "label added" message shown
- It would be better to change the message to "Label already added"
OR
remove the labels once added.

**Comment by paulbert** [comment]
Related to #5793 since both involve improving the UX after a label has been added.

We should remove the labels already added from the list of labels to add.
