### ISSUE TITLE
Improve myplanet crash log

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#5798]
We have view for crash log of myplanet. Right now its just list of all crashes. We need to improve it so that it also shows date and device where crash is occuring.
Also we can add filter for device or date
http://localhost/eng/logs/myplanet

**Comment by paulbert** [comment]
We can probably reuse `MyPlanetTableComponent` for this page.  Instead of the count in the last column we can show a button that opens a dialog with the text of the crash log.
