### ISSUE TITLE
News: Reply Add Label list is always same as main message's

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5817]
- Create a message
- add label to it
- reply to this message
- add different label than main message
- check add label list (remaining one)
- both reply and message shows same list
![Screenshot from 2020-02-20 20-20-09](https://user-images.githubusercontent.com/27276132/74944930-ed95f000-541e-11ea-93e0-08acc76473c4.png)
![Screenshot from 2020-02-20 20-20-02](https://user-images.githubusercontent.com/27276132/74944933-eec71d00-541e-11ea-935d-617bf1199a27.png)

**Comment by paulbert** [comment]
Editing.  There are some unnecessary steps in here.

The main thing is that the label list should reflect the specific news item, not the message that you are viewing the replies of.

**Comment by paulbert** [comment]
Oops.  Changed the title of the wrong issue
