### ISSUE TITLE
Certification: on clicking of "Save"/"Save & return" doesn't show any success message

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5819]
![Screenshot from 2020-02-20 20-41-05](https://user-images.githubusercontent.com/27276132/74946476-757cf980-5421-11ea-8053-6846b7cdcdc6.png)

**NOTE: Same goes when removing any course, no success message is shown.**

**Comment by paulbert** [comment]
We should add a message when the certification is saved, either from the **Save** or **Save & Return** button

There are already visual cues for adding & removing courses, so no need to add a message for those actions.
