### ISSUE TITLE
New resource notification

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#5842]
Notification when new resource is added works from notification icon, but it does not work from list of notification.
Also `sort=createdDate` parameter added to route does not work.
![Screen Shot 2020-02-25 at 8 01 58 AM](https://user-images.githubusercontent.com/2909490/75209112-8c1aac00-57a5-11ea-8c03-a0c3132f2003.png)
![Screen Shot 2020-02-25 at 8 01 41 AM](https://user-images.githubusercontent.com/2909490/75209122-92108d00-57a5-11ea-8170-ee663d3c06b4.png)

**Comment by paulbert** [comment]
@gyawaliamit7 Looks like the link is relative in **NotificationsComponent**, but not in the menu.

It should be absolute there as well.

**Comment by paulbert** [comment]
Oops fixed in #5922
