### ISSUE TITLE
Re-take test label is not updated in course detail page

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5859]
![Screenshot from 2020-02-27 20-10-32](https://user-images.githubusercontent.com/27276132/75454316-58a27200-599d-11ea-89ad-2d0660c68a10.png)
![Screenshot from 2020-02-27 20-10-18](https://user-images.githubusercontent.com/27276132/75454320-5a6c3580-599d-11ea-8d12-a1adfa286eb8.png)

**Comment by paulbert** [comment]
The main issue #5847 is still open.
