### ISSUE TITLE
CertificationsView: Enhancements for empty tables and edit link

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5864]
it should show "No record" on empty.
It would be nice to have Edit Certification in this page.
![Screenshot from 2020-02-27 20-49-38](https://user-images.githubusercontent.com/27276132/75457727-edf53480-59a4-11ea-956a-3ceab89ad922.png)
![Screenshot from 2020-02-27 20-49-27](https://user-images.githubusercontent.com/27276132/75457729-ee8dcb00-59a4-11ea-9b2c-5909681bbcd5.png)

**Comment by paulbert** [comment]
Three things for this issue:

1. Add some text when there are no courses in **Course Requirements**
2. Add some text and hide the empty table when no members have completed the certification in **Certified Members**
3. Add an edit button next to the certification title
