### ISSUE TITLE
back button of myLife component of Dashboard redirects to Community page

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5865]
is this the correct behaviour?
or it should redirect to myDashboard page?

**Comment by paulbert** [comment]
All of the `myLife` components' back buttons lead to the Community page, which is not ideal.

Let's make all of the components in `myLife` child routes of `myDashboard` so we can just have the back button go up one level in the routing tree.  That way if we change application structure again it will be easier to maintain this routing structure.
