### ISSUE TITLE
ReportsMyPlanet & LogsMyPlanet: Incorrect error message

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#5872]
If there is an error loading the myPlanet reports the error message will show **There was a problem getting Nation** or **There was a problem getting Community**.

Let's change this to always be **There was a problem getting myPlanet activity**.

**Comment by Haoran-Hu** [comment]
@paulbert How do I view that error message

**Comment by paulbert** [comment]
In **ReportsMyPlanetComponent** you can insert above line 83 
```
switchMap(() => throwError('error')),
```
In **LogsMyPlanetComponent** you can insert above line 53 `throwError('error')`

These will cause an error to be thrown on those pages.
