### ISSUE TITLE
CoursesView: Activity stored is previous course viewed

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#5883]
![IMG_20200303_084026](https://user-images.githubusercontent.com/2909490/75738574-c72f5900-5d2a-11ea-9c12-a714c08249cd.jpg)

**Comment by lmmrssa** [comment]
Difficult to reproduce, occurred once but not happening again. In any case, we can filter record if there is no courseId.

**Comment by paulbert** [comment]
Updating the title.  The issue is that the activity is triggered before the course information is fetched, and the service simply uses the previous value.  If there was not a previous course stored on the service, the `courseId` and `title` are undefined.
