### ISSUE TITLE
Troubleshooting section

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/planet#590]
It maybe good to have a troubleshooting section with at least one common issue people working on Planet tends to encounter from time to time (e.g. adding imports to certain top level part of application requiring restart of the watch/serve command), that then could be extended?

I have not seen that in the github or http://open-learning-exchange.github.io/#!pages/robots/rbts-angular.md, but it seems like it would make sense to add somewhere?

**Comment by paulbert** [comment]
Fixed in #755
