### ISSUE TITLE
Community Services: Edit Community Description.

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#5904]
In community services page there is  **Edit Community Description** even when we haven't written community description. Can we show **Write Community Description** when no description is written and after description is written can we show  **Edit Community Description**.

![Screenshot from 2020-03-05 09-17-32](https://user-images.githubusercontent.com/45058288/75945599-d34e1e80-5ec2-11ea-8ef3-a6fd5ad12b0a.png)

**Comment by paulbert** [comment]
Let's have the text be **Add Community Description** if there is nothing there currently.
