### ISSUE TITLE
Teams: Reset filter in type name to search.

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#5905]
In both teams and enterprise we have search in toolbar. Can we add reset filter in search.

![Screenshot from 2020-03-05 09-30-55](https://user-images.githubusercontent.com/45058288/75946044-15c42b00-5ec4-11ea-9a33-42ddf8822099.png)

![Screenshot from 2020-03-05 09-30-31](https://user-images.githubusercontent.com/45058288/75946048-18bf1b80-5ec4-11ea-8cab-0d2aba00761e.png)

Similar feature has been added in **Certification Search**

![Screenshot from 2020-03-05 09-34-32](https://user-images.githubusercontent.com/45058288/75946215-98e58100-5ec4-11ea-9bc6-ac048e73473c.png)

**Comment by paulbert** [comment]
Note Teams and Enterprises both use the same **TeamsComponent** so this change only needs to happen in one spot.

This is **Low Priority** because there is only the text field there so it is not difficult to clear.
