### ISSUE TITLE
CourseView: Tooltip in mat-panel-description

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#5908]
The symbol in **CourseView** doesn't have any description so its hard to know their meaning. It would have been easier if there were tooltip for those symbol.

![5e60db0c1d038_image_name](https://user-images.githubusercontent.com/45058288/75975279-56da3080-5f00-11ea-8428-bd8abdb74a44.jpg)

**Comment by paulbert** [comment]
It would be good to have a tooltip for these.

These icons are also used in **CoursesStepComponent**.  Let's make a **CoursesIconComponent** so the tooltip text is the same for both and only written in one place.
