### ISSUE TITLE
Style: Length of components guidance?

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/planet#591]
Styleguide, could have info on preferred length of components? 

What is generally considered to long for the JS/TS part? 

The components I've seen in the codebase with >200 lines seems like it is requiring a bit more effort to keep track of what it does happening?

**Comment by paulbert** [comment]
Added Code Climate which will flag files over 200 lines, helping us remedy this.  I'm going to close this, but a small section of documentation on Code Climate might help in the future
