### ISSUE TITLE
Community: Deleted Team (from Team list) still shown Teams link in Services

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#5935]
Add  team as a service link to community.
Now go to team and delete that Team link.
Now go to service, Team link can still be seen.

Note: This problem is only with team but not with enterprise.

**Comment by paulbert** [comment]
Took a little while to figure this one out, but the error is found when deleting a team using the button in **TeamsViewComponent**, not **TeamsComponent**.

This problem exists for both teams and enterprises.
