### ISSUE TITLE
Gender validation

### ISSUE THREAD

**Issue by AlekseiKorolev** [open-learning-exchange/planet#5942]
Gender radio button mark as required and it's work as that, but don't show an error if neither is selected.
![Untitled](https://user-images.githubusercontent.com/42728999/76344303-a2764b00-6301-11ea-9726-45507feb5218.png)

**Comment by RheuX** [comment]
![image](https://github.com/user-attachments/assets/bb21a25e-415e-42d6-af08-0bfbb7006f20)
Still the same issue, could be implemented similarly with #7669 since choices field are the only choices that have no visible error.

**Comment by Mutugiii** [comment]
The error message should suffice for now
