### ISSUE TITLE
ExamsAdd: No completion message for test preview

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#5957]
### Current Behavior

Clicking **Submit Answer** on the last question does nothing

### Desired Behavior

A message should show up saying **Test is complete...** next to the buttons.  It showed up through version 0.10.33, but with the addition of the **Finish Test** button it is no longer showing up.

https://www.loom.com/share/d1fc661e70aa47ecb0ddd8db2b90ae64

**Comment by lmmrssa** [comment]
Related to #5954
