### ISSUE TITLE
CoursesView: Take Test button text changes on hide/show of course step detail

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5958]
- go to any course that has atleast two steps with each having their own test.
- submit the first test without clicking on "Finish test". That will result in "Continue test" status
- now go to CoursesViewComponent.
- toggle the First step with "Continue test" status. leave it as it is
- toggle the second step.
- Now both step shows status "Take test"
![1edca592-fc96-419e-8b3a-41fc866aa3ad](https://user-images.githubusercontent.com/27276132/76530181-78589080-649b-11ea-8cb6-b9b6c74734c2.gif)

**Comment by paulbert** [comment]
Editing to make it clear the issue is on **CoursesViewComponent**

**Comment by paulbert** [comment]
I think a `TrackByFunction` ([example](https://angular.io/api/common/NgForOf#description)) in the `*ngFor="let step of courseDetail.steps...` may be a solution for this.

If not, check the `opened` event for `mat-expansion-panel` ([reference](https://material.angular.io/components/expansion/api#MatExpansionPanel))
