### ISSUE TITLE
Review attempts remove table columns

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5970]
In review attempts dialog box, Name shows "[Course Name] + [some random number].
is this the course step number or it just assigned any random value?
If its a course step number, then it is not matching it in current scenario.
because then for each attempts on given step Name is same though.
![Screenshot from 2020-03-17 07-13-51](https://user-images.githubusercontent.com/27276132/76813272-87369e80-681f-11ea-910c-19db74ee407e.png)

**Comment by paulbert** [comment]
This isn't a random number, but it is not the step number.

In this view let's try only showing **Status** and **Updated On**
