### ISSUE TITLE
Date started and most recent activity column is blank

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5994]
![Screenshot from 2020-03-19 20-02-29](https://user-images.githubusercontent.com/27276132/77077269-152ba880-6a1d-11ea-893c-95690c99793b.png)

**Comment by paulbert** [comment]
@singharpita If the member hasn't visited the first course step page, then nothing is shown for these columns.  That is by design to show that the member signed up, but hasn't actually started the course.
