### ISSUE TITLE
Completed survey notification link shows "page not found"

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5995]
- Create a survey (not linked to any course)
- send survey to one or two member.
- complete the survey by that member
- now login to admin
- notification can be seen that "survey has been filled by [member]"
- click on that notification
- result in "Sorry page not found" 
![Screenshot from 2020-03-19 20-09-41](https://user-images.githubusercontent.com/27276132/77077830-df3af400-6a1d-11ea-951d-31c4216e85c6.png)
![Screenshot from 2020-03-19 20-09-38](https://user-images.githubusercontent.com/27276132/77077832-e06c2100-6a1d-11ea-91b9-e14cf1d3eca7.png)

**Comment by lmmrssa** [comment]
url seems to be missing `/myDashboard` before `/submissions` so it should look like `/myDashboard/submissions/....`
