### ISSUE TITLE
Enterprise: title inconsistency

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5996]
in list page, it says what is actually entered
but in detail page "Office" suffix is added to it.
should be consistent in either way.
![Screenshot from 2020-03-19 20-14-52](https://user-images.githubusercontent.com/27276132/77078294-7dc75500-6a1e-11ea-9bbb-368d29e24e2a.png)
![Screenshot from 2020-03-19 20-14-39](https://user-images.githubusercontent.com/27276132/77078298-7ef88200-6a1e-11ea-900c-42bde748981c.png)

**Comment by lmmrssa** [comment]
Adding **Office** on Enterprise has been requested by our BOSS :) Name of Enterprise is actually what shows on the list and Page of Enterprise had Office added to represent like virtual office or an enterprise.

**Comment by paulbert** [comment]
Closing.  As @lmmrssa said, this was added by request.
