### ISSUE TITLE
Community Add Event: event start date (alone) can be of before date?

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6015]
right now when there is only start date entered for an event, start date is allowed to take any previous year.
![Screenshot from 2020-03-24 07-33-26](https://user-images.githubusercontent.com/27276132/77380110-6b447700-6da2-11ea-9e89-dd9217cb57b8.png)
![Screenshot from 2020-03-24 07-39-53](https://user-images.githubusercontent.com/27276132/77380247-c2e2e280-6da2-11ea-858d-86f17ad2ac4a.png)

**Comment by paulbert** [comment]
We want to allow members to retroactively add events that have happened or to modify events after the fact if the date/time changed so they have it in the record.
