### ISSUE TITLE
Course view step jump

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#6039]
From list of steps on course view. it is possible to jump to another step (take exam) by clicking on take exam of any step

**Comment by paulbert** [comment]
Let's disable the `Take Exam` button if the learner has passed the previous exam.

Maybe the easiest thing would be to set a `maxExam` property based on `courseDetail.steps` and `progress` which is the step number for the first exam that is not passed (or if they are all passed just the final step number).

Then you could disable the button for any step greater than `maxExam`.

**Comment by sjkadali** [comment]
@paulbert , I'll start working on it. Thanks!

**Comment by sjkadali** [comment]
@paulbert, So no retake for passed exam?

**Comment by sjkadali** [comment]
@paulbert please review the changes to the PR. Thanks!
