### ISSUE TITLE
ourNews: reply has not been added and shows console error

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6040]
- go to myDashboard->ourNews
- add new news
- reply to above added news
- spinner keeps on loading and shows console error
![Screenshot (6)](https://user-images.githubusercontent.com/27276132/77657525-89c29200-6f9d-11ea-9335-5f2c2853c40e.png)

**Comment by lmmrssa** [comment]
We are working on community news recently so need to check if we want to keep our news

**Comment by Mutugiii** [comment]
To add to this there is a notification 
![oleOurNewsNoti](https://user-images.githubusercontent.com/48474421/82570017-b3f19400-9b89-11ea-9368-f636dea9f773.png)

**Comment by lmmrssa** [comment]
@paulbert shall we deactivate ournews part as we are showing community news as first page. And not seeing use of ournews

**Comment by RheuX** [comment]
not sure where is OurNews? is it a disabled feature now?
