### ISSUE TITLE
Survey Complete message

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#6041]
When taking survey if some of question skipped and reaching end of survey still gives survey complete message. Now if you move back by arrow that message will still be there unless you go by next arrow and come to unanswered question

**Comment by lmmrssa** [comment]
looks more like issue with short question.

**Comment by paulbert** [comment]
Are you seeing this when you "skip" an answer after typing something in for it?  That answer gets saved to the database, so it counts as submitted.

I think with the "Finish Test/Survey" button we've got this covered.  Somebody won't accidentally submit a survey for review, but their answer won't get thrown out if they click the arrow button.
