### ISSUE TITLE
Report of resource view shows course url in report

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6054]
also the title shows in below image is of Resource.
![Screenshot (11)](https://user-images.githubusercontent.com/27276132/77979880-8fb1cd80-7325-11ea-8fb5-1e2777428e30.png)
![Screenshot (12)](https://user-images.githubusercontent.com/27276132/77979884-92142780-7325-11ea-93a1-e8e794dfcbda.png)

**Comment by lmmrssa** [comment]
@singharpita this is the url where it was viewed. So this is ok as it was opened from course

**Comment by paulbert** [comment]
@lmmrssa is correct.  Closing.
