### ISSUE TITLE
Course/Resource Report: Average rating on blank should show N/A

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6070]
right now its empty/blank.
![Screenshot (15)](https://user-images.githubusercontent.com/27276132/78254350-7f604500-7515-11ea-9d6a-d46da9f458e6.png)
![Screenshot (16)](https://user-images.githubusercontent.com/27276132/78254356-812a0880-7515-11ea-911b-e639c9c5993c.png)

**Comment by paulbert** [comment]
I'm going to close this.  Blank is fine, it makes it easier to scan which resources have been reviewed.
