### ISSUE TITLE
TeamsView: Vertical alignment off for "Request Pending"

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6087]
Same for Enterprise
![Screenshot (28)](https://user-images.githubusercontent.com/27276132/78625331-84bde680-78ab-11ea-92cd-129d60e50611.png)

**Comment by paulbert** [comment]
Changing the title for more clarity.  Looks like this issue is specific to Firefox

**Comment by paulbert** [comment]
A couple things that could be tried: Using flexbox to align those items or remove the `div` element that doesn't appear to be doing anything.

Make sure that the fix doesn't break the view in Chrome.
