### ISSUE TITLE
Teams: Share main chat post 

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#6089]
### Current Behavior

The **Share with Community** button does not show up for the main post (outlined in gray) when viewing replies for that post.

### Desired Behavior

If it meets the other criteria (not already shared, the post above it in the chain has been shared), then the button should show.

![image](https://user-images.githubusercontent.com/9203229/78625810-02a5d180-785b-11ea-831f-3c4c41184cba.png)

**Comment by Haoran-Hu** [comment]
@paulbert I tested the feature, after clicking **Show Replies**, the **showShare** attribute for the component is actually true, so I am kind of confused about the absence of the share button...

**Comment by Haoran-Hu** [comment]
@paulbert  never mind. Maybe I did the wrong test.
