### ISSUE TITLE
Teams/Enterprise: Add Members Dialog box Buttons

### ISSUE THREAD

**Issue by sjkadali** [open-learning-exchange/planet#6096]
In the Teams/Enterprise View, the Add Member dialog box buttons can be made to look consistent with buttons of other dialog boxes.

![Screenshot from 2020-04-08 21-04-15](https://user-images.githubusercontent.com/39105848/78847513-04979e00-79dd-11ea-9122-51c4bec8bc4a.png)

**Comment by lmmrssa** [comment]
it will not be required once we implement #6388
