### ISSUE TITLE
ResourcesAdd: Public resource should not show "Private" flag

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6103]
- create a resource with private resource enabled.
- View and rating will not be shown
- now toggle and make it public
- view and rating will be shown
- again make it private.

Rating and view count is still shown in report. So will it be shown in report or have to be hidden?

**Comment by lmmrssa** [comment]
Private resource are supposed to be not known by other people and also not readable by others so we might not want to show them on report

**Comment by paulbert** [comment]
Once a resource is public it should not be able to be toggled back to private.  Changing the title to reflect this.
