### ISSUE TITLE
Courses View-  On Continuing test going to previous question and skipping it not allowed

### ISSUE THREAD

**Issue by sjkadali** [open-learning-exchange/planet#6104]
On continuing the test, going back to the previous unanswered questions and then skipping it and going to the next question not allowed.

![Screenshot from 2020-04-09 09-43-36](https://user-images.githubusercontent.com/39105848/78903416-17e05300-7a49-11ea-8d50-1bb094f401c7.png)

![Screenshot from 2020-04-09 09-44-26](https://user-images.githubusercontent.com/39105848/78903439-1f076100-7a49-11ea-9a6c-dcd752230252.png)

**Comment by paulbert** [comment]
@sjkadali I am not able to replicate this.

If you select the incorrect answer and try to skip, the "Incorrect answer" message will come up first and the answer will clear.  Clicking the next arrow again will skip the question.  Did you have something selected before the second image in the issue?

**Comment by sjkadali** [comment]
@paulbert ,  no tried going to the next question without selecting the answers.

**Comment by Mutugiii** [comment]
Unable to replicate
