### ISSUE TITLE
myHealth: newly added examination should be shown first in column

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6105]
since latest examination matters, it would be good to show the latest examination report at first rather than appending it to the last.
![Screenshot_2020-04-09 Planet Learning(3)](https://user-images.githubusercontent.com/27276132/78905094-307a5880-7a9d-11ea-8f47-96b1ecd843bd.png)

**Comment by lmmrssa** [comment]
there was auto scroll to last health record added for this purpose. This feature is something on hold so we keeping hold label

**Comment by paulbert** [comment]
Autoscroll is implemented, see: https://www.loom.com/share/331c6b1c2dea42ab918c9545cc2b0944

This is a very specific request that time should flow from left to right in this view.  Closing.
