### ISSUE TITLE
Courses-Rating Dialog

### ISSUE THREAD

**Issue by sjkadali** [open-learning-exchange/planet#6107]
In the Courses Rating dialog box, a Cancel button can also be added in case rating need not be updated.

![Screenshot from 2020-04-09 11-36-42](https://user-images.githubusercontent.com/39105848/78913387-f1291900-7a56-11ea-9483-74cc7f3cdf5e.png)

**Comment by paulbert** [comment]
See #3300 we removed the cancel button since the rating has already been submitted.  There isn't anything to "Cancel".

Closing.
