### ISSUE TITLE
ReportsDetail: End date non inclusive after change

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#6113]
filter end date to something older then select current date. Filter will not update current dates record.
If manually update end date to tomorrow then it shows today's count as well.

**Comment by paulbert** [comment]
Editing the title to be clearer.  It seems like the end date is not inclusive after changing its value.

I think the easiest change would be to make sure endDate is rounded to the end of the day in **ReportsDetailData**.
