### ISSUE TITLE
ReportsDetail: Show full member names for community on nation

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#6116]
### Current Behavior

We show full names in the bottom left of the **ReportsDetailComponent** for members but only when viewing the local data (community on community or nation on nation).

### Desired Behavior

Full names should be shown when looking at the data of a community on the nation as well.  These are stored in the `child_users` database.

Note that there may be slight differences in the visit counts by member.  Will make another issue for that.

_On Community_
![image](https://user-images.githubusercontent.com/9203229/79176539-810bf180-7dce-11ea-8e9d-1a1926fda34c.png)

_On Nation_
![image](https://user-images.githubusercontent.com/9203229/79176557-8cf7b380-7dce-11ea-9303-c02c5e610aec.png)

**Comment by paulbert** [comment]
Just saw the names show up on the nation.  Seems like data is fetched from `child_users`, but most of the time it does not update the view.

**Comment by sjkadali** [comment]
@lmmrssa / @paulbert  needed help with how to test nation in the dev environment. Could you please explain again? Thanks in advance!

**Comment by lmmrssa** [comment]
update  `/src/environment/environment.ts` and change couchAddress to 
`couchAddress: 'https://planet.dev.ole.org:2200`
