### ISSUE TITLE
Report detail date filter: start date shows current date while loading

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6118]
then after page is being loaded, start date is changed into least date range of the report.
i am not sure its because of slow internet or large amount of data.
![Screenshot (33)](https://user-images.githubusercontent.com/27276132/79176794-ec7eaf00-7e20-11ea-8f6d-8e65e08df1f2.png)
![Screenshot (34)](https://user-images.githubusercontent.com/27276132/79176795-ee487280-7e20-11ea-851e-d55e387d5634.png)

**Comment by paulbert** [comment]
Maybe we could hide the filters until there is a value for `minDate` in **ReportsDetailComponent**
