### ISSUE TITLE
Resources- Change Collections

### ISSUE THREAD

**Issue by sjkadali** [open-learning-exchange/planet#6133]
In Change Collections dialog box of Resources, Ok button should be enabled only when the collections check box is selected. A cancel button can be added in case no collections change is needed.

![Screenshot from 2020-04-15 11-55-35](https://user-images.githubusercontent.com/39105848/79359776-fc75bc00-7f10-11ea-8118-cac55e0f549d.png)

**Comment by paulbert** [comment]
It is valid to change the collections for a resource to none selected.  "Cancel" would be confusing because that implies no change rather than changing to none selected.  Closing.
