### ISSUE TITLE
Resources-Checkbox Selection

### ISSUE THREAD

**Issue by sjkadali** [open-learning-exchange/planet#6134]
In the resources/courses, shouldn't the selection be reset after performing the action i.e Change Collections?

![Screenshot from 2020-04-15 14-16-44](https://user-images.githubusercontent.com/39105848/79373249-56cc4800-7f24-11ea-8f1c-d58211fab2e9.png)

**Comment by lmmrssa** [comment]
We are maintaining selection for those which will be visible on the list. Once it is not seen on the list then selection for those resource will be reset.
