### ISSUE TITLE
Course Report allows to update course rating?

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6139]
since report is basically used to represent the summary of any community or nation. so does course report dialog should allow to update the rating?
![Screenshot_2020-04-16 Planet Learning](https://user-images.githubusercontent.com/27276132/79464288-9a54ae00-8019-11ea-9ef6-79621a56de88.png)

**Comment by lmmrssa** [comment]
It should be ok to give rating here.

**Comment by paulbert** [comment]
Yes I think this is OK.  Even if it isn't, I don't think this is high enough priority to work on it.
