### ISSUE TITLE
CoursesAdd: New course sometimes still cached after saving

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6157]
- create 3-4 course consequently.
- after creating 3rd or 4th course,  click on add course button
- value of last added course shows in the form.

If the course is already been added then it should not be shown in the Course add Form.
And another weird thing, it shows for 2-3 times only. try to cancel the form and again click to Add button. This time cache value disappears.

https://www.loom.com/share/afbf347489ff4befac62aeea29a6c4b8

**Comment by paulbert** [comment]
I saw this in the afternoon as well.  From what I can see, this only happens when a course is added without a test or survey
