### ISSUE TITLE
myHealth: units for major elements such as weight, temprature

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6158]
its better to have units of the examination's element such as 
- weight
- height
- temperature
- blood pressure
- pulse

both in  add form and view section.

**But for now can be initiated with default unit of all these in view section.**
![Screenshot_2020-04-21 Planet Learning(1)](https://user-images.githubusercontent.com/27276132/79816325-b7cfa200-83a2-11ea-9695-95521a8b0c89.png)
![Screenshot_2020-04-21 Planet Learning](https://user-images.githubusercontent.com/27276132/79816327-b900cf00-83a2-11ea-9275-8c74d439e85b.png)

**Comment by paulbert** [comment]
We should validate each of these fields to only accept numbers (except for Blood Pressure, see below).

**Units to add**
Temperature: degrees C
Pulse: BPM (beats per minute)
Blood Pressure: No additional label needed.  This should be two numbers separated by a **/**.  We should add validation to make sure it is in this format.
Height: cm
Weight: kg

Let's start with this and we can move on from there.  Need to find out what would be appropriate for Vision and Hearing.
