### ISSUE TITLE
Community: Deleting main story from show reply gives error.

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#6160]
1. Add new story.
2. Reply to that story.
3. Click on show reply.
4. Delete main story.

[Loom video](https://www.loom.com/share/5b505aa65a08483c99803ee5a014f328)

This will give console error and never-ending spinner.

**Comment by paulbert** [comment]
Before deleting the main story we should make sure the news list navigates up a level.  It's likely throwing errors because the main story no longer exists.
