### ISSUE TITLE
Ratio of image is not maintained on resource view dialog

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#6192]
We should have scroll on resource view. Right now if you open image on pages such as report or team resource list, then it squeeze the image as ratio of image is not maintained and stretched to fix dialog box

**Comment by paulbert** [comment]
I noticed this too.  Are you seeing this issue in the field?  I think this is something we should fix eventually, but if it's not showing up in the field then it's a little lower priority

**Comment by paulbert** [comment]
I did a little digging.  `object-fit` is supported by all of the browsers we would like to support, so let's try it:

https://stackoverflow.com/a/39039206

**Comment by paulbert** [comment]
I think we want `object-fit: contain` for our use.
