### ISSUE TITLE
myHealth: in case of self-examination, two links are shown for detail info

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6203]
it would be better to remove one of the link as both shows the same info or detail.
![Screenshot_2020-04-28 Planet Learning](https://user-images.githubusercontent.com/27276132/80436894-ed830680-891f-11ea-8ea2-b19c458d2626.png)

**Comment by paulbert** [comment]
This is intentional, the entire column can be clicked to view the details. Closing.
