### ISSUE TITLE
Community(new Story): admin is not getting any notification regarding new story post by members

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6205]
earlier admin was getting notification regarding new story added by other members.
![Screenshot_2020-04-28 Planet Learning(3)](https://user-images.githubusercontent.com/27276132/80439334-05f61f80-8926-11ea-87f9-01aad09d4051.png)

**Comment by RheuX** [comment]
![image](https://github.com/user-attachments/assets/b712913f-f5a9-4099-86c3-982454db1c1b)

**Comment by Mutugiii** [comment]
unable to replicate issue as well
