### ISSUE TITLE
Community: Reply to message not deleted.

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#6223]
1. Add a story.
2. Reply to that story.
3. Go to show replies.
4. Delete main story.

Main story is deleted but reply to that story is not deleted.
https://www.loom.com/share/e36c137933f4438f851ddeba9b0f9256

**Comment by lmmrssa** [comment]
Replies will be moved to parent that is how it was designed.

**Comment by paulbert** [comment]
Yes we don't want to allow a person to delete messages that other people wrote (which they could do if all replies were removed).  Closing.
