### ISSUE TITLE
Task: deadline meet task should not be editable

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6224]
deadline meet task is editable such that it allows to change all fields including date.
![Screenshot_2020-04-30 Planet Learning(2)](https://user-images.githubusercontent.com/27276132/80718414-d60f6d80-8b19-11ea-9873-85a785bd052a.png)
![Screenshot_2020-04-30 Planet Learning(1)](https://user-images.githubusercontent.com/27276132/80718418-d7409a80-8b19-11ea-9d4f-eeee26256535.png)

**Comment by lmmrssa** [comment]
if edit we should allow to be back date. Right now we are not allowing backdate.
