### ISSUE TITLE
Rating of resources - people "thumbnails" and scale not intuitive 

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/planet#624]
At least when having one rating of a resource, it looks like below. At least when having one rating this seems more confusing than clarifying. Why is there a woman to the right and a man to the left? What is the blue bar supposed to do?

<img width="213" alt="screen shot 2018-04-07 at 22 03 17" src="https://user-images.githubusercontent.com/16757941/38666770-f545f1b4-3e69-11e8-9981-f8aadb5a0f11.png">

**Comment by lmmrssa** [comment]
Having percent shown next to icon will make it more clear as in one of our proposed designs. @paulbert @dogi Shall we have it

**Comment by Tille88** [comment]
Aha, I see @paulbert 
That makes this very low priority, but if I was an analyst or maybe admin, I would consider that to perhaps be of interest. As a regular user I'm not certain how much interest I would have in the gender distribution though, but as I said, way more high priority things out there.

**Comment by paulbert** [comment]
I'm going to close this, as it's too low priority to keep up.  We may reasses this during a redesign.
