### ISSUE TITLE
DialogsForm: Rearrange buttons

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6240]
similar to other dialog form.
![Screenshot_2020-05-05 Planet Learning(1)](https://user-images.githubusercontent.com/27276132/81027870-0864f600-8e9f-11ea-91c1-f336d07ef88b.png)
![Screenshot_2020-05-05 Planet Learning](https://user-images.githubusercontent.com/27276132/81027875-0a2eb980-8e9f-11ea-850a-fd4e05047274.png)

**Comment by paulbert** [comment]
I'm going to reverse this issue.  The Community Services dialog is how we should be doing things, and we should update the Feedback dialog to match.

**Comment by paulbert** [comment]
To be clear:

- The **Submit** button should be on the right.  This matches the Material design spec.
- The **Cancel** button should be in white.  That way we save red for more destructive actions (mainly things that would delete from the database).
