### ISSUE TITLE
Team/Enterprise: Add members dialog fixes

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6244]
- Can header "name" be capitalized such as "Name"?
- Since **Full Name** can be empty most of the time, hence **Name** column can be placed at first?
- display "N/A" in case of empty Full Name

**Comment by paulbert** [comment]
I'm going to close this.  We should move towards a dialog that uses the reusable **UsersTableComponent** instead, but that is a longer project and it is too low of a priority to start now.
