### ISSUE TITLE
CoursesView & CoursesStepView: Open resource with dialog

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#6245]
Found that some media that open inside planet is not supported by browser on its own so lets wrap content with html tag when opening resource instead of calling empty tab

**Comment by paulbert** [comment]
Changing this to specifically encompass opening the resources in a dialog in the **CoursesView** and **CoursesStepView** components.

**Comment by paulbert** [comment]
Realized the dialog doesn't make sense in **CoursesStepViewComponent**.  There we should change the button text to `View Resource Details` and link to the resource page.

Use the dialog in **CoursesViewComponent**.
