### ISSUE TITLE
Course/Resource Dialog: consistency in close button

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6250]
In course dialog for teams, there is "Close" button where as for resource there is "Close" icon
1. it would be better to maintain consistency, either button or icon in both
2. Cross icon in resource dialog should be places a bit top right corner.
![Screenshot_2020-05-05 Planet Learning(4)](https://user-images.githubusercontent.com/27276132/81030804-dc9b3d80-8ea9-11ea-9d63-3134f553e0d9.png)
![Screenshot_2020-05-05 Planet Learning(3)](https://user-images.githubusercontent.com/27276132/81030806-ddcc6a80-8ea9-11ea-9dc0-912c95279821.png)

**Comment by paulbert** [comment]
Let's go with adding a **Close** button to **DialogsResourcesViewerComponent** and removing the X icon.

**Comment by Haoran-Hu** [comment]
@singharpita I don't see how you get o the page on the first screenshot

**Comment by robinGiri** [comment]
@Haoran-Hu you can follow following steps to replicate issue.
1. Go to **Teams**
2. Go to any one team on which you are member.
3. Go to **Resources** tab
4. Select any resource ( If you don"t have any resources don't forgot to add resources from **Add Resources**  button)

**Comment by lmmrssa** [comment]
First add resources to team page
