### ISSUE TITLE
my Health: Blood pressure field is saved even with warning

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6261]
- add any integer to blood pressure field
- there will be warning shown.
![Screenshot_2020-05-07 Planet Learning](https://user-images.githubusercontent.com/27276132/81300128-fb125c00-9096-11ea-80a5-3e8c3c8a181f.png)
- without correcting the field ,click on save
- examination get saved and show the above entered value
![Screenshot_2020-05-07 Planet Learning(1)](https://user-images.githubusercontent.com/27276132/81300180-0e252c00-9097-11ea-9d8e-6fe28235dee7.png)

**Comment by lmmrssa** [comment]
We should block if validation fails. But if field is empty we should allow submit as all fields are optional.

**Comment by lmmrssa** [comment]
@paulbert saw #6248 which is prompting user if value seems abnormal. shall we just implement that or also implement blocking if format is wrong.

**Comment by paulbert** [comment]
We should also block if validation fails.

**Comment by jessewashburn** [comment]
This has been fixed.
