### ISSUE TITLE
myHealth: validation should be shown for various fields

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6263]
![Screenshot_2020-05-07 Planet Learning](https://user-images.githubusercontent.com/27276132/81303286-3adb4280-909b-11ea-9eda-84b5c31bf049.png)
-Temperature **integer only**
- Pressure -**integer only**
- height **integer only**
-weight **integer only**

**Comment by paulbert** [comment]
@singharpita This is on Firefox, correct? I believe Chrome will not allow letters to be inputted at all.
