### ISSUE TITLE
Teams/View- Members Add Role

### ISSUE THREAD

**Issue by sjkadali** [open-learning-exchange/planet#6267]
In Teams/View on selecting members and clicking Add Role,  in the dialog box that opens the Submit button is enabled though there's no entry for Role field. Also on clicking Submit ,  "Role has been updated " message is shown.

![Screenshot from 2020-05-07 10-15-24](https://user-images.githubusercontent.com/39105848/81306220-39832900-904d-11ea-9cf0-3160f5386f3a.png)

**Comment by lmmrssa** [comment]
This is set such way so that if there is already role then you can clean the input and save it to remove role
