### ISSUE TITLE
Teams/View- Add Resources/Courses

### ISSUE THREAD

**Issue by sjkadali** [open-learning-exchange/planet#6268]
In Teams/View, on clicking Add Resources/Courses , in the dialog box that opens , the OK button is enabled though none of the Reources checkboxes is selected.

![Screenshot from 2020-05-07 10-28-37](https://user-images.githubusercontent.com/39105848/81306980-1e64e900-904e-11ea-9030-f8d0ffee5c73.png)

**Comment by lmmrssa** [comment]
We have something similar on member list page when adding member to team or sending survey to users.
This issue is in both course and resource selection.
