### ISSUE TITLE
Deleting all resources in library is very easy

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/planet#627]
It is just a single popup asking if you want to delete the courses (at least from admin account).

If clicked yes, I don't know how to get them back. At least perhaps have the resources to be deleted in the confirmation box?

**Comment by lmmrssa** [comment]
Course or resource same is there when we delete single entity. For multiple list will be longer so we haven't kept it there. But we will think about it. Thanks @Tille88

**Comment by paulbert** [comment]
Fixed #2019
