### ISSUE TITLE
Resources: Double horizantal scroll bar.

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#6280]
Go to **Resources**.
Select any resource.
Click **Change Collection**

(There is double scroll bar in the dialog if list is long like in planet.dev. This makes really hard to click on reset and ok button.)

![Screenshot from 2020-05-11 09-50-56](https://user-images.githubusercontent.com/45058288/81523563-e6bbb100-936d-11ea-9667-ee9dad7849db.png)

**Comment by RheuX** [comment]
Not sure, I don't have that many collections, so I only see one horizontal bar

**Comment by Mutugiii** [comment]
I believe this is happening when we have smaller screens

**Comment by jessewashburn** [comment]
I was never able to replicate this. Tried multiple browsers and every screen size with 30+ collections. 
[screen-recorder-mon-dec-16-2024-14-41-11.webm](https://github.com/user-attachments/assets/33611e63-780f-4fe2-8a00-633f11be71bb)

**Comment by RheuX** [comment]
still same, i couldnt replicate the main issues
