### ISSUE TITLE
myHealth: allowing 0 in Vitals fields

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6284]
since we are restricting number to be greater or equal to 0, it doesn't make sense to have value 0 in weight, height, pulse and pressure in it.

![Screenshot_2020-05-12 Planet Learning(2)](https://user-images.githubusercontent.com/27276132/81628212-be8c8a80-941f-11ea-9aec-ce07256a9489.png)

**Comment by paulbert** [comment]
We can move the min value for weight, height, pulse and temperature up to 1.  Let's leave Blood Pressure as is so we don't over complicate the regular expression.

#6248 will handle creating a warning if values seem like they are incorrect.

**Comment by paulbert** [comment]
`HealthEventComponent` is the component to change
