### ISSUE TITLE
myHealth: Emergency contact labels are confusing while updating details

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6285]
Updating details in myHealth shows labels as "Emergency Contact" for Emergency contact name
"Contact Type" for emergency contact type and "Contact" for Emergency Contact.
which gives impression of "Emergency Contact" field only as Emergency Contact field.

Can the placeholder be change or these three field can be framed in small box with main heading as Emergency Details?
![Screenshot_2020-05-12 Planet Learning(5)](https://user-images.githubusercontent.com/27276132/81629226-630fcc00-9422-11ea-8371-5c363dc5e44c.png)
![Screenshot_2020-05-12 Planet Learning(4)](https://user-images.githubusercontent.com/27276132/81629228-63a86280-9422-11ea-8ce3-2706e2cd7c3a.png)

**Comment by paulbert** [comment]
Let's have a subheader **Emergency Contact** above those fields and the placeholder Emergency Contact should change to Name.
