### ISSUE TITLE
myHealth-Update Details/Add Examination 

### ISSUE THREAD

**Issue by sjkadali** [open-learning-exchange/planet#6289]
In myHealth/Update Details and Add Examination, margin can be added to the buttons.

![Screenshot from 2020-05-12 12-33-29](https://user-images.githubusercontent.com/39105848/81721514-f90d1c00-944d-11ea-87d4-dce5eeb75407.png)

**Comment by paulbert** [comment]
There is a gap there created by a grid layout, but we can change this to be more consistent with other button groups by replacing all of the container classes with `action-buttons`.

**HealthEventComponent** and **HealthUpdateComponent** are the components to change.
