### ISSUE TITLE
Changing password procedure could inform user more of progress

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/planet#630]
When changing the user password, the following things I considered unexpected behaviour

-  ~~not required to insert old password~~ https://github.com/ole-vi/planet/issues/619
-  ~~no confirmation on password change~~ https://github.com/ole-vi/planet/issues/619
-  logs out the user after password change, without redirecting/routing to log in screen

**Comment by nirojdyola** [comment]
There is already raised issue https://github.com/ole-vi/planet/issues/619 which is similiar to the third point.

**Comment by nirojdyola** [comment]
For the first issue,
![screen shot 2018-04-16 at 12 50 08 pm](https://user-images.githubusercontent.com/7495421/38794425-9addbd46-4144-11e8-88dd-538b62f3f22d.png)

link : http://docs.couchdb.org/en/2.0.0/intro/security.html
@paulbert  do we really need to ask old password before changing it ? I don't find the same condition for couch db while testing(port:2200).

**Comment by Tille88** [comment]
Ah, sorry @nirojdyola, did not see that other issue, confirmation maybe included as well. Making those points strike-through for now. 

Last point... just custom I guess, depends on security level, will not be catastrophic for the users, but if several people share the same tablet, forgetting to log out would not be that rare I guess..
