### ISSUE TITLE
Reports Detail- Health

### ISSUE THREAD

**Issue by sjkadali** [open-learning-exchange/planet#6305]
In Report details/Health, the date filter not working properly.

![Screenshot from 2020-05-14 09-45-37](https://user-images.githubusercontent.com/39105848/81942250-e3bbfd00-95c7-11ea-964f-561d7391518b.png)

**Comment by lmmrssa** [comment]
related to #6307 Last date of the filter does not show up on health record

**Comment by paulbert** [comment]
@sjkadali I'll take this one.  We should refactor so we don't have to modify the end date every time we call this function.

**Comment by sjkadali** [comment]
ok, @paulbert. <https://github.com/paulbert> <https://github.com/paulbert>
