### ISSUE TITLE
MyHealth: Add Examination feature

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6308]
**Problem:**
Under the Condition and Treatment, diagnosis  should there be an "unknown" choice for a diagnosis? 

**Steps to reproduce the problem:**
Going to add examination tab under manager settings

**Screenshots:**

![Planet_Learning should have unknown checkbox-option](https://user-images.githubusercontent.com/40531136/81942947-ccc9da80-95c8-11ea-910b-39651c372c61.png)

![adding unknown choise in health](https://user-images.githubusercontent.com/40531136/81942986-d5baac00-95c8-11ea-9597-f7b77957acab.png)

**proposed solution:**

Add "unknown" to the list of choices

**Comment by lmmrssa** [comment]
We will most probably not add Unknown as that does not have much analysis value in report and also it is not that we just put one diagnosis, instead we allow many

**Comment by paulbert** [comment]
Closing.  I agree this would not be useful for analysis.
