### ISSUE TITLE
TeamsView: Can we add cancel button on event dialog?

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#6312]
Go to **Teams**
Go to **Calendar Tab**
Add Event
Then click on event

Dialog Pups up but it doesn't have cancel button. Can we add **Cancel** button there?

![Screenshot from 2020-05-14 20-10-18](https://user-images.githubusercontent.com/45058288/81946344-f9104600-961e-11ea-8e47-f4ab3f5df09c.png)

**Comment by lmmrssa** [comment]
We can add this to make consistency in our all dialog forms in general

**Comment by paulbert** [comment]
The button should say **Close** because there is no action from that dialog.
