### ISSUE TITLE
MyHealth: Vitals, hearing is not showing the whole input text

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6316]
**Problem:**
Under the Condition and Treatment under the Vitals section section. When the field for heaing is filled in, the beginning of the text is not visible.

**Steps to reproduce the problem:**
Going to [add examination](http://localhost:3000/myDashboard/myHealth/event;id=org.couchdb.user:chtelmko)

**Screenshots:**
![my health in hearing test does not show the beggining](https://user-images.githubusercontent.com/40531136/81950610-2682d280-95d2-11ea-9326-88b993001101.png)

**proposed solution:**

NA

**Comment by lmmrssa** [comment]
This is not an issue as text is longer than input field so it will be hidden
