### ISSUE TITLE
Reports Detail-Health doesn't show examinations of all members of the planet

### ISSUE THREAD

**Issue by sjkadali** [open-learning-exchange/planet#6326]
In Reports Detail/Helath,  examination details of all members of the planet are not shown.

![Screenshot from 2020-05-15 13-47-50](https://user-images.githubusercontent.com/39105848/82080799-37574500-96b3-11ea-84dc-ae9bc38b7577.png)

**Comment by lmmrssa** [comment]
looks like this issue is no longer valid

**Comment by paulbert** [comment]
I'm not sure what this is referring to.  @sjkadali Could you give a little more detail?

**Comment by sjkadali** [comment]
Two members of the community had examination details added. But in the health report , patients seen was shown as 1. I checked again now and it's showing the correct number of patients seen. So closing this issue.
