### ISSUE TITLE
Snackbars in UI: behaviour seems not to be in line with expected urgency of message

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/planet#633]
Course deleted snackbar is shown much longer than I would expect. 
This may be useful functionality for some cases, but maybe create different urgency levels of snackbars and color code/make them disappear/be animated according to urgency level could perhaps be useful. 
Having deleted course snackbar be open and maybe not even seen until way later, could confuse more than help.

<img width="251" alt="screen shot 2018-04-07 at 22 19 13" src="https://user-images.githubusercontent.com/16757941/38669697-227ced48-3e71-11e8-90d8-5d72f20edcee.png">

**Comment by BasnetSamriddhi** [comment]
@Tille88  If you look into the code there are two snackbars created, one that will show up only for few seconds where as the other one has to be removed manually by the user. The one you have mentioned is the later one and once you click the cross ( X ) it will go away.

**Comment by nirojdyola** [comment]
Yes that's make a sense. We need to put some duration . @BasnetSamriddhi , Please check it once .

**Comment by lmmrssa** [comment]
There are already other similar issues #787 so closing it
