### ISSUE TITLE
Health Report: Hide detail if no exams in date range

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6339]
right now its blank/empty
![Screenshot_2020-05-19 Planet Learning(3)](https://user-images.githubusercontent.com/27276132/82275641-fb69fb80-99a2-11ea-8373-5f6b431a6c73.png)

**Comment by paulbert** [comment]
This is not "default value", but when there were 0 examinations during the dates selected.

If this is the case let's hide everything from **Diagnoses** down.
