### ISSUE TITLE
myHealth (Examination): warning message UI/UX fixes

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6341]
- In alert warning message " Click cancel to fix or click ok to submit.", OK and Cancel should be made **BOLD** or **Quoted** 

![Screenshot_2020-05-19 Planet Learning(5)](https://user-images.githubusercontent.com/27276132/82276492-25242200-99a5-11ea-947d-21f2c97f7252.png)

**Comment by paulbert** [comment]
The text should be capitalized as well

**Cancel** and **OK**
