### ISSUE TITLE
News: Don't add notification when replying to own message

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#6342]
When replying for your own message, we still get notification. It should not send notification if user reply to own message (story)

**Comment by Haoran-Hu** [comment]
@lmmrssa @paulbert funtion **getNotifications()** in both **HomeComponent** and **NotificationsComponent** have
`
if (this.userService.get().isUserAdmin) {
      userFilter.push({ 'user': 'SYSTEM' });
    }
`

not quite sure what it does

**Comment by lmmrssa** [comment]
Issue is related to creating notification. you should not change on get notification
