### ISSUE TITLE
Courses: sorting.  selecting courses by title (checkbox) 

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6343]
Problem:
When you have some courses already selected (by title) the checkbox turns into a minus sign. 
If you click on the checkbox again it selects the remaining courses(that were not selected).
Should it remove the selected courses instead?

![sorting courses the minus button by title](https://user-images.githubusercontent.com/40531136/82277002-cf278e00-9954-11ea-8b0c-21c36ead5e0a.png)
![sorting courses the minus button by title adds courses](https://user-images.githubusercontent.com/40531136/82277265-6b519500-9955-11ea-9996-90f7a0fbe716.png)

**Comment by paulbert** [comment]
This behavior is OK and not something we'd change at the moment.  Closing.
