### ISSUE TITLE
Dialog "Submit" and "Cancel" button consistency issues

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6344]
On the _Community_ tab, the 4 subtabs (News, Community Leaders, Services, Finances) have a dialog pop up to input data and the order of the buttons on the dialog is "Cancel" and "Submit".

![Annotation 2020-05-18 212150](https://user-images.githubusercontent.com/54686871/82277656-fa6fa480-9977-11ea-8cff-bcb397979bcd.png)

While on most other places in the app the order is "Submit" (or some other action), then "Cancel".

![Annotation 2020-05-18 212215](https://user-images.githubusercontent.com/54686871/82277752-3276e780-9978-11ea-8a5c-878a6489fdc5.png)

What is the preferred order of the buttons?

**Comment by paulbert** [comment]
Good question.

The dialog is good and follows Material guidelines.

I'm not sure about the second one.  My thought was to have submit aligned with the outer edge of where it's placed, but I haven't had the time to look at what Material says about this.

[Material Design](https://www.material.io)
