### ISSUE TITLE
Dialogs: Change Button UI

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6347]
The color of **Cancel**  buttons is red for some dialogs, which is not necessary.

Choose a team, click **Add member**, **Add Resources**, **Add Courses** and **Delete** to see.

# Screenshots
![Screen Shot 2020-05-18 at 10 40 13 PM](https://user-images.githubusercontent.com/57075986/82280020-e74edb80-995b-11ea-8f6d-22e9bd86d3e9.png)
![Screen Shot 2020-05-18 at 10 40 05 PM](https://user-images.githubusercontent.com/57075986/82280030-f170da00-995b-11ea-886d-5a5b9072c158.png)
![Screen Shot 2020-05-18 at 10 40 26 PM](https://user-images.githubusercontent.com/57075986/82280034-f46bca80-995b-11ea-8f4c-fe88abc0feb7.png)
![Screen Shot 2020-05-18 at 10 38 42 PM](https://user-images.githubusercontent.com/57075986/82280055-03eb1380-995c-11ea-9e58-ab07864301be.png)

**Comment by paulbert** [comment]
The components which need to be changed:

- **DialogsListComponent**
- **DialogsPromptComponent**
- **DialogsAddCoursesComponent**
- **DialogsAddResourcesComponent**

Cancel should be white, OK should be blue, and OK should be on the right.
