### ISSUE TITLE
Health: Allow examination without vitals?

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#6351]
Allow an examination to be added without input of vitals? It allows an examination to be submitted with just a condition.
![olehealthsubmit](https://user-images.githubusercontent.com/48474421/82302937-f5841280-99c2-11ea-974b-b5a15431a7d0.png)
![olehealthpopup](https://user-images.githubusercontent.com/48474421/82302934-f5841280-99c2-11ea-8383-eb5641bf9a79.png)

**Comment by lmmrssa** [comment]
Yes that is how it is created right now so we can create examination if any of the detail is filled up.
