### ISSUE TITLE
Resources: Check unique is slow when RPi having power issues

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#6353]
Right now we are seeing on field that when rpi is 3B+ and having some low power issue causing pi to be slower, they are not able to upload resource because title validation timeout.
So may be instead of doing couch search if we use stateservice we used to speed up resource loading can help to do quick unique search

**Comment by paulbert** [comment]
I think having an index for that `_find` or a view would be better.

Running the full `stateService` flow, especially for resources, after every time the text changes could cause some slowing on the device.
