### ISSUE TITLE
myHealth: validation inconsistency

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6365]
entering number fields with pattern "**30.**" is not throwing any error or validation warning.
![Screenshot_2020-05-21 Planet Learning(2)](https://user-images.githubusercontent.com/27276132/82568272-4865f180-9b9e-11ea-9618-2d773b600f70.png)

**Comment by lmmrssa** [comment]
Yes this is little confusing for user. It saves and displays correct when you just put `.` at end by converting it to whole number when saving

**Comment by paulbert** [comment]
@jsschf I'm going to move you off this issue.  The validation for this is already a bit complex/hacky and this could make it even more so.

Need to do a bit more due diligence to see if this would be valuable.

**Comment by paulbert** [comment]
#6380 also handles this by rounding the `.` away

**Comment by paulbert** [comment]
Closed too soon, the decimal is still visible despite the rounding.

**Comment by RheuX** [comment]
couldn't replicate the issue, the `.` dissapear without any decimal places
