### ISSUE TITLE
Error on health member list page

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#6367]
There is javascript error on health page
![image](https://user-images.githubusercontent.com/2909490/82569366-ddb5b580-9b9f-11ea-9140-f408521b9290.png)
This cause some loading image to show on health list page for examination date
![image](https://user-images.githubusercontent.com/2909490/82569397-ead2a480-9b9f-11ea-8e4f-de57d805a5c9.png)

**Comment by paulbert** [comment]
Duplicate of #5284

**Comment by paulbert** [comment]
@singharpita Reassigning since I think this is fixed with #6412
