### ISSUE TITLE
myHealth: Update details screen, should there be a pop- up warning for consistancy?

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6368]
Should there be a pop- up warning  to show that they are required to enter language and birthday?
![warning edit detail 1](https://user-images.githubusercontent.com/40531136/82569616-7ae7fe00-9b4e-11ea-82d6-90f9ea4bf3c7.png)

![warning edit detail](https://user-images.githubusercontent.com/40531136/82569446-43795180-9b4e-11ea-9163-7a65ca31ab4a.png)

**Comment by lmmrssa** [comment]
This is not something we want to implement, as we do not allow user to submit when required fields are not filled up. And red highlight of the input field denotes that field has error.
We have popup only on examination page as we allow them to save even with odd values but we want to warn them that value might not be correct.

**Comment by paulbert** [comment]
Yes, no need for extra popups with normal form validation that does not allow the form to be submitted if the values do not pass
