### ISSUE TITLE
User list dialog search by Full name

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#6371]
Right now on user list dialog we can only search by username. We should also search by name of user.

**Comment by lmmrssa** [comment]
Also we can change label name to username as there is `Full name` and `name` which is confusing

**Comment by paulbert** [comment]
Let's just change the search.

We should move away from this component for selection.  It would be better to have something like `DialogsAddCoursesComponent` for users since that dialog is more fully featured.
