### ISSUE TITLE
TeamsView: Add cancel pending request.

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#6372]
1. Go to **Team**
2. Create new team.
3. Login in as another user.
4. Go to team and click **Request to join** .

For the users who are not added to a team they can **Request to join** that team. But once they requested to join that team they can't cancel that request. Can we add a button to cancel **Request pending**?

**Comment by lmmrssa** [comment]
I don't think this is something we will work on. Because if you are added you can always leave the team.
