### ISSUE TITLE
ourNews: Delete news story, should the cancel button be blue and the ok button be red?

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6373]
When you click on delete button, should the cancel button be blue and the Ok button be red, for consistency?

![news cancel button be blue and ok be red](https://user-images.githubusercontent.com/40531136/82573154-6a865200-9b53-11ea-98b6-2dc7f4a0cb8f.png)

**Comment by lmmrssa** [comment]
Lets try to keep color consistent with the design. So we will have OK as blue color
