### ISSUE TITLE
Promoting an inactive account activates it

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#6374]
In the manager setting, 
1. view all members.
2. Deactivate account.
3. Click promote.
4. Route to another location.
5. Route back to members page.

An inactive account is activated after you try to promote(At first causes error). When you route to another page & route back, you find the account is activated

[Link](https://drive.google.com/file/d/1XzuOpsTglteuQXNWY0vCUEq1V8Kkk6u-/preview) to preview

**Comment by lmmrssa** [comment]
This is intended. Couchdb itself works on role permission and once there is some role user can login and do certain task.
