### ISSUE TITLE
myHealth-Add Examination

### ISSUE THREAD

**Issue by sjkadali** [open-learning-exchange/planet#6378]
Option to enter allergies can be added to Add Examination

**Comment by paulbert** [comment]
@sjkadali **Allergies** is an option as seen below.  Did you have a suggestion to change this?

![image](https://user-images.githubusercontent.com/9203229/82693720-ff5e7d80-9c2f-11ea-9f2a-830e1636b336.png)

**Comment by sjkadali** [comment]
@paulbert, would it be better to list allergies under 'Condition and
Treatment' ?

**Comment by sjkadali** [comment]
Would it be better to list the allergies under Diagnosis with a checkbox to select.

**Comment by paulbert** [comment]
@sjkadali Not at this stage.  The benefit of the diagnosis checkboxes is for ease of reporting, and allergies is not something we need currently for aggregated reports.

Closing.
