### ISSUE TITLE
myHealth: update profile allows number input for birthplace

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6389]
Should the birthplace field under update profile allow a number or a text input?

![allows number for birthplace_Planet_Learning](https://user-images.githubusercontent.com/40531136/82851563-2d60ed80-9ece-11ea-8f6a-33313b800f39.png)

**Comment by lmmrssa** [comment]
it should be ok as address can have some numbers as well

**Comment by paulbert** [comment]
Address or postal/zip code could have numbers, and we're not going to disallow those as answers at this stage.  Closing
