### ISSUE TITLE
myHealth: update profile, the birthplace is not being updated

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6390]
When you go to update profile under myhealth, type something for the birthplace and hit submit. The birthplace says N/A on the main page.

![the birthplace isnt being updated birthplace_Planet_Learning](https://user-images.githubusercontent.com/40531136/82851801-035bfb00-9ecf-11ea-80bb-3cc6de957964.png)

**Comment by lmmrssa** [comment]
seems to work after logout login and updating

**Comment by paulbert** [comment]
Also seems to only not update the first time changing.

**Comment by paulbert** [comment]
Confirmed it's an issue if the `birthplace` field did not exist before adding it to the member's profile
