### ISSUE TITLE
Health Report: Self Examination and age UI fixes

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6392]
- Self Examination column displays TRUE/FALSE value. it will be good to Convert TRUE/FALSE with YES/NO.
- Age column displays  **null** in case no age is defined. It would be good to show it as **N/A**

<img width="535" alt="Capture" src="https://user-images.githubusercontent.com/27276132/82853023-31b7f580-9f24-11ea-8ea8-d52b875580e2.PNG">

**Comment by paulbert** [comment]
I don't think these changes make these reports much clearer, if at all.  Not worth the time at this stage.  Closing.
