### ISSUE TITLE
Health Report: Blood Pressure (bp) shows wrong value

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6393]
bp shows Date value rather than value in format "/"
<img width="275" alt="Capture" src="https://user-images.githubusercontent.com/27276132/82853819-6cbb2880-9f26-11ea-8f54-86355cddccdb.PNG">

**Comment by paulbert** [comment]
This is because the value looks like a date and Excel converts it to one when importing.  Since the expected values for Blood Pressure shouldn't be low enough to look like a date in normal use, I'm going to close this.
