### ISSUE TITLE
Courses: Course "How to use course" the test icon 

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6394]
When you go to the course on "How to use course" and click on the test icon. Should there be a "take the test" button?

Or is the user supposed to use the "preview" button or the "view step" button, to navigate?

![take test  dropdown Planet_Learning](https://user-images.githubusercontent.com/40531136/82854092-6781bd80-9ed5-11ea-992d-e42b2ea25c88.png)

**Comment by paulbert** [comment]
I see that this could be confusing.  A course has to be "joined" before you are able to take a test, so the **Take Test** button will not appear until then.
