### ISSUE TITLE
Reports (Summary): Date format enhancement

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6397]
right now Summary report shows Date in format "MM-YY".
Can Year be converted into format YYYY? its kind of confusing at first glance wether that two digit field is date or year.
<img width="233" alt="Capture" src="https://user-images.githubusercontent.com/27276132/82854583-92e1c800-9f28-11ea-8e34-c08353d58509.PNG">

**Comment by paulbert** [comment]
The value is getting converted into a date by Excel and shown in Excel's date format.

We already send in the full year with the CSV.  We could try `month: 'long'` in `monthDataLabels` in `reports.utils.ts`.  If that doesn't work then I don't think it's worth the time to come up with another solution since we don't have control over what Excel does with the value.

**Comment by singharpita** [comment]
- tried by changing "month:long" , **no change**
shows same as above mentioned. in this case Excel treated date as **custom** format.
- tried by keeping this as option { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
shows full value. in this case Excel treated date as **general** format

seems not possible since its handled by Excel.

**Comment by robinGiri** [comment]
I haven't change anything with code. I exported Summary Report. My system is Ubuntu 20.04 and I use **LibreOffice Calc**. It has year in  format YYYY.

![Screenshot from 2020-05-28 15-46-18](https://user-images.githubusercontent.com/45058288/83128557-50241980-a0fb-11ea-90d5-5b7c2737dd97.png)


### So I think it depends on which machine we are on.

**Comment by paulbert** [comment]
Not the machine, but the program used to open the CSV.  Excel converts those values into a "Date" format, but LibreOffice keeps it as a string.

@dogi @lmmrssa Remind me which spreadsheet program we are telling them to use in the field?  I remember it's not Excel.  If it's LibreOffice we can just close this, I think.
