### ISSUE TITLE
Courses: Redundant Preview test drop down

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6398]
Unless there are sometimes other things in the dropdown after clicking _Preview_, the dropdown seems unnecessary.

![Annotation 2020-05-25 212801](https://user-images.githubusercontent.com/54686871/82854645-99f0e200-9ef8-11ea-841b-c3e4f439d6d7.png)

**Comment by paulbert** [comment]
This button should have different actions depending on what is attached to the course step:

1. If a test and a survey are there the menu should open with the two options.
2. If only one of a test or a survey is there the button should click through to previewing it.

**Comment by paulbert** [comment]
The preview button can show up in **CoursesViewComponent** and **CoursesStepViewComponent**
