### ISSUE TITLE
myHealth: Pulse doesn't follow the max threshold

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6399]
In self examination you can set the pulse to 66666666666666666666 and save the examination without warning.

Also it shows wrong value in the examinations tab.

![the blood pressure minimum myHealth](https://user-images.githubusercontent.com/40531136/82854942-e4159b80-9ed7-11ea-895f-b7e285c245f0.png)

![my health pulse does not follow the maximum](https://user-images.githubusercontent.com/40531136/82854922-d9f39d00-9ed7-11ea-99bf-3f2b09e4c1e2.png)

**Comment by paulbert** [comment]
It rounds the value to 0, which in the rounding process is converted into an empty string.

I'm going to roll this up with #6391
