### ISSUE TITLE
Update Details: required fields not working properly

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6415]
In **myHealth** section, select **Update Details**, **Language** and **Birthdate** are required, but users can exit the form without filling up those required fields. 

### Screenshots
![Screen Shot 2020-05-28 at 9 31 05 AM](https://user-images.githubusercontent.com/57075986/83148029-7085b100-a0c6-11ea-976b-f93a3db7bd70.png)
![Screen Shot 2020-05-28 at 9 31 16 AM](https://user-images.githubusercontent.com/57075986/83148042-75e2fb80-a0c6-11ea-8639-a8158c5e724d.png)

**Comment by lmmrssa** [comment]
by exit do you mean cancel? Yes cancel should be ok only if its able to submit then that is problem

**Comment by Haoran-Hu** [comment]
@lmmrssa Yes, I mean cancel. It makes sense. However, maybe the users should be asked to fill up all the required fields when creating the account.
