### ISSUE TITLE
Add Examination: More restrictions needed

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6416]
When a user type in unrealistic data for vitals in **Add Examination**, there should be warnings. 

### Screenshots
![Screen Shot 2020-05-28 at 9 42 06 AM](https://user-images.githubusercontent.com/57075986/83149250-e2122f00-a0c7-11ea-8dcc-388252a86718.png)

**Comment by lmmrssa** [comment]
there is already warning for this. Have you check if you are on latest version and reset your cache?

**Comment by Haoran-Hu** [comment]
@lmmrssa It is the latest version, I do not see the warnings.

**Comment by lmmrssa** [comment]
It was cache issue so closing it
