### ISSUE TITLE
myHealth: Warning dialog message enhancement

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6417]
It would be good if action Cancel and Ok can be Bold and Uppercase
"Click cancel to fix or click ok to submit"
![Screenshot_2020-05-28 Planet Learning(1)](https://user-images.githubusercontent.com/27276132/83149648-10b8f580-a11a-11ea-80d9-425834781aff.png)

**Comment by paulbert** [comment]
Duplicate of #6341. Closing.
