### ISSUE TITLE
Surveys: No planetCode in pdf exported.

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#6418]
Go to Manager Settings
Go to Surveys
Export any survey in pdf.

( There is no planetCode in exported pdf.  Should we add planetCode or Planet name or community so that we could know where its coming from? in  CSV export there is planetCode from which we can know where its coming from. )

### pdf survey export
![Screenshot from 2020-05-28 19-19-25](https://user-images.githubusercontent.com/45058288/83148278-7b693180-a118-11ea-9059-7342b5fff96f.png)

### CSV survey export
![Screenshot from 2020-05-28 19-33-34](https://user-images.githubusercontent.com/45058288/83149820-4827a200-a11a-11ea-8bc3-5a0b38901c47.png)

**Comment by lmmrssa** [comment]
csv is for analysis or generate reports but pdf is just for view so we might not require more of those information

**Comment by paulbert** [comment]
I think having the Planet Name could be useful in the future, but right now surveys are only taken by people on one Planet, anyway.
