### ISSUE TITLE
Courses: Creating a course has confusing set up

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6419]
**Steps to replicate the problem:**
Clicking the "Add" icon on the courses menu, you are taken to a screen that has course title,information and some other buttons.
Clicking on "Add Step" button (this creates "step 1" to the right).

Thing that may be confusing:

1. There are two "Add Step" buttons that do the same thing.
2.  When you click the back arrow (in the left corner ) you end up back at the courses menu. Once you click on "Add" icon, the course already has step one show up. Even though you didn't click save. 
 It doesn't show up only if you have clicked cancel to exit out of the course menu.
3. You only need to fill in the "title" and  "description" info when you click "submit" or  "Add Step" buttons, not when editing steps or using back arrows.
 

![create a step in course](https://user-images.githubusercontent.com/40531136/83141732-2ef10800-a0be-11ea-99ad-36876ad7bbb5.png)
ck, it will direct you to myDashboard

![courses already has the first step](https://user-images.githubusercontent.com/40531136/83144880-f8b58780-a0c1-11ea-8d9e-a116b74ad4b2.png)

![courses in the second step](https://user-images.githubusercontent.com/40531136/83144445-5a292680-a0c1-11ea-8f2d-12eee1cf6893.png)

**Comment by lmmrssa** [comment]
all of this is intended. we keep copy of course locally so that even if it is not saved for long time it remains there. Usually when you are working on very long course as planet will logout by that time and you might end losing data.
back arrow never save so there is no validation. validation are done when you save.
