### ISSUE TITLE
myHealth: round off inconsistency for Temperature, height and weight field

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6420]
- try to enter value less than 1 i.e 0.4 or 0.7 
- press "tab"
- only warning message shown , value is not round off to nearby value
**NOTE: this behavior is only shown for value less than 1. otherwise working fine**
![Screenshot_2020-05-28 Planet Learning(2)](https://user-images.githubusercontent.com/27276132/83151069-cdf81d00-a11b-11ea-86ed-326bb1434717.png)

**Comment by lmmrssa** [comment]
rounding rounds to nearest 1 value decimal so it looks ok. If you put 0.95 or higher it will roundoff to nearest decimal 1
