### ISSUE TITLE
Courses/Enrolled-Show enroll date

### ISSUE THREAD

**Issue by sjkadali** [open-learning-exchange/planet#6423]
In Courses/Enrolled list, enroll date can also be included.
![Screenshot from 2020-05-28 10-09-39](https://user-images.githubusercontent.com/39105848/83152566-f22c0d80-a0cb-11ea-8715-90140d0d0e1b.png)

**Comment by paulbert** [comment]
The **Date Started** should be very similar to **Enroll Date** in normal use.  Closing.
