### ISSUE TITLE
myHealth: should survey be saved if no vitals are entered?

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6424]
Should myHealth survey require vitals input?

![my health no vitals](https://user-images.githubusercontent.com/40531136/83152717-1f78bb80-a0cc-11ea-81e0-057118f9850a.png)
![should health surver require vitals input](https://user-images.githubusercontent.com/40531136/83152722-21427f00-a0cc-11ea-913c-0f8bad1f3e77.png)

**Comment by lmmrssa** [comment]
This is not something we will be doing right now. As its not always a case that vitals are taken.

**Comment by lmmrssa** [comment]
Duplicate of #6351
