### ISSUE TITLE
Achievements: "My certifications" formatting

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6427]
![Annotation 2020-05-28 092522](https://user-images.githubusercontent.com/54686871/83154059-3381e480-a0ef-11ea-8d0d-58d6081ae6df.png)

**Comment by lmmrssa** [comment]
we might be able to improve this view but right now we are not focusing on achievments so will keep it on hold

**Comment by paulbert** [comment]
@jsschf Do you have some specific improvements in mind?

**Comment by jsschf** [comment]
@paulbert I didn't realize it was supposed to be a side-by-side list until @lmmrssa showed me today during the meeting. I thought it was supposed to be a single centered field like the content above it.

As far as improvements goes for both the _My Certifications_ and _My Achievements_ UI on this page, maybe something where the content is always centered, but based off the number of items the layout changes dynamically. Kind of like this picture:
![Annotation 2020-05-28 222812](https://user-images.githubusercontent.com/54686871/83217992-89d93c80-a15c-11ea-85e8-baa4b7dd70a1.png)

Where if there's only one item then the layout would look like the first row, and if there's two items then the second row, and so on.

However, I'm not sure how easy it would be to implement it but I could look into it if you want me to.
