### ISSUE TITLE
Cancel button style

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6434]
In **Library** and **Courses**, when a user try to manage a resource or a course. Is the color of the **Cancel** button supposed to be red?

### Screenshots
![Screen Shot 2020-05-28 at 11 04 34 AM](https://user-images.githubusercontent.com/57075986/83158927-69b16b00-a0d3-11ea-9edd-f6e00bc6d8fb.png)
![Screen Shot 2020-05-28 at 11 04 57 AM](https://user-images.githubusercontent.com/57075986/83158937-6cac5b80-a0d3-11ea-8b4d-6a41a56713ca.png)

**Comment by lmmrssa** [comment]
yes this is what we had in our design from begining
