### ISSUE TITLE
Surveys: PDF export has extra page between responses

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#6446]
### Current Behavior

When exporting a survey as a PDF with answers or both answers and questions selected, there is a full blank page between each response

### Desired Behavior

There should be a page break so each response begins on a new page, but the fully blank page should not be there.

![image](https://user-images.githubusercontent.com/9203229/83469489-d7e88b80-a44d-11ea-825c-7e1af4493453.png)

**Comment by paulbert** [comment]
This is handled in **SubmissionsService** in `getPDFAnswerText` and the other 3 related functions below.

**Comment by singharpita** [comment]
could not see this happening could it be related to some browser or operating system? This is what I see for same survey from dev.
[Survey - Tartanka Har Har ee Ganacsiga - Har Har Enterprise Challenge Guidelines (1).pdf](https://github.com/open-learning-exchange/planet/files/4723347/Survey.-.Tartanka.Har.Har.ee.Ganacsiga.-.Har.Har.Enterprise.Challenge.Guidelines.1.pdf)

**Comment by Mutugiii** [comment]
unable to replicate
