### ISSUE TITLE
DialogsAddTable: Member table should not include "Action"

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#6447]
### Current Behavior

There are three UI changes for this dialog:
1. The dialog for adding a member includes the "Action" column with one button per row to "View Profile".  The button fortunately does not perform an action, but it should be removed regardless.
2. The profile image has a pointer icon when the cursor hovers over which should not be there
3. A user can remove roles from another member from this view.

### Desired Behavior

1. The "Action" column should not be there in the dialog.
2. The cursor should remain default on the image.
3. No roles should be changed in this view.

Note that dialog is **DialogsAddTableComponent** with `mode` set to `'users'`.  That has **UsersComponent** as a child which in turn has **UsersTableComponent** as a child.

![image](https://user-images.githubusercontent.com/9203229/83471140-ea64c400-a451-11ea-9b66-d90501596996.png)

**Comment by lmmrssa** [comment]
Also right now role can be removed on dialog. It should only be view only

**Comment by lmmrssa** [comment]
clicking on profile image or view profile button is disabled so need to make atleast one clickable and open in new tab similar to resources/courses

**Comment by paulbert** [comment]
Nothing should happen when clicking except for selection at this stage.

So the two additional tasks to add are (both specific to the dialog):
1. Remove the `cursor-pointer` class from the profile image
2. Remove the ability to remove a role
