### ISSUE TITLE
Survey Report(PDF/excel): undefined should be handled 

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6448]
- Create a survey with only one question in it.
- record that survey
- Now edit the survey such that add another question in the survey
- Click on PDF export or Excel export
- SInce no answer or survey is saved for newly added question, this result in "undefined" for new question.
It should replaced by blank or N/A
![Screenshot_2020-06-02 Survey - Survey with no course-1 pdf](https://user-images.githubusercontent.com/27276132/83470425-df398480-a4a1-11ea-9e5e-c340f6afe82e.png)
<img width="451" alt="Capture" src="https://user-images.githubusercontent.com/27276132/83470446-e5c7fc00-a4a1-11ea-8b3f-e2242c19bc14.PNG">

**Comment by paulbert** [comment]
This will be handled by #5091.  Closing.
