### ISSUE TITLE
Dialog: cancel button needed

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6449]
After a user finishes rating a resource or a course, there would be a dialog showing up asking for comments, which has no **Cancel** button. 

### Screenshot
![Screen Shot 2020-06-01 at 9 37 30 PM](https://user-images.githubusercontent.com/57075986/83470423-25fe8e80-a450-11ea-8fc5-3f430d313374.png)

Adding a **Cancel** button might be better if a user does not want to add any comments and simply want to exit.

**Comment by paulbert** [comment]
@lmmrssa is correct.  Closing.
