### ISSUE TITLE
Courses: Rating snackbar message

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6453]
When rating a course, the dialog pops up to ask if the user wants to add additional comments with their rating. However, the snackbar at the bottom pops up at the same time as the dialog, saying "Thank you, your rating is submitted" before the user actually submits the rating.
![Annotation 2020-06-01 211227](https://user-images.githubusercontent.com/54686871/83472470-d8494c80-a476-11ea-800f-9db7901429df.png)

**Comment by paulbert** [comment]
The rating has been submitted at that point, the dialog allows you to change it and/or add a comment.
