### ISSUE TITLE
Survey: preview, the submit answer button

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6454]
from managers setting:
click on surveys 
click on 'update survey'
click on 'preview survey'
fill in an answer for each question and click 'submit answer'

On the last question the 'submit answer' button is blue, but cannot be clicked. The 'finish test' button is greyed out, your only option is to 'close  preview'.
if you use the back error buttons your answers are not saved.

**question**
why is the 'submit answer' button available to be clicked if it is not functional in the preview?

![submit answer in the preview survey is not working](https://user-images.githubusercontent.com/40531136/83473549-dae87980-a457-11ea-9e04-baae0f1ae237.png)

**Comment by paulbert** [comment]
We want the preview to mimic as closely as possible what the person would see while taking the survey.

Unfortunately, the button is not working the same as it would when the survey is taken.

This already has a couple of issues #5957 and #5954, so closing.
