### ISSUE TITLE
No pop up warnings for Vision and Hearing

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6456]
In **myHealth**, **Add Examination**, when a users type unrealistic data for **Vision** and **Hearing**, there is no pop-up warnings like other vitals do. 

![Screen Shot 2020-06-01 at 10 36 19 PM](https://user-images.githubusercontent.com/57075986/83473766-564a2b00-a458-11ea-88cf-f02a85816128.png)

**Comment by paulbert** [comment]
This is part of #6315.  Closing.
