### ISSUE TITLE
myHealth: NaN allows form submit

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6457]
In the Height or Weight fields if you enter I think over 20 digits the warning message pops up saying "NaN", but still allows you to submit. Then on past examinations the field is empty.
![Annotation 2020-06-01 211324735](https://user-images.githubusercontent.com/54686871/83474508-bb634800-a47b-11ea-82ac-45cbf077bb0b.png)
![Annotation 2020-06-01 214819](https://user-images.githubusercontent.com/54686871/83474514-bd2d0b80-a47b-11ea-85ca-877a361fea30.png)

**Comment by paulbert** [comment]
Good catch.  The rounding function must be returning `NaN` when the number is too large.

**Comment by paulbert** [comment]
This can be found in **PlanetRoundDirective**
