### ISSUE TITLE
Survey: Return button should say "Save & Return"

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6458]
Click  'add survey"
Don't fill anything in and then click the 'return' button  "

it doesn't let you return to main survey page(error that some required fields are missing).
is this intended behavior? 
![unable to return to main survey page](https://user-images.githubusercontent.com/40531136/83474852-028d1100-a45b-11ea-80f1-89fa56cefde0.png)

**Comment by paulbert** [comment]
This button should say **Save & Return** so it's clear the action includes saving.  If the form is invalid the save will be blocked.
