### ISSUE TITLE
ReportsHealth: Add "Week Of" label to diagnosis chart

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6478]
Added Covid-19 in todays date. but the end date still shows 30 may.

![Screenshot_2020-06-04 Planet Learning](https://user-images.githubusercontent.com/27276132/83764410-a106b580-a699-11ea-9b82-0ac60ce04d98.png)

**Comment by lmmrssa** [comment]
Data is reflected based on filter date but yes graph label is not updating.

**Comment by paulbert** [comment]
Updating the name.  We can add an x-axis label "Week Of".
