### ISSUE TITLE
Use different assets name using hash every build

### ISSUE THREAD

**Issue by empeje** [open-learning-exchange/planet#648]
These are the assets inside our production Docker image artifact

```
/usr/share/nginx/html # ls
0.55d193bdb36065d2c7a1.chunk.js
1.8460076ce4f8875f27bf.chunk.js
2.95dd4876fefa7dc180ce.chunk.js
3.5245c8d5a1170e4df920.chunk.js
3rdpartylicenses.txt
4.c038698167124985327c.chunk.js
5.893e4a03bb6b36ea2e5f.chunk.js
6.212744d182c31571a3ce.chunk.js
7.78bc8c91b4d566bcf29b.chunk.js
MaterialIcons-Regular.012cf6a10129e2275d79.woff
MaterialIcons-Regular.570eb83859dc23dd0eec.woff2
MaterialIcons-Regular.a37b0c01c0baf1888ca8.ttf
MaterialIcons-Regular.e79bfd88537def476913.eot
assets
index.html
inline.9f795a71f32ae9b76833.bundle.js
main.696e3b89c2786f0cde64.bundle.js
manifest.json
ngsw-worker.js
ngsw.json
polyfills.407a917a12d3da9eb2a2.bundle.js
styles.bc5b28ef85bd9011c4d5.bundle.css
/usr/share/nginx/html # ls assets/
BELL_invision_artboard-V-LeonardSnapsSplash-Screen.png.png
OLE_Logo1.png
avatar.png
cropped-ole-ico-logo-180x180.png
cropped-ole-ico-logo-32x32.png
document.doc
flags
github.txt
icons
image.png
planet_home.png
sample_csv.csv
tenses.pdf
```

When I `ls assets/` I got some images with the name as a literal name to some pdf and images files. Imagine you change the files but not changing the name of the assets, when you deploy, the user might be seeing the old images not the new one because they already cached our image with the same name.

See here for more details https://rea.tech/static-assets-in-an-eventually-consistent-webapp-deployment/

**Comment by paulbert** [comment]
Closing for now.  The files in `/src/assets` have not changed in a year, and that was just to add new files.

I understand this would be a problem if the assets were changing often, but that is not the case practically.
