### ISSUE TITLE
Health Report: Date Search also filters weekly data ?

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6481]
right now its not filtering based on Date search filter.
![Screenshot_2020-06-04 Planet Learning(1)](https://user-images.githubusercontent.com/27276132/83766364-0d82b400-a69c-11ea-8ab6-56a5340784f4.png)

**Comment by lmmrssa** [comment]
This is showing start of the week so May 30 means May 30 - June 5
