### ISSUE TITLE
Teams: Menu scrolling

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6484]
On `Teams`, click on a team. Then There is the following menu at the top:
![Annotation 2020-06-04 090655](https://user-images.githubusercontent.com/54686871/83767423-2a53c300-a66d-11ea-8509-ed39394100cb.png)

There's a horizontal scroll bar because the tab**Join Requests** doesn't fit on the screen. It seems unnecessary to have a scroll bar for only one tab.

### Potential Fix
Decrease the menu tab width on all the tabs to allow them all to fit without the need of the scroll bar.

**Comment by lmmrssa** [comment]
This is the consistent design in Planet and myPlanet. Also this feature goes between team and enterprise and we are trying to keep consistent size for all tabs.
Will keep it open for second though other person
