### ISSUE TITLE
myHealth: spacing between First label column and second column

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6485]
right now its look clumsy while looking at the first examination record column.
It would be better to have spacing or line placed between label column and first examination record.
![Screenshot_2020-06-04 Planet Learning(2)](https://user-images.githubusercontent.com/27276132/83768700-d3ff7800-a69e-11ea-9431-a95f22931585.png)

**Comment by lmmrssa** [comment]
May be aligning it to right instead of left align will be good

**Comment by paulbert** [comment]
I'm going to close this.  The right alignment did not line up well making this difficult to read, so I think let's stick to how it is.
