### ISSUE TITLE
Health Report: Resourse label rating 

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6488]
Could the "There are no resource ratings" label be moved a little to the right( under the Average  Rating"  to make it more clear that there is no rating
![report style](https://user-images.githubusercontent.com/40531136/83771203-0a61d680-a650-11ea-9b62-6c74ed63c138.png)
?

**Comment by paulbert** [comment]
I think having it centered makes it stand out more so it's clear something is different with that section.

This is a little too opinion based and not enough value to change, overall.  Closing.
