### ISSUE TITLE
Proper warnings needed for Finances

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6503]
In **Community**, **Finances**, when adding transactions, there should be some warnings when the balance is negative.

### Screenshots
![Screen Shot 2020-06-08 at 6 24 23 PM](https://user-images.githubusercontent.com/57075986/84086282-855f2000-a9b5-11ea-9b90-2b9dd9f35f16.png)

**Comment by paulbert** [comment]
We could add a message at the top if the balance is negative.  Should only do this when viewing all transactions.

**Comment by paulbert** [comment]
Let's have the message be placed above the table, start with a `warning` icon and have the text `The current balance is negative`.
