### ISSUE TITLE
Dialog: Add event cancel button style

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6504]
In **Community**,  when adding an event, the **Add new Meetup** dialog pops up, the style of **Cancel** button is not the same with other types of dialogs.

### Screenshot
![Screen Shot 2020-06-08 at 6 29 13 PM](https://user-images.githubusercontent.com/57075986/84086751-98bebb00-a9b6-11ea-9aa2-739ea37440e0.png)

**Comment by paulbert** [comment]
Buttons should be on the right, cancel button should be white

![image](https://user-images.githubusercontent.com/9203229/84102471-907a7600-a9de-11ea-8c8b-ef713bf8860c.png)
