### ISSUE TITLE
Surveys: more choices required for multiple choice question

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6505]
When creating a **multiple-choice** question, at least two choices are needed otherwise the question would essentially be a short answer or a long answer question.

It does not make sense to only give one choice, regardless of the choice provided is correct or wrong.

### Screenshot
![Screen Shot 2020-06-08 at 6 58 26 PM](https://user-images.githubusercontent.com/57075986/84088249-159f6400-a9ba-11ea-8ba4-dc4eef00a1e7.png)

**Comment by paulbert** [comment]
Could be used for a question with test/survey instructions with a "I read and understand" for the answer.  Closing.
