### ISSUE TITLE
Health Report: Diagnosis trend showing chart/graph for empty value

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6507]
- select a data range where no examination has been taken during the week or else Diagnosis is empty
- see the Diagnosis Trend.
- It still show graph even though there is no value for respective Diagnosis
![Screenshot_2020-06-09 Planet Learning](https://user-images.githubusercontent.com/27276132/84096530-e4f31500-aa21-11ea-9f27-f2199fae886c.png)

It should be empty in case no value for Diagnosis.

**Comment by paulbert** [comment]
Let's remove the chart if the selected diagnosis has 0 occurrences.
