### ISSUE TITLE
myHealth: birthdate does it go too far out?

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6508]
When you set a birthdate under the myHealth profile it allows you to pick a date starting in the 1700s 
![bithdate too far out](https://user-images.githubusercontent.com/40531136/84098464-5789d380-a9d5-11ea-8a42-31f509114fba.png)

**Comment by paulbert** [comment]
Let's make this minimum Jan 1, 1900 to be simple.
