### ISSUE TITLE
Health Report: Excel report is not showing Age

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6509]
- Updated DOB of a member
- take health examination
- go to Manager Dashboard -> Report ->Health Report
- Age is always showing 0. 
![Screenshot_2020-06-09 Planet Learning(1)](https://user-images.githubusercontent.com/27276132/84098632-7dd85f00-aa27-11ea-8853-552489bfe7e4.png)
<img width="950" alt="Capture" src="https://user-images.githubusercontent.com/27276132/84098645-86309a00-aa27-11ea-811a-99d02fd358a1.PNG">

**Comment by paulbert** [comment]
Based on these screenshots, that's expected.  This person would not have passed their first birthday, so their age is recorded as **0**.
