### ISSUE TITLE
myHealth: Provider information

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6515]
In Examinations under the `myHealth` tab, should any non-self examination have the name of the health provider that administered the exam, because more than one person in a team can have the role? Maybe in the window that pops up when you click on a past exam?
![Annotation 2020-06-08 214355](https://user-images.githubusercontent.com/54686871/84100506-89159580-a9fb-11ea-8b1c-a759b538e3e1.png)
![Annotation 2020-06-08 214435](https://user-images.githubusercontent.com/54686871/84100513-8b77ef80-a9fb-11ea-9d92-2d318ea28a44.png)

**Comment by paulbert** [comment]
Yes, let's put **Performed by:** and the name of the member that performed the examination in the dialog if it is not a `selfExamination`.

**Comment by Haoran-Hu** [comment]
@paulbert How to carry the information about the provider over to `HealthEventDialogComponent` in this case

**Comment by lmmrssa** [comment]
@Haoran-Hu there is data property passed to dialog so send additional data by adding to that data property
