### ISSUE TITLE
Teams: Inconsistent navigation

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6518]
On the **Teams** page when you click on all members, you get redirected to the _members_ page where you can assign roles. 

Again back on the **Teams** page, if you click on a team, navigate to `Members`, it shows a tab view of each of the members. If you click on their name to go to their profile, then hit the back arrow you get navigated to the **Members** page rather than the **Teams** page that you were just on.
![Annotation 2020-06-08 220001](https://user-images.githubusercontent.com/54686871/84101513-a3e90980-a9fd-11ea-9add-0de973f3f3c2.png)
![Annotation 2020-06-08 220024](https://user-images.githubusercontent.com/54686871/84101518-a6e3fa00-a9fd-11ea-94ae-d1e4297d2cb8.png)
![Annotation 2020-06-08 220045](https://user-images.githubusercontent.com/54686871/84101521-a8152700-a9fd-11ea-8561-6cb3b6077de1.png)
![Annotation 2020-06-08 220118](https://user-images.githubusercontent.com/54686871/84101523-a9deea80-a9fd-11ea-957f-b9efaa0fce7f.png)

**Comment by paulbert** [comment]
We could do this as a dialog with the profile information or have a child route of the team with a user profile view that navigates back to the team page.
