### ISSUE TITLE
course progress of a 3 steps each 3 question course

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/planet#6524]
![image](https://user-images.githubusercontent.com/13684059/84177424-da9c3f80-aa50-11ea-8649-2094d390c0ab.png)

steps here should be "question"

**Comment by paulbert** [comment]
The text here changes correctly if you click on the step box.  It does not change if you select from the select box.

Need to change from **Steps** to **Quest.** if the dropdown is used, too.
