### ISSUE TITLE
Courses: course detail view

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6535]
go to courses
click on a course ( I clicked on the [March 16 2020 Test Course](http://localhost:3100/eng/courses/view/42945ef5fc9b393fb0172745f504329a))

Why does the "Test and a thing" step show that it is still in progress, if I have looked through it and have taken the test?
![why does it say its in progress](https://user-images.githubusercontent.com/40531136/84395510-0d1e7780-abcc-11ea-858a-118baf399ddd.png)
![already have taken the test, why in progress](https://user-images.githubusercontent.com/40531136/84395534-0f80d180-abcc-11ea-83b1-8d3bd5a62d04.png)

**Comment by lmmrssa** [comment]
If test has question other than multiple choice it needs to be reviewed.
