### ISSUE TITLE
Calendar: Current day highlight

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6539]
The yellow/tan highlight that show the current day is inconsistent with the theming of the rest of the app. I would recommend a light blue to match.
![Annotation 2020-06-11 092448](https://user-images.githubusercontent.com/54686871/84398554-9f844280-abef-11ea-98bd-6cb9044337d9.png)

**Comment by lmmrssa** [comment]
I would not prefer to change it, as if we have lots of events today and we have light blue as color then it will be difficult to identify. 
![image](https://user-images.githubusercontent.com/2909490/84406626-85675600-ac29-11ea-9e49-aba6c1ed6113.png)
