### ISSUE TITLE
Enterprises: Calendar for Enterprise doesn't show

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#6540]
**Steps to reproduce**

Go to Enterprises  ->  Click on an enterprise  -> Go to its Calendar

![oleentrepisecalendar](https://user-images.githubusercontent.com/48474421/84398856-1d087c80-ac09-11ea-935e-7b976cf2b41f.png)

The calendar shows when you go to a different month

**Comment by lmmrssa** [comment]
It is the problem you will also see with team page. If there is no event record then calendar is not showing. There is an old issue #4828 for this
