### ISSUE TITLE
Community leaders: Add title shows "Updated title" success message

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6542]
- go to community leaders
- add title to members
- message shown as "Title Updated"
It should show "Title added".

![Screenshot (44)](https://user-images.githubusercontent.com/27276132/84399621-cad35580-ac20-11ea-8580-07ccef821945.png)

**Comment by lmmrssa** [comment]
Remember having similar issue created, could not find it right now. As when we want to remove title we are making it empty, so we are giving generic message for now.
may be based on if there is title value or not we can change message. But will put it as low priority and as question

**Comment by lmmrssa** [comment]
Right now seeing community leader title not updating issue on my end. Lets try to update message and dialog title based on older and new value of form. This should affect community tab and also member tab of team.
