### ISSUE TITLE
Feedback: self-reply should be disabled

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6545]
A user should not reply to its own feedback

### Screenshot
![Screen Shot 2020-06-11 at 10 50 41 AM](https://user-images.githubusercontent.com/57075986/84401667-87052f80-abd1-11ea-89e3-0076a91c89c5.png)

**Comment by lmmrssa** [comment]
this is intended for two way communication if there is any problem or feedback
