### ISSUE TITLE
Feedback: confusing close button

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6547]
The **Close** button is used for closing the feedback, but people may think the button is to close the window and click it, so the feedback is accidentally closed.

### Screenshot
![Screen Shot 2020-06-11 at 10 50 41 AM](https://user-images.githubusercontent.com/57075986/84402064-00048700-abd2-11ea-94b3-568f1550e1ab.png)

**Comment by lmmrssa** [comment]
This feature is only available for admin, not for general users. so admin should be aware of it
