### ISSUE TITLE
Surveys: redundant button

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6561]
When a user is taking a survey, the **Finish Survey** button is showing for every question. Even though it is disabled, it is kind of redundant.  Maybe only show **Finish Survey** button when a user reaches the last question.

### Screenshot
![Screen Shot 2020-06-15 at 9 23 57 PM](https://user-images.githubusercontent.com/57075986/84721682-384bf280-af4f-11ea-8dac-4407bf99b255.png)

**Comment by Mutugiii** [comment]
The exams component is used in both surveys and tests, and we have that workflow to support auto-correction of answers during test taking. This would require an overhaul of the exam system or separation of surveys/tests.
