### ISSUE TITLE
Survey: remove unnecessary members

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6563]
When a user tries to send a survey to other members, the dialog is showing all the members. Maybe disable select option for the members that already took the same survey, or remove those who took the survey before in order to prevent sending the same survey to the same member twice.

### Screenshot
![Screen Shot 2020-06-15 at 9 27 14 PM](https://user-images.githubusercontent.com/57075986/84722008-05562e80-af50-11ea-966b-ac4bf95fab9b.png)

**Comment by paulbert** [comment]
Need to check the submissions database for surveys where the `parent._id` and the `parent._rev` are the same as the survey selected.
