### ISSUE TITLE
Finances: Total field

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6566]
The "Total" row looks exactly like the actual transaction rows underneath, with the word "total" being the only difference. Should we do something to make it stand out? Like add a background color or bold the text or add spacing between the total row and the list of transactions?

**Comment by paulbert** [comment]
Let's try bold, background (try `$light-grey` and `$primary-light` from `_variables.scss`) and both.

Make screenshots of each and add to a PR with all of the changes.
