### ISSUE TITLE
myHealth: Can't access myHealth through the dashboard view

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6567]
When I click on the myHealth icon, nothing happens
![myHealth can't access myHealth through the dashboard](https://user-images.githubusercontent.com/40531136/84722781-30da1880-af52-11ea-8bda-602c87c20d53.png)

**Comment by Haoran-Hu** [comment]
@chtelmko Does not have this problem on my end. Maybe check your code to see if there are unintentional changes.

**Comment by paulbert** [comment]
This was an error with the browser cache.  Closing.
