### ISSUE TITLE
Finances: Zero input for credit/debit

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6569]
Is there a use case for having only zero considered valid input? If so, then should we have it actually display zero, rather than an empty string?
![Annotation 2020-06-15 210536](https://user-images.githubusercontent.com/54686871/84723821-15810480-af76-11ea-8eca-78bc3881d7cd.png)

**Comment by paulbert** [comment]
Let's set the minimum value to `0.01`.  I don't think there is a case for a 0 here.
