### ISSUE TITLE
HealthReports: Diagnosis Trend dropdown

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6574]
All the items in the Diagnosis Trend dropdown menu are in alphabetical order except for "HIV/AIDS". Is that intentional or an error?
![Annotation 2020-06-15 212113](https://user-images.githubusercontent.com/54686871/84724650-35192c80-af78-11ea-8970-2fba75d0ee7d.png)

**Comment by paulbert** [comment]
That is an error.  Needs to be fixed in `health/health-constants.ts`.
