### ISSUE TITLE
Courses: Preview test error

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6575]
go to courses
click on the "Take course on myplanet" course
click on view the "Start myPlanet" step
click on preview button 

The question says the its "question 1 of 0 " and the next arrow button is available 
![test question 1of 0](https://user-images.githubusercontent.com/40531136/84724733-e4450c00-af56-11ea-9419-75fef2985f32.png)

**Comment by paulbert** [comment]
This is due to an issue with how courses saved tests and was fixed in 

I think we should just handle this error by routing back to **CoursesStepViewComponent** and showing an alert using **PlanetMessagesComponent** that reads:

> Preview is not available for this test
