### ISSUE TITLE
TeamsView: Error when loading dialog.

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#6590]
In planet.dev few teams member dialog is throwing error. Its not with all but with few teams member only.
![Screenshot from 2020-06-18 18-55-46](https://user-images.githubusercontent.com/45058288/85024232-90743600-b195-11ea-917c-79abeb27727a.png)

**Comment by lmmrssa** [comment]
problem is with member from different community.

**Comment by paulbert** [comment]
This is a wider problem with the view being pretty broken.  Working on a fix.
