### ISSUE TITLE
Stars and rating not matching

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6591]
The stars disappear while the rating is still showing.

### Screenshot
![Screen Shot 2020-06-18 at 9 14 53 AM](https://user-images.githubusercontent.com/57075986/85024625-5b8bc300-b144-11ea-8b3c-2b47acabd62c.png)

**Comment by Haoran-Hu** [comment]
Just realize it is because the user who gave the rating is different from the current user, the stars are not showing.

**Comment by lmmrssa** [comment]
@Haoran-Hu stars are your rating and number is average rating.
