### ISSUE TITLE
MyHealth: Condition. Should you be able to select all conditions at the same time?

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6594]
Under the Condition and Treatment, Should there be a limit on how many conditions you could select?
![limit to how many are selected](https://user-images.githubusercontent.com/40531136/85027500-00f46600-b148-11ea-8a44-b9fdd5d2c8e3.png)

**Comment by lmmrssa** [comment]
Lets not put limit, as these are not something people will try to put randomly. Its only able to be recorded by people (self) and by health workers. Also there is no specific statics that we can follow and say people can have only these number of disease at a time.

**Comment by paulbert** [comment]
I generally agree we should not limit this.  If at some point we have feedback from an expert on limits we should apply here we can change this, but that likely won't happen for a while.
