### ISSUE TITLE
MyHealth: Condition. select/unselect

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6595]
Could we have something that select all, or unselects the conditions you selected? Right now you have to cancel out completely
![limit to how many are selected](https://user-images.githubusercontent.com/40531136/85028164-baebd200-b148-11ea-9269-d70310d8515f.png)
 to clear the form or unselect by hand.
![select all](https://user-images.githubusercontent.com/40531136/85028825-90e6df80-b149-11ea-88cb-e9f078b52cc0.png)

**Comment by paulbert** [comment]
If we get feedback after field usage that a "Clear Selection" button would be helpful we can add it, but a "Select All" would be very strange.  Closing.
