### ISSUE TITLE
myHealth-Examination Edit

### ISSUE THREAD

**Issue by sjkadali** [open-learning-exchange/planet#6596]
On the Examination Edit page, tried editing the examination details after 5 minute. It keeps on showing the message to check whether the entered measurements are correct and doesn't route back to HealthComponent.

![Screenshot from 2020-06-18 09-48-30](https://user-images.githubusercontent.com/39105848/85028850-9ba17480-b149-11ea-8d72-eedd33d62ed5.png)

**Comment by paulbert** [comment]
Tried this out locally.  78 degress C is very hot, so the dialog is correct behavior.  Clicking OK routes back to the Health page as normal.

Closing.
