### ISSUE TITLE
Community: Timestamps for replies of shared posts

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#6598]
### Description
When a message is shared from a Team/Community to the community, a timestamp shows when it is shared. For replies that are made in the community news, they inherit the shared timestamp, this is a bit conflicting especially when a user replies from the team/entreprise & shares with community

![olecommunitytimestamps](https://user-images.githubusercontent.com/48474421/85028903-5b131c80-b184-11ea-98d3-171f9a37c10d.png)

Sceenshot2 showing the bottom part well
![olecommunitytimestamp2](https://user-images.githubusercontent.com/48474421/85038574-67e93d80-b18f-11ea-96a4-a4820af99d12.png)

**Comment by lmmrssa** [comment]
This seems to be ok as being shared. As if people is replying from community then that reply is actually visible in both community and team itself. So this helps team to know that this message is visible in community and no need to share. Only thing i see need to be fixed here is time of share getting copied from old message. We should make it shared at the time of wrote. @paulbert any view from your side?

**Comment by paulbert** [comment]
The shared time should not show up on a reply that was written directly on the community.

Good catch, @Mutugiii!

**Comment by singharpita** [comment]
@paulbert that means Shared time should be hidden/removed from replies right ???

**Comment by paulbert** [comment]
@singharpita The shared time should not exist if the reply is made directly on the community.  It should only show up if the reply was made on the team/enterprise and then shared with the community.

Ideally the `sharedTime` is not set in the case if the reply is made directly on the community.

![image](https://user-images.githubusercontent.com/9203229/85245449-96784a00-b415-11ea-9b7e-64c22b6b4eaa.png)
