### ISSUE TITLE
Services: Removing links

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6600]
In other pages of the app the delete icon is always present. However on the services page you have to click `Remove Links` for the icon to appear and then `Done Removing Links` to make it disappear.

![Annotation 2020-06-18 090351](https://user-images.githubusercontent.com/54686871/85030413-f6989300-b16c-11ea-8cda-9ce8f7c71811.png)

**Comment by lmmrssa** [comment]
This is how we wanted to implement it so that delete is not prominent.
