### ISSUE TITLE
Courses: Add course or Update course

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6602]
Should the name of the person who added or edited a course or survey be shown somewhere? In addition should there be a "last updated" date shown with the date of the last time a course or survey was updated by someone?
![who created or edited course](https://user-images.githubusercontent.com/40531136/85030999-22efe780-b14c-11ea-854a-d1f95c94ff37.png)
![who eddited course](https://user-images.githubusercontent.com/40531136/85031002-24b9ab00-b14c-11ea-9176-c35deefce516.png)

**Comment by lmmrssa** [comment]
Good suggestion.
We are not showing creator as it is not much of a value to learners. As course/resource could be created by (authored) someone and fed to system by someone else. But we are tracking it as it might be something useful for admin or report. So we can think about getting report or showing it to admin.
Regarding last updated, we are thinking to notify or have something to tell learners that course has been updated than last time you took it. We have not decided how we want to actually go with it.

**Comment by lmmrssa** [comment]
Let's add Course or Resource creator at detail section

**Comment by lmmrssa** [comment]
closing as there is already another issue #6769 related to this
