### ISSUE TITLE
UserProfile: Updating user profile leads page not found

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#6604]
Go to **Manager Settings**
Go to **Members**
Click on any **Member Profile**
Click **Edit Profile**

(This leads to page not found.)

![Screenshot from 2020-06-18 20-26-38](https://user-images.githubusercontent.com/45058288/85034684-08e0f400-b1a2-11ea-97b1-2539fbf3157f.png)

**Comment by paulbert** [comment]
Fixed in #6607
