### ISSUE TITLE
Library: Add collections

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6623]
Go to the Library tab
click on resource
click edit
click add collection 

What does the number in parenthesis after the collection name, represent ?
![number after the collection name](https://user-images.githubusercontent.com/40531136/85349805-668c7d80-b4cd-11ea-8878-2f0f6e9d95a8.png)

**Comment by paulbert** [comment]
The numbers in parentheses are the total number of resources that are a part of that collection.
