### ISSUE TITLE
Use UserProfileDialog in different parts of app.

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#6627]
**Current Behavior**
**UserProfileDialogComponent** is used to view members in team and in Community Leaders page.

**Desired Behavior**
Can we add **UserProfileDialogComponent** in TeamsView Chat and TeamsView Join Requests as well?

**Comment by paulbert** [comment]
The components are **NewsListItemComponent** and **TeamsViewComponent**
