### ISSUE TITLE
Record Survey's Update profile shows no page found

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6628]
- Go to myDashboard -> Survey
- Record any survey
- Update Profile will display
- update profile fields
- hit submit button
- No page found error shown
![Screenshot_2020-06-23 Planet Learning(1)](https://user-images.githubusercontent.com/27276132/85351672-096fe680-b524-11ea-9206-e7c1ed02d868.png)

**Comment by paulbert** [comment]
Routing must be hardcoded to `/surveys`.

Quick fix: hardcode to `/manager/surveys`.
Longer, better fix: Make the user profile page route `/manager/surveys/profile` and make the routing relative.
