### ISSUE TITLE
Reports: page number footer

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6629]
Go to reports 
click on courses, resources or health 
scroll all the way down

The footer showing the number of pages, shows more pages than there are
![page says one of 4](https://user-images.githubusercontent.com/40531136/85351812-92f6c880-b4d2-11ea-98bc-68e99f88864f.png)
![footer](https://user-images.githubusercontent.com/40531136/85351818-94c08c00-b4d2-11ea-9cba-75966c2c35b5.png)

**Comment by Haoran-Hu** [comment]
@chtelmko That is not the page number. I think that is how many data entries you have right now (i.e. number of rows).

**Comment by paulbert** [comment]
Correct, that is the number of items/rows in the table.  Closing.
