### ISSUE TITLE
DialogRatings: empty case handling

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6630]
right now dialog box displayed with Header title and OK button.

It would be good to show "No rating found" in DialogRatings

OR

Show message no rating found similar to success/warning message without displaying DialogRatings box.

![Screenshot_2020-06-23 Planet Learning(2)](https://user-images.githubusercontent.com/27276132/85351970-a29efd00-b524-11ea-81b1-bfbd991ae2d3.png)

**Comment by paulbert** [comment]
I think the third option, disabling the `View Ratings` button if there are none, is the way to go.

**Comment by paulbert** [comment]
There should be a `rating.totalRating` property with the count of the ratings for both resources and courses.
