### ISSUE TITLE
Reports: Should user be allowed to set the same date, for end and start dates?

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6633]
Similar to issue #6114

When you set the same date, for end and start date. There is no data shown in the chart
![reports the same end and start date](https://user-images.githubusercontent.com/40531136/85352730-a3a83e00-b4d4-11ea-8a17-1a2639e57cc3.png)

**Comment by paulbert** [comment]
Both values the same is valid.  Then the data is one day of activity.
