### ISSUE TITLE
ResourcesView & CoursesView: No editing from nation

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6638]
from managers dashboard click on list courses
Click on a course
Click edit
Click back arrow 

The back arrow takes you to Courses page, is this desired behavior ?
![courses lists routing](https://user-images.githubusercontent.com/40531136/85353804-161a1d80-b4d7-11ea-9223-06f95f03c004.png)
![goes back to Courses page, is this desired](https://user-images.githubusercontent.com/40531136/85353808-187c7780-b4d7-11ea-9905-6f8e7adb030b.png)

**Comment by paulbert** [comment]
The course and resources from the nation should not be editable.  If the route is `/manager/courses/...` or `/manager/resources/...` the edit button should not be there.

![image](https://user-images.githubusercontent.com/9203229/85357193-c7708180-b4de-11ea-9f84-1e6f74172c61.png)

**Comment by Haoran-Hu** [comment]
@paulbert Originally tired `this.route.snapshot._routerState.url.includes('/manager/courses/')`, however, it seems like check `this.parent` will do.
