### ISSUE TITLE
Courses: Manage in the drop down next to a course

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6660]
Should the button "Manage" be called "edit" in the drop down next to a course?
![edit the course](https://user-images.githubusercontent.com/40531136/85731101-39f08580-b6c8-11ea-8d26-673aaf26ab70.png)
![editable in course](https://user-images.githubusercontent.com/40531136/85731110-3bba4900-b6c8-11ea-98ff-8031d8bf9857.png)

**Comment by lmmrssa** [comment]
We selected this term as while updating course or resource we even do managing of courses by collections, and we also allow to update exams, resources linked to course, etc. That's why we went with broader term **Manage**
