### ISSUE TITLE
MyHealth-Console Error

### ISSUE THREAD

**Issue by sjkadali** [open-learning-exchange/planet#6661]
From myDashboard, on clicking myHealth getting console error.

![Screenshot from 2020-06-25 09-37-51](https://user-images.githubusercontent.com/39105848/85731134-3f4dd000-b6c8-11ea-8203-097ab9b436fc.png)

**Comment by lmmrssa** [comment]
@sjkadali have you done force reload (Shift+F5) or (Ctrl+R).

**Comment by sjkadali** [comment]
@lmmrssa, now on clicking myHealth it's going to myHealth page and no console error shown.
