### ISSUE TITLE
Adding members automatically add members not in the list

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6666]
When a user adds a member to the team, an additional member gets added as well, but the additional member is not in the member list.

When **Member D** gets added, **d** is added too. However, **d** is not a member.

Is it the desired behavior?

### Screenshot
![Screen Shot 2020-06-25 at 9 51 27 AM](https://user-images.githubusercontent.com/57075986/85732892-ba63b600-b6c9-11ea-8fff-ff40a78e3d09.png)

**Comment by Haoran-Hu** [comment]
**d** is only the username when login to the **Member D** account. 
This never happened before.

**Comment by lmmrssa** [comment]
This looks same issue as #6643 which is already being worked on
