### ISSUE TITLE
Teams/Entreprises: Viewing an applicants profile

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#6667]
### Description
While trying to view the profile of a user who has applied to join a team(by clicking on their name):
- As an admin: On clicking and viewing profile, on routing back, it fails to route back to the entreprise and routes to dashboard
- As a non-admin user: On clicking and viewing profile, it fails to route back to the entreprise and routes to dashboard

![oleteamentreprisejoin](https://user-images.githubusercontent.com/48474421/85734617-d422ee80-b705-11ea-9887-dc036f74e748.png)

#### Steps to reproduce
In a Team or Entreprise, visit the subsection for Join requests(teams)/Applicants(entreprises), Click on a users name to view their profile

### Possible Fix
Change the profile to a popup, one that resembles the popup in the `team` subsection to avoid any routing as below:
![oleteamentrepriseprofile](https://user-images.githubusercontent.com/48474421/85734699-dedd8380-b705-11ea-8fa8-8b35ad82a3be.png)

**Comment by lmmrssa** [comment]
This is already being worked on #6627
