### ISSUE TITLE
myHealth: empty space for vision or hearing vital is valid to submit 

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6670]
Similar to  #6599

You can enter an empty space for vision or hearing vital and submit the examination.
![vision](https://user-images.githubusercontent.com/40531136/85737832-ad48c600-b6cd-11ea-8638-e7c2f58ce0d8.png)
![vision submit](https://user-images.githubusercontent.com/40531136/85737859-afab2000-b6cd-11ea-838d-170b1cc5722e.png)

**Comment by lmmrssa** [comment]
This is similar to #6599 so can be worked along with PR #6617

**Comment by paulbert** [comment]
Fixed in #6617
