### ISSUE TITLE
Teams: Task list font size

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6673]
On the _Member_ tab on **Teams**, the cards also list assigned tasks. However the font size of label "Tasks" seems smaller than other places on the app, like smaller than the default font size.

![Annotation 2020-06-25 092830](https://user-images.githubusercontent.com/54686871/85739723-923b7d80-b6f0-11ea-9cea-b5211d1f5ecd.png)

**Comment by lmmrssa** [comment]
This is just there for reference and we wanted to highlight task itself not label.
