### ISSUE TITLE
Remove beta option from Manager Dashboard.

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#6675]
Do we still have anything in beta? If we don't have anything on beta then lets remove beta feature option from Manager Dashboard Component.
![Screenshot_2020-06-25 Planet Learning(2)](https://user-images.githubusercontent.com/45058288/85741167-eb6fd500-b721-11ea-85d3-411a037242c9.png)

**Comment by lmmrssa** [comment]
This we will keep it there as our system is continuously developing and we will have new features being added. So we need this beta guard to say these community will get new features whenever we develop them. And even now we have certificate in beta, just health has been taken out of beta
