### ISSUE TITLE
Courses: Preview button be avaliable

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6676]
Should the "preview " button be available, when you access the course list from the manager settings?
![should preview be avaliable](https://user-images.githubusercontent.com/40531136/85741358-58f31580-b6d0-11ea-87c6-623a05cc2da1.png)

in other places its available without having to click on view step:
![preview is avalible to look at](https://user-images.githubusercontent.com/40531136/85741781-b5563500-b6d0-11ea-8744-a2639b3b5ef9.png)

**Comment by lmmrssa** [comment]
When you are viewing course or resource from manager page, you are actually viewing it from nation. Which means exam or courses are not in your community. So we only give then option to view details of course not complete course. That is why we do not show preview, join course, etc for these courses.
If you like course detail then you can download them to local community and then view it from courses page.
