### ISSUE TITLE
Courses: preview not matching actual test

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6679]
Preview test showing no questions.

### Screenshots
![Screen Shot 2020-06-25 at 10 53 10 AM](https://user-images.githubusercontent.com/57075986/85743687-41b52780-b6d2-11ea-8f4f-cb3812f9f2e9.png)
![Screen Shot 2020-06-25 at 10 52 54 AM](https://user-images.githubusercontent.com/57075986/85743698-44b01800-b6d2-11ea-95a7-4e9d6cd90383.png)
![Screen Shot 2020-06-25 at 10 53 20 AM](https://user-images.githubusercontent.com/57075986/85743709-47127200-b6d2-11ea-8351-306f7dbed55a.png)

**Comment by lmmrssa** [comment]
This is one of the old exam more than year old and this exam pattern has issues so it will not open on taking exam. Please check with new exam if this problem persist.
