### ISSUE TITLE
Community Leaders- Title

### ISSUE THREAD

**Issue by sjkadali** [open-learning-exchange/planet#6684]
For community leaders, in the dialog for adding/updating title, the submit button should be enabled only if there's entry for title.

![Screenshot from 2020-06-26 17-10-01](https://user-images.githubusercontent.com/39105848/85901688-6099e380-b7d0-11ea-922b-7663b3a5f412.png)

**Comment by paulbert** [comment]
This is intentional.  You can remove the title by submitting an empty title.  Closing.
