### ISSUE TITLE
Enterprises: warning for finances

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6690]
For **Finances** section in **Enterprises**, a negative balance should trigger some warning similar to the **Finances** section in the **Community**.

### Screenshots
![Screen Shot 2020-06-29 at 9 37 04 PM](https://user-images.githubusercontent.com/57075986/86073180-4a4e8a80-ba51-11ea-9ebd-f075deb4a0f7.png)

![Screen Shot 2020-06-29 at 9 40 58 PM](https://user-images.githubusercontent.com/57075986/86073154-3dca3200-ba51-11ea-9906-b4c1669e44e4.png)

**Comment by paulbert** [comment]
There is an error in the console when loading the **TeamsViewComponent**.  This specific enterprise is available on Planet Dev as an example.  Locally, I have not been able to reproduce.

![image](https://user-images.githubusercontent.com/9203229/86077546-26437700-ba5a-11ea-800e-3d385dd2ebbd.png)

**Comment by lmmrssa** [comment]
Saw this when filtering date. Not happening when your start date is before any finance record. But once you filter date after first record it will hide this message.

**Comment by paulbert** [comment]
@lmmrssa That is by design.  The message should only show up if all transactions are shown.  The code checking that is where this error is thrown
