### ISSUE TITLE
DialogsRatings: Sorting options

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6692]
right now, latest rating added up in last.
![Screenshot_2020-06-30 Planet Learning](https://user-images.githubusercontent.com/27276132/86074186-26b52f80-baa5-11ea-9c94-3f0d321a4a2b.png)

**Comment by paulbert** [comment]
These are not sorted, currently.  Instead of simply sorting these once, let's add some sorting options.  For now let's just do a simple selection dropdown in the upper right of the dialog with:

Rating: Highest to Lowest, and the opposite
Most Recent and Oldest
