### ISSUE TITLE
MyHealth: empty text field submission with the text editing buttons

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6694]
Similar to #6599 and #6670

You can click on any of the text editing buttons above the text fields,  and submit the examination.
![href link button](https://user-images.githubusercontent.com/40531136/86074508-22acf180-ba54-11ea-85d8-a176be74a4db.png)

**Comment by paulbert** [comment]
I'm going to close this.  We need to wait and see if this mistake is made often with normal use before devoting resources to fix it.
