### ISSUE TITLE
Comunity Leaders: Leaders from Nation shows up in community.

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#6695]
Some of the leaders from Nations shows up in Community leaders List. Is this intended?

![image](https://user-images.githubusercontent.com/45058288/86074452-b78c0b00-baa5-11ea-93ca-293f8da30683.png)

**Comment by paulbert** [comment]
Seeing this in my community, too.

We made a change to fetch the `parent_users` database with the **UsersService** methods.  This is likely related to that, and we need to filter out the "leaders" that do not match the `planetCode` in this view.
