### ISSUE TITLE
Login: Add link to myplanet on Play Store

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#6699]
We'd like to add a link to our Android app in the Google Play Store on the login page.  Below **Planet Learning** let's add:

On Android?  [Try myPlanet](https://play.google.com/store/apps/details?id=org.ole.planet.myplanet&hl=en_US)

![image](https://user-images.githubusercontent.com/9203229/86075619-6e609a80-ba56-11ea-88f3-da7e09dbfeaf.png)

**Comment by lmmrssa** [comment]
https://play.google.com/store/apps/details?id=org.ole.planet.myplanet

**Comment by paulbert** [comment]
As an additional note the link should open in a new tab.
