### ISSUE TITLE
myHealth Examintaion: Edit timer is not updating after making an update to examination

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6700]
- Add an examination to myHealth.
- will start showing timer that how many lefts
- edit the examination and submit
- timer still set with previous value. In case of Edit , timer should be reset to 5 minute .
https://www.loom.com/share/af80608cf0184e01a8c123c108079515

**Comment by paulbert** [comment]
Just a little crossing of PRs.  Line 65 should use `updatedDate` instead of `date`.

**Comment by paulbert** [comment]
This is in **HealthEventDialogComponent**
