### ISSUE TITLE
myDashboard: should there be information to what the "x" action is?

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6702]
Should there be an explanation of what will happen, when you click on a 'X" when you hover over it?
![myDashboard Should there be an explanation](https://user-images.githubusercontent.com/40531136/86076058-6a814800-ba57-11ea-9b9c-a68e73e375ac.png)

**Comment by lmmrssa** [comment]
we can add tooltip

**Comment by paulbert** [comment]
I agree, `mat-tooltip` with **Remove from myLibrary** (or whichever row) would be a good addition.
