### ISSUE TITLE
Community: Icon behavior when window shrunk

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6703]
On the "News" tab the icons in the mat-card behavior strangely when the viewport width is shortened.

![Annotation 2020-06-29 212943](https://user-images.githubusercontent.com/54686871/86076636-f1dfb300-ba79-11ea-813c-d046be0ca1c4.png)

**Comment by paulbert** [comment]
When the width is under 800px, let's hide the calendar.  If possible, let's also add it as a tab in the `mat-tab-group`.
