### ISSUE TITLE
Resources: progress bar

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6722]
For **Courses**, there is a **Your Progress** bar for the courses a user has enrolled in, there is no **Your Progress** for **Resources** that have been added to **myLibrary**. 

Is it the desired behavior?

### Screenshots
![Screen Shot 2020-07-02 at 9 29 55 AM](https://user-images.githubusercontent.com/57075986/86365093-0cb35280-bc47-11ea-8ff3-86979e0d8d5b.png)
![Screen Shot 2020-07-02 at 9 29 40 AM](https://user-images.githubusercontent.com/57075986/86365100-0fae4300-bc47-11ea-867d-1c2c72cc93bc.png)

**Comment by paulbert** [comment]
This is intended, and for the time being won't change.
