### ISSUE TITLE
Numbers allowed for user name

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6725]
Numbers are allowed for users' names. Users' names cannot be numbers technically.

### Screenshot
![Screen Shot 2020-07-02 at 9 40 36 AM](https://user-images.githubusercontent.com/57075986/86366055-5486a980-bc48-11ea-9740-aed9d0e78096.png)

**Comment by paulbert** [comment]
I'd rather leave this as is than limiting this and possibly rejecting valid inputs.  Closing
