### ISSUE TITLE
Members Dialog box on empty should show user atleast

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6732]
right now it shows dialog box with empty information which could mislead that which user profile we are viewing right now.
It could be better if we could include Username saying "Member Profile of [username]" atleast in case Full name is missing

![Screenshot_2020-07-02 Planet Learning(1)](https://user-images.githubusercontent.com/27276132/86368460-e9b38d80-bc9c-11ea-8888-e8976160f3f4.png)

**Comment by paulbert** [comment]
One thought, we removed the below toolbar entirely which has the username and the gender icon.  We could put that back in and just have the buttons hidden in the dialog.

**Comment by Haoran-Hu** [comment]
@paulbert Are those buttons supposed to be removed or just disabled?
