### ISSUE TITLE
Courses: Routing when editing a course

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#6736]
### Description
When editing/updating a course, on routing back to course details, it routes to the full course list.

#### Steps to Reproduce
Go to Courses -> Select a course -> Click the edit button -> Route back

![olecourseedit](https://user-images.githubusercontent.com/48474421/86370206-17daa280-bc88-11ea-9497-1c0059651b73.png)

**Comment by paulbert** [comment]
Right now the routes are 

```
/courses/update/{id}
```

and

```
/courses/view/{id}
```

To work smoothly we'd need the route from clicking the edit button in **CoursesViewComponent** to route to

```
/courses/view/{id}/update
```

and improve the handling of the `navigateBack()` method in **CoursesAddComponent** to be relative to the current route.
