### ISSUE TITLE
Courses: Courses View. Brief message before showing the course detail

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6744]
Click on Courses
Click on a course title (any course)

Before the course detail view opens up, there is a brief message that appears and quickly disappears. Not sure what this message is,  maybe" no preview is available for this course"
![courses view](https://user-images.githubusercontent.com/40531136/86497775-fabdd680-bd50-11ea-84a3-43b854a770fb.png)

**Comment by paulbert** [comment]
@chtelmko Could you please try to replicate again and get a screenshot of the message?  Or at least type the exact message in the text of this issue?

There isn't enough here to be able to work on this effectively.

**Comment by chtelmko** [comment]
This is what I can see, but it happens very quickly:
![this error 1](https://user-images.githubusercontent.com/40531136/86615146-10661280-bf82-11ea-8534-dbc477ead0b3.jpg)

**Comment by chtelmko** [comment]
This is the video of what is happening:
https://www.loom.com/share/b9d9e632baec43feabd9869fe7751c1f

**Comment by paulbert** [comment]
Ok I see it now.  The text says **There is no content available for this course**.

We should only show that message after the course has been fetched from the database.  When that happens `courseDetail._id` should be set.
