### ISSUE TITLE
members should be sorted alphabetically

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6754]
right now members in team/enterprise or anywhere is shown based on the latest added members at top.

![Screenshot_2020-07-07 Planet Learning](https://user-images.githubusercontent.com/27276132/86685010-cbde8380-c022-11ea-8b48-05f1d0c53d59.png)

**Comment by paulbert** [comment]
Sort by `lastName` if it exists and then by username or _id.
