### ISSUE TITLE
Finance: "Current balance is negative" only shown for All transaction?

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6760]
right now warning message is only shown in case of viewing All transaction.
![Screenshot_2020-07-07 Planet Learning(2)](https://user-images.githubusercontent.com/27276132/86688199-9b4c1900-c025-11ea-8288-436d4987fbb6.png)

If performed any date filter such that Current balance remains shown as negative, warning message is disappeared in this case.
![Screenshot_2020-07-07 Planet Learning(1)](https://user-images.githubusercontent.com/27276132/86688298-b028ac80-c025-11ea-95f8-b2abd2d4016b.png)

Is this intended behavior??

**Comment by paulbert** [comment]
Yes this is intended behavior.
