### ISSUE TITLE
myDashboard: myAchievements, click on a certification to view it?

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6762]
Should you be able to pick a certification from the list and  to click on it to view it? maybe have it open in a new tab.
![should you be able to click on a certification to view it  maybe have it open in a new tab](https://user-images.githubusercontent.com/40531136/86689054-a591f700-bfd4-11ea-9177-9d4ef203d72d.png)

**Comment by Mutugiii** [comment]
Can be tackled by #7443
