### ISSUE TITLE
Feedback: Chips with no action

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6765]
![Annotation 2020-07-06 210714](https://user-images.githubusercontent.com/54686871/86689663-b9e6eb80-bff6-11ea-866b-20eef45220fb.png)

The buttons/labels in the "Priority" and "Status" columns don't have the `cursor-pointer` class, but still have an animation when the mouse is hovered over them and an animation on click. This seems misleading because they stand out on the page and have animations but have no functionality.

The Submissions page also has these buttons/labels. I'm not sure if there are other parts of the app that have them.

**Comment by paulbert** [comment]
https://v8.material.angular.io/components/chips/api

I believe `disableRipple` will help with that.  It may not remove all of the changes when clicking, but it at least removes the animation.  `disabled` will grey out the chip a bit making it more difficult to read, and I don't think we want that.

**Comment by jsschf** [comment]
For me:
* Eventually want to remove all animation, including: 
    * hover, click, and shadow
