### ISSUE TITLE
Shelf database reorganization?

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#678]
I realized something today about the `shelf` database (for user selected items that show up on the dashboard): we could reorganize it so that queries are easier for both "all x in user y shelf" and "all users with x in shelf":
```
{
  type = 'resource'|'course'...
  userId
  itemId
}
```

@lmmrssa @dogi How does this look to you?

**Comment by lmmrssa** [comment]
here you want shelf of each item to have it down doc right? It looks good but we need to look for case when we are adding/removing shelf for each course or resource if that already exist or not in list.

**Comment by paulbert** [comment]
Closing.  The current organization is working well now.
