### ISSUE TITLE
EnrolledList: Error loading enroll list in certain courses.

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#6784]
There is error in loading enroll list  of some courses in planet.dev. One of the course is **How to use planet**.

![Screenshot from 2020-07-09 19-33-20](https://user-images.githubusercontent.com/45058288/87048350-5689d300-c21b-11ea-8067-90e0ca834cc8.png)

**Comment by paulbert** [comment]
Better error message:

![image](https://user-images.githubusercontent.com/9203229/87055789-ca53bd80-c1d2-11ea-905b-b093e0ba5ae1.png)
