### ISSUE TITLE
ExamsAdd: Previewing a test or survey endless spinner

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#6789]
### Description
When previewing a survey, submitting an answer causes the app to load infinitely

### Steps to reproduce
Go to the Courses tab, create a new course,  add a survey step to the course,  add a question(text-long answer), preview the survey, write and submit an answer.

![oleplanetloadbug](https://user-images.githubusercontent.com/48474421/87049905-31d73080-c206-11ea-9691-fd2f299835a6.png)

**Comment by lmmrssa** [comment]
not seeing this happening

**Comment by paulbert** [comment]
This is throwing the following error.  **SubbmissionsService** stores a submission that is checked when going to the next question, but preview mode doesn't set this so if it hasn't been set this fails.

![image](https://user-images.githubusercontent.com/9203229/87057886-68e11e00-c1d5-11ea-98ad-30b314e8638d.png)

**Comment by paulbert** [comment]
This will throw an error when submitting the first question, no matter the number of questions in the survey or test.

**Comment by paulbert** [comment]
Note to replicate go to course add, refresh, and then go through the steps.

**Comment by Haoran-Hu** [comment]
@paulbert Still throwing an error when it is NOT in the preview mode.

**Comment by Haoran-Hu** [comment]
![Screen Shot 2020-07-11 at 3 48 59 PM](https://user-images.githubusercontent.com/57075986/87232616-3f1f2700-c38e-11ea-97d7-eb81ab5b8322.png)

**Comment by Haoran-Hu** [comment]
@paulbert Maybe some hints to kick start.
