### ISSUE TITLE
ReportsDetail: Members list

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6790]
The `>` list of members makes it seem like there is a drop down when you click on it but that is not current behavior. I'm not sure if that's something that is planned for the future.

![Annotation 2020-07-09 090151](https://user-images.githubusercontent.com/54686871/87049813-f1b78400-c1ec-11ea-8181-942dd88e6305.png)

**Comment by paulbert** [comment]
Just the icon we decided on to indent.  This is used in other areas for expandable content, so suggestions for alternatives are welcome.

Preferably from https://material.io/resources/icons/?style=baseline

**Comment by robinGiri** [comment]
@paulbert , these two icons seems like good alternative. What do you think?

arrow_right_alt
![Screenshot_2020-07-10 Material Icons(1)](https://user-images.githubusercontent.com/45058288/87125408-30f7da80-c2aa-11ea-936a-1d00544b51f0.png)

arrow_right
![Screenshot_2020-07-10 Material Icons(2)](https://user-images.githubusercontent.com/45058288/87125427-3b19d900-c2aa-11ea-8605-2fb70a525f8f.png)
