### ISSUE TITLE
myDashboard: Routing when any dashboard item is empty

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#6791]
## Description
While on myDashboard, if any of the catalogs are empty(myLibrary, myCourses, myTeams) when you click on any it routes to where a user can add them, on routing back, it goes to the community page

### Steps to reproduce
Go to myDashboard -> click on any empty catalog(e.g myCourses) -> Route back

**Comment by RheuX** [comment]
I believe this is already implemented? but i may be wrong since if catalogs are empty in the dashboard, it would navigate your directly
