### ISSUE TITLE
Mysubmissions: Add graded date column

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6795]
when you update a submission under Mysubmissions the "Updated on" field stays the same.
![when you update a submission under my submission](https://user-images.githubusercontent.com/40531136/87053013-71cef100-c1cf-11ea-95cb-0c7abacd9fb4.png)

**Comment by paulbert** [comment]
There is another field `gradeTime` for when the submission is graded in **mySubmissions**.

Let's add that for **Tests** (**Surveys** are not graded) in the **mySubmissions** view and the view shown when clicking **Review Submissions**.
