### ISSUE TITLE
Calendar: Add the space between buttons

### ISSUE THREAD

**Issue by eonshikkim** [open-learning-exchange/planet#6796]
It would be better to add a margin between the "Add Event" button and "<" and ">" buttons in a small screen size.

![image](https://user-images.githubusercontent.com/47366411/87053936-2402ba80-c1c8-11ea-9d54-0a94da7e91f7.png)

**Comment by paulbert** [comment]
See https://fullcalendar.io for modifying the styles with these buttons.

Just add a top/bottom margin between the buttons.  No additional left/right margins needed.

**Comment by Mutugiii** [comment]
The calendar does indeed collapse to its own tab, however for super small screens there is the spacing issue

![image](https://github.com/user-attachments/assets/f288b92e-a413-4a80-87dc-0648f5309c44)

**Comment by jessewashburn** [comment]
I don’t think I’m able to replicate the issue. 

Tested with a screen width of 375px:
![image](https://github.com/user-attachments/assets/dc000237-bbce-4c47-9ca9-1277453571eb)

**Comment by Gavinp14** [comment]
I was also not able to replicate this issue.

**Comment by RheuX** [comment]
**Only works below 400px**

<img width="643" alt="Screenshot 2024-10-31 at 7 31 36 AM" src="https://github.com/user-attachments/assets/b56f3969-7670-4848-9beb-eaa5c5bdb324">

This happen if you open the sidebar also

![image](https://github.com/user-attachments/assets/5658d0db-ee1b-4e7b-8a54-dd5ce81b99ba)

**Comment by jessewashburn** [comment]
Oh I see. Yes, I am getting it when I open the sidebar and the width is less than 505px.
