### ISSUE TITLE
Mysubmissions: Number count 

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#6797]
## Description
In myDashboard, the total number count for mySubmissions is just for the `tests`, should the number count include `surveys`?

## Steps to reproduce
Go to myDashboard -> View submission count -> Click on mySubmissions, Toggle between tests and surveys and see the total count(when at least one survey is there)

![olemysubmissionscount](https://user-images.githubusercontent.com/48474421/87053751-0276f280-c20b-11ea-926f-2ebde9f8d2d7.png)

![olemysubmissionssurveys](https://user-images.githubusercontent.com/48474421/87053772-07d43d00-c20b-11ea-8098-3c38d8473fc9.png)

![olemysubmissionstests](https://user-images.githubusercontent.com/48474421/87053788-0c98f100-c20b-11ea-9f20-9e2b077dc1d0.png)

**Comment by paulbert** [comment]
The number indicates the number of tests that require grading.  Closing.
