### ISSUE TITLE
Mysubmissions: needs grading chip

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6802]
Now that there is the "Graded on" date in tests under mySubmissions view . The "requires grading" chip is confusing
![needs grading chip](https://user-images.githubusercontent.com/40531136/87108097-73c89c80-c22f-11ea-9344-dbee0e4df1cf.png)
.

**Comment by paulbert** [comment]
I think keeping it simple with one status showing that there are questions remaining that still require grading rather than adding another is better.
