### ISSUE TITLE
Courses: Infinite loading/console error on adding question to existing test step

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6809]
### Steps to reproduce
* Choose any course with tests
* Edit the course
* Click on one of the steps with a test
* Click "Update Test"
* Add a question of any kind
* Click "Save & Return"
* Click "Submit"

Here's a screen recording:
https://www.loom.com/share/6bfe51c8bbb843819f35cae5ca9445af

Here's the console error: 
![Annotation 2020-07-10 123843](https://user-images.githubusercontent.com/54686871/87182723-3702b100-c2d4-11ea-9b5e-1d79f50af622.png)

**Comment by jsschf** [comment]
This also works if you click "Update Test" and then hit "Save & Return" without adding any questions

**Comment by jsschf** [comment]
Once you reach the infinite loading and get the max call stack size console error, if you hit back in the browser, then hit "Save and Return" again, you get the following console errror:


![Annotation 2020-07-10 125412](https://user-images.githubusercontent.com/54686871/87184256-37e91200-c2d7-11ea-8f3d-eab542828fb6.png)

Here is an updated Loom:
https://www.loom.com/share/c2931549c4ed425aa94a83266c7fb061

**Comment by jessewashburn** [comment]
unable to replicate

**Comment by Mutugiii** [comment]
unable to replicate as well
