### ISSUE TITLE
CoursesUpdate: Back button text not appearing

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6817]
When you try and update a course, the text next to the back arrow doesn't show up.

![Annotation 2020-07-13 204124](https://user-images.githubusercontent.com/54686871/87370757-5c611a80-c573-11ea-89bf-1f3462e9693f.png)

**Comment by paulbert** [comment]
The same goes for **ResourcesAddComponent**.

**Courses** and **Library** should be the headers.
