### ISSUE TITLE
Library/Courses: Collections overlapping

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6819]
I created a **Collection** called Collection 1 for **Courses** and added a course in that collection. Then go to **Library** and click on **Collections**, you can see the **Collection 1** that has been created for **Course** but it contains no courses.

Is it the desired behavior? The same collection is applicable for both **Library** and **Courses**? If so, why there is nothing in the **Collection 1** that has been created for **Courses**? There should be a course which was added before.

### Screenshots
![Screen Shot 2020-07-13 at 9 45 13 PM](https://user-images.githubusercontent.com/57075986/87371184-d03efb00-c552-11ea-9066-f1b757c6c2ad.png)
![Screen Shot 2020-07-13 at 9 45 38 PM](https://user-images.githubusercontent.com/57075986/87371190-d339eb80-c552-11ea-830e-f5fb3c573f71.png)
![Screen Shot 2020-07-13 at 9 45 48 PM](https://user-images.githubusercontent.com/57075986/87371199-d59c4580-c552-11ea-98dd-6b481ccecc2d.png)

**Comment by paulbert** [comment]
Closing.  Cannot replicate anymore.
