### ISSUE TITLE
Limit course description length

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#682]
![course_long_description](https://user-images.githubusercontent.com/9203229/38972594-9689a520-436f-11e8-943f-67a2e2946ec2.png)

After 3 or 4 lines should end with an ellipsis `...` (CSS can do this with `text-overflow: ellipsis;`)

**Comment by lmmrssa** [comment]
max-height: 3.1em;
line-height: 1em;
overflow: hidden;
display: -webkit-box;
-webkit-line-clamp: 3;
seems to do it but it only works for -webkit browsers

**Comment by paulbert** [comment]
Fixed by limiting height and scrolling on overflow for description
