### ISSUE TITLE
Courses: collection selection

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6822]
Is it confusing that the number of courses in a collection, does not match the selected collection?

It happens when you select the grade level first and then click on "collection" and select from the list.

![number of courses in a collection, does not match the selection](https://user-images.githubusercontent.com/40531136/87372395-6d029800-c555-11ea-8247-d9667d1112af.png)

**Comment by paulbert** [comment]
Let's make the count match the number of available courses or resources left based on the filter.
