### ISSUE TITLE
mySubmissions: clicking on "course name" shows correct or incorrect

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6826]
When you click on course name under my submissions the grade for the step shows up, but the test hasn't been graded yet.

![when you click on a couse under my submissions the grade for the step shows up, but the test hasn't been graded yet](https://user-images.githubusercontent.com/40531136/87373080-fe263e80-c556-11ea-949d-3948b7d85516.png)

**Comment by chtelmko** [comment]
I think its because it was a multiple choice answer.

**Comment by paulbert** [comment]
Yes, a MC answer is automatically set as "Correct" or "Incorrect".  Closing.
