### ISSUE TITLE
Markdown: Add Image dialog header

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6848]
This dialog should have a header/title called "Recently Added" or something similar.

![Annotation 2020-07-16 085319](https://user-images.githubusercontent.com/54686871/87679629-effd3b80-c76b-11ea-8d10-690ef4f96d95.png)

**Comment by paulbert** [comment]
**Select an Image** would work

**Comment by paulbert** [comment]
The plan is:

* If there are images **Select an Image**
* If there are no images **No Images to Select**
