### ISSUE TITLE
Course: Completing the course to show up in reports

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6851]
I am not sure, if I am testing this correctly(maybe the course needs to be graded first for it to show up as complete) but i pick a course without a test and take it. Yet its not showing up as complete in the reports.

![taking survay is the last step](https://user-images.githubusercontent.com/40531136/87680149-0e9f0a80-c74b-11ea-9fe6-ed3494eb1bed.png)

![i am finished with the survay](https://user-images.githubusercontent.com/40531136/87680234-27a7bb80-c74b-11ea-97e5-343e767c09a9.png)

![course is now complete](https://user-images.githubusercontent.com/40531136/87680420-69d0fd00-c74b-11ea-9711-a471ad193ead.png)

![does that mean its completed](https://user-images.githubusercontent.com/40531136/87679937-cd0e5f80-c74a-11ea-852f-a18f249b000b.png)

![courses completed updates](https://user-images.githubusercontent.com/40531136/87679916-c67fe800-c74a-11ea-8b3c-40bf1697c36b.png)

**Comment by paulbert** [comment]
A course is not counted as completed until all tests have been graded.  Closing.
