### ISSUE TITLE
Courses: Duplicate images in dialog

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6852]
If you add the same images with the same title from your filesystem multiply times, each one gets saved in the dialog.

![Annotation 2020-07-16 090222](https://user-images.githubusercontent.com/54686871/87680676-3dc67380-c76d-11ea-8e19-04fad7563d41.png)

**Comment by paulbert** [comment]
Short term quick fix: Reject images with the same filename as one already created and direct the user to rename the file.

Longer term fix: If the filename and the image match what's on the database, just use the existing image.  If it does not add it with a (2), etc added at the end of the `title`.  Means every image with the same `filename` needs to be checked each time.

**Comment by paulbert** [comment]
Error message if file exists:

**An image with that filename exists.  Please rename or select other image.**
