### ISSUE TITLE
Courses:  images add boarder

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6853]
Would it be easier to tell where one course ends and the other begins. If there was a boarder around the pictures?
I added similar pictures to different courses and its hard to tell, that they are separate.
![boarder](https://user-images.githubusercontent.com/40531136/87681562-c8e34180-c74c-11ea-9478-26f6167ea44c.png)

**Comment by paulbert** [comment]
I don't think we should add a border around images that the course creators cannot remove, and I think we have other priorities to work on before we change the table layout & styles.  Closing.
