### ISSUE TITLE
Profiles: Allow users to remove profile picture

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#6855]
Should the users be allowed to remove their profile picture?

**Comment by paulbert** [comment]
Yes, they should!  There is a stale PR open that ran into some issues & needed more work #4812.

I think at this point a new PR would be better, but the challenges with that PR could be useful to look at for the new PR.

**Comment by RheuX** [comment]
![image](https://github.com/user-attachments/assets/34885ed4-3175-4996-8f92-8cf7d0cb1a41)

**Comment by Mutugiii** [comment]
Resolved in #7378
