### ISSUE TITLE
myHealth: Examinations formatting

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6879]
Centralize the data in all the columns for a better visual. If not, the first left column could be difficult to see.

### Screenshot
<img width="662" alt="Screen Shot 2020-07-20 at 9 09 39 PM" src="https://user-images.githubusercontent.com/57075986/88001279-c1fe5b00-cacd-11ea-8425-53b1c551ca0d.png">

**Comment by paulbert** [comment]
We could try having it centered.  There was a PR to have it right aligned but it was too messy.

**Comment by paulbert** [comment]
See #6685
