### ISSUE TITLE
Courses: Finished test not being indicated

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6880]
Go to **Courses**, select a course and take tests, the finished tests do not have the check icon except for the last test, correspondingly, the progress bar still showing yellow. Is it intended?

### Screenshot
<img width="1761" alt="Screen Shot 2020-07-20 at 8 46 55 PM" src="https://user-images.githubusercontent.com/57075986/88001610-8dd76a00-cace-11ea-8663-f01ca57c32d3.png">

**Comment by paulbert** [comment]
Yes the green will only be there after the test has been graded 100%.  The last step has all multiple choice questions which were graded automatically.
