### ISSUE TITLE
UsersProfileDialog: Open profile button routes to own profile

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#6885]
### Current Behavior

In **UsersProfileDialogComponent** the link to **View full profile** routes to the currently logged in user's profile always.

### Desired Behavior

This should route to the user profile page of the person's profile being viewed.

![image](https://user-images.githubusercontent.com/9203229/88003642-56b78780-cad3-11ea-9e47-df21cd879d45.png)

**Comment by lmmrssa** [comment]
also it looks like this option is available only for admin not learner

**Comment by paulbert** [comment]
@lmmrssa Handling the condition for showing this button is in #6876
