### ISSUE TITLE
Health Report: Diagnosis trend reverts to COVID selected after changing time filter

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6888]
i am not sure whether its intended behavior or not
https://www.loom.com/share/de637c85f512462e96ce67f6a3eb3c8b

**Comment by paulbert** [comment]
Any time the diagnosis is changed and then the time filter is changed (either by clicking on the week in the weekly chart or changing the start/end date selection) the data reverts to COVID-19 but the dropdown selection stays the same.
