### ISSUE TITLE
Courses: Tests unable to proceed with wrong answers

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6889]
When a user is taking a test, and select the wrong answer, a warning shows up and the user cannot proceed until he/she gets it right. In this case, every user would get 100% for a test.

 If it is a test, users should be able to submit the test first and their submissions should be marked later.

### Screenshot
<img width="1160" alt="Screen Shot 2020-07-20 at 9 56 29 PM" src="https://user-images.githubusercontent.com/57075986/88004126-5cfa3380-cad4-11ea-93bb-7a484537754a.png">

**Comment by lmmrssa** [comment]
This is intended way of implementation.
