### ISSUE TITLE
Feedback: Add the specified item info in the page

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6892]
Using the Courses menu to submit feedback on a specific course doesn't have the course information in the feedback title in Manager Settings. The path is just "/courses".

![Annotation 2020-07-20 212041](https://user-images.githubusercontent.com/54686871/88005413-e58acb00-caf8-11ea-9e45-f5bd56e7961b.png)
![Annotation 2020-07-20 212102](https://user-images.githubusercontent.com/54686871/88005415-e6bbf800-caf8-11ea-8ce7-63ff2417a3a5.png)
![Annotation 2020-07-20 212123](https://user-images.githubusercontent.com/54686871/88005418-e885bb80-caf8-11ea-9cac-ec3b4b003726.png)

**Comment by paulbert** [comment]
The difference is that there is a link directly to the course in the right.

Maybe with the menu course we can directly add the `courseTitle` in the feedback title instead of the URL?  The same would go for resources, teams, and enterprises.
