### ISSUE TITLE
Courses, Finish the course button

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6895]
If you go to Courses, and select a course that does not have a test or a survey for the last step. 

The last step will have the "take survey"  or "take test" button, even though the  test or survey is in another step (survey is in step 3, in this example).

After you click "take survey" and go through the survey you have to go back to the previous step to click on "finish survey" or "finish test".

Should the course have "finish survey" or "finish test" button on the last step ? 

![taking survay is the last step](https://user-images.githubusercontent.com/40531136/88005888-638aaa00-cad8-11ea-8d42-52ecbd5ad89a.png)

![taking survay is the last step you have to go back](https://user-images.githubusercontent.com/40531136/88005856-4a81f900-cad8-11ea-8be7-80d2fb26c473.png)

![step 4](https://user-images.githubusercontent.com/40531136/88006003-aa789f80-cad8-11ea-850d-ebee86cd84ce.png)

**Comment by paulbert** [comment]
The tests & surveys have the "Finish" buttons to indicate that those are ready to be reviewed by the leadership.  Since that's all of the content for a course that needs to be reviewed, there doesn't need to be an additional "Finish" button at the end of the course.
