### ISSUE TITLE
Enterprise Reports: Initial value for start date and end date

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#6909]
Beginning value should be value of previous month closing
By default current month/previous month beginning and end should be as default start end date

**Comment by paulbert** [comment]
Let's start with the dates.

Start date should be the first of the previous month, and end date should be the final day of the previous month.

For example, today is July 23.  `startDate` should initialize to June 1 and `endDate` to June 30.

**Comment by paulbert** [comment]
@robinGiri Realized I should have this done for tomorrow's meeting, and I will not have a chance to review in the morning.  I just reassigned you to a few different issues.
