### ISSUE TITLE
Enterprise- Add report: validation is missing in End date field

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6912]
![Screenshot_2020-07-23 Planet Learning(1)](https://user-images.githubusercontent.com/27276132/88292773-cc149980-cd19-11ea-92f3-26577618fbfa.png)

**Comment by paulbert** [comment]
The function is added to the field but it is not implemented correctly.  `endDateValidator` returns a validator function.  It is not a validator function itself.
