### ISSUE TITLE
Enterprise- Add Report: Delete action not working

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6913]
![Screenshot_2020-07-23 Planet Learning(2)](https://user-images.githubusercontent.com/27276132/88293040-2a417c80-cd1a-11ea-92b6-8d919c020a47.png)

**Comment by lmmrssa** [comment]
![image](https://user-images.githubusercontent.com/2909490/88293805-35e17300-cd1b-11ea-8963-a9bf0c4a9cc8.png)

**Comment by paulbert** [comment]
@singharpita I realized this should get merged for tomorrow's meeting, but I won't have time to review anything tomorrow morning.  I assigned you to a new issue.
