### ISSUE TITLE
Enterprise- Add Report: Show asterisk for required fields

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6915]
right now only summary field is shown as required fields which result in everything in the form as value 0 which doesn't make any sense
![Screenshot_2020-07-23 Planet Learning(3)](https://user-images.githubusercontent.com/27276132/88293398-ad62d280-cd1a-11ea-96bd-78e4f43d81ae.png)

**Comment by paulbert** [comment]
We can add the `*` at the end of the fields show that they are required, but they are all required fields.  They initialize to 0, which is a valid input for all of those fields.
