### ISSUE TITLE
Teams: teams plan deadline

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6918]
Should there be some way to indicate the expected time frame for the plan, similar to a task?
![date time for the plan](https://user-images.githubusercontent.com/40531136/88295093-f854f980-ccca-11ea-89a2-16296d587d96.png)

**Comment by paulbert** [comment]
We'll leave that open to the teams to put into the text of the plans.  There's no need to have a specific "plan date" recorded in the plan.
