### ISSUE TITLE
Enterprises Add Report: Disable submit until form is valid

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#6919]
Should we disable submit button until any one field is filled except start date and end date?
![Screenshot_2020-07-23 Planet Learning(1)](https://user-images.githubusercontent.com/45058288/88295076-ad63d200-cd1c-11ea-83f7-5d67882f68f0.png)

**Comment by paulbert** [comment]
It still would be valid to have all zeros here.

Let's change so submit is disabled when the form is invalid by setting `disableIfInvalid` in `openDialogsForm` `options`.
