### ISSUE TITLE
Enterprises: Report dialog edit icon

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6922]
Should the edit icon be part of the title of the dialog?

![Annotation 2020-07-23 090712](https://user-images.githubusercontent.com/54686871/88296223-f05a8100-cced-11ea-8a05-519e036a0d45.png)

**Comment by paulbert** [comment]
I think we can remove this.  Merging with #6917 since it's dealing with the same thing.

**Comment by paulbert** [comment]
Closing in favor of #6917
