### ISSUE TITLE
Survays: sorting arrow for Created/Updated on

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6924]
Does the sorting arrow make it look like you are sorting by action, not The Created/Updated on field?
This is done everywhere else, but could a space between Created/Updated on and action fields help?
![the sourting arrow makes it look like you are sorting by action, not The CreatedUpdated on field](https://user-images.githubusercontent.com/40531136/88296653-fb50e980-cccc-11ea-8942-e33f576e9b49.png)

**Comment by paulbert** [comment]
We can make that column wider so there is space between the arrow and **Action**
