### ISSUE TITLE
CoursesView: Join/Leave does not work after refresh

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#6926]
## Description
While in a certifications, trying to join/leave a course you must refresh the page for the action to be noted

### Steps to reproduce
Visit certifications in the manager settings -> Select a course (You are redirected to another page) -> Click join or leave (Refreshing the page shows the action)

**Comment by paulbert** [comment]
Certifications opens **CoursesViewComponent** in a new tab, which is similar to a refresh.  Tested, and if you:

1. Open the course
2. Refresh
3. Click join/leave

Nothing happens until you refresh again

**Comment by paulbert** [comment]
For clarity, this is an example of **CoursesViewComponent**

![image](https://user-images.githubusercontent.com/9203229/88306733-19244b80-ccd9-11ea-993b-6e1e46f2e4c7.png)
