### ISSUE TITLE
Enterprise Report: More information for details

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6928]
In **Enterprise**, show detaisl for **Report** shows the same information before clicking **View Details**, so maybe add more information to **View Details** dialog?

### Screenshots
<img width="417" alt="Screen Shot 2020-07-23 at 10 17 36 AM" src="https://user-images.githubusercontent.com/57075986/88297562-0b1cfd80-ccce-11ea-9fcf-8846fdafcc1d.png">
<img width="342" alt="Screen Shot 2020-07-23 at 10 17 45 AM" src="https://user-images.githubusercontent.com/57075986/88297568-0c4e2a80-ccce-11ea-8672-b31c40ded3c7.png">

**Comment by paulbert** [comment]
There isn't anything else to add, but we could try to detect if all of the information is shown and remove the button & click action if so.

This will be a little bit of a challenge reading the DOM and checking if the elements in **PlanetTeamsReportsDetailComponent** exceed the height of the `mat-card-content` element in **PlanetTeamsReportsComponent**

**Comment by robinGiri** [comment]
@paulbert  I'm  unable to understand this issue can you explain a bit more about what am I suppose to do?

**Comment by paulbert** [comment]
Outdated.  Summary no longer shows up in this view as of #6973
