### ISSUE TITLE
Enterprise Reports: close button

### ISSUE THREAD

**Issue by Haoran-Hu** [open-learning-exchange/planet#6946]
Select any **Enterprise** reports, click **View Details**, the **close** button is shadier than other active buttons.

### Screenshot
<img width="661" alt="Screen Shot 2020-07-27 at 9 05 17 PM" src="https://user-images.githubusercontent.com/57075986/88607361-08633500-d04d-11ea-87c6-e4117ba94806.png">

**Comment by lmmrssa** [comment]
we can use our general close button system which is grey button not blue one
