### ISSUE TITLE
Teams: Click on member name "Object not found" error

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6949]
Clicking on a person's name to open the user profile dialog gives the following response in the console.

![Annotation 2020-07-27 203140](https://user-images.githubusercontent.com/54686871/88608893-550d3700-d072-11ea-8965-13af91969145.png)

**Comment by lmmrssa** [comment]
This is fine as user has not created achievement. Unless user has achievement when searching for available achievement will be not found message. It is not an error
