### ISSUE TITLE
Enterprise Add Report: negative numbers in Numeric field still allowing to submit form

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6951]
- add report
- add negative values in beginning balance or other numeric field
- as soon as you type "-", submit is disabled but when you type any number after "-", Submit button is enabled and allows you to submit the form
![Screenshot_2020-07-28 Planet Learning(3)](https://user-images.githubusercontent.com/27276132/88609690-7dae2480-d0a4-11ea-91c2-27e554804a18.png)
![Screenshot_2020-07-28 Planet Learning(2)](https://user-images.githubusercontent.com/27276132/88609692-7edf5180-d0a4-11ea-8b3f-fbab7d735e33.png)

**Comment by lmmrssa** [comment]
#6910 has not been worked yet
