### ISSUE TITLE
Enterprise - Report: subheaders should be fixed style

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6981]
subheaders right now is focused out if there are more than 4-5 reports.

![Screenshot_2020-07-30 Planet Learning(2)](https://user-images.githubusercontent.com/27276132/88929827-5f117e80-d29a-11ea-98fa-cffb478a0ae4.png)

![Screenshot_2020-07-30 Planet Learning](https://user-images.githubusercontent.com/27276132/88929834-60db4200-d29a-11ea-9463-ea6d50d8ab61.png)

![Screenshot_2020-07-30 Planet Learning(1)](https://user-images.githubusercontent.com/27276132/88929833-6042ab80-d29a-11ea-8a0d-110389eb9890.png)

**Comment by paulbert** [comment]
In other words, the buttons should always be visible.  The section of the screen with the report grid should be the only scrollable part.
