### ISSUE TITLE
TeamsView: Tabs & action buttons fixed position

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6989]
Similar to #6981 , but with transactions. The "Add transaction" button and the input fields for the filter should stay fixed.

**Comment by paulbert** [comment]
I'm going to make this more broadly **TeamsViewComponent** should have better scrolling.

The tabs and any action buttons should be fixed.  Information like news posts, the calendar, tasks, mission/plan, etc. should be the only scrollable portion.

**Comment by jessewashburn** [comment]
fixed by #6981
