### ISSUE TITLE
Missing translation sections

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#7057]
Dashboard

**Comment by rheam97** [comment]
I identified some before you updated, will check again this weekend and come up with a list of things to fix

**Comment by rheam97** [comment]
so on planet.dev.ole.org, I noticed a few places that could be translated: the calendar on community, the text under services, teams, and enterprise. Then there's the dashboard tile names such as mycoses, myeline, etc... the filter on library as you pointed out and courses as well. The source of a resource and the rating. The grade level and subject of a course. the feedback modal. notification status. and the messages info.

**Comment by jessewashburn** [comment]
These are all translated already, or will be once Crowdin gets pulled.
