### ISSUE TITLE
Make login page to break line

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#7061]
In tablet design break On android and try planet to two lines
<img width="534" alt="image" src="https://user-images.githubusercontent.com/2909490/158987881-af0e6b9d-8279-491a-b7a8-ada83b06f0ae.png">
For mobile design make it cover whole screen i.e cover whole wrapper screen
<img width="428" alt="image" src="https://user-images.githubusercontent.com/2909490/158987977-ac38bf1c-684f-475a-af4c-63609c06f8d6.png">

**Comment by rheam97** [comment]
@lmmrssa I think I need to open another pr for this because I took away the important properties because I was worried it would mess up the code in the future

**Comment by rheam97** [comment]
fixed!

**Comment by rheam97** [comment]
@lmmrssa I should make another PR for this as well to merge before the mobile login

**Comment by Mutugiii** [comment]
Closing. Addressed in #7073
