### ISSUE TITLE
Convert login design for mobile something like this

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#7062]
<img width="384" alt="image" src="https://user-images.githubusercontent.com/2909490/158990949-41645e9f-857c-4b33-811a-a24ec7121930.png">
<img width="331" alt="image" src="https://user-images.githubusercontent.com/2909490/158991675-0073f668-797d-4b58-b470-5b16e1fa4171.png">

**Comment by rheam97** [comment]
Hey @lmmrssa what screen size is this? in my Firefox, mobile has a max width of 812 px. Also, should I do this instead of the second part of the last issue?

**Comment by rheam97** [comment]
Hi @lmmrssa, so I tried to keep the display grid, but even when I set it to one column, it doesn't look right. so for the mobile for now I've changed it to display flex with a flex-direction of column and it looks closer to this.
<img width="1216" alt="Screen Shot 2022-03-21 at 7 07 32 AM" src="https://user-images.githubusercontent.com/94139372/159249512-b93a1893-c19e-4a8f-9c46-ca9e45bf83e7.png">

vs. flex

<img width="1233" alt="Screen Shot 2022-03-21 at 7 07 59 AM" src="https://user-images.githubusercontent.com/94139372/159249544-ac9e4521-f27e-48bd-806b-6a2219244ec0.png">

**Comment by lmmrssa** [comment]
@rheam97 it is not about fix screen size we mostly need to look at which screensize current design breaks and add style based on that. We can take tablet size and mobile size and also look at orientation. i.e. width and height ratio.

**Comment by rheam97** [comment]
hi @lmmrssa I was able to make the layout you wanted but im still having issues with the build even though the branch is named '7062-mobilelogin'. Here is what it looks like:
<img width="997" alt="Screen Shot 2022-03-23 at 5 31 34 PM" src="https://user-images.githubusercontent.com/94139372/159799410-7c4cb6a7-aeed-43b0-ac0a-6befb8cb727a.png">

**Comment by rheam97** [comment]
Ill fix the logo actually during the hacking meeting

**Comment by rheam97** [comment]
@lmmrssa Im having an issue making it landscape because its not taking the properties that I put in the landscape media query. I don't want to use the !important property because I noticed and saw that it messes everything else up before it.
<img width="1342" alt="Screen Shot 2022-03-25 at 3 38 14 PM" src="https://user-images.githubusercontent.com/94139372/160190059-50699d9f-a086-4336-ac25-b04a4bd3404c.png">

**Comment by rheam97** [comment]
@lmmrssa I removed the important properties because I think it won't be as easily maintainable with them. it sort of messed up the progress I've made

**Comment by rheam97** [comment]
fixed it!
