### ISSUE TITLE
Categorize low-priority issues as "on hold"

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/planet#707]
Is there any good way to get low priority issues, or issues that will be relevant, but are too early to implement, into a "on hold"-category? 

**Reasons:**
It would be nice to have such things moved out from waffle.io inbox a bit, and also makes it easier to post issues that are relevant later without flooding the issues list with currently irrelevant stuff...

**Comment by paulbert** [comment]
I'm going to close this, but noted as I think we can always improve our issue organization.
