### ISSUE TITLE
localization: `Planet Learning` is getting localized

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#7231]
![image](https://github.com/open-learning-exchange/planet/assets/48474421/2bb22865-9349-4a62-85c9-ab5760ba46d2)

**Comment by jessewashburn** [comment]
This has now been corrected on Crowdin. Just needs to be pulled.

![image](https://github.com/user-attachments/assets/67a7bc51-2556-4b3e-87b5-b4acc7d01e57)
