### ISSUE TITLE
Code duplication: MatTables

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#726]
Right now we have a lot of duplication across our components with MatTables.

We should refactor to reduce these components to reduce this repetition as much as possible (follow [T-DRY](https://angular.io/guide/styleguide#t-dry-try-to-be-dry)

Right now the components with tables are 4 of the top 5 worst files according to CodeClimate:

![image](https://user-images.githubusercontent.com/9203229/39157002-b50ae788-4726-11e8-962b-1dd15e845c0d.png)

**Comment by paulbert** [comment]
Feedback table also has some duplication now (see #1569)

**Comment by lmmrssa** [comment]
@paulbert shall we go with inheritance of classes then? So we have all common functions on parent class and child will overwrite based on their requirement.
