### ISSUE TITLE
no Nation is showing up when earth.ole.org is center

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/planet#728]
![a-20180423-233840](https://user-images.githubusercontent.com/13684059/39164926-f3016f98-474f-11e8-88ab-e2e42c35df30.png)

even we have a nation there

**Comment by lmmrssa** [comment]
List is showing from earth as it can be seen in snapshot below. But there was issue that it was returning `local_domain` where we have changed it to be `localDomain` now. Updating earth.ole.org to reflect that change
![screen shot 2018-04-24 at 18 31 42](https://user-images.githubusercontent.com/2909490/39188477-a2edd0b4-47ef-11e8-8b3a-de675e1e4f3e.png)

**Comment by lmmrssa** [comment]
closing this issue as it has already been resolved
