### ISSUE TITLE
Feedback choice fields don't throw error when not clicked on submit

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#7353]
![image](https://github.com/open-learning-exchange/planet/assets/48474421/6022a968-bf86-4e14-bd0c-78a0c5be59d7)

**Comment by Abdelhafid01** [comment]
@Mutugiii I'll take this issue, can you assign it to me please.

**Comment by xyb994** [comment]
Hi @Abdelhafid01, feel free to fork this repo and create a pull request :)

If you need help with setting up the project, we do have a setup guide coming up for our virtual interns that you could reference to, but it's a wip and would not be ready for approximately another 2 weeks.
