### ISSUE TITLE
Hide subject and grade level when empty

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#7362]

**Comment by Mutugiii** [comment]
Grade and subject level are never empty. The initialization when the not set by the user is different:

![image](https://github.com/open-learning-exchange/planet/assets/48474421/10142b95-c1dc-4fea-9a99-96bf076fa274)

**Comment by Okuro3499** [comment]
@Mutugiii seems like there is some data inconsistency on the values of grade and subject
![image](https://github.com/open-learning-exchange/planet/assets/64019708/cd056ee4-b3f8-4922-843e-c865a34ff59d)
![Screenshot 2023-12-06 135414](https://github.com/open-learning-exchange/planet/assets/64019708/5c4d1369-f490-425f-bcde-182e584919d0)
