### ISSUE TITLE
course steps with tests blocked during preview mode

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#7387]
In the courses, should users be able to go through all the course steps during preview mode

Other things to consider:
- How do we inform them that there is a course test

**Comment by jessewashburn** [comment]
We are able to preview course steps.

![image](https://github.com/user-attachments/assets/36003eeb-76a2-495d-a0ce-1af795805d80)

There is an icon to indicate tests associated with steps. 
![image](https://github.com/user-attachments/assets/6c80773e-a1cd-47cd-bf99-d31e268799ef)
