### ISSUE TITLE
tslint depraction warning

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#7521]
![image](https://github.com/user-attachments/assets/d1a97dbb-7a6c-4300-a5f2-654aa3d3c1a3)

**Comment by Abdelhafid01** [comment]
hello @Mutugiii , where do you have this issue ? can you more information about this issue ?

**Comment by jessewashburn** [comment]
![image](https://github.com/user-attachments/assets/f05d325d-7296-4e05-8075-d2f426a5f82c)
Doesn't seem to be the case anymore
