### ISSUE TITLE
myPlanet Report: Responsive toolbar

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#7619]
Implement Responsive toolbar style for the `myPlanet Report` page in the `Manager Dashboard`

![image](https://github.com/user-attachments/assets/57863dd2-08c4-4a66-a70a-8bb1b8c8fb92)

With respect to desktop, tablet($screen-md) and mobile($screen-sm) views

**Comment by RheuX** [comment]
for this one specifically, do i need to a android phone to add a report inside this page(?). I'm assuming its not responsive because of the `community reports` from `myplanet`. But I currently have no records inside my planet.

**Comment by RheuX** [comment]
actually i see that the search bar is also not responsive, ill go ahead and make a PR
