### ISSUE TITLE
Reports: responsive secondary toolbar

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#7620]
Implement a responsive secondary toolbar(blue) in the `Reports` page of the `Manager Dashboard`

![Screenshot_20241018_201055_Chrome.jpg](https://github.com/user-attachments/assets/4114650f-601c-4638-b6c4-6d08423d3b87)

With respect to desktop, tablet($screen-md) and mobile($screen-sm) views

**Comment by RheuX** [comment]
I'm not too sure what you meant by the secondary toolbar, everything seems fine to me except for the `Reports` button overflowing

**Comment by Mutugiii** [comment]
The secondary toolbar refers to the blue toolbar with the `Reports` button overflowing
