### ISSUE TITLE
AI Configurations: Responsive page and alignment issues

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#7622]
- Fix any alignment issues.
- Make config form more responsive.

![Screenshot_20241018_201149_Chrome.jpg](https://github.com/user-attachments/assets/741fc100-c4e6-4356-97a2-543e32e9b15a)

With respect to desktop, tablet($screen-md) and mobile($screen-sm)

**Comment by jessewashburn** [comment]
Please see PR #7623
