### ISSUE TITLE
Profile: Toolbar responsiveness

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#7627]
Implement a `kebab menu icon` toolbar in mobile screens in the view profile page

![image](https://github.com/user-attachments/assets/757e31cb-fdf9-4968-a744-89864bc71b04)

**Comment by jessewashburn** [comment]
Please see my newest commits to #7642. I retained the same kebab-menu functionality, but I used the Device Type and Event Listener in the ts file in order to minimize CSS and improve maintainability.
