### ISSUE TITLE
desktop missing icons when shrinking page

### ISSUE THREAD

**Issue by sahilvunnam** [open-learning-exchange/planet#7640]
When I shrink the page, the icons on the left side are missing for Community, Courses, Library and Teams

![Image 10-24-24 at 7 25 AM](https://github.com/user-attachments/assets/eb8d1b67-228d-4fd2-a8b8-c07bf8a66911)

**Comment by RheuX** [comment]
I cannot seem to replicate this issue, how did you do it?

**Comment by jessewashburn** [comment]
Strange, I can't replicate it either.

**Comment by sahilvunnam** [comment]
I don't know I just minimized the screen and noticed that there were some icons missing

**Comment by RheuX** [comment]
Does it occur on a specific dimension, or just when you shrink your page to a certain dimension(?)

**Comment by Mutugiii** [comment]
This is likely network related
