### ISSUE TITLE
achievements page overflow

### ISSUE THREAD

**Issue by sahilvunnam** [open-learning-exchange/planet#7652]
When adding content to My Purpose, My Goals, and My Achievements I an overflow

![Image 10-25-24 at 8 17 AM](https://github.com/user-attachments/assets/a69404ad-589b-435c-a8e4-dca3c6fabef5)

**Comment by Mutugiii** [comment]
Nice catch!

**Comment by Mutugiii** [comment]
Not sure how to replicate though

![image](https://github.com/user-attachments/assets/c06b1ddc-d451-4106-af10-038b2711a77b)

**Comment by jessewashburn** [comment]
Confirmed, I am having the same issue. 
![image](https://github.com/user-attachments/assets/b3a6f807-cddf-410d-94cb-e5b66de33e77)

**Comment by RheuX** [comment]
![image](https://github.com/user-attachments/assets/18dd283a-b2cc-49ca-820a-fa99581958ea)

This is mine from master branch
