### ISSUE TITLE
Achievements: Toolbar responsiveness

### ISSUE THREAD

**Issue by jessewashburn** [open-learning-exchange/planet#7658]
Buttons are cramped and text is overflowing. 

Consider resizing buttons on $Screen-sm or implementing a kebab menu icon toolbar on mobile screens in the view achievements page (Similar to #7642).

![image](https://github.com/user-attachments/assets/3734895f-a519-41bc-98fb-4da5e2819c5d)

**Comment by Mutugiii** [comment]
Fixed in #7637
