### ISSUE TITLE
Toolbar Buttons not responsive for mobile screens

### ISSUE THREAD

**Issue by Gavinp14** [open-learning-exchange/planet#7666]
On mobile screen, toolbar/action buttons are cramped together 
<img width="350" alt="buttonIssues" src="https://github.com/user-attachments/assets/f8c16d3b-c5e0-4d9c-958d-6f13f0eeed9a">

**Comment by RheuX** [comment]
if youre reffering to the secondanry toolbar (like the action and edit button), i think its related to this one already

PR #7627
