### ISSUE TITLE
Download resource takes you out of planet in same tab

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/planet#767]
**Tested on 0.1.6**

Uploaded a resource (pdf), clicking download (not in reader itself), takes me to the reader and makes me leave planet. I would expect it to be in a tab, or in other way show me that I'm still in Planet.

**Comment by paulbert** [comment]
Might be specific to PDFs.

**Comment by Tille88** [comment]
Seems like it would be possible to just force it to download no matter what in the response:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

Longer discussion:

https://superuser.com/questions/1277819/why-does-chrome-sometimes-download-a-pdf-instead-of-opening-it?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by lmmrssa** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
this says cross origin download is not accepted anymore. And it does not seem to work neither on chrome or firefox. 
* So we might have to force content-deposition from couchdb itself or
* We can read file and give blob file to download from application itself.
