### ISSUE TITLE
Courses section: Step creation

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/planet#769]
**Tested on 0.1.6**

I can't seem to reorder "steps" if I have added them in the wrong order.

Having new step on tab key would make sense with a keyboard, on a tablet, not really an issue though...

**Comment by paulbert** [comment]
There are reordering buttons, but only when the expansion panel is open.  This is a difficult one since I don't think the Material expansion panel allows for buttons when closed.

**Comment by paulbert** [comment]
Out of date, this is now handled with PlanetStepListComponent
