### ISSUE TITLE
enterprises: make enterprise name align

### ISSUE THREAD

**Issue by sahilvunnam** [open-learning-exchange/planet#7694]
When you minimize the screen and go to the enterprise section or the teams section the name doesn't align with the content below it, should we fix this?

![Image 10-31-24 at 6 58 AM](https://github.com/user-attachments/assets/516f176b-be70-4475-9cbb-953c38abc320)

![Image 10-31-24 at 6 44 AM](https://github.com/user-attachments/assets/04212647-2076-45c7-840d-96ef8ac03a31)

**Comment by Gavinp14** [comment]
This should be an open issue. It looks weird when it is not aligned

**Comment by Gavinp14** [comment]
@sahilvunnam I was not able to replicate this issue. This is what my screen looks like. Is this still an issue for you on your computer?
<img width="365" alt="alignmentreplication" src="https://github.com/user-attachments/assets/2e0be363-b575-43ed-b715-ef85d5a7a84d">

**Comment by sahilvunnam** [comment]
@Gavinp14 Yes it does still happen for me, but it might only be my system experiencing this type of behavior

**Comment by Gavinp14** [comment]
I get this issue where it is not aligned on the master branch. When I checkout on this branch the issue is fixed. I did not make any changes to this.
