### ISSUE TITLE
Search bar is not present on mobile screen

### ISSUE THREAD

**Issue by Gavinp14** [open-learning-exchange/planet#7703]
<img width="467" alt="searchnarclearbuttonissue" src="https://github.com/user-attachments/assets/c6937efd-12a9-49be-ae7c-04e39f1cc40f">

**Comment by RheuX** [comment]
not sure what you mean?

if you referring to the search bar for the resources, it's on the filter list

![image](https://github.com/user-attachments/assets/1fd71139-1cce-4945-a0dd-12ebcd81e6b7)
