### ISSUE TITLE
Library: needs loading message

### ISSUE THREAD

**Issue by jessewashburn** [open-learning-exchange/planet#7706]
Currently says No Content for This Resource. Recommend a loading message similar to other pages. 

[screen-recorder-fri-nov-01-2024-12-54-42.webm](https://github.com/user-attachments/assets/a22873f0-6d14-41b2-a065-dcee7766f434)

**Comment by RheuX** [comment]
anyone trying to replicate this issue, for easier time seeing, you could refresh the page constantly, and sometimes, the page says there's no constant
