### ISSUE TITLE
courses/library: rating without enrollment

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#7726]
Should we allow rating of courses/resources without enrolling into the courses/saving the resource?

**Comment by sahilvunnam** [comment]
I don't think this is a good idea because I feel like kids would just rate many courses without taking them. Also the rating of the course will mean less to us because anyone can rate it now, even without taking it. They could just rate it because they want to.

**Comment by jessewashburn** [comment]
I agree with Sahil.

**Comment by Mutugiii** [comment]
current implementation allows for any learner to rate without enrolling

**Comment by Gavinp14** [comment]
Yes, the learners should not be able to rate a course without being enrolled in it. I feel like it defeats the purpose of ratings in the first place.

**Comment by RheuX** [comment]
Then should we only allow them to rate after they have completed everything(?).

**Comment by RheuX** [comment]
or only when they have enrolled only(?)

**Comment by Mutugiii** [comment]
Enrollment alone should be sufficient to avoid being too strict i.e some courses with tests need to be manually graded before being marked as completed
