### ISSUE TITLE
courses: progress reports export button visibility

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#7729]
Hide the button when we don't have any exportable data? On click we have a message that there is no valid data.
Given that we use the hiding strategy in other parts of the app, which approach should we use?

![image](https://github.com/user-attachments/assets/31c3d908-df51-4bd7-8151-aa0749ffe741)

**Comment by sahilvunnam** [comment]
I think we should hide the button if there is no data to export. Continue previous strategies.

**Comment by jessewashburn** [comment]
I agree with Sahil.
