### ISSUE TITLE
Snackbar issue remaining. Can be blocking to UI.

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/planet#774]
**Tested on 0.1.6**

Some snackbars remain open for unnecessarily long periods of time still.

On certain resolutions, they can even block/hide crucial UI elements like here Log Out

<img width="905" alt="screen shot 2018-04-26 at 21 41 35" src="https://user-images.githubusercontent.com/16757941/39313978-76483ae0-499d-11e8-8738-cbc8b5687fd7.png">

**Comment by paulbert** [comment]
Fixed #782, and we also added a close time for `showAlert` so it doesn't block the UI indefinitely as well.
