### ISSUE TITLE
myProgress: formatting is broken 

### ISSUE THREAD

**Issue by jessewashburn** [open-learning-exchange/planet#7740]
~~Can someone replicate?~~

Confirmed. This page needs formatting. 

![image](https://github.com/user-attachments/assets/b2f4b779-e528-47ca-b32e-3b8f9830b324)

**Comment by Gavinp14** [comment]
I was not able to, where exactly did you navigate to in the software to create this issue?

**Comment by jessewashburn** [comment]
I went from myDashboard>myProgress. Can you show me what it looks like for you?

**Comment by Gavinp14** [comment]
Aha, I was able to replicate this issue. it looks the exact same for me. I was just going to the wrong area

**Comment by jessewashburn** [comment]
Fixed by #7785
