### ISSUE TITLE
Selected resources indication (number of selected, which ones added)

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/planet#775]
**Tested on 0.1.6**

I would like to have an indication of number of selected/checked resources by the "Add to library"-button

<img width="165" alt="screen shot 2018-04-26 at 22 06 13" src="https://user-images.githubusercontent.com/16757941/39314680-0527eaca-499f-11e8-8e01-168cc7d395d7.png">

Alternatively, or in combination: have the added snackbar say something like:
“{{ ResourceName }} added to your library" Instead of “Resource added to your library”

<img width="370" alt="screen shot 2018-04-26 at 22 13 29" src="https://user-images.githubusercontent.com/16757941/39314703-118f4146-499f-11e8-8597-4a7fb69a9861.png">

**Comment by lmmrssa** [comment]
There is #776 specifically for already added indication. Number of selected item is already done.
