### ISSUE TITLE
Already added indication of resources

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/planet#776]
**Tested on 0.1.6**

Depending on how difficult it is to implement, but if possible, could there be an indication of which resources have already been added to the personal library **in resource list view**? 

Adding things twice does nothing, but gives notification of added.

**Comment by Rupesh87** [comment]
![screenshot-2018-4-27 planet learning](https://user-images.githubusercontent.com/18145146/39348681-d7fdc550-4a17-11e8-8eac-f29ab5c446aa.png)


@Tille88 it's working well in planet v0.1.6 once it has added to library then the option changes to removed from library as shown in snapshot. I think the issue you have might be the case of the previous version. Please check it once...

**Comment by Tille88** [comment]
@Rupesh87 
Try ticking the box and click the "Add to library" button on top of the list. I did not check that hidden menu yesterday, but I'm pretty sure it was 0.1.6, since I did install Docker from scratch yesterday evening.

**Comment by paulbert** [comment]
Fixed #2489
