### ISSUE TITLE
what is the local url there for

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/planet#777]
Do we need to change it? If not, why do we show it at all? 
<img width="712" alt="screen shot 2018-04-26 at 5 43 10 pm" src="https://user-images.githubusercontent.com/2836302/39322471-8266b8a2-4979-11e8-953d-a77b3528fffd.png">

**Comment by paulbert** [comment]
I'm going to close this because I think it's covered by the change of #780.  We still may take out localUrl eventually, but for now it's in a good place
