### ISSUE TITLE
Dashboard: profile reminder only pops up after refresh

### ISSUE THREAD

**Issue by jessewashburn** [open-learning-exchange/planet#7818]
I understood from #7765 that if you dismiss the reminder, it should only return after a fresh login. Instead, it returns every time you refresh, including on a fresh login. 

[dashboard_profile_reminder.webm](https://github.com/user-attachments/assets/e927aeef-7c75-41e4-8df2-b9a4f35f50c4)

**Comment by RheuX** [comment]
might ask @Mutugiii since the local storage was removed i think, im not sure if its now an intended feature or not

**Comment by Mutugiii** [comment]
Think localstorage is not the most ideal, Will work on using a couchdb flag

**Comment by Mutugiii** [comment]
After some thought, I believe it’s fine in its current state, considering that it behaves as expected if you don't refresh and we want to prompt users until they complete it.
