### ISSUE TITLE
chat: chatbox size

### ISSUE THREAD

**Issue by RheuX** [open-learning-exchange/planet#7874]
![image](https://github.com/user-attachments/assets/3794ea8a-5315-4a4c-8d4f-31419116cb9c)

![image](https://github.com/user-attachments/assets/75d07aae-a911-48de-9270-f0ad1040623a)

I think having the chat size box be any size you want shouldn't be allow, its nicer if they just scroll if there's a lot that they want to type.

**Comment by jessewashburn** [comment]
I agree.
