### ISSUE TITLE
mySurveys: survey not loading

### ISSUE THREAD

**Issue by jessewashburn** [open-learning-exchange/planet#7877]
These simple 1 question surveys won't load, except for a split second before I navigate away. Anyone able to replicate?
[screen-recorder-tue-dec-03-2024-15-15-00.webm](https://github.com/user-attachments/assets/9b5dfe33-1f94-4c9f-a06a-5868fbfab167)

**Comment by Gavinp14** [comment]
I was able to replicate this as well. This is a valid issue

**Comment by jessewashburn** [comment]
Seems the Submissions and mySurveys are broken in this way The branch used by #7785 works, so something that got merged since Nov. 14th broke it. I thought it might be  #7649 but reverting those changes did not fix it. What's the most efficient way to diagnose this? @Mutugiii

**Comment by jessewashburn** [comment]
Actually, I learned how to use Git Bisect and found that this issue was created between v0.15.51 and v0.15.52. So, it seems to me  PR #7781 is to blame.

**Comment by Mutugiii** [comment]
Can confirm seems to be #7781

**Comment by RheuX** [comment]
oh okay ill take a look at this
