### ISSUE TITLE
Add feedback action like open close to message

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#788]
It will be nice to have the message to show actions taken on feedback such as 'User closed feedback'.
We can show it as different layout than what we are showing for normal message

**Comment by Rupesh87** [comment]
And also submitting feedback it doesn't show any success message..

**Comment by paulbert** [comment]
Not sure what this is referring to, but we have messages when opening, closing, deleting, and adding feedback.  Closing this issue.
