### ISSUE TITLE
library filter 'level' field is broken

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#7880]
![image](https://github.com/user-attachments/assets/fa3dcc85-7526-4fde-8406-faf754ae2beb)

**Comment by jessewashburn** [comment]
I'm unable to replicate. I see the level filter, and it works for me. 

![image](https://github.com/user-attachments/assets/f264a5a8-8618-4a1c-9ef2-1f2492b4076d)

**Comment by Gavinp14** [comment]
I was also not able to replicate this issue.

**Comment by Mutugiii** [comment]
Can replicate this on:
- Earth: Resources[Language -> ] & Courses filter[Language -> ]
![image](https://github.com/user-attachments/assets/c74875c6-ce02-4d30-bd07-867cd20cc3ce)
![image](https://github.com/user-attachments/assets/6354aa89-22f4-4a2c-a8c3-175f56580b16)

- Vi: Resources[Language -> ], Courses ok
![image](https://github.com/user-attachments/assets/132bcba5-8235-401e-b2a2-cb6977058e61)

- Learning: Resources[Language -> ], Courses ok

- Guatemala:  Both ok

- SanPablo: Both ok
