### ISSUE TITLE
courses: edit button reverted to manage button

### ISSUE THREAD

**Issue by jessewashburn** [open-learning-exchange/planet#7889]
![image](https://github.com/user-attachments/assets/b2e642cc-2f6e-486c-8535-8a2735c3699e)

I thought this got fixed by #7790

**Comment by Mutugiii** [comment]
Looks ok for me in the courses, although we need to update it on the resources side.

courses
![image](https://github.com/user-attachments/assets/c53a3a37-1898-4450-9bda-8cde45c86e0e)

resources
![image](https://github.com/user-attachments/assets/bf8349a0-5561-47d0-b8eb-f2f0b7fd8d20)

**Comment by jessewashburn** [comment]
Ah, of course. I thought I had changed it for both. Fixed by PR #7897
