### ISSUE TITLE
courses: persistent in progress icon

### ISSUE THREAD

**Issue by jessewashburn** [open-learning-exchange/planet#7891]
![image](https://github.com/user-attachments/assets/95d500d5-0fc4-4f44-bd8a-43781909f336)

![image](https://github.com/user-attachments/assets/638e35a9-cb12-4347-a705-13fa67ffcd87)

Step 7 always says in progress. I created a test with a single step that is a short answer question. I completed it multiple times but the icon persists. I created other steps with the same test format but was not able to replicate the issue.

**Comment by Mutugiii** [comment]
This is because there is a question in the test that needs to be graded, after grading by the coach/teacher the course step should be marked as complete

**Comment by jessewashburn** [comment]
> This is because there is a question in the test that needs to be graded, after grading by the coach/teacher the course step should be marked as complete.
> 
> If after grading it's not being marked as complete then there is an issue

I see. I am unable to grade submissions due to issue #7877, so lets leave it open until that gets fixed.
