### ISSUE TITLE
Add reports table for the chats

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#7896]
Add a reports table that tracks the chats usage per month

**Comment by RheuX** [comment]
@Mutugiii would i need to add on to the database for chat usage?

the only thing i see that is being keep track of is the `chat_history`, which only keep track of the `creation_date` and `last_updated`

**Comment by Mutugiii** [comment]
No, we need a table that shows the chats created on a monthly basis

![image](https://github.com/user-attachments/assets/3991183f-64d1-4eb0-8bb6-f0be5fae18c9)

**Comment by RheuX** [comment]
I see, so even if people are using the chat, but the older chat, that means that there would be no chat usage that day?

Because we're only tracking the chat created right?
