### ISSUE TITLE
myProgress: course names should link you to the course 

### ISSUE THREAD

**Issue by jessewashburn** [open-learning-exchange/planet#7911]
![image](https://github.com/user-attachments/assets/9274d3a7-ccd1-47da-a473-b2178dd430c7)

**Comment by Gavinp14** [comment]
Would the desired behavior be if you clicked on a course, it would navigate you to that specific course view page?

**Comment by jessewashburn** [comment]
> Would the desired behavior be if you clicked on a course, it would navigate you to that specific course view page?

Yes, just the main course view, as the learners will not necessarily have access to the course leader progress.

**Comment by jessewashburn** [comment]
Fixed by #7938
