### ISSUE TITLE
Courses: Overflow occurs for long non-spaced course titles and descriptions

### ISSUE THREAD

**Issue by Gavinp14** [open-learning-exchange/planet#7919]
<img width="1256" alt="nonspacedlettersissue" src="https://github.com/user-attachments/assets/bc809f14-7836-4e32-a307-c5cddeb38806" />
The vert even goes away as well.

**Comment by jessewashburn** [comment]
Related to #7664, which I'm taking over from Sahil.

**Comment by RheuX** [comment]
If you have a progress bar also, its will misaligned, so hopefully #7664 will fix it

**Comment by Gavinp14** [comment]
This is good to be closed
