### ISSUE TITLE
Add markdown support

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#808]

**Comment by lmmrssa** [comment]
List of some MDE
* https://github.com/dimpu/ngx-md
* https://github.com/sparksuite/simplemde-markdown-editor

**Comment by paulbert** [comment]
One issue with ngx-md: They have an accepted PR which maybe creates an XSS vulnerability.  I commented on their PR, so we should wait to see what their response is.

XSS is a good thing to be aware of as we look at these editors as we should make sure we do not allow malicious scripts to run.
