### ISSUE TITLE
Responsive design?

### ISSUE THREAD

**Issue by mappuji** [open-learning-exchange/planet#84]
I see that we will use tablet as main client of our app, why not designing our app as a responsive app?

<img width="826" alt="capture d ecran 2017-10-14 a 12 57 10 am" src="https://user-images.githubusercontent.com/11813607/31559404-aaec8aa6-b07a-11e7-84fb-26d4ba493e00.png">

Reference: https://www.w3schools.com/html/html_responsive.asp

**Comment by LKhadka** [comment]
I am concerned about this too. What devices are we targeting? If we are going for smaller screens, it would be better to build it up from there to bigger screens

**Comment by mappuji** [comment]
I think we need to support tablet at least.

**Comment by mappuji** [comment]
What is the progress of this @paulbert and @lmmrssa?
