### ISSUE TITLE
Empty step should not be saved

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#851]
If step is empty, it should not be saved. Or it needs validation to have atleast title.
May be for empty we can add default title.

**Comment by lmmrssa** [comment]
![screen shot 2018-05-03 at 09 20 40](https://user-images.githubusercontent.com/2909490/39591633-0a7a08b6-4f24-11e8-801c-84947dba95a2.png)

**Comment by paulbert** [comment]
I left validation out for the title so if it is blank it will just show "Step 1".  It should not show up as "Step undefined".  Is there a `stepTitle` field at all for that step?

**Comment by lmmrssa** [comment]
@paulbert This shows when you look at the view of course.
It shows Step 1 only when you are on manage. But it does not save that Step 1 on title field.

**Comment by paulbert** [comment]
If title field is blank it should just show Step 1/2/3...
