### ISSUE TITLE
Logout issue

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#859]
0.1.9

![image](https://user-images.githubusercontent.com/9203229/39646024-1b1084f0-4fa8-11e8-8949-d8da89bd7c07.png)

**Comment by Rupesh87** [comment]
@paul this error occurs only when user double click to logout icon

**Comment by paulbert** [comment]
I'm going to close this.  The issue was that the `login_activities` db for Earth did not have the correct index (we had changed `login_time` to `loginTime`).  It's fixed now.
