### ISSUE TITLE
no appropriate error when user already exsists on nation

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/planet#910]
![a-20180510-100924](https://user-images.githubusercontent.com/13684059/39874027-95182c94-543a-11e8-9182-6f549699c67b.png)

**Comment by dogi** [comment]
It will be difficult to make user understand that username is already taken

**Comment by lmmrssa** [comment]
Once #926 and #927 are merged. We might not require to check the conflict of username on parent planet.

**Comment by leomaxi** [comment]
After trying to register the same username twice, It prompted me `Username already exist, Please register with a different user name`. So I tried to guess my password right and got to my dashboard. But the foot alert `Username already exist, Please register with a different user name` was still showing even-though I had logged in successfully... 

<img width="1595" alt="screen shot 2018-05-15 at 11 02 07 pm" src="https://user-images.githubusercontent.com/2836302/40087922-4927aa90-5894-11e8-802b-32d24a6e2a44.png">

**Comment by paulbert** [comment]
No longer an issue as we append community code to nation username
