### ISSUE TITLE
Potential memory leak issue

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/planet#912]
**Instructions of profiling tools:** https://docs.google.com/document/d/1fuvzKw7w62phL97UozinGY_UEvz3B8PHBAwSISCWxyM/edit?usp=sharing
Using profiling tools in Chrome seem to show issues at times:

![screen shot 2018-05-10 at 9 18 12 pm](https://user-images.githubusercontent.com/16757941/39874366-be4d4baa-5497-11e8-96a7-6eebe251c79c.png)

![screen shot 2018-05-10 at 9 18 31 pm](https://user-images.githubusercontent.com/16757941/39874372-c1fa93e8-5497-11e8-81ca-99fa9d02ba89.png)

This was the result of clicking around the left navbar in rapid succession, and then letting it just rest (not in the home dashboard), and seems to not release the memory.

At times though, it does seem to be garbage collected properly (see drop in heap (blue), this one was clicking around a bit less rapidly, and then opening the dashboard and then letting it 'rest' there before turning off the profiler:

![screen shot 2018-05-10 at 9 06 49 pm](https://user-images.githubusercontent.com/16757941/39874524-27b89bbc-5498-11e8-95c8-ef069f2168fb.png)
 
**I do not know the reason for this, and perhaps memory will be released eventually after more than 15 seconds, but it would be good to have more people test this on their machines, to see if there are things kept in scope for no good reason, or if there are circular dependencies somewhere**

Since a framework is used, it should be cleaning up after itself pretty well, but better be safe than sorry :)

**Comment by paulbert** [comment]
Closing.

This helped bring up the need to destroy RxJS subscriptions, and now it seems to be (relatively) under control.
