### ISSUE TITLE
meetup view selection not working 

### ISSUE THREAD

**Issue by Rupesh87** [open-learning-exchange/planet#923]
version: 0.1.12

![meetup](https://user-images.githubusercontent.com/18145146/39920400-aa1dcf2a-5536-11e8-9418-43030f341270.png)

**Comment by lmmrssa** [comment]
Issue is not clearly described. In master I could see select all being unselected when doing any action but selection of all items remain. If issue is to remove selection then there is issue #869 which contradict with it.

**Comment by paulbert** [comment]
Fixed in #924
