### ISSUE TITLE
Image resources downloads opens in same tab in Chrome

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/planet#929]
**Tested on 0.1.12**

When clicking download, on 'downloadable' image resources in library in Chrome, they do not download but opens in same window as below:

![screen shot 2018-05-13 at 8 26 33 pm](https://user-images.githubusercontent.com/16757941/39967780-11f7a0ba-56ec-11e8-93d8-b39a7077db41.png)

If opening in new window/tab, e.g. Cmr + click on mac, it downloads to the local machine.

**Comment by MacNew** [comment]
Sorry @Tille88  it works on chrome version 64.0.3282.119. It is not working on Mozila Firefox. And This Issue is same as a [https://github.com/open-learning-exchange/planet/issues/885](url) so you can close this issue.
