### ISSUE TITLE
How to handle secondary errors

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#947]
An open question so this doesn't get lost.  See #897 where the user & matching shelf are deleted & an error is thrown if the one of these two CouchDB requests fail.  If they do not, there is then an update to the shelf database which removes that user from anyone else's shelf.  Notifying a non-technical user at this point of success or error would be confusing (the user is already deleted from the DB, so there is already success for what the user intended), but should we try to keep a record on CouchDB of this error or set up some sort of debug logging that we can turn on for production?

**Comment by mappuji** [comment]
I think in current setup we set the log level to default https://github.com/open-learning-exchange/srv/blob/master/vi/conf/local.ini (I don't know if its ERROR or INFO), should search further.

We can always set the log level in `local.ini` for the CouchDB itself, but for the application (planet), should we add that option? I think so.

**Comment by paulbert** [comment]
Outdated.
