### ISSUE TITLE
View requested, rejected, accepted community list

### ISSUE THREAD

**Issue by Pr0chin** [open-learning-exchange/planet#97]

**Comment by nirojdyola** [comment]
Example from Bell App:
![community list.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58aeb9eb257d931a000df4b2/125516c66e82c728ace21e0d46eb9b972e978da09bf0ff4fad4ee4d665043761260ea62864c7b96aea1b7f550a0c48aa105e094dfef8892ba4e06826df580ae9c3714d36976345f3e5db55ea43a82a994e82bcbd8f4cc8ef3e26e08e8a483a1d1755.png)

**Comment by nirojdyola** [comment]
Already implemented it in https://github.com/ole-vi/planet/issues/96 .
Snapshot
![Community.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58aeb9eb257d931a000df4b2/125516c66e82c728ace21e0d46cb9b972e978da09bf0fd0fe64de29b234324676b5ee17e2981b72dbc142d00590947ae40585f46aaaddf7ea2b73862964e49bc8f3900299f7744eeaa880dbe06b0218e4f8dbebf8f44c5e13924e099c2.png)

Only Delete Button is added. @dogi , @paulbert Do we need "View Details" and other features ? Let us know .
