### ISSUE TITLE
Rating comment gets old comment

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#977]
When you click rating star, comment from last form remains on form.
![screen shot 2018-05-16 at 19 04 34](https://user-images.githubusercontent.com/2909490/40119662-f34289ca-593c-11e8-94f2-2c45d0f99121.png)

**Comment by paulbert** [comment]
I'm seeing this only happen on ResourcesView component, and when I click on the rating the entire view changes to another resource.

Didn't we realize that this was an issue with our mock data?
