### ISSUE TITLE
Structure of planet app

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#98]
Planet app will have 3 levels
- Center
- Nation
- Community

Each of these level will have different user roles
- Manager (possibly)
- Member (default)

Do we want to have single code base that will handle all levels of application with roles per level?
**OR**
Do we want to have code base per application level and control only user role view per that code base?

Could we have some ideas posted regarding how can we structure the application and manage code base.

**Comment by paulbert** [comment]
Closing as I think we have come up with an overall structure
