### ISSUE TITLE
Add buttons on course view.

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#989]
We can probably add take test or view resource on course view itself. Also admission button needs to be added on course.
![screen shot 2018-05-17 at 19 19 29](https://user-images.githubusercontent.com/2909490/40180755-4f2e5c08-5a07-11e8-9ce4-e785bf2981ef.png)

**Comment by Rupesh87** [comment]
@lmmrssa for admission/resign button there is already issue https://github.com/open-learning-exchange/planet/issues/931
