### ISSUE TITLE
Changing rating and clicking cancel still updates rating

### ISSUE THREAD

**Issue by Tille88** [open-learning-exchange/planet#992]
Below went from 1 star to 4 stars. When clicking cancel it still shows 4 stars.

![screen shot 2018-05-17 at 9 13 11 pm](https://user-images.githubusercontent.com/16757941/40183170-550214e8-5a17-11e8-9a73-34b1018dbf19.png)

**Comment by lmmrssa** [comment]
this is one of the old issue #877 Also this it the intended feature. So rating will be recorded when you click star. Popup is only for adding comment
